### ISSUE TITLE
Change vocabulary base URL for v2 context

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-model#1002]
From `https://www.w3.org/2018/credentials` to `https://w3.org/ns/credentials`

**Comment by mprorock** [comment]
big +1 from me on this

**Comment by OR13** [comment]
@mprorock please amend your comment to include a year so we know which version of `+1` you meant, for example, I am still on `+1-2020`

**Comment by msporny** [comment]
It's unclear what this issue is intending to change. It could be talking about any of the following:

* A non-breaking change that publishes the v2 context at `https://www.w3.org/ns/credentials` (note, we tried dropping the `www` before and the W3C systeam said: No, that would result in two hits against our infrastructure which can be a dangerous thing for anything in `/ns`.
* A backwards-incompatible breaking change that changes the entire Credentials vocabulary, and the JSON-LD context terms, to point to a wholly new location.
* A backwards-compatible breaking change that changes the entire Credentials vocabulary to point to a wholly new location but provides some sort of equivalence statements in the new vocabulary.
* A redirect from the new location to the old location.
* A redirect from the old location to the new location.
* Combinations of the above.

Which of the above combinations, and their repercussions, are we talking about in this issue?

**Comment by msporny** [comment]
I've raised PR #1003 to force the issue -- sooner we get this settled and moved on to the new v2 context, the better.

**Comment by brentzundel** [comment]
with PR #1003 merged, can this issue be closed?

**Comment by OR13** [comment]
yes, I believe this can be closed.
