### ISSUE TITLE
Clarifying credential from verifiable credential

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#1009]
The credential exists regardless of whether it has a cryptographic verification mechanism attached to it or not. Various (incompatible) verification methods exist which are being separately standardised. Nevertheless the underlying credential should be identical in all cases. Consequently many of the properties in the VCDM actually refer to the credential and not to the verifiable credential. Examples include: valid from, valid to, id, type, `@context`, issuer.
A PR is needed to ensure that all the properties that describe the credential refer to the credential and not to the verifiableCredential.
By way of example, the current (v1.1) text for identifier states
"The first identifier is for the `verifiable credential` and uses an HTTP-based URL. The second identifier is for the `subject` of the `verifiable credential` (the thing the [claims] are about)"
This should be more correctly stated as
"The first identifier is for the `credential` and uses an HTTP-based URL. The second identifier is for the `subject` of the `credential` (the thing the [claims] are about)"

Note that different proofing mechanisms may add their own `id` for the proof (i.e. for the verifiableCredential), akin to the serialNumber in X.509 public key certificates, and this should not be confused with the `id` of the `credential`.

**Comment by awoie** [comment]
I do agree with @David-Chadwick . I remember that the VCWG made this distinction between credentials and verifiable credentials in the past. A PR to fix these references make sense from my perspective.

**Comment by Sakurann** [comment]
no objection with the direction to clarify.

just a nuance..
> Nevertheless the underlying credential should be identical in all cases.

As defined in v1.1, the actual body of what is signed is different between JWS and LDP - hence transformation section of mapping to JWT claims in section 6.3.1. 
I would agree that `the data model used by a credential should be identical in all cases", though I honestly want a term "data model" to be defined explicitly. right now it is implicit, which I think have contributed to this confusion around data-model -> credential -> verifiable credential transformation..
not sure how much this will impact replacing `verifiable credential` with `credential` - concrete text would be helpful

**Comment by David-Chadwick** [comment]
@Sakurann Since we are now making changes to v2, and not v1.1, then I believe/hope that the credential proofed by either a JWT or JSON-LD will be identical in all cases. i.e. we will adopt the "as well as" algorithm for JWT instead of "instead of". 

I will produce some concrete text for you.

**Comment by TallTed** [comment]
@David-Chadwick -- 

Please edit your initial comment on this issue, and put code fences around `@context`. 

Single [backticks a/k/a grave accents](http://dbpedia.org/resource/Backtick) are easiest in this case (i.e., ``` `@context` ```).

[Single-quotes](https://dbpedia.org/resource/Quotation_mark), whether curly or straight, as you have there now (i.e., `'@context'`), are *not* code fences.

**Comment by David-Chadwick** [comment]
Thankyou. I used the wrong "'" :-)

**Comment by David-Chadwick** [comment]
I dont know how the closure came about. I did not intend to close this issue. (It must have been some strange combination of characters that I pressed by mistake). Sorry!

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-04-04-vcwg-special#section1-9) on 2023-04-04

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.9. Clarifying credential from verifiable credential (issue vc-data-model#1009)

_See github issue [vc-data-model#1009](https://github.com/w3c/vc-data-model/issues/1009)._




**Manu Sporny:** I'll take this one. We need to do a pass through the specification..  
… Now an editor needs to make sure we mean "credential" or "verifiable credential" appropriately. This is ready for PR. My expectation is we will largely refer to "verifiable credential" in the specification, since that's what the media type is about..  

**Kristina Yasuda:** Can I help you with that?.  

**Manu Sporny:** Absolutely..  
… DavidC I'll add you too.  

**David Chadwick:** Thanks.  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-06-07-vcwg#section2-6) on 2023-06-07

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.6. Clarifying credential from verifiable credential (issue vc-data-model#1009)

_See github issue [vc-data-model#1009](https://github.com/w3c/vc-data-model/issues/1009)._




**Brent Zundel:** moving to issue 1009, assigned to Manu, DavidC and Kristina.  
… wonder if this has been overtaken by events. How should we mark before or post CR?  

> *Orie Steele:* Suggest closing this, the group has essentially resolved there is no difference.

> *Orie Steele:* There is not spec legal way to distinguish between credential and verifiable credential.

**David Chadwick:** this needs someone to carefully go through current version and ensure use of credential or verifiable credential are proper and submit editorial change.  

> *Orie Steele:* indeed, the base media type explains that you never know.

**Joe Andrieu:** Appreciate the clarification. Agrees the language in the spec is confusing.  

**Orie Steele:** +1 to what Joe said. Base media type does not talk about securing mechanism.  

**Brent Zundel:** suggests to make this as post CR.  

**Orie Steele:** this may effect normative statements. esp the definition of what a proof is. Must be addressed before CR.  

**Brent Zundel:** adding before CR label.  

</details>

**Comment by OR13** [comment]
@brentzundel @Sakurann this seems pretty critical to start fixing

**Comment by brentzundel** [comment]
I believe this Issue may be superseded by #1126 
I am marking it as pending close and will do so in 7 days if no one objects.

**Comment by David-Chadwick** [comment]
I object simply because #1126 is necessary but not sufficient to address this issue. Lets see how #1126 pans out with a PR before closing this issue, since it is important that this issue is fully resolved in the v2 DM

**Comment by OR13** [comment]
Seems we are nearly needing a label for "blocked-by-credential-vs-verifiable-credential"

**Comment by msporny** [comment]
I have raised #1211 in an attempt to address this issue. If #1211 is merged, this issue will be closed.

**Comment by msporny** [comment]
PR #1211 has been merged, closing.
