### ISSUE TITLE
Need to clarify the nature of the media type in relationship to "credential" vs "verifiable-credential"

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-model#1012]
Related to #1009 

Work to be done:

Add extra paragraph around the media type, something to this effect:

`application/credential+ld+json`

1. `proof` MUST NOT be present.
1. `proof` MAY be present.
1. `proof` MUST be present.

**Comment by TallTed** [comment]
Seems to also need something alongside, like

`application/verifiable-credential+ld+json`

1. `proof` MUST NOT be present.
1. `proof` MAY be present.
1. `proof` MUST be present.

and similar for any other known/expected simple or compound media types (incorporating `jws`, `jwt`, etc.)

**Comment by paulfdietrich** [comment]
Manu, after discussions today and the specification language 

"This specification registers the application/credential+ld+json MIME Media Type specifically for identifying documents conforming to the Verifiable Credentials format."

This seems clear enough to me that this means a document conforming to the VC format.  Not sure why there needs to be any language around whether a proof is required as it clearly is not.     The string "credential" does evoke questions, but something like "w3c-vc",  or "w3c-vc-2.0" would make it clearer to me that this media type dictates a document that conforms to this specification.

Whether there needs to be additional media types to specify a restricted data model where a proof MUST be present or MUST be absent, I defer to others, but there should be a media type that describes any document compliant with the data model VC specification.

**Comment by OR13** [comment]
Seems we can close this, I will close based on the resolutions we have taken.

**Comment by Sakurann** [comment]
superceded by a resolution to use vc+ld+json for a credential

**Comment by iherman** [comment]
Reopening temporarily to add proper records of the meeting, closing it afterwards...

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-04-11-vcwg-special#section1-5) on 2023-04-11

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.5. Need to clarify the nature of the media type in relationship to "credential" vs "verifiable-credential" (issue vc-data-model#1012)

_See github issue [vc-data-model#1012](https://github.com/w3c/vc-data-model/issues/1012)._




**Kristina Yasuda:** Need to clarify the nature of the media type in relationship to "credential" vs "verifiable-credential" - was this resolved?.  

> *Dave Longley:* +1 to the idea that this is resolved.

**Orie Steele:** agrees that this has been resolved.  

**Joe Andrieu:** suggests to move past this.  

**Kristina Yasuda:** cheers on closing issue.  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-04-11-vcwg-special#section1-5) on 2023-04-11

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.5.  (issue vc-data-model#1012)

_See github issue [vc-data-model#1012](https://github.com/w3c/vc-data-model/issues/1012)._




**Kristina Yasuda:** Need to clarify the nature of the media type in relationship to "credential" vs "verifiable-credential" - was this resolved?.  

> *Dave Longley:* +1 to the idea that this is resolved.

**Orie Steele:** agrees that this has been resolved.  

**Joe Andrieu:** suggests to move past this.  

**Kristina Yasuda:** cheers on closing issue.  

</details>
