### ISSUE TITLE
Specify allowed Verifier interactions with Verifiable Data Registries 

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1016]
@David-Chadwick wrote in https://github.com/w3c/vc-data-model/commit/d3981a450f32f03aa88cd1930344402cb9b2a8ee#r97379419:
Actually the verifier may interact directly with the VDR of the issuer. The issued VC will contain sufficient information for the verifier to determine where the issuer's VDR is and how to obtain information such as the public key of the issuer from this. So I suggest this wording

> By requesting verifiable credentials of a particular `type`, the verifier is able to gather specific information about the issuer(s) from these verifiable credential(s) provided by the holder. This will enable the verifier to determine the next stage of its interaction with the holder.

@TallTed responded:
This feels a lot like a sneaky "phone home" which we have explicitly is an anti-pattern and major potential privacy hole. I submit that this discussion belongs in its own issue against the line(s) you want changed (rather than in comments on an already committed commit), so that the whole WG is more likely to be aware of and participate in it.

**Comment by David-Chadwick** [comment]
Verifiers must know about and trust issuers if they are to accept their issued VCs. Issuers say who they are in the issuer property. This property may be an object that can contain its URL, DID, X.509 PKC and other such properties.
Thus there is no way that the verifier cannot determine who the issuer is, but if there was, the verifier would not be able to determine if the issued VC was trustworthy or not.
This is nothing to do with 'phoning home'. It is to do with first verifying and then validating the issued VC.
So given that the verifier must know who the issuer is, it also must obtain (by some out of band means) the cryptographic material of the issuer in order to technically verify the issued VC. It may also require other metadata of the issuer (such as where revocation information is located, which schemas control the issuer's issued VCs etc.) Now whether the issuer behaves ethically or not when the verifier is doing this e.g. by monitoring its VDR to see who and when it is being called, is outside the scope of the VC DM. It is a feature of the VC DM that the verifier must contact the VDR to obtain the issuer's metadata.
So do we need some Implementors notes or other advisory information to describe the difference between 'phoning home' and obtaining an issuer's metadata?

**Comment by Sakurann** [comment]
could the proposed text be simplified to just say, `Verifier treats the valid VC according to its policy`?

**Comment by Sakurann** [comment]
could the proposed text be simplified to just say, `Verifier treats the valid VC according to its policy`?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-06-06-vcwg-special#section1-7) on 2023-06-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.7. Specify allowed Verifier interactions with Verifiable Data Registries  (issue vc-data-model#1016)

_See github issue [vc-data-model#1016](https://github.com/w3c/vc-data-model/issues/1016)._




**Brent Zundel:** Specify allowed verifier interactions w/ verifiable data registries.  
… Not much discussion... before/after CR, or pending close.  

> *Orie Steele:* Verifiable Data Registries are blockchains?

**Ted Thibodeau Jr.:** We should indicate who's issue this is when introduced.  

**Brent Zundel:** noted.  
… before/after CR, or pending close?  

**Joe Andrieu:** I'm struggling to make sense of the comment.  

**Brent Zundel:** pending close unless we get more information?  

> *Orie Steele:* Seems he is interested in VDRs as trust stores.

**Joe Andrieu:** VDRs are not a thing in the VC universe?  
… This is about DIDs... not this spec/work?  

**Brent Zundel:** so pending close, but for other reasons?  
… any objections to pending close?  

> *Orie Steele:* +1.

> *Phillip Long:* pending closed for 1016.

**Manu Sporny:** +1.  

**all:** None heard, marking as pending close.  

**Brent Zundel:** I'll ask David for more information if he wants to keep it open.  

</details>

**Comment by brentzundel** [comment]
@David-Chadwick bringing this to your attention. It was not clear to the group what changes are being proposed.

**Comment by brentzundel** [comment]
No objections raised since marked `pending close`, closing.
