### ISSUE TITLE
Requesting content type for presentation

### ISSUE THREAD

**Issue by andresuribe87** [w3c/vc-data-model#1017]
Similar to https://github.com/w3c/vc-data-model/issues/978 , `VerifiablePresentations` should also have a content type associated with them as well. `"application/presentation+ld+json"` seems like a great candidate.

**Comment by msporny** [comment]
I suggest we go with `application/vp+ld+json` to align w/ what's in the core spec `application/vc+ld+json`.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-04-05-vcwg#section3-5) on 2023-04-05

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.5. Requesting content type for presentation (issue vc-data-model#1017)

_See github issue [vc-data-model#1017](https://github.com/w3c/vc-data-model/issues/1017)._




**Brent Zundel:** Requesting content type for presentation.  

**Manu Sporny:** Self-assigned and ready for PR.  

</details>

**Comment by Sdssourcing** [comment]
#

**Comment by OR13** [comment]
We could just not request a media type for VPs, and just say `vc+ld+json` also works for Verifiable Presentations

**Comment by brentzundel** [comment]
There is now a content type for presentations: https://w3c.github.io/vc-data-model/#vp-ld-media-type

I am closing this issue as it has been addressed.
