### ISSUE TITLE
Add a unique version property to the core data model

### ISSUE THREAD

**Issue by decentralgabe** [w3c/vc-data-model#1046]
Add a required property `version` or similar that points to the _exact specification version_ that a VC or VP is created against.

This is similar to the `$schema` property in [JSON Schema](https://json-schema.org/specification.html) e.g.

```json

  "$id": "https://example.com/address.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "An address similar to http://microformats.org/wiki/h-card",
  "type": "object",
  "properties": {
    "post-office-box": {
      "type": "string"
    ....
```

the `spec_version` property in [Credential Manifest](https://identity.foundation/credential-manifest/#versioning) and similar properties in other specifications.

It is useful to have a completely unambiguous version identifier.

**Comment by bumblefudge** [comment]
Isn't that redundant if there's an unambiguously versioned @Context file? 🌶️ 🌶️ 🌶️

**Comment by decentralgabe** [comment]
@bumblefudge the `@context` does not point to **a specific version of the specification**

**Comment by bumblefudge** [comment]
Well the base context is updated every major version, was the joke I was making. Mostly I was teasing because LD folks who make their own extension `@context` file could and often do version it every version of their own system, so the combination of the two does something roughly equiv to what you're requesting (as a side effect). But having an unambiguous prop across mime types might be worthwhile, I just wanted to tease out a feasible counterargument and maybe troll just a tiny bit.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-04-12-vcwg#section4-2) on 2023-04-12

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.2. Add a unique version property to the core data model (issue vc-data-model#1046)

_See github issue [vc-data-model#1046](https://github.com/w3c/vc-data-model/issues/1046)._




**Brent Zundel:** add a unique version property to the data model.  

**Gabe Cohen:** useful to have a unique version model to track it. There isn't anything that points it to a particular specification.  

**Brent Zundel:** would Gabe take on this issue?  

**Gabe Cohen:** yes!  

**Manu Sporny:** core data model is JSON-LD has an `@context` value is the version identifier. A separate unique version isn't needed.  

**Dave:** +1 to Manu's observation/recommendation. Should close it. Core data model doesn't need it.  

</details>

**Comment by decentralgabe** [comment]
As was discussed on the call, it seems most are fine with using a required context as a version identifier. This falls down unless contexts are versioned themselves. As we see with [v1.1 of the data model](https://www.w3.org/TR/vc-data-model/) the context listed still shows v1, which is not helpful for implementers when receiving a VC in the wild.

Additionally, if one receives a credential that has a mapping to the core data model, without a context, there is no guaranteed way to determine which version of the spec the credential is for. At the least I'd like to see a requirement for mappings to include versioning information in their media type.

**Comment by dlongley** [comment]
@decentralgabe,

> As we see with [v1.1 of the data model](https://www.w3.org/TR/vc-data-model/) the context listed still shows v1, which is not helpful for implementers when receiving a VC in the wild.

v1.1 is backwards compatible -- and the changes from v1.0 can be seen here:

https://www.w3.org/TR/vc-data-model/#revision-history

Can you give an example of a problem for implementers in the wild? Changing versions in the data when it isn't necessary also causes problems for implementers in the wild -- so there's a balance here. Just updating a version string that has no impact on implementers would be more problematic, not less. If there is something that implementers will need to switch off on, then that should be the trigger to change the version -- and we should do that, as we will be doing for 2.0.

> Additionally, if one receives a credential that has a mapping to the core data model, without a context, there is no guaranteed way to determine which version of the spec the credential is for. At the least I'd like to see a requirement for mappings to include versioning information in their media type.

The mapping output MUST have a context, which will necessarily say the version (since we use the context URL as the version). The mapping rules already must define which context that will be.

**Comment by decentralgabe** [comment]
> Can you give an example of a problem for implementers in the wild?

Sure.

The revision history from 1 -> 1.1 states
> Loosen the requirement to use URLs to use [URIs](https://www.w3.org/TR/vc-data-model/#dfn-uri) in the id property of the credentialStatus and refreshService sections of the data model.

If I had a credential validation lib set to 1.0 I may not process `id` properties properly (dropping URNs for example, since URIs are a superset of URLs).

> Just updating a version string that has no impact on implementers would be more problematic, not less

How would this have no impact on implementers? It would clearly tell them which version of the specification to implement against. It's as easy as a switch statement in many common programming languages:

```go
switch VCDMVersion {
case v1.0:
  // process according to 1.0 
case v1.1:
  // process according to 1.1
case v2.0:
  // process according to 2.0
}
```

Today this is difficult, since we need to infer the version of a spec an object is associated with.

Also...
> The mapping output MUST have a context, which will necessarily say the version (since we use the context URL as the version). So the mapping rules already must define which context that will be.

Yes, the mapping, but certainly you may process a VC without a mapping...

**Comment by dlongley** [comment]
@decentralgabe,

> If I had a credential validation lib set to 1.0 I may not process id properties properly (dropping URNs for example, since URIs are a superset of URLs).

Even without that change, URNs were already [acceptable as URLs](https://www.rfc-editor.org/rfc/rfc2141):

> The URN syntax has been defined so that URNs can be used in places
> where URLs are expected.  A resolver that conforms to the current URL
> syntax specification [[3](https://www.rfc-editor.org/rfc/rfc2141#ref-3)] will extract a scheme value of "urn:" rather
> than a scheme value of "urn:<nid>".
>
> An URN MUST be considered an opaque URL by URL resolvers and passed
> (with the "urn:" tag) to an URN resolver for resolution.

So there's every reason to think that software that did that was incorrect for 1.0. We removed the ambiguity in 1.1 without making a breaking change. There's a long storied history of confusion around URI, URN, and URL -- and what the *actual* distinctions are. Indeed, this is why we've started using the WHATWG spec to clarify this in 2.0 by using URL everywhere with "URIs" being essentially a deprecated name.

>> Just updating a version string that has no impact on implementers would be more problematic, not less
>
> How would this have no impact on implementers? It would clearly tell them which version of the specification to implement against.

Sorry, to be clear, I meant that if we updated the string and there was nothing *else* to signal because of it -- that would be an unnecessary ask of implementers. There definitely *would* be an impact on implementers -- but the *only* impact would be the headache of having to update their software and releases everywhere to accept two different version strings with no other actual software changes. It's the "go kick rocks" of the software world.

> Yes, the mapping, but certainly you may process a VC without a mapping...

If you process something that can be mapped to a VC without mapping it -- then you use whatever the other processing rules are. We don't say what those are in the core data model. You can of course raise an issue around that with any representation that is able to be mapped to a VC if you feel it's an important thing to be considered over there.

**Comment by decentralgabe** [comment]
I take the point that if all sub versions of a major version at to only include backwards compatible changes then a version string is less necessary for representations of the core data model. That said you'd still need to find a way to go from context string -> spec version, but I won't die on that hill.

> If you process something that can be mapped to a VC without mapping it -- then you use whatever the other processing rules are. We don't say what those are in the core data model. 

That's correct; however, the core data model allows for these mappings, and could advocate for a version identifier in the media type or elsewhere.

I'll leave this open for a week and if no one else thinks this is a good idea I'll close 😄

**Comment by TallTed** [comment]
@dlongley — Your [quote from RFC2141](https://github.com/w3c/vc-data-model/issues/1046#issuecomment-1509144172) lost a key bit, where `<nid>` is below; it needs to be code-fenced to keep the angle-brackets from triggering HTML treatment —

> The URN syntax has been defined so that URNs can be used in places
> where URLs are expected. A resolver that conforms to the current URL
> syntax specification [[3](https://www.rfc-editor.org/rfc/rfc2141#ref-3)] will extract a scheme value of "`urn:`" rather
> than a scheme value of "`urn:<nid>`".

**Comment by decentralgabe** [comment]
Closing
