### ISSUE TITLE
Holders and Identifiers

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#105]
The current text in 1.3 says 
Holders SHOULD be able to easily control and own their own identifiers.

This applies equally to subjects, perhaps even more so than holders,
since VCs apply to subjects and contain subject IDs. VCs do not contain holder IDs.
Suggest either replace Holders with Subjects or add the requirement for subjects

Subjects SHOULD be able to easily control and own their own identifiers.

**Comment by stonematt** [comment]
does everyone agree and is this true?

**Comment by dlongley** [comment]
I think it's fine to add:

"Subjects SHOULD be able to easily control and own their own identifiers."

As a requirement. Nothing in the data model would prevent that capability and the spec's agnosticism with respect to identifiers generally supports any such statement, regardless of role.

**Comment by David-Chadwick** [comment]
This text has not yet made it into the latest version (13 Feb 18) so it is not closed yet

**Comment by David-Chadwick** [comment]
This text has not yet made it into the latest version (18 April 18). Worse still the latest text says 

identifier registry
    Mediates the creation and verification of subject identifiers.

So from the above, there is no mention of issuers or holders having identifiers as well. Nevertheless the following text is still present

Holders SHOULD be able to easily control and own their own identifiers.

This will be confusing to new readers of the specification.

**Comment by burnburn** [comment]
@David-Chadwick please take a look and let us know what concerns remain given the current text.

**Comment by David-Chadwick** [comment]
@burnburn I do not believe that the text has yet made it into the data model document.

**Comment by David-Chadwick** [comment]
@msporny This textual change is such a simple clarification, so I wonder why it is taking so long to make it into the data model document?

**Comment by TallTed** [comment]
I think it is good this hasn't gone in yet, as it is not a simple clarification.  I am sorry not to have noticed this sooner.

"Anyone can say anything about anything" rather contradicts the idea that "Subjects SHOULD be able to easily control and own their own identifiers."  

In fact, I think that the existing "Holders SHOULD be able to easily control and own their own identifiers" is also problematic. 

As an *Issuer,* I may Identify the Subjects of my statements however I like, verifiably or otherwise.  Consider the University identifying its Professors, which may know that it has two "John Q Smythe" to deal with, while one of those believes himself to be the only "John Q Smythe" in the universe, and so wants a simpler identifier than the University intends needs to use in order to differentiate.

Putting either Subject or Holder in control of the Subject Identifiers puts an unreasonable burden on Issuers, at best.

**Comment by stonematt** [comment]
@TallTed @dlongley @David-Chadwick are we conflating/confusing identifiers that are managed in internals business systems, like the university example (clearly the domain of the university/issuer) with the personal identifiers in a holder's wallet (maybe not human readable, probably in the domain of the holder/subject).  When a holder accepts a VC that an issuer is issuing an aspect of the protocol will have to negotiate and manage the linkage between the two types of identifiers. 

If that's the case, how do we close this issue?

**Comment by David-Chadwick** [comment]
There are two different issues now being discussed:
i) confusion and ambiguity over the current text on identifiers, as originally highlighted by me, and
ii) who is responsible for issuing the subject and holder identifiers, which Ted introduced.

I would like @TallTed to bring up the second issue in a new issue item, so that this issue can concentrate on resolving the confusing text that I highlighted. The underlying assumption is that holders and subjects are responsible for managing their own identifiers, as these are self sovereign credentials.

If it subsequently turns out from discussing Ted's issue, that subjects and holders are not responsible for managing their own identifiers, then the clear and unambiguous text that is produced by the current issue can be suitably modified.

**Comment by David-Chadwick** [comment]
I propose that the current issue is resolved by adding the following text

"Subjects SHOULD be able to easily control and own their own identifiers."

that both myself and @dlongley suggest is OK to add to the current document.

**Comment by David-Chadwick** [comment]
@TallTed you are correct that in today's world, issuers control identifiers and assign to subjects whatever identifiers they want to. Subjects have no control over them.
But I thought that with VCs we were trying to move to a new world order in which the subject/holder was more in control - hence the title 'self sovereign'. Now it might be that this is an idealistic and unattainable objective. But I thought that the data model had been written with this objective in mind.

**Comment by msporny** [comment]
> The only identifiers anyone (whether Holder, Subject, or otherwise) can control are the ones they emit when they make an Assertion.

This is not true for cryptographic identifiers, which is what 90%+ of the implementations are using. It is true that anything may make an assertion about a cryptographic identifier. However, you can certainly know with an incredibly high degree of reliability that a statement made by an entity in control of the private key material associated with a cryptographic identifier came from them and not some random entity out there on the Internet.

To overly simplify, what the language is attempting to convey is: "People implementing this specification should use cryptographic identifiers as it greatly increases the trust in the ecosystem around the provenance of statements." So, perhaps we should reword to something more accurate/specific @TallTed?

**Comment by TallTed** [comment]
@David-Chadwick - To my mind, "self sovereign" in this context is meant to convey that everyone is their own "[certificate] authority" -- there is no need for any entity to go to anyone else (to appeal to a higher authority, an _other sovereign_) in order to make an authoritative assertion about any other entity.

To a lesser extent, "self sovereign" means that each entity is the master of their own destiny -- the entity is in control of itself and its emissions.  However, this does not give that "self" any "sovereignty" over others -- which others may still assert anything they like about that "self", and may use any identifier they like for that "self" when doing so.

Verifiable Provenance (or Assertions, or Claims, or Credentials, or ...) on the other hand is about being able to confirm that a given Claim/Credential was emitted by a given self-sovereign entity.

@msporny - If that's what we're trying to convey, perhaps that's what we should say, maybe even in those words?  Working from that, I say again -- the only entity which has control over a cryptographic identifier is the creator of that cryptographic identifier.  Many entities may make assertions about a single other entity, and each asserting entity may use their own cryptographic identifier to designate that "subject" entity, which may or may not be the "holder" entity at the time of Provenance (or Assertions, or Claims, or Credentials, or ...) Verification.

**@all** - "Meatspace" verification of assertions and provenance is done using (among other things) biometrics (such as photographs, height, and/or eye color), other physical evidence (such as signatures), and assertions of identity (my name is…, my car has VIN…, etc.), and may require interaction with various third-party entities (State Department, Registry of Motor Vehicles, etc.) -- and is often impossible to anonymize.  Electronic verification requires similar mechanisms, and may not always be anonymizable -- even if the goal is to maximize the potential for anonymity.  Certainly, while a human may choose their name, the car has no control over its VIN, and neither has (much) control over its height.

**Comment by msporny** [comment]
@TallTed -- agree with everything you say above.

@David-Chadwick, @TallTed  -- can we boil this down to specific spec text? I suggest adding something to this effect in the spec:

NOTE: This specification RECOMMENDS the use of cryptographic identifiers for **subjects**, **holders**, and **issuers** in order to increase trust in the provenance of verifiable credentials and verifiable presentations. A **cryptographic identifier** is one where it is possible to map the identifier to cryptographic material (e.g., a public key) such that digital proof (e.g, a digital signature) may be associated with verifiable credentials and verifiable presentations. Examples of cryptographic identifiers include decentralized identifiers,   ed25519 public keys, and URLs that are associated with public keys in some way.

**Comment by TallTed** [comment]
I have no particular issue with this "NOTE" paragraph.  Would the idea be to replace the current existing ["Holders are able to easily control and own their own identifiers"](https://w3c.github.io/vc-data-model/#x1-3-use-cases-and-requirements) text (with which I still strongly disagree)?

**Comment by David-Chadwick** [comment]
I am also happy with the NOTE text.
Then we should say "Holders, issuers and subject are able to easily control and own their own cryptographic identifiers"

**Comment by TallTed** [comment]
Again, only issuers are really able to control or own the cryptographic identifiers.  Requesters of such issuance, which might subsequently be holders and/or subjects, may *influence* but will neither control nor own those cryptographic identifiers.

**Comment by David-Chadwick** [comment]
@TallTed I dont believe you are correct. I can create an asymmetric key pair, and I am totally in control of this (aka PGP). I can use the public key as my identifier.

**Comment by TallTed** [comment]
@David-Chadwick - 

If "create" does not equate to "issue", I'll need a more detailed explanation of what you mean, and why you disagree with my assertion. 

_Your_ identifier-of-you, your self-created, self-issued, public key, may not be what anyone else uses to identify you, though their identifiers-of-you may be in `owl:sameAs` relations with your identifier-of-you, as they co-refer to the same referent (i.e., you).

I understand any identifier used to identify **me** to be one of "[my](https://en.oxforddictionaries.com/definition/my) identifiers", because although they may not belong to me and I may have no control over them, they are nonetheless associated with me.

Yes, this is dreadfully pedantic.  That's unfortunately necessary in documents such as the one we're drafting, as evidence of which you may see numerous revisions of RFC and other specs.

**Comment by David-Chadwick** [comment]
@TallTed 
I think I might have misunderstood your use of the term issuer. I took it to mean the issuer of a VC. Is this what you meant?
You said "I understand any identifier used to identify me to be one of "my identifiers", because although they may not belong to me and I may have no control over them, they are nonetheless associated with me." Furthermore you may not even be aware of them. You have no idea how I refer to you when I speak to my wife about you. Do you still think of this as "your identifier". I do not. I think of this as the issuer's identifier of me, and not as "my identifier".

**Comment by TallTed** [comment]
@David-Chadwick 

> You have no idea how I refer to you when I speak to my wife about you.

Exactly!  You (the Issuer) have made an assertion (which might be in a Verifiable form if, for instance, you "spoke" in a note instead of vocally) about me (the Subject) to your wife (the Holder).  In such an electronic note, you may have visibly referenced me as "TallTed", but your software may have helpfully included a cryptographic Identifier so it's clear you're not talking about any other TallTed.

Neither I (the Subject) nor your wife (the Holder) of that VC (_Verifiable CAssertion;_ the "C" is silent) have any control over the Identifier you (the Issuer) used for me -- "your Identifier for me" which may also be read as "my Identifier".

Barring significant additional explanatory text going into the spec, the statement that "Holders, issuers, and subjects are able to easily control and own their own cryptographic identifiers" sounds to me like saying that I have control and ownership over the cryptographic identifiers anyone may use to identify me.

**Comment by David-Chadwick** [comment]
@TallTed  
"You may have visibly referenced me as "TallTed", but your software may have helpfully included a cryptographic Identifier so it's clear you're not talking about any other TallTed."

I think we are in agreement that the issuer can insert any identifier into a VC that it wants to, to identify the subject. In this example I could have used "VeryTallTed" to refer to you. And the subject had no control over this.

But are we in agreement about the cryptographic identifier?

Who would be the owner of the cryptographic identifier that I inserted into the VC? It surely must be you, and refer to the public key of the key pair that you created yourself. It clearly would not be much use if I created a key pair for you, and then I put that public key into the VC as the cryptographic identifier of you. If my wife used this as your cryptographic identifier, then I could masquerade as you, since I have the private key. So if I the issuer, put your public key in the VC as the cryptogrphic identifier of you, and I issue this to my wife, nevertheless you the subject, still has full control over that cryptographic identifier. And this is what the text is aiming to say. "Holders, issuers and subject are able to easily control and own their own cryptographic identifiers".

**Comment by msporny** [comment]
@David-Chadwick and @TallTed -- I need a spec text proposal that both of you agree on to close this issue out. I can add the note I mentioned above to the spec, but it looks like both of you fundamentally disagree on one of the sentences.

**Comment by msporny** [comment]
A PR would need to be raised at this point to make a concrete, non-normative change to the spec.

**Comment by TallTed** [comment]
I *think* (more than 3 years out, after a conversation that ranged wildly through multiple issues, PRs, calls, etc., it's hard to be sure) that this was resolved by #277 and other PRs.  Certainly, I can find nothing like the offensive statement that opened this issue in the official [Verifiable Credentials Data Model 1.0 W3C Recommendation as of 19 November 2019](https://www.w3.org/TR/vc-data-model/) (though its subtitle of "Expressing verifiable information on the Web" is problematic, since the data model is really about "Expressing information with [verifiable provenance](https://github.com/w3c/vc-data-model/issues/105#issuecomment-414414815) on the Web", something which continues to confuse people today, as evidenced in the CCG and its work items and task forces, among other places ... for which I've created PR #780).

I believe this issue can be closed.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-06-14-vcwg#section3-4) on 2021-06-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.4. Holders and Identifiers 

_See github issue [#105](https://github.com/w3c/vc-data-model/issues/105)._




**Brent Zundel:** is this to resolve/fix a bug in the spec, or add to it?  

**David Chadwick:** there is ambiguity when subject does not equal holder  

**Brent Zundel:** describes an error which needs to be corrected - this issue can be labelled "Editorial"?  

**kdentartog:** a bug but not necessarily "fixable", should be part of "Editorial" - some changes to the text  

**Manu Sporny:** agreed, non-normative change - expectation of subject/holder/identifiers  

**Brent Zundel:** do we formally mark this as erratum?  

**Kyle Den Hartog:** agreed, believe it is  

**Manu Sporny:** the text no longer exists in the spec, may no longer be an issue  

**David Chadwick:** already some proposal in the issue, we could clarify in the text  

**Brent Zundel:** next steps - raising a PR which addresses concrete changes to the spec  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-09-08-vcwg#section6-2) on 2021-09-08

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 6.2. Holders and Identifiers (issue vc-data-model#105)

_See github issue [#105](https://github.com/w3c/vc-data-model/issues/105)._




**Brent Zundel:** #105. Holders and identifiers.  
… There's been a conversation since 2018 on this.  
… It's been going on for a while.  
… Is this an issue that still needs resolution?  
… If so, what do we feel that resolution ought to be?  

**David Chadwick:** This is also tied up into later discussions we've had about holders and subjects.  
… Holders are not properly represented in the document...  
… There is reference to holders but not what they are...  
… Maybe we could say subsumed by... one of the other issues about holders  

**Brent Zundel:** Would it be appropriate to close this issue and note that conversation is continuing...  

**David Chadwick:** I think... Issue 789...  

> *Brent Zundel:* subsumed by [https://github.com/w3c/vc-data-model/issues/789](https://github.com/w3c/vc-data-model/issues/789) closing

**Brent Zundel:** And we are out of time. Thank you everybody.  
… Next week will be at our earlier time, a little friendlier for you David.  
… I will let folks know on the mailing list, we'll be meeting more regularly.  

**David Chadwick:** This meeting was meant for New Zealand, for Kyle, wasn't it.  
… He definitely won't be at the next one - four hours earlier  

**Brent Zundel:** We can only do our best and hope  
… Thanks, appreciate the work. Hope for more clarity next week.  

---

</details>
