### ISSUE TITLE
issuer dependent credentials should be a URN

### ISSUE THREAD

**Issue by melvincarvalho** [w3c/vc-data-model#1058]
Following on from https://github.com/w3c/vc-data-model/pull/1049 (reproducing text for convenience)

Normally in Linked Data a term in a vocab will dereference so that it's possible to learn more about the term, for example the type of the item (string, number, date etc.) the human readable label and so on

Looking at this vocab, that seems not to be the case here wrt dereferening

If the term will not dereference would it not be better to remove the centralized http dependency, and extra round trip by using a URN?

RFC 8141 provides for a documentation to be given for URNs without requiring the round trips that many libraries (e.g. solidOS) will fire off automatically.

It would be good to understand this pattern from a Linked Data point of view.

If the aim is to provide a placeholder for json terms that are not registered, then there could be more benefit from a general solution that many systems could use, solving the problem of uniftying JSON and JSON-LD once and for all

> @iherman  I find the argument of using a URN for this case compelling. This should probably be raised as a separate issue.

A possible working proposal would be to register `urn:jsonld` with IANA at.  Or if a better name, or VC specific name, can be thought of, that's also fine.

https://www.iana.org/assignments/urn-namespaces/urn-namespaces.xhtml

This provides for text to be added to guide implementers, without incurring a round trip

Note that this would be useful not only for VC but the whole JSON / JSON-LD ecosystem

cc @OR13 @msporny

**Comment by msporny** [comment]
> If the term will not dereference would it not be better to remove the centralized http dependency, and extra round trip by using a URN?

No, it wouldn't be better because pointing to a web page that instructs the individual on how they can improve was the goal. Using a URN would defeat that goal. :)

**Comment by iherman** [comment]
> > If the term will not dereference would it not be better to remove the centralized http dependency, and extra round trip by using a URN?
> 
> No, it wouldn't be better because pointing to a web page that instructs the individual on how they can improve was one of the main goals. Using a URN would defeat that goal. :)

Oops, indeed. I forgot about that aspect, though I now remember this was mentioned in the past. My bad. And a URN would indeed defeat this goal.

**Comment by melvincarvalho** [comment]
@msporny thanks for the response.  URNs do indeed point to an instructive web page.  For example `urn:isbn` will point to an explanation of how ISBNs work, as per RFC 8141

The issue here is that you will incur a round trip to a term that does not exist.  That round trip will be fired off by many systems, for example, to determine the label or the type.  I'd like to understand if this pattern has been used before in specs or if there's some explanation behind it.   Typically, with linked data systems, that I've used, existing terms are defined.  If the term is just a name, and not dereferncable, normally you would use a URN. 

The URN approach appeals because it also paves a cow path for a general solution for problems of this kind, which is something that's been needed for a while in many projects, and specs.

I'd like to determine what is correct here, but also ask you if you think `urn:jsonld` would be an appropriate place holder, for a urn, as an alternative to an HTTP URI?

**Comment by msporny** [comment]
> @msporny thanks for the response. URNs do indeed point to an instructive web page. For example `urn:isbn` will point to an explanation of how ISBNs work, as per RFC 8141

I just typed: urn:isbn:9780140276664 into Chromium, Firefox, Brave, and Chrome and nothing happened in most of them. In the rest of them I saw "Your search - urn:isbn:9780140276664 - did not match any documents." ... that is, in the entire index of the Internet that these search companies have, we got zero results back.

That's the sort of experience we DO NOT want developers to have.

To be clear, I get what you're asking for from a Semantic Web modelling / solutions standpoint... but what you're asking for won't result in something that's useful for developers, which is who we're designing for with the solution that's been committed in the WG.

> The issue here is that you will incur a round trip to a term that does not exist.

Who is "you"? 

If "you" is a machine, who cares? We should probably list that issuer-defined URL in a robots.txt file as a "DO NOT cache/follow/index" link. It's only meant for humans.

> That round trip will be fired off by many systems, for example, to determine the label or the type. 

Citation... do you have data backing up the claim above. :)

I know that W3C ns documents have been hammered over the years by bad implementations... and perhaps the same will happen here... but given that the machines are getting no information back, and given how cheap an HTTP request is these days, and given that there are only a handful of developers we need to talk to if this happens (the software libraries that are actually making these requests), then it doesn't seem like an issue, to me, at least.

> I'd like to understand if this pattern has been used before in specs or if there's some explanation behind it. 

No, as far as I know, the pattern hasn't been used before. We're trying it out to see if it's a workable pattern. There was opposition to having a default `@vocab` that pointed to the VC vocabulary because that might promote term squatting, which some of us didn't want. There was opposition to not defining a default `@vocab` because developers would have a bad first experience when working w/ VCs. So, this was the compromise position... set a default vocabulary, but make it very clear to the developer that they're doing something that's probably ok in a "I'm just slapping stuff together" environment, but probably not ok if they're not conveying the semantics through another mechanism (or defining the semantics properly).

We'll see if this pattern works out well, and if it does, we might re-use the pattern in other places.

> Typically, with linked data systems, that I've used, existing terms are defined. 

This is not the case that the default `@vocab` in the VC spec is solving for.

> If the term is just a name, and not dereferncable, normally you would use a URN.

This is not the case that the default `@vocab` in the VC spec is solving for.

> The URN approach appeals because it also paves a cow path for a general solution for problems of this kind, which is something that's been needed for a while in many projects, and specs.

The URN approach is appealing for things you expect to never have to be dereferenced, or for cases where there are special rules for dereferencing that live outside of most web browser and web client implementations. Again, they are a good solution for a subset of problems, but definitely not for the problem we're addressing with the current default `@vocab` solution.

> I'd like to determine what is correct here, but also ask you if you think `urn:jsonld` would be an appropriate place holder, for a urn, as an alternative to an HTTP URI?

No, I'd mark `urn:jsonld` as an anti-pattern. We shouldn't be favoring a namespace for a serialization of RDF unless that namespace is strictly for the serialization itself. Undefined terms are not a JSON-LD only thing... they are a general problem in RDF, so some sort of `urn:rdf:undefined:` thing might be better... but then, I'm skeptical of that being more useful than just treating it as a blank node (or a named blank node).

Hope the above is helpful in explaining why URNs were not used as a solution to the default `@vocab` value problem in Verifiable Credentials.

**Comment by OR13** [comment]
I don't believe the VCWG should use URNs for any term definitions.

**Comment by melvincarvalho** [comment]
@msporny thanks for the detailed response, I'm going to take some time to digest fully.  I'll just reply to your specific question, quickly inline.  My motivation is wholly to create a good devX for folks wishing to use JSON and JSON-LD (but not the whole of RDF), and I think we both the same goal here, ie to on board developers.  I'll reply in full after doing some more research.  

> Who is "you"?  If "you" is a machine, who cares?

Linked data systems that use "follow your nose" such as [SolidOS](https://github.com/SolidOS/solidos).  Or systems working on the decentralized web that may not with to incur a centralized dependency on http / w3.org.

> No, as far as I know, the pattern hasn't been used before

Great to know, and thanks for pioneering something new.

> I forgot about that aspect, though I now remember this was mentioned in the past.

@iherman do you have a pointer to this?

**Comment by iherman** [comment]
> 
> > I forgot about that aspect, though I now remember this was mentioned in the past.
> 
> @iherman do you have a pointer to this?

I am sorry, but I do not have any. It would be fairly long to find a specific remark, because the discussion around the introduction of this extra `@vocab` was very long, part of fairly convoluted discussion threads around the usage of JSON-LD (or not) in general.

**Comment by melvincarvalho** [comment]
@iherman ok thanks.  It just seems to me that you were supportive of the suggestion of using a URN then decided against based on a conversation.  I think I get the general gist of it around being a match for the VCDM use case.  I would still recommend a URN but I see there isnt an appetite in the WG for that path, and that's fine with me

I think I have at this point solved the general issue of uniting JSON and JSON-LD, for use in decentralized scenarios, and not to rely on a centralized http website.  And that is NOT to use `urn:jsonld`, but rather, `urn:json`.  I'll note as an aside I had a corridor conversation with @timbl once and he suggested https://w3.org/ns/json# as a possible solution to this.

However given the feedback, I think everyone has a path in which they can work.  Thanks for the responses, this can be closed, and I'll take `urn:json` upstream.

**Comment by OR13** [comment]
If the goal is content URI, data URI should probably be used
