### ISSUE TITLE
Add references in vocabulary that link back to the VCDM document

### ISSUE THREAD

**Issue by andresuribe87** [w3c/vc-data-model#1061]
This issue is being separated from the conversation in https://github.com/w3c/vc-data-model/pull/1057#discussion_r1127606226

Tl;dr. there is terminology used in vocabulary that's defined in the VCDM. One example is the term `claim`

**Comment by iherman** [comment]
I agree this should be done. I would like to wait a few days, until the dust, hopefully, settles on some of the other PR-s (e.g., #1057, but also on PR-s affecting the exact definition of credentials vs. verifiable credentials) and then I will do this. I definitely "own" this problem.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-06-06-vcwg-special#section1-12) on 2023-06-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.12. Add references in vocabulary that link back to the VCDM document (issue vc-data-model#1061)

_See github issue [vc-data-model#1061](https://github.com/w3c/vc-data-model/issues/1061)._




**Brent Zundel:** Don't know if this is pre/post CR -- depends on making vocab and/or base context normative.  
… Going to mark this before CR, unless there are objections?  

> *Manu Sporny:* No objections.

</details>

**Comment by iherman** [comment]
This can be closed if and when #1209 is merged.

**Comment by iherman** [comment]
#1209 has been merged. @brentzundel this issue could/should be closed.

**Comment by brentzundel** [comment]
This has been addressed, closing
