### ISSUE TITLE
How could an issuer indicate that the VC is deliberately fake?

### ISSUE THREAD

**Issue by brentzundel** [w3c/vc-data-model#1070]
Gen has run into numerous cases where Issuers are building and testing VC-related infrastructure; real issuers and holders, but sample credentials.
We feel it would be beneficial to have a standard way for any issuer to indicate that a VC that has been issued as a sample (i.e., in a testing environment) should not be accepted as authentic.

We believe it could be as simple as adding an optional `"sampleCredential":"true"` field (or whatever else it should be called) to the VC Data Model.
@mavarley

**Comment by mavarley** [comment]
Yes - and I believe that normative guidance on the spec is the important part (especially in a decentralized environment) on how a Verifier uses this flag - i.e. "the information MUST NOT be trusted..."

Happy to hear others views or alternatives on this topic.

**Comment by David-Chadwick** [comment]
Good idea. "testCredential" or whatever. The property can have a null value.

**Comment by Sakurann** [comment]
I understand the need for such mechanism, but I am not sure this belongs in the core data model. if JSON-LD is used, the property can be defined in the `@context`, and if not, a JWT claim needs to be understood between the parties involved otherwise.

**Comment by mwherman2000** [comment]
My suggestion is to call it _trustLevel_ and make it an enumeration.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-04-12-vcwg#section4-6) on 2023-04-12

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.6. How could an issuer indicate that the VC is deliberately fake? (issue vc-data-model#1070)

_See github issue [vc-data-model#1070](https://github.com/w3c/vc-data-model/issues/1070)._




**Brent Zundel:** Brent raised this issue - we're using a production environment using real VCs without real date in them. Should this be clearly indicated? Verifiers should not trust it if presented to a verifier.  

> *Joe Andrieu:* Isn't feature freeze in effect?

**Sten Reijers:** Is there a possibility of marking it as a particular type such as test?  

**Dave Longley:** would be worried about that suggestion. Best way is to have a different issuer if in a production environment.  

**Brent Zundel:** that doesn't work if you want to test trusting the issuer.  

**Gabe Cohen:** this is a larger trust issue. Should be up to a verifier. Communicating level of trust to a verifier might be an interesting topic.  

**Oliver Terbu:** likes the credential type approach. Agrees with Dave that a production environment should have a different cert or something similar.  

**Brent Zundel:** likes suggestions made. Suggests moving it to the implementation guide for implementers.  
… issue #1063.  

> *Dave Longley:* could be a mess with SD-style VCs ... where every one of them would have to say "you must disclose if this is a test credential or not" ... and so on -- lots of potential problems with independent claims / selective disclosure mechanisms.

</details>

**Comment by brentzundel** [comment]
There didn't seem to be much consensus around adding a new property to the data model to handle this use case in a general way. Closing.
