### ISSUE TITLE
Verifiable Credentials Vocabulary v2.0 not contains "name" and "description"

### ISSUE THREAD

**Issue by suutaku** [w3c/vc-data-model#1074]
according [vc 2.0 schema](https://www.w3.org/ns/credentials/v2), a `name` and a `description` was defined. but in `https://www.w3.org/2018/credentials/#VerifiableCredential`, i cannot found any about `name` or `description`. it's confused me.
When i use `json-ld` to process my document, if `frame blank node` option on, the `name` and `description` value will be `null`.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-04-12-vcwg#section4-8) on 2023-04-12

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.8. Verifiable Credentials Vocabulary v2.0 not contains "name" and "description" (issue vc-data-model#1074)

_See github issue [vc-data-model#1074](https://github.com/w3c/vc-data-model/issues/1074)._




**Brent Zundel:** Verifiable Credentials Vocabulary v2.0 not contains "name" and "description".  

> *Orie Steele:* name and description are not in [https://www.w3.org/2018/credentials/](https://www.w3.org/2018/credentials/).

**Manu Sporny:** i'll take it.  

**Brent Zundel:** Manu assigned to it.  

</details>

**Comment by OR13** [comment]
I don't know how to update the vocabulary since it is built from an RDF tool, I am not familiar with.

**Comment by iherman** [comment]
Per the current JSON-LD context file, the `name` term is mapped on `https://schema.org/name` and `description` on `https://schema.org/description`. Ie, these terms are not _defined_ by VCDM and, therefore, should not appear in the vocabulary file.

**Comment by brentzundel** [comment]
Thank you for that answer @iherman.
I am marking this `pending close` and will close it in a week if there are no objections.

**Comment by brentzundel** [comment]
No objections raised since marked `pending close`. Closing
