### ISSUE TITLE
Better visualization of data model

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-model#1095]
We have some images in our core spec today.

It would be nice to be able to automatically produce visualizations, especially of examples.

So we can see the how `proof` and `id` and other fields that relate to `@type`, `@vocab`, `@id`, `@container` etc...

Originally discussed in: https://github.com/w3c/vc-data-model/issues/973

**Comment by decentralgabe** [comment]
I'm in favor of better visualizations–they may be better suited for inclusion in an appendix. If they could auto-render based on existing examples in the spec -- even better. I think we more broadly need to do a glow up of our examples (more, better).

**Comment by brentzundel** [comment]
I love this idea but am completely unqualified to try and make it happen.

**Comment by OR13** [comment]
This is sorta blocked by: 

https://github.com/w3c/vc-data-model/issues/1103

You get different visualizations for different values of a context.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-05-24-vcwg#section2-2) on 2023-05-24

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.2. Better visualization of data model (issue vc-data-model#1095)

_See github issue [vc-data-model#1095](https://github.com/w3c/vc-data-model/issues/1095)._




**Kristina Yasuda:** Images in the data model.  
… Is there anyone who could take the lead on this?  

> *Manu Sporny:* This is a great idea, we should have it in the spec, there are some possibilities... but starved for time. :(.

**Michael Prorock:** I pun intended ... think this is a beautiful idea but have no bandwidth to deal with it. If no one else is willing to stand up I'm willing to mark as pending closed.  

> *Orie Steele:* suggest closing.

**Brent Zundel:** Another option is to mark this as post CR. This is proposing completely editorial changes. Theoretically we'd have time and bandwidth once we're in CR and going through that process. Now we could say "our diagrams are prettier!" and that's not a substantive change.  

> *Michael Prorock:* +1 brent - this is editorial in nature.

**Kristina Yasuda:** Any objections to post CR label?  
… Ok, we'll do that.  

> *Orie Steele:* [https://github.com/digitalbazaar/respec-vc/pull/8](https://github.com/digitalbazaar/respec-vc/pull/8).

**Orie Steele:** I do think ... Manu raised a concern regarding the existing SVG assets that we have. Something to the effect that we need semantic annotation so we can align with a11y requirements of W3C.  
… I wanted to confirm that W3C requires SVG with web a11y with annotation to provide images in specs.  
… I've also updated a plugin for examples and updated that to support the latest VC-JWT spec.  
… It contains some visual examples using mermaid.  

**Kristina Yasuda:** I'm keeping post CR for now.  
… If later on -- we can close or address.  

</details>

**Comment by OR13** [comment]
https://transmute-industries.github.io/respec-vc-jwt/

Made this after the call yesterday.
