### ISSUE TITLE
Clarify what "reserved properties might be more formally defined in future versions" means

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1098]
@David-Chadwick wrote:
> Some (most) of these properties have already been formally defined in v1.0 and v1.1 with the words MUST etc. being part of their definitions. It is not clear to me what it means when v2 says "might be more formally defined in future versions". More formally than what? Does it mean the MUST might be changed to MAY, or further MUSTs added, or simply that the semantics might be tweaked somewhat? There is a big difference in these two extremes.

**Comment by David-Chadwick** [comment]
Once we have the full list of reserved properties and we know which existing properties from v1 and v1.1 will be removed entirely from v2, then we can improve the description in order to answer this issue.

**Comment by OR13** [comment]
Related: https://github.com/w3c/vc-data-model/issues/1103

If we make the vocabulary normative and the context normative, this seems easier to achieve.

**Comment by brentzundel** [comment]
had a bit of a chat about this in #981

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-01-17-vcwg#section2-3) on 2024-01-17

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.3. Clarify what "reserved properties might be more formally defined in future versions" means (issue vc-data-model#1098)

_See github issue [vc-data-model#1098](https://github.com/w3c/vc-data-model/issues/1098)._




**Manu Sporny:** I think what we meant with this text -- this was before we marked things at-risk and had the table of reserved properties...  
… I think we get rid of the statement "might be more formally defined in future versions" if we remove things from the spec. Either we formally define and have a concrete thing to point to or not -- and not say it might be more formally defined in the future.  
… Orie said that once we make the vocab normative and so on it might be easier to achieve but that didn't end up happening, we have a normative vocab and context, it doesn't change the fact that we probably shouldn't be saying...  
… Now that I'm reading this ... in the reserved properties section we say that the properties might be more formally defined in the future. I think we need David.  

**Jeffrey Yasskin:** Another case where making this a registry would help you. If this is a registry with some expert review and status column that is provisional/standardized, that by itself implies that they're expected to get more formally defined. Then things can move between different specifications, but registry deals with that for you.  

**Brent Zundel:** Chair hat off, registries would be a sensible methodology for this WG to engage with.  

**Manu Sporny:** We have vc-specs-dir and could have extensions put there. We do have a core vocab, but the question is whether anyone can just come along and register in that core vocab and we have to add it to the vocab officially and so on.  
… Maybe that's ok -- I don't know. A registry would be easy to deal with, I agree, but the other challenge for people who are new, we did define these extension points in 1.1.  

> *Jeffrey Yasskin:* [https://www.w3.org/2023/Process-20231103/#reg-pub](https://www.w3.org/2023/Process-20231103/#reg-pub) has "Registries can be published either as a stand-alone technical report on the Registry Track called a registry report, or incorporated as part of a Recommendation as a registry section.", so you don't even need to move it to the extensions report.

**Manu Sporny:** Some are clearly being used. There's a question around "at what point does it become a part of the core spec". I think we need that other issue to talk about.  
… +1 to having a registry generally that would be one way of dealing with some of these properties.  

**Brent Zundel:** We could have a "registries" section of the spec, based on what Jeffrey said above.  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-02-21-vcwg#section4-2) on 2024-02-21

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.2. Clarify what "reserved properties might be more formally defined in future versions" means (issue vc-data-model#1098)

_See github issue [vc-data-model#1098](https://github.com/w3c/vc-data-model/issues/1098)._




**Brent Zundel:** This is about setting up a mini registry inside the spec.  
… What are the next steps?  

**David Chadwick:** The issue sets it out clearly.  
… It's a question of semantics.  
… If something is already defined, what does it mean to more formally define it?  

**Manu Sporny:** The distinction is between a term being defined, referencing a URL, and writing text about the definition.  
… For example, we may reserve render method but we won't write normative text about it.  

**David Chadwick:** I can buy that.  
… We have a table of reserved properties anyway.  
… We can say that "these terms are reserved" and may be defined later.  

> *Manu Sporny:* +1 to that suggestion.

**David Chadwick:** I can create a PR.  

</details>

**Comment by David-Chadwick** [comment]
PR #1447 created to fix this

**Comment by msporny** [comment]
PR #1447 has been merged, closing.
