### ISSUE TITLE
VC Vocabulary v2.0 does not have any term definitions

### ISSUE THREAD

**Issue by andresuribe87** [w3c/vc-data-model#1117]
[This section](https://www.w3.org/2018/credentials/#term_definitions) is empty. I'm not sure if this is intentional, but I do remember seeing it having multiple terms in the past.

Should the section be populated?

**Comment by msporny** [comment]
Just looking into this issue a bit further... Echidna isn't publishing the latest vocabulary document because the Github build actions were never set up. Compare these build instructions (that build the Github Pages):

https://github.com/w3c/vc-data-model/blob/main/.github/workflows/gh-pages.yml#L32-L37

to these build instructions (that build the Echidna pages):

https://github.com/w3c/vc-data-model/blob/main/.github/workflows/echidna.yml

Also, note that we don't publish the vocabulary.html file at all via Echidna today. I suspect we're loading the Github pages one via a W3C proxy (or something to that effect). If we want to publish the vocabulary via W3C, which there seems to be consensus building to do so, we'll have to use a more involved Echidna set up (documented here):

https://w3c.github.io/spec-prod/#multiple-specs-in-same-repository

The next step is to see what file W3C TR space is serving when this URL is hit: https://www.w3.org/2018/credentials/

... and then make sure that file is updated as a part of the Echidna publication process. The future state will have us publishing a "index.html" file as well as a "vocabulary.html" file.

**Comment by iherman** [comment]
This problem has been solved. Marking this issue as pending close.
