### ISSUE TITLE
Media Types and HTTP

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-model#1118]
I am not sure where this goes, but this would help solve a lot of interoperability issues we have observed regarding http apis for verifiable credentials.

Currently, due to how open ended "Verifiable Presentation" are, I can see us potentially not needing a separate content type for them... 

### Case 0

```ts
const res = await axios.get('https://platform.example/credentials', {
  headers: {
    'Accept': 'application/vp+ld+json' // ask for a presentation
  }
});
```

```json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2"
  ],
  "type": "VerifiablePresentation",
  "verifiableCredential": [  ... credentials of ANY media type ]
}
```

### Case 1

```ts
const res = await axios.get('https://platform.example/credentials/urn:uuid:123', {
  headers: {
    'Accept': 'application/vc+ld+json' // ask for a single credential
  }
});
```

```json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2"
  ],
  "id": "urn:uuid:123", or "https://platform.example/credentials/urn:uuid:123"
  "type": "VerifiableCredential",
  ...
}
```

### Case 2

```ts
const res = await axios.get('https://platform.example/credentials', {
  headers: {
    'Accept': 'application/vc+ld+json' // ask for many credentials?
  }
});
```

```json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2"
  ],
  "type": "VerifiablePresentation",
  "verifiableCredential": [  ... credentials of only media type `vc+ld+json` ? ] 
}
```

Several  of the related cases seem like they might be invalid, it would be nice to developers to point out the valid and invalid cases...

See the following informative sections of the spec:

- https://w3c.github.io/vc-data-model/#presentations

And the following normative sections of the spec:

- https://w3c.github.io/vc-data-model/#presentations-0

**Comment by andresuribe87** [comment]
The object being returned in Case 2 is not conformant with the VCDM (e.g. it doesn't contain `credentialSubject`). Thus, it's media type shouldn't be `application/vc+ld+json`. I believe that's an invalid case. 

Case 0 and Case 1 may make sense to me.

**Comment by brentzundel** [comment]
We now have a content type for VPs, is there more that needs to be done to address this issue, or can it be closed?

**Comment by OR13** [comment]
Can be closed when we comment on the use of `Accept` and `Content-Type` regarding the media types we are requesting registration for.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-07-05-vcwg#section2-5) on 2023-07-05

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.5. Media Types and HTTP (issue vc-data-model#1118)

_See github issue [vc-data-model#1118](https://github.com/w3c/vc-data-model/issues/1118)._




**Manu Sporny:** I think we have clear media types in the spec now.  
… That's what this issue was attempting to resolve.  
… We could mark it pending close.  
… I'd be interested to hear from Orie.  

**Orie Steele:** This issue is specific to HTTP.  
… At least some basic guidance on where you expect them to show up is needed to close this issue.  
… We need a sentence about registering types with IANA.  
… It could show up in the content type or accept header.  

**Manu Sporny:** What Orie is asking for is to say somewhere that it is expected that HTTP endpoints use accept headers, etc.  

> *Orie Steele:* +1 manu.

> *Orie Steele:* explain how to use the requested registrations.

**Manu Sporny:** This wouldn't go in the IANA Considerations.  
… This is ready for PR.  

> *Orie Steele:* +1 selfissued and manu.

> *Michael Prorock:* +1.

**Michael Jones:** No, it doesn't go in the IANA registration, it goes in text in the body of the specification describing how we expect to use the media types. I've registered a lot of media types, none of them say what you use them for in the registration.  

**Kristina Yasuda:** I'm assigning Orie.  

</details>
