### ISSUE TITLE
Is Verifiable Credentials sufficiently different from Verifiable Claims?

### ISSUE THREAD

**Issue by trbouma** [w3c/vc-data-model#112]
Maybe, I'm a bit late to this discussion and my issue is moot, but I don't see enough of a difference between Verifiable Credentials (VCr) and Verifiable Claims (VCl) to warrant a separate model.

I understand the motivation to model the document world (e.g. driver's license) but I would argue we are trying to move away from the document construct. In my opinion, a VCr can be modeled as a VCl which, in turn, contains a set of VCls.

My inclination would be to keep the models together as one. Further, I see 'credential' as simple a claim (or collection of claims) that I hold.

**Comment by msporny** [comment]
> I don't see enough of a difference between Verifiable Credentials (VCr) and Verifiable Claims (VCl) to warrant a separate model.  In my opinion, a VCr can be modeled as a VCl which, in turn, contains a set of VCls.

We're attempting to avoid modeling the document world. Fundamentally, we need containers and we need to call those containers specific things so that we can communicate the concepts clearly to developers and organizations. There are really two containers, the first holds a set of claims -- we call this a Credential. The second holds a set of credentials -- we call this a Profile.

While it is possible to model everything as a claim... turtles all the day down, this confuses most developer conversations we have as people want to be able to call a specific bundle of claims something, and so we have "Credential". 

Another issue we've had when not using the word "Credential" is that a non-trivial number of people (for some reason) jump to the conclusion that all "claims" are true. That is, if a claim exists, it must be true, when that's not the data model at all. Adding the "credential" terminology in helps people understand that claims are asserted by an entity, and some credentials are fraudulent, outdated, etc.

Yet another issue with combining the claims/credentials data model is that one needs to be able to make statements about the claims themselves. From a data modeling perspective, there are three graphs of information -- the first graph (Claims) contains the claims themselves, the second graph (Credential) contains assertions about the claims (issuer, validity period, terms of use) made by the issuer, and the third graph (Profile) contains assertions about multiple Credentials (a set of second graphs) made by the subject.

There has been a tremendous amount of debate over the data model spanning at least 4+ years and we've settled on something that seems to work for everyone, having considered what you propose above. I don't expect that we'd be able to get consensus around combining the model as you suggest above given the arguments above.

I'm going to leave the issue open for now so that others from the group that may have other thoughts can weigh in.

**Comment by burnburn** [comment]
No objections, so closed.

**Comment by msporny** [comment]
This was discussed on the call today - consensus position was what I said above (no desire to combine data model in the way that @trbouma mentioned above): https://www.w3.org/2018/03/13-vcwg-minutes.html#item04

**Comment by trbouma** [comment]
Thanks. This makes sense and a good evolution of the model. As you may be aware - we (Government of Canada) separated 'credentials' from 'identity' (credentials being anonymous/pseudonymous). That was the first iteration; how we initially defined 'credential' is really now similar to 'authenticator'.  What is being proposed now is more general and maintaining a useful distinction separating credentials from claims, where credentials are not necessarily anonymous/pseudonymous.

**Comment by msporny** [comment]
@trbouma wrote:
> What is being proposed now is more general and maintaining a useful distinction separating credentials from claims, where credentials are not necessarily anonymous/pseudonymous.

Yes, correct. We also had a breakthrough at the most recent VC face-to-face meeting in that the package now supports the full range of credential types (anonymous, pseudonymous, weakly identified, strongly identified). We believe we're meeting the WGs needs while also not overly complicating the core data model.
