### ISSUE TITLE
Should we bundle contexts for credentialSchema and credentialStatus int he v2 core context?

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-model#1134]
The argument for doing so is that they are used by data integrity proofs, and this would make things easier for developers.

If we don't do this, we should make sure to include normative guidance on adding context values to the context array when these features are used, to avoid confusion regarding term definitions.

**Comment by iherman** [comment]
(Meta comment.) 

This issue seems to refer to the same underlying question than, for example, issues #1091 or #1090 (I did not do an exhaustive search). That question can be formulated as:

> Should the V2 Core context include ***only*** terms that are strictly defined in the VCDM specification, or should it also include references to other terms, constructions, etc.?

To make it clear, the current context is based on the answer "no". If the answer is "yes", then the v2 context should be significantly pruned, removing the terms listed in the issue title, the terms that are currently defined in other specs or vocabulary, like DI, ODRL, or schema.org specs, and would also lead to the removal of the `@vocab` statement.

Note that the question is also closely related to #1103.

I would propose to close this issue and open an issue with that question instead. That would also makes it easy to handle #1091 and #1090 (and possibly others).

**Comment by OR13** [comment]
Noting the current vc json schema does not require context bundling, see https://w3c.github.io/vc-json-schema/

**Comment by OR13** [comment]
@decentralgabe you are volunteered for this.

**Comment by decentralgabe** [comment]
Does bundling context meaning adding term definitions for `JsonSchema2023` and `CredentialStatusList2021` etc in the core context? If so I'm willing to make that change.

**Comment by OR13** [comment]
@decentralgabe yes, assume W3C will define the URLs for them, same as it did for "VerifiableCredential".
