### ISSUE TITLE
Missing security considerations on MITM, cloning etc.

### ISSUE THREAD

**Issue by awoie** [w3c/vc-data-model#1138]
We should add to the security considerations section that the VCDM does not prevent from MITM, replay and cloning attacks. This applies to online and offline use cases. The VCDM does not have any mechanisms to allow a verifier to understand whether the presented VC belongs to the holder.

**Comment by decentralgabe** [comment]
+1 to pointing to this being handled by securing mechanisms. As part of this it may be worth opening issues on existing securing mechanisms to make sure this is covered.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-07-12-vcwg#section5-2) on 2023-07-12

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.2. Missing security considerations on MITM, cloning etc. (issue vc-data-model#1138)

_See github issue [vc-data-model#1138](https://github.com/w3c/vc-data-model/issues/1138)._




**Brent Zundel:** missing security considerations... seems post CR.  

> *Manu Sporny:* +1 to after CR.

**Brent Zundel:** who will be assigned?  

**Gabe Cohen:** I can take it.  

</details>
