### ISSUE TITLE
Depreciation of "Evidence"

### ISSUE THREAD

**Issue by rceleste125** [w3c/vc-data-model#1147]
The Open Credentialing Initiative (OCI, oc-i.org) develops and maintains W3C-based Verifiable credentials, openAPIs, and conformance criteria for use by the US Pharmaceutical industry supporting the Drug Supply Chain Security Act (DSCSA).  We have been asked by the industry to explore the use of Evidence as a means of providing transparency to the due diligence that backs up a claim.  

There is significant interest in using this extension and we would like to request that depreciation be reconsidered.

Bob Celeste
rceleste@oc-i.org

**Comment by decentralgabe** [comment]
Deprecation does not mean you cannot use the property. In fact there are uses of the property here: https://w3c.github.io/vc-specs-dir/#evidence

What deprecation does mean is that there is not a normative evidence spec we can reference to pass CR. Because the data model is JSON LD, which provides a mechanism for decentralized extensibility, you will always be able to add an evidence property to a credential.

**Comment by brentzundel** [comment]
The `evidence` keyword is still being reserved, but the section that describes how to normatively use the `evidence` extension suffers from a lack of implemented specifications that can be pointed to from the VC data model. 

Removal of the `evidence` section does not prohibit implementers from continuing to explore the use of `evidence` within VCs, but rather makes clear that currently, work on `evidence` is in an exploratory state.

**Comment by brentzundel** [comment]
No objections raised since marking `pending close`.
Closing, but note that #870 is open to continue tracking the `evidence` extension point.
