### ISSUE TITLE
VC Identity owner impersonation

### ISSUE THREAD

**Issue by r3-za** [w3c/vc-data-model#115]
I am looking into a specific attack vector of using VCs..
It is possible for a person to impersonate a VC holder by stealing the identity owner's phone and sharing the VC with service providers. Are there any mechanisms as part of the VC work that prohibit such attacks? 

I am looking into how the identity owner's key pair (or biometrics) be used as a way to prevent attackers from impersonating the identity owner. However if the identity owner's phone is stolen and hacked into (e.g., by guessing the pin) chances are their private key is also compromised.

**Comment by msporny** [comment]
> It is possible for a person to impersonate a VC holder by stealing the identity owner's phone and sharing the VC with service providers. 

Yes by:

* Not password/pin protecting their phone
* Using a weak password on their wallet

... but those are the same attacks for any website.

> Are there any mechanisms as part of the VC work that prohibit such attacks?

No, because what you describe are the common form of attack on any mobile phone-based system.

> I am looking into how the identity owner's key pair (or biometrics) be used as a way to prevent attackers from impersonating the identity owner. However if the identity owner's phone is stolen and hacked into (e.g., by guessing the pin) chances are their private key is also compromised.

There are ways to mitigate this:

* Turn on password pin/pattern protection.
* Turn on facial biometric login w/ a very long pin pattern
* Password protect your wallet (wallet specific)
* Password protect your keys (wallet specific)
* Use a separate Hardware-based key mechanism (wallet specific)
* All of the above.

There are various mitigations that are not specific to VC that we expect that VCs will use to prevent the sorts of attacks that you are talking about.

In general VC's have the following replay protections in place for VCs delivered to verifiers:

* Timestamp and nonce (to prevent replay attacks after a certain time)
* Domain binding (to prevent replay attacks to a different verifier)

Does that answer your question?

**Comment by msporny** [comment]
Add spec text in security section about this attack.

**Comment by msporny** [comment]
I propose that we resolve this issue by adding the following spec text to the Security Section of the specification:

## Device Theft and Impersonation

When verifiable credentials are stored on a personal device and that device is stolen by an attacker, it may be possible for the attacker to then gain access to systems using the victim's verifiable credentials. Mitigations for this attack include:

* Enabling password, pin, pattern, or biometric screen unlock protection.
* Enabling password, biometric, or multi-factor authentication for the credential repository.
* Enabling password, biometric, or multi-factor authentication when accessing cryptographic keys
* Utilizing a separate hardware-based signature mechanism.
* All or any combination of the above.

**Comment by David-Chadwick** [comment]
Looks good to me
