### ISSUE TITLE
Transfer respec-vc to W3C VCWG?

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1154]
For several years now, we've been using a ReSpec plugin called respec-vc. It takes unsecured VCs and generated secured VCs as examples. We use this throughout the specification to show what a secured VC looks like using Data Integrity and using VC-JWT:

https://w3c.github.io/vc-data-model/#example-usage-of-the-id-property

This code has been hosted at Digital Bazaar for a while now:

https://github.com/digitalbazaar/respec-vc

... and while we're happy to continue to host and develop the code, perhaps a better place to host/develop the code is the W3C VCWG (or the CCG). This issue is to track where we should keep the code base.

/cc @brentzundel @Sakurann @iherman

**Comment by iherman** [comment]
I do not see any problems either transferring the repo to W3C (with the extra metadata in w3c.json saying that this tooling repo is "owned" by the VC WG), or to create a new repo where you can reproduce the code. As you prefer.

**Comment by m00sey** [comment]
transferring this seems to be a positive move.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-07-05-vcwg#section2-3) on 2023-07-05

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.3. Transfer respec-vc to W3C VCWG? (issue vc-data-model#1154)

_See github issue [vc-data-model#1154](https://github.com/w3c/vc-data-model/issues/1154)._




**Manu Sporny:** This is a post-CR thing.  

**Kristina Yasuda:** Why didn't this already happen? What's the IPR status?  

**Manu Sporny:** This just didn't happen. I believe it's Open Source.  

> *Phillip Long:* +1 to transferring - BSD is good!

**Kristina Yasuda:** It's currently a BSD 3 clause license.  
… The licensing needs to be addressed.  
… The next three are horizontal review. I'll skip them. We don't have horizontal review responses yet.  

</details>

**Comment by iherman** [comment]
Note that I cannot transfer this by myself, because I do not have admin rights in the source repo...

**Comment by msporny** [comment]
This has been done: https://github.com/w3c/respec-vc
