### ISSUE TITLE
Consider removing Use Cases summary from core DM

### ISSUE THREAD

**Issue by brentzundel** [w3c/vc-data-model#1169]
When the VC Data Model was first published, the Use Cases document wasn't in the state it currently is. So a section of use cases was added to the core data model.

Now that we have a published and (soon to be new and improved) Use Cases document, I propose we rely on that document and remove the use cases summary from the core data model.

Concretely, I think we should remove [section 1.3](https://w3c.github.io/vc-data-model/#use-cases-and-requirements) and instead point to [Use Cases and Requirements](https://www.w3.org/TR/vc-use-cases/)

**Comment by OR13** [comment]
I agree.

**Comment by msporny** [comment]
> Concretely, I think we should remove [section 1.3](https://w3c.github.io/vc-data-model/#use-cases-and-requirements) and instead point to [Use Cases and Requirements](https://www.w3.org/TR/vc-use-cases/)

I'd be ok with doing that if someone cross-references all of the items in this list and ensures they are captured in the use cases.

The reason we had this section initially was to ensure that the WG wrote down exactly what sort of ecosystem they wanted to create; that is, the three-party ecosystem (since we had organizations claiming that the three-party ecosystem was unnecessary at the time, or were confused about what such an ecosystem actually looked like).

I'd feel more comfortable if this section was moved to the Use Cases document in its entirety, and then whittled away over time as the statements were incorporated into that document.

**Comment by OR13** [comment]
I'd be fine moving the section to use cases as a first step.

**Comment by brentzundel** [comment]
@jandrieu and @KDean-GS1 there is a suggestion to either entirely remove, or move the [VC Data Model Uses Cases section](https://w3c.github.io/vc-data-model/#use-cases-and-requirements) into [VC Use Cases](https://www.w3.org/TR/vc-use-cases/). I would appreciate your thoughts here.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-07-19-vcwg#section2-1) on 2023-07-19

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.1. Consider removing Use Cases summary from core DM (issue vc-data-model#1169)

_See github issue [vc-data-model#1169](https://github.com/w3c/vc-data-model/issues/1169)._




**Brent Zundel:** 1169 - since the Use Cases say what we want to say, I suggest removing the Use Case summary from the data model.  

**Manu Sporny:** I fully support removing it as long as we make sure we have accounted for everything.  
… The list is important as we spent a lot of time making sure that it was complete.  

> *Manu Sporny:* +1 this is post CR.

**Brent Zundel:** This is purely editorial, so I will label it post-CR.  

**Joe Andrieu:** if someone wants the granularity expressed in the list, they can go to the separate document. However, a few concrete use-case examples would be beneficial.  

</details>
