### ISSUE TITLE
Provide guidance for when hash values do not match specification text

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1177]
@jyasskin [wrote](https://github.com/w3c/vc-data-model/pull/1158#discussion_r1244063720):
> What are implementations supposed to do if they [the hash values] don't match?

The current specification mentions that certain files should match certain hash values but does not provide guidance to processors on what to do when dereferenced values do not match the hashes provided in the specification. The specification should provide guidance on what to do when hash values don't match, or how to ensure that the hash values always match.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-08-02-vcwg#section2-2) on 2023-08-02

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.2. Provide guidance for when hash values do not match specification text (issue vc-data-model#1177)

_See github issue [vc-data-model#1177](https://github.com/w3c/vc-data-model/issues/1177)._




**Kristina Yasuda:** manu, status?  

**Manu Sporny:** I will do this PR, straighforward PR.  

</details>

**Comment by msporny** [comment]
PR #1249 has been raised to address this issue. This issue will be closed once PR #1249 has been merged.
