### ISSUE TITLE
Portions of data model spec should be considered for removal

### ISSUE THREAD

**Issue by mprorock** [w3c/vc-data-model#1188]
Certain sections of the data model spec are informative only, but open more questions than they close and either conflict with other terminology or would need extensive work to be useful.  

Especially thinking of bearer credentials here.  Any reason we should not remove sections like that to improve overall readability and understanding of the text?

**Comment by OR13** [comment]
I really feel we should remove as much informative text from the core TR as possible.

We have other documents which can host informative content, such as use cases, and implementation guide.

**Comment by TallTed** [comment]
> Certain sections of the data model spec

*Which* sections?  This sort of question needs specifics, and probably should be one issue per section of which you speak.

**Comment by OR13** [comment]
On the call today, it was suggested to raise separate issues for each section, and debate the merits of each section.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-07-19-vcwg#section2-4) on 2023-07-19

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.4. Portions of data model spec should be considered for removal (issue vc-data-model#1188)

_See github issue [vc-data-model#1188](https://github.com/w3c/vc-data-model/issues/1188)._




**Manu Sporny:** I think we need to make other PR and issues for other informative sections for removal.  
… For this *specific* issue, I would suggest closing it as it is not actionable itself.  

> *David Chadwick:* +1 manu.

**Orie Steele:** I agree with Manu. However, I find that it is difficult to deal with others not taking interest in informative statements.  

> *Manu Sporny:* +1 to use less words to communicate the same concepts.

**Orie Steele:** Therefore, I would suggest reducing the word-count to make the important parts count more.  

> *Manu Sporny:* +1 to improving current text.

> *Dave Longley:* +1 to make things easier to understand in fewer words as possible.

> *Manu Sporny:* +1 to close, but raise issues/PRs on specific sections to rework/remove.

> *Ted Thibodeau Jr.:* comment already added.

**Sebastian Crane:** Opinion not exactly contrary to Orie, before we remove, we might want to have things in less formal but easily accessible place.  

> *Orie Steele:* +1, we have use cases, imp guid as notes...

**Brent Zundel:** so move to use cases, or implementation guide?  

**Sebastian Crane:** Yes, exactly. You can have a pithy definition, but can only understand it after having engaged in years of discussion.  

> *Orie Steele:* I prefer references to informative stuff, not inlining large amounts of informative text.

> *Sebastian Crane:* I don't even think referencing it within the spec is necessary, just making it accessible on a website.

</details>

**Comment by brentzundel** [comment]
no objections raised since marked `pending close`, closing.
