### ISSUE TITLE
Example could include @language

### ISSUE THREAD

**Issue by aphillips** [w3c/vc-data-model#1191]
## Proposed comment

Contexts
https://www.w3.org/TR/vc-data-model-2.0/#contexts
https://www.w3.org/TR/vc-data-model-2.0/#example-usage-of-the-context-property

Example 4 includes an `@context` example.  It might be useful to illustrate other context values, particularly `@language` in the context, given that the `name` of _Example University_ is in English.

Note that this comment is entirely editorial. We recognize that your "internationalization considerations" section covers this in detail and that your specification is not a primer about localizability.

**Comment by OR13** [comment]
@shigeya can you comment on this?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-07-19-vcwg#section2-5) on 2023-07-19

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.5. Example could include @language (issue vc-data-model#1191)

_See github issue [vc-data-model#1191](https://github.com/w3c/vc-data-model/issues/1191)._




**Orie Steele:** I think we talked about the subject of #1191 at the last TPAC.  
… I thought we had concluded that the JSON-LD `@language` feature had some issue with it and so wasn't recommended?  

**Manu Sporny:** The issue is that people aren't using the feature.  

> *Orie Steele:* its the JSON syntax for RDF lang tags.

**Sebastian Crane:** Is this related to the RDF language tags?  

**Manu Sporny:** Yes, this is just an additional example of that.  

**Sebastian Crane:** I can try to handle this issue.  

</details>

**Comment by shigeya** [comment]
If I understand JSON-LD spec correctly, one of my projects related to educational certification will use the `@language` soon.

While the internationalization-related specification is now fully covered by JSON-LD spec, it is still helpful to show how in the VCDM spec.

According to the meeting transcript, Sebastian Crane will work on it. I am also willing to address this.

Thanks for mentioning me @OR13.

**Comment by msporny** [comment]
We now have multiple examples in the specification that use `@language` inline:

https://www.w3.org/TR/2024/WD-vc-data-model-2.0-20240106/#example-usage-of-the-name-and-description-property-0
https://www.w3.org/TR/2024/WD-vc-data-model-2.0-20240106/#language-and-base-direction

The WG could not come to consensus on suggesting the use of `@language` in the `@context` or not, so the specification stays silent on the matter. That said, there are now plenty of examples and sections that discuss i18n approaches supported by the specification.
