### ISSUE TITLE
Explain that natural language examples are illustrative

### ISSUE THREAD

**Issue by aphillips** [w3c/vc-data-model#1192]
Throughout the document there are examples of `name` fields carrying natural language text. These strings are used as human readable representations of the locale-neutral data representation within the data file and thus serve to concisely illustrate to spec readers what it going on.

An example of this is in [Example 5](https://www.w3.org/TR/vc-data-model-2.0/#example-usage-of-the-id-property):

```json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
    "https://www.w3.org/ns/credentials/examples/v2"
  ],
  "id": "http://university.example/credentials/3732",
  "type": ["VerifiableCredential", "ExampleDegreeCredential"],
  "issuer": "https://university.example/issuers/565049",
  "validFrom": "2010-01-01T00:00:00Z",
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "degree": {
      "type": "ExampleBachelorDegree",
      "name": "Bachelor of Science and Arts"
    }
  }
}
```

In this example, the field `name` says "Bachelor of Science and Arts", which is an English-language representation of the value.

Other examples show personal names such as "Jayden Doe" and "Jane Doe". Again, these are illustrative and not part of the data structures defined in this spec.

The specification contains an "Internationalization Considerations" section that describes what to do with natural language strings and which links to String-Meta and this problem is not the direct concern of this specification. However, it might be useful to have a more prominent note about the use of examples in English for spec readability? Perhaps by adding a "note" to the Section 1 (Introduction) similar to the following or by including at the start of the "internationalization considerations" section:

> Note: Examples provided throughout this document include descriptive fields in English
> to assist with understanding of the spec. These examples do not necessarily reflect the data 
> structures needed for international use.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-07-19-vcwg#section2-6) on 2023-07-19

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.6. Explain that natural language examples are illustrative (issue vc-data-model#1192)

_See github issue [vc-data-model#1192](https://github.com/w3c/vc-data-model/issues/1192)._




**Manu Sporny:** I'll address 1192.  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-01-24-vcwg#section2-2) on 2024-01-24

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.2. Explain that natural language examples are illustrative (issue vc-data-model#1192)

_See github issue [vc-data-model#1192](https://github.com/w3c/vc-data-model/issues/1192)._




**Brent Zundel:** This is editorial, it is post CR and also i18n. This is assigned to you, can you give us an update on this issue?  
… This looks editorial.  

**Manu Sporny:** I can take this, this came up during their pre-CR review. They want us to say "our examples are in English to make the spec easier to read".  
… They would rather we have i18n everything in the specification, but understand that it's harder to read examples if we have every single human-readable text string have 15 different translations.  

**Brent Zundel:** Ok, that makes sense. This one is straightforward so if anyone wants to step forward and grab it.  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-02-28-vcwg#section3-1) on 2024-02-28

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.1. Explain that natural language examples are illustrative (issue vc-data-model#1192)

_See github issue [vc-data-model#1192](https://github.com/w3c/vc-data-model/issues/1192)._




**Manu Sporny:** I will do this -- anything that's assigned to me, I have 9 issues assigned to me, as a ready for PR issue, I will do all of those.  
… Feel free to check in on each one, but my answer will be "I will raise a PR for this".  

**Brent Zundel:** So the main question will be -- do you need any group discussion or decision from the group?  

**Manu Sporny:** Nothing needed here.  

</details>

**Comment by msporny** [comment]
PR #1449 has been raised to address this issue. This issue will be closed once PR #1449 has been merged.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-03-06-vcwg#section2-10) on 2024-03-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.10. Explain that natural language examples are illustrative (issue vc-data-model#1192)

_See github issue [vc-data-model#1192](https://github.com/w3c/vc-data-model/issues/1192)._




_See github pull request [vc-data-model#1449](https://github.com/w3c/vc-data-model/pull/1449)._




**Brent Zundel:** excellent!  
… 1192.  
… has a PR, 1449...still open.  

**Manu Sporny:** the rest of the list have PRs.  

**Brent Zundel:** we'll go through them one by one.  
… PR1449 looks ready for merging this week.  

</details>

**Comment by msporny** [comment]
PR #1449 has been merged, closing.
