### ISSUE TITLE
Define `verification material` find replace `public keys`

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-model#1197]
Avoids confusion related to proof types that don't use public keys... aligns with DID Core better.

**Comment by TallTed** [comment]
@OR13 — I do not understand the title of this issue. The initial comment doesn't provide much help with that understanding. Please expand on what you mean?

**Comment by OR13** [comment]
data integrity has this: 

- https://www.w3.org/TR/vc-data-integrity/#retrieve-verification-method

If you search the vc data model, you see lots of comments about "public keys"...

But DID Core called them "verifiable material" to support ZKPs, and blockchain addresses, and other stuff...

This issue is filed in case we want to align the vocabulary we are using... here are some screenshots of what I mean:
<img width="915" alt="Screen Shot 2023-07-12 at 6 20 20 PM" src="https://github.com/w3c/vc-data-model/assets/8295856/2c11ffe2-d939-4b68-ac65-01bf67c1ddbd">
<img width="874" alt="Screen Shot 2023-07-12 at 6 20 11 PM" src="https://github.com/w3c/vc-data-model/assets/8295856/360e8d7d-5c04-44a0-ab7c-a805ec99d38f">

**Comment by fhk33336** [comment]
[_**@**_]()

**Comment by fhk33336** [comment]
[_**@**_]()

**Comment by msporny** [comment]
I'm fairly certain that this is editorial, so can be done post-CR. All we would have to do is 1) add the term to the terminology section, and 2) find/replace "public key" with "verification material".

**Comment by OR13** [comment]
I agree.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-01-17-vcwg#section2-6) on 2024-01-17

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.6. Define `verification material` find replace `public keys` (issue vc-data-model#1197)

_See github issue [vc-data-model#1197](https://github.com/w3c/vc-data-model/issues/1197)._




**Brent Zundel:** I believe everywhere we're saying "public keys" use "verification material"?  
… There are four instances of "public key" to "verification material" in the spec.  

> *Ted Thibodeau Jr.:* be sure to match all plurals/singulars!

**Nicholas Steele:** I'll take it.  

**Ted Thibodeau Jr.:** Verification Material (singular) everywhere is probably ok.  

**Manu Sporny:** All this is fine. A couple of suggestions, Nick. We use the word "cryptographic material" for public/private/secret key.  
… We say "verification material" if it's a public key or some mechanism that verifying some other proof of X (work, time) etc.  
… For some people it might be weird so we could pull the definition from the VC-DI spec and put it in the VCDM. So we say "when we say verification material, it's anything to verify a proof" that includes public keys, inputs to an algorithm, anything like that.  
… It doesn't make it that much more difficult and I can help with the PR on how to do that.  

</details>

**Comment by selfissued** [comment]
Where we mean "public key", we should use the term "public key".  Using a different term would create an unnecessary level of indirection.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-02-21-vcwg#section4-3) on 2024-02-21

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.3. Define `verification material` find replace `public keys` (issue vc-data-model#1197)

_See github issue [vc-data-model#1197](https://github.com/w3c/vc-data-model/issues/1197)._




**Michael Jones:** The term "public key" is well known, "verification material" is not, why would we do this?  

**Manu Sporny:** There are verification methods that don't use public keys.  

**Brent Zundel:** A response to this issue entails going through the spec and inspecting the places we use the term "public key".  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-03-13-vcwg#section4-3) on 2024-03-13

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.3. Define `verification material` find replace `public keys` (issue vc-data-model#1197)

_See github issue [vc-data-model#1197](https://github.com/w3c/vc-data-model/issues/1197)._




**Brent Zundel:** assigned to X, manu said he will take it. manu: still planing to work on this.  

</details>

**Comment by msporny** [comment]
Fixed in a80301dc7b78a7c11aa25636a744d3a4b201ced7, closing.
