### ISSUE TITLE
VCDM editors draft has incorrect link for published version

### ISSUE THREAD

**Issue by brentzundel** [w3c/vc-data-model#1224]
The `TR` seems to be missing from the link in the editor's draft
![image](https://github.com/w3c/vc-data-model/assets/10376511/da36adbe-8ed8-415d-aedb-7a529c5fafeb)

**Comment by brentzundel** [comment]
resolved, closing

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-08-15-vcwg-special#section2-1) on 2023-08-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.1. VCDM editors draft has incorrect link for published version (issue vc-data-model#1224)

_See github issue [vc-data-model#1224](https://github.com/w3c/vc-data-model/issues/1224)._




**Brent Zundel:** first issue: 1224. noticed in the ED there wasn't a link to the published version that was working. I opened. can be post-CR but should be straightforward.  

**Manu Sporny:** did check when I saw it raised and think all links resolved unless I was clicking on the wrong link. latest ED and published version links work. and this version works. all go to the appropriate 2.0 places.  

**Brent Zundel:** will close.  

</details>
