### ISSUE TITLE
[VC-JWT] Reference is wrong

### ISSUE THREAD

**Issue by nikosft** [w3c/vc-data-model#1233]
[VC-JWT] reference (https://www.w3.org/TR/vc-data-model-2.0/#bib-vc-jwt) redirects to a 404 page (https://w3c.github.io/vc-jwt/)

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-08-15-vcwg-special#section2-3) on 2023-08-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.3. [VC-JWT] Reference is wrong (issue vc-data-model#1233)

_See github issue [vc-data-model#1233](https://github.com/w3c/vc-data-model/issues/1233)._




**Brent Zundel:** next issue 1233...reference to VC-JWT is wrong, has a PR; marking as PR exists.  

</details>
