### ISSUE TITLE
Revert language change on the definition of Subject

### ISSUE THREAD

**Issue by jandrieu** [w3c/vc-data-model#1235]
In another PR, https://github.com/w3c/vc-data-model/pull/1172, from @RieksJ, updates some definitions, including a change to what a claim is, which pulls in a definition of Subject that requires Subjects to actually exist.

This is a fairly big shift to my understanding, and based on the last two VCWG calls, to several others.

However, in reviewing PR #1999, I realized that @RieksJ likely pulled that definition directly from our terminology section:
> [subject](https://w3c.github.io/vc-data-model/#dfn-subjects)
An [entity](https://w3c.github.io/vc-data-model/#dfn-entities) about which [claims](https://w3c.github.io/vc-data-model/#dfn-claims) are made. Example subjects include human beings, animals, and things. In many cases the [holder](https://w3c.github.io/vc-data-model/#dfn-holders) of a [verifiable credential](https://w3c.github.io/vc-data-model/#dfn-verifiable-credential) is the subject, but in certain cases it is not. For example, a parent (the [holder](https://w3c.github.io/vc-data-model/#dfn-holders)) might hold the [verifiable credentials](https://w3c.github.io/vc-data-model/#dfn-verifiable-credential) of a child (the [subject](https://w3c.github.io/vc-data-model/#dfn-subjects)), or a pet owner (the [holder](https://w3c.github.io/vc-data-model/#dfn-holders)) might hold the [verifiable credentials](https://w3c.github.io/vc-data-model/#dfn-verifiable-credential) of their pet (the [subject](https://w3c.github.io/vc-data-model/#dfn-subjects)). For more information about these special cases, see the [Subject-Holder Relationships](https://www.w3.org/TR/vc-imp-guide/#subject-holder-relationships) section in the Verifiable Credentials Implementation Guide [[VC-IMP-GUIDE](https://w3c.github.io/vc-data-model/#bib-vc-imp-guide)]. 

It has been a oft-repeated principle of this work that with a VC you can say anything about anything. This definition would preclude that.

I'd like to get a sense of the group's opinion on this and if there's consensus, we should get a PR together that restores the ability for Subjects to be abstract concepts, and therefore, not necessarily "entities" or "things".

**Comment by dlongley** [comment]
I suspect that some may be thinking that "abstract concepts" are also "things". When people say "any*thing*", that is "any thing", including "intangible things" or "abstract things".

**Comment by TallTed** [comment]
First thing, the key to that sentence is *Example subjects*, which is to say it is a *non-exhaustive list*, which was not written to _limit_ what a `subject` might be.

If you're objecting to the *first* sentence, where we say that a `subject` is an `entity`, then I'm afraid you've lost the plot, and I must refer you back to [§1.2 Resources and Statements of _RDF 1.1 Concepts and Abstract Syntax_](https://www.w3.org/TR/rdf11-concepts/#resources-and-statements) where it says:

> Any [IRI](https://www.w3.org/TR/rdf11-concepts/#dfn-iri) or [literal](https://www.w3.org/TR/rdf11-concepts/#dfn-literal) denotes something in the world (the "universe of discourse"). These things are called resources. Anything can be a resource, including physical things, documents, abstract concepts, numbers and strings; the term is synonymous with "entity" as it is used in the RDF Semantics specification [[RDF11-MT](https://www.w3.org/TR/rdf11-concepts/#bib-RDF11-MT)].

If it would make you feel better, I think we could change --

> `Example subjects include human beings, animals, and things.`

-- to --

> `An inexhaustive list of <b>example</b> subjects includes human beings, animals, physical things, documents, abstract concepts, numbers, and strings.`

The degree to which these subject must "actually exist" comes down to "the issuer can think of them, and wants to say something about them".

**Comment by RieksJ** [comment]
@jandrieu : For quite some time now I have been advocating that we use the terms in the meaning in which they are defined, by which I mean: as defined in the terminology section. It helps to construct a terminology that is useful for the standard itself, and enables us to express our ideas in a coherent and consistent manner. 

Regarding 'subject' in [Merriam-Webster](https://www.merriam-webster.com/dictionary/subject), the definitions/descriptions it has under its section 3c point into the direction of what we try to do. I did note that they (correctly) consistently distinguish between the something that is being referred to, or 'denoting that of which something is predicated', thereby differentiating between
- something that refers to 'the subject', which we could call the 'subject identifier' and
- something that is 'the subject', and that does not appear in a claim, but is referred to within a claim.

As a side note, I think this differentiation between subject identifiers (more in general: pointers) and subjects (the stuff that pointers refer to) should be emphasized, as it is still causing lots of trouble, even though most of us no longer use C. But that's perhaps a subject (:-) for another issue.

As explained a bit more in my argument in [this comment](https://github.com/w3c/vc-data-model/pull/1172#discussion_r1282035868) of PR #1172, I propose 

1. to have a term whose meaning is defined as follows: "**anything that is known to exist, e.g., a person (yourself included), a computer, an issuer, a holder, a verifier, an extinct animal, a thought, an idea, a concept, a JSON-object, a verifiable credential, a claim, etc. Really, it is _anything_ that _anyone_ can think of and/or knows to exist.**", because such a criterion/description says what it is that we actually need.
2. to see if we can get a consensus on the need of that meaning, and only thereafter, come up with some word or phrase (term) that we then use in that meaning, and include in the VCDM terminology section (which I would happily do in PR #1172, so that I can use that in the related definitions of 'claim' and 'subject').
3. Consider including another definition for the identifier (URI or otherwise) that would refer to this 'someone or something that is known to exist' that is used in claims to refer to the subject of that claim, and I would therefor call a 'subject identifier'.

**Comment by RieksJ** [comment]
I wasn't aware of such discussions, but reading up on the link, as well as on RDF basics, the solution might be quite simple.

RDF has this concept called 'resource', of which the [RDF primer](https://www.w3.org/TR/rdf11-primer/) states that it "can be anything, including documents, people, physical objects, and abstract concepts." This concept is sufficiently similar to what I think we are looking for that I would say we keep it. We could keep the name 'resource', or use another term. For now, I'll call it `rdf:resource`.

Then, if we can keep the term `entity` as is, i.e. something/someone with a distinct existence that can perform a role in the ecosystem (i..e.: holder, verifier, issuer). Obviously, an  `entity` qualifies as a `rdf:resource`, but the converse isn't necessarily true.

The subject of a claim would then be an `rdf:resource`, which means we can make claims about holders, verifiers and issuers but also about documents, physical objects, and abstract concepts. I don't mind adopting the RDF convention of using IRIs to identify resources (after all, that's what they are there for).

**Comment by TallTed** [comment]
As noted elsewhere, I refer all and sundry to [RDF Concepts, Introduction](https://www.w3.org/TR/rdf11-concepts/#resources-and-statements), where `resource` is clearly stated to be synonymous with `entity`, and both/either may be _anything_.

**Comment by RieksJ** [comment]
@TallTed I fully agree with you. Being a non-native American speaker, this is what I always thought was the case. 

However, it seems as if there at some point in time there was consensus about using the term in a different meaning. I would very much like 'entity' to be what you propose, which would then mean we would need to have another term for the concept that its current definition describes, i.e. a person, organization or device that can perform the roles of issuer and/or holder and/or verifier. 

To me, it seems as if the discussions revolve about two different concepts: one as VCDM calls an 'entity' and another one that is 'anything about information can be associated with' (or something like that). I think both are relevant to have (for different reasons), and therefor should be called differently. I don't care what names we use, as long as we're clear about the concepts they refer to.

**Comment by jandrieu** [comment]
@TallTed I agree with you that in the RDF community, entities are resources, full stop.

However, we currently define entities as (1) having distinct and independent existence and (2) something that performs one or more roles in the ecosystem.

> entity
A thing with distinct and independent existence, such as a person, organization, or device that performs one or more roles in the ecosystem.

Abstract subjects do not have distinct and independent existence (they can be fictitious) and do not necessarily perform any particular role in the ecosystem. 

NOTE: Somewhere in the evolution of the document, the definition of "role" was expanded to (non-normatively) include Subjects and VDRs. However, I would assert that since neither Subjects nor VDRs take any actions in the ecosystem, they are not roles. Interestingly, the terms document definitions only describe Verifiers, Issuers, Holders, and VDRs as roles.

Regardless of the appropriateness of calling "Subject" and "VDR" a role, we have the deeper problem that the current language, in multiple places, implies that Entities and therefore Subjects must have a concrete existence.

We should update something so that Subjects need not be concrete. They do not need "to exist". In fact, it is vital that we can issue a VC that says something like "Joe asserts that 'Santa Claus does not exist'". If Subjects are required to "exist" that statement would not be possible to make.

**Comment by TallTed** [comment]
> However, we currently define entities as (1) having distinct and independent existence and (2) something that performs one or more roles in the ecosystem.

That's a surprising, and I think incorrect, reading of the definition you quoted just below.

> A thing with distinct and independent existence, such as a person, organization, or device that performs one or more roles in the ecosystem.

The actual definition is "_A thing with distinct and independent existence_", and the rest of that sentence is ***examples*** of such things, "_such as a person, organization, or device that performs one or more roles in the ecosystem_".

Your interpretation might be correct if the definition were phrased as "A thing with distinct and independent existence that performs one or more roles in the ecosystem, such as a person, organization, or device", but then I would (or would have) take(n) issue with that definition.

I also believe that "distinct and independent existence" is entirely possible for a concept, fictitious being, or other etheric thing. I do not believe that _material_ or _physical_ existence is required. We did not say "measurable", among other qualifiers that might have forced materiality or physicality.

If we are seriously considering redefining `entity` as something other than a synonym for `resource`, where both effectively mean "any thing", then we should use a different word in its place, and discard most if not every instance of `entity` and `resource`.

**Comment by dlongley** [comment]
I agree with @TallTed's analysis above and have always thought (IIRC) that "entity" covered concepts, fictitious beings, and so on as well. Even if we hadn't meant for "entity" to refer to "anything", it would be certainly worthwhile, IMO, to make it so now, as it seems to be the simplest resolution to a number of issues without any obvious drawbacks to me (that couldn't then also be be solved in some other way).

**Comment by jandrieu** [comment]
Will work on update to definition for "entity" so it clearly includes abstract objects (not just concrete things)

**Comment by RieksJ** [comment]
I then suggest that such a revision also looks at phrases that state that entities are what preform the roles of issuer, holder and verifier as that seems to have been the whole idea behind defining entities the way they are defined now. One possibility would be to just use another word for that concept (and change the other texts accordingly).

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-08-16-vcwg#section2-6) on 2023-08-16

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.6. Revert language change on the definition of Subject (issue vc-data-model#1235)

_See github issue [vc-data-model#1235](https://github.com/w3c/vc-data-model/issues/1235)._




**Joe Andrieu:** I think references to entity implied that subject had to be something that physicaly exists, in RDF world, it can be a concept (doesn't need to "physically exist") -- we should clear up "entity" to include "abstract concepts".  

> *Orie Steele:* +1 to ready for PR.

**Manu Sporny:** +1 entity includes abstract concepts --.  

> *Ted Thibodeau Jr.:* +1.

**Joe Andrieu:** I think what Ted said makes sense... say entity can be abstract.  

> *Phillip Long:* +1.

> *Benjamin Young:* +1.

> *Dmitri Zagidulin:* +1.

</details>

**Comment by brentzundel** [comment]
I am marking this issue `pending close`, as there doesn't seem to be any action to take. Will close in 7 days if there is no objection.

**Comment by jandrieu** [comment]
I created a PR and updated the labels.

**Comment by msporny** [comment]
PR #1269 was raised to address this issue and has been merged, closing.
