### ISSUE TITLE
Add references to Sub-Resource Integrity

### ISSUE THREAD

**Issue by decentralgabe** [w3c/vc-data-model#1237]
In the [securing section there are references to HASHLINK](https://github.com/w3c/vc-data-model/blob/main/index.html#L4886) which should be updated to be in line with the rest of the specification which references SRI as such

> information for the resource constructed using the method specified in <a href="https://www.w3.org/TR/SRI/#integrity-metadata">Subresource Integrity</a>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-08-15-vcwg-special#section2-4) on 2023-08-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.4. Add references to Sub-Resource Integrity (issue vc-data-model#1237)

_See github issue [vc-data-model#1237](https://github.com/w3c/vc-data-model/issues/1237)._




**Brent Zundel:** next issue 1237 to add references to SRI..believe its safe to assume we can label it as post-CR.  

**Gabe Cohen:** labeling it as post-CR is fine.  

**Brent Zundel:** no objections; post CR.  

</details>
