### ISSUE TITLE
Recommend that DIDs are used with VCs

### ISSUE THREAD

**Issue by decentralgabe** [w3c/vc-data-model#1243]
We have [a section on identifiers](https://w3c.github.io/vc-data-model/#identifiers) which calls out that DIDs can be used, and further, a note that states

> As of this publication, [DIDs](https://w3c.github.io/vc-data-model/#dfn-decentralized-identifiers) are a new type of identifier that are not necessary for [verifiable credentials](https://w3c.github.io/vc-data-model/#dfn-verifiable-credential) to be useful. Specifically, [verifiable credentials](https://w3c.github.io/vc-data-model/#dfn-verifiable-credential) do not depend on [DIDs](https://w3c.github.io/vc-data-model/#dfn-decentralized-identifiers) and [DIDs](https://w3c.github.io/vc-data-model/#dfn-decentralized-identifiers) do not depend on [verifiable credentials](https://w3c.github.io/vc-data-model/#dfn-verifiable-credential). However, it is expected that many [verifiable credentials](https://w3c.github.io/vc-data-model/#dfn-verifiable-credential) will use [DIDs](https://w3c.github.io/vc-data-model/#dfn-decentralized-identifiers) and that software libraries implementing this specification will probably need to resolve [DIDs](https://w3c.github.io/vc-data-model/#dfn-decentralized-identifiers). [DID](https://w3c.github.io/vc-data-model/#dfn-decentralized-identifiers)-based URLs are used for expressing identifiers associated with [subjects](https://w3c.github.io/vc-data-model/#dfn-subjects), [issuers](https://w3c.github.io/vc-data-model/#dfn-issuers), [holders](https://w3c.github.io/vc-data-model/#dfn-holders), credential status lists, cryptographic keys, and other machine-readable information associated with a [verifiable credential](https://w3c.github.io/vc-data-model/#dfn-verifiable-credential).

I believe that this language should be strengthened to advocate more for the usage of DIDs with VCs as they can promote the principles the spec is set out to achieve, namely:
- Stronger privacy (not true with all DID methods, but many)
- Simpler verifiability (DIDs have keys)
- Decentralized resolvability (not just relying on domains/TLS for discovering keys)
- Natural tie in to VDRs/storage with the serviceEndpoint property

To achieve this goal I'd recommend removing the note and turning it into a new section with normative guidance on favoring the usage of DIDs.

**Comment by OR13** [comment]
Feels like maybe the opposite approach would be better, given the adoption issues and formal objections to DIDs.

**Comment by selfissued** [comment]
I agree with Orie.  If anything, the use of DIDs should be NOT RECOMMENDED.

**Comment by decentralgabe** [comment]
@OR13 
> Feels like maybe the opposite approach would be better, given the adoption issues and formal objections to DIDs.

Please substantiate your claims. It's a formal standard, objections are dismissed.

@selfissued 
> If anything, the use of DIDs should be NOT RECOMMENDED.

Why?

**Comment by jandrieu** [comment]
FWIW, I think DIDs are preferable, and VCs were literally designed to work with DIDs, but I doubt we'll get consensus on this as several members of the working group consistently attack DIDs whenever they are mentioned.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-08-15-vcwg-special#section2-6) on 2023-08-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.6. Recommend that DIDs are used with VCs (issue vc-data-model#1243)

_See github issue [vc-data-model#1243](https://github.com/w3c/vc-data-model/issues/1243)._




**Brent Zundel:** next issue is 1243 recommend that DIDs are used in VCs raised by gabe.  

**Manu Sporny:** agree to highlight the importance of DIDs...only problem would be around normative guidance..concern there is that a concept of a controller document can be published on the web (http); certain W3C members are cranky with DIDs. current spec tries to be agnostic to URL schemes.  
… this may be asking for more trouble than it's worth.  
… adding normative language may be a bridge too far.  

**Gabe Cohen:** I do think that usage of DIDs barring some objections that might or might not have logical weight, are well aligned w/ principles/data model -- taking stronger stance on privacy-promoting technology such as DIDs... we should consider that.  

**Michael Jones:** DIDs are just a key look up method, you can look up keys in many ways that are privacy preserving.  

**Gabe Cohen:** Some DID Methods have stronger guarantees than web domains.  

> *Kristina Yasuda:* -1 to anything stronger that implying DIDs are possible to be used.

> *Sebastian Crane:* +1 to possibility of pre-CR.

**Brent Zundel:** post CR or before CR?  

**Michael Jones:** post CR or close.  

**Brent Zundel:** not hearing any objections to post CR.  

**Gabe Cohen:** Happy to be assigned, but won't work on anything until there is consensus.  

</details>

**Comment by decentralgabe** [comment]
Closing, will consider opening an issue in the controller doc spec.

**Comment by iherman** [comment]
Closing now that the meeting minutes are added
