### ISSUE TITLE
Mitigating Location Correlation via Common Issuers

### ISSUE THREAD

**Issue by awoie** [w3c/vc-data-model#1245]
From PING review https://github.com/w3cping/privacy-request/issues/121#issuecomment-1638908803:
> On a related note, Who an issuer of a credential is can act as a vector of correlation about the subjects location or region or other PII and should also be considered. Issuer based correlation can be reduced through the use of common issuers rather than distributing across many issuers (e.g. think about issuing a drivers license credential at the state level rather than a separate issuer per county) or via cryptographic means such as a ring signature. An additional point should be added to the privacy considerations section to highlight this further.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-08-23-vcwg#section3-5) on 2023-08-23

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.5. Mitigating Location Correlation via Common Issuers (issue vc-data-model#1245)

_See github issue [vc-data-model#1245](https://github.com/w3c/vc-data-model/issues/1245)._




> *Manu Sporny:* +1 to this being a security consideration, post CR.

**Brent Zundel:** This is a security consideration. This is less of a data model aspect; maybe this is Post-CR.  

> *Greg Bernstein:* +1 1245 post CR.

**Sebastian Crane:** Essentially my comments regarding the previous issue apply to all of the ones from PING. We don't have to have normative statements, but Post-CR could just be undesirable given how critical these things are.  

**Manu Sporny:** To address Sebastian's concerned, maybe we should add a topic specifically for discussing the PING review in general.  

> *Greg Bernstein:* Post CR I may have more time to help with PING items...

</details>

**Comment by Sakurann** [comment]
also this: https://datatracker.ietf.org/doc/html/draft-ietf-oauth-selective-disclosure-jwt-05#name-issuer-identifier

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-09-15-vcwg#section3-4) on 2023-09-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.4. Mitigating Location Correlation via Common Issuers (issue vc-data-model#1245)

_See github issue [vc-data-model#1245](https://github.com/w3c/vc-data-model/issues/1245)._




**Brent Zundel:** Gabe can you let us know if you're ready to move forward on this?  

**Gabe Cohen:** Issuers being considerate of information they're disclosing... can do PR soon.  

**Nick Doty:** Just to clarify this, in some models, privacy pass -- separate attester and issuer, attester is doing detailed subject matter evaluation, pass on fact of user w/o passing information on -- if I pass on single claim from DL, you get claim and details about who signed it -- which authority issued the DL.  
… Who issued is more substantial than piece of information I'm revealing, user has asked for age -- and actually what is being rquested is not age, but what is sent i who government authority is.  

> *Kristina Yasuda:* this is what we wrote for SD-JWT: [https://datatracker.ietf.org/doc/html/draft-ietf-oauth-selective-disclosure-jwt-05#name-issuer-identifier](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-selective-disclosure-jwt-05#name-issuer-identifier).

> *Kristina Yasuda:* on the issuer identifier.

**Manu Sporny:** There are systems that exist, that takes in a identifying VC that translates to a privacy preserving VC, then uses the privacy-preserving VC.  

> *Gabe Cohen:* there is a section [https://w3c.github.io/vc-data-model/#issuer-cooperation-impacts-on-privacy](https://w3c.github.io/vc-data-model/#issuer-cooperation-impacts-on-privacy).

**Brent Zundel:** Yes, Gen is working on similar model, we can translate one VC to another to create that privacy preserving thing such as what TruAge does. Their trust in the system is what enables it to work. I do think that we need to, if we haven't already, note that trusting issuer can reveal thing sabout it, additional information there could help.  

**Gabe Cohen:** I'll add more details in that section.  

**Brent Zundel:** If there are no other comments on this issue, w/ VC data model, moving on to other items.  

</details>
