### ISSUE TITLE
Section title and contents mismatch on "Complex Language Markup"

### ISSUE THREAD

**Issue by shigeya** [w3c/vc-data-model#1254]
The current discussion in [10.2 Complex Language Markup](https://w3c.github.io/vc-data-model/#complex-language-markup) is discouraging to use of markup languages capable of containing executable scripts for complex language markup and not providing advice on how to markup.

If the language we need is security considerations, this section should be moved to the appropriate section to discourage this type of markup language.

If the description we need is how to implement complex language markup, we need to provide actual advice on how.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-08-23-vcwg#section3-1) on 2023-08-23

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.1. Section title and contents mismatch on "Complex Language Markup" (issue vc-data-model#1254)

_See github issue [vc-data-model#1254](https://github.com/w3c/vc-data-model/issues/1254)._




**Sebastian Crane:** Is this considered important enough to be its own bullet point in security considerations or is it best practice to just know it?  

**Manu Sporny:** I would suggest 'Post-CR' for this issue. I don't think we should add normative text to the specification about this issue.  

**Sebastian Crane:** I would like to agree with Manu and have the extra justification for post-PR is that this can be said about anything in RDF; we can put any content anywhere and it's up to implementers to be careful in what they pass in what security context they want to.  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-09-06-vcwg#section4-1) on 2023-09-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.1. Section title and contents mismatch on "Complex Language Markup" (issue vc-data-model#1254)

_See github issue [vc-data-model#1254](https://github.com/w3c/vc-data-model/issues/1254)._




**Sebastian Crane:** this one is going well and almost done, maybe today, will move on to the other issue assigned to me soon.  

**Manu Sporny:** my one thought on 1254 is that internationalization guidance (w3c-wide) is being updated lately, and i don't know if you want that in your PR or in a separate one.  

**Sebastian Crane:** actually I think the PR was only mentioning `@language` in reference to security of LD documents.  

> *Manu Sporny:* Great, that sounds like it's not an issue then, Sebastian! :).

**Sebastian Crane:** so not related I don't think.  

</details>

**Comment by seabass-labrax** [comment]
I'm going to be pretty occupied from now until Easter with other open source projects, so unfortunately it might be a little before I can get to this issue. If someone else would like to take this that would be great, and I can provide a review :)

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-02-21-vcwg#section4-1) on 2024-02-21

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.1. Section title and contents mismatch on "Complex Language Markup" (issue vc-data-model#1254)

_See github issue [vc-data-model#1254](https://github.com/w3c/vc-data-model/issues/1254)._




**Manu Sporny:** This text is in the internationalization write-up.  
… I think it's fine where it is.  

> *Ivan Herman:* +1 to manu.

**Manu Sporny:** It doesn't need to be in the Security Considerations.  
… I think we should mark the issue pending close.  

**Brent Zundel:** Any objections to that?  
… No objections.  

</details>

**Comment by shigeya** [comment]
I read the document through yesterday (I will provide some minor feedback later).
On the read yesterday, I was puzzled by the title "Complex language markup." 
(Note: I think JSON-LD language markup is already complex)

Now, I think it is unnecessary to move the security consideration section (since it's already in the internationalization section), but I want the title to be adjusted to something like "Multilingual string with HTML processor," to reflect the actual discussion in the section.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-03-06-vcwg#section2-4) on 2024-03-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.4. Section title and contents mismatch on "Complex Language Markup" (issue vc-data-model#1254)

_See github issue [vc-data-model#1254](https://github.com/w3c/vc-data-model/issues/1254)._




**Brent Zundel:** 1254 is about complex language markup.  
… this was pending close.  
… we got a comment that if the title is adjusted, that would better apply or reflect the content.  
… sounds like a simple change.  

**Manu Sporny:** I'll take it.  
… and just try to work with title, since Sebastian's no longer with us.  
… I'll provide a PR and we can talk about it there.  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-03-13-vcwg#section4-1) on 2024-03-13

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.1. Section title and contents mismatch on "Complex Language Markup" (issue vc-data-model#1254)

_See github issue [vc-data-model#1254](https://github.com/w3c/vc-data-model/issues/1254)._




**Manu Sporny:** I'll continue to work on this.  

</details>

**Comment by msporny** [comment]
PR #1463 has been raised to address this issue. This issue will be closed once PR #1463 has been merged.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-03-27-vcwg#section3-4) on 2024-03-27

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.4. Section title and contents mismatch on "Complex Language Markup" (issue vc-data-model#1254)

_See github issue [vc-data-model#1254](https://github.com/w3c/vc-data-model/issues/1254)._




_See github pull request [vc-data-model#1463](https://github.com/w3c/vc-data-model/pull/1463)._




**Brent Zundel:** this PR can be merged by the end of this week.  

</details>

**Comment by brentzundel** [comment]
PR #1463 has been merged, closing this issue as is has been addressed.
