### ISSUE TITLE
Add `revoked` and `expired` to verification method classes

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-model#1262]
We need to update the vocabulary and contexts to align Multikey and JsonWebKey.

Once https://github.com/w3c/vc-data-integrity/pull/184#pullrequestreview-1598383320 is merged, we will need to update the core contexts.

**Comment by iherman** [comment]
Can you be more explicit @OR13 ? #184 already includes a change in the vocabulary, namely that the domain `expired` is set to both (i.e., the union) of `Proof` and `VerificationMethod`. Should `revoked` be treated the same way (I was actually wondering about that)?

**Comment by OR13** [comment]
@iherman I filed this to track the request from @msporny https://github.com/w3c/vc-data-model/pull/1260#pullrequestreview-1596985574

And yes! thats why I filed the issue, we should address `revoked` and `expired` and `publicKeyMultibase` / `publicKeyJwk` consistently.

I also fear that `revoked` and `status lists` will be confused, and we might use the vocabulary to help remove that confusion.

**Comment by dlongley** [comment]
It doesn't really make sense to add `revoked` to a proof as it would require generating a new proof to do it. Proofs / VCs in that sense need to be tracked via some other status mechanism like `StatusList`.

**Comment by OR13** [comment]
@dlongley i'm confused by your comment... perhaps its related "casing" being the only difference between `verificationMethod` and `VerificationMethod` ? My original comment was on `VerificationMethod` -> `MultiKey` having "revoked", but VerifiableCredential -> CredentialStatus having a "status" of "revoked".

**Comment by dlongley** [comment]
@OR13

Sorry, my comment was in response to Ivan. I'll edit that to make it clear.

**Comment by iherman** [comment]
> @iherman,
> 
> > ...the domain `expired` is set to both (i.e., the union) of `Proof` and `VerificationMethod`. Should `revoked` be treated the same way (I was actually wondering about that)?
> 
> It doesn't really make sense to add `revoked` to a `Proof` as it would require generating a new proof to do it. Proofs / VCs in that sense need to be tracked via some other status mechanism like `StatusList`.

Fine with me. This is moot then.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-08-29-vcwg-special#section2-2) on 2023-08-29

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.2. Add `revoked` and `expired` to verification method classes (issue vc-data-model#1262)

_See github issue [vc-data-model#1262](https://github.com/w3c/vc-data-model/issues/1262)._




> *David Waite:* kristina, TallTed: mark as discuss.

**Manu Sporny:** Orie noticed that JWK didn't have the expired and revoked properties that multikey had.  
… alignment would mean JWK would have all the same properties.  
… being aligned in DI, after that may need to be aligned in base context.  
… may be able to do it post-CR since the context can be modified, but not preferred.  

---

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-09-14-vcwg#section2-4) on 2023-09-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.4. Add `revoked` and `expired` to verification method classes (issue vc-data-model#1262)

_See github issue [vc-data-model#1262](https://github.com/w3c/vc-data-model/issues/1262)._




**Brent Zundel:** next issue: 1262. add revoked and expired to verificationMethod classes.  
� been conversation, but no one assigned. can anyone give a summary.  

**Manu Sporny:** there was a misalignment in the data integrity between multikey and jsonwebkey.  
� we've added those properties to json web key. now the same properties.  
� so that's fixed in DI, but we think Orie wanted that change reflected into the base context.  
� it is unlikely that that PR is going to be merged. The one that defines those keys.  
� as a result, this issue is a bit moot.  
� If we don't define the RDF classes for JWK and multikey in the base context (and we aren't), then we don't need to do anything with this issue.  
� and the misalignment has been fixed in data integrity.  

**Brent Zundel:** sounds like once that PR is closed, this issue should be closed.  

**Manu Sporny:** i believe so, but we need to check if Orie agrees.  

**Brent Zundel:** having closed that PR. we should close this one. (after checking that we did in fact do that).  
� any opposition to adding Pending-Close on this issue?  
� hearing none. I'm going to add the tag.  

</details>

**Comment by brentzundel** [comment]
no objections raised since marked `pending close`, closing.
