### ISSUE TITLE
Tell a bit more about `verificationMethod` type schema

### ISSUE THREAD

**Issue by Voronar** [w3c/vc-data-model#1274]
Hi!
[A.5 notice](https://www.w3.org/TR/vc-data-model-2.0/#proofs-signatures) said that `The verificationMethod property specifies, for example, the public key that can be used to verify the digital signature. Dereferencing a public key URL reveals information about the controller of the key, which can be checked against the issuer of the credential.`, but it would be more helpful to tell about it a bit more (that it is not only a URL string), for example referencing to [the verificationMethod definition from Verifiable Credential Data Integrity spec](https://www.w3.org/TR/vc-data-integrity/#dfn-verificationmethod).

But for implementers [the verificationMethod JSON Schema](https://github.com/w3c/vc-data-model/blob/main/schema/verifiable-credential/verifiable-credential-schema.json#L82) would be the most useful link.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-01-31-vcwg#section2-6) on 2024-01-31

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.6. Tell a bit more about `verificationMethod` type schema (issue vc-data-model#1274)

_See github issue [vc-data-model#1274](https://github.com/w3c/vc-data-model/issues/1274)._




**Brent Zundel:** A little bit more about verification method type schema. Either this is just an answer we need to give or some editorial content to resolve it.  
… Do we need more information about the `verificationMethod` property, does it need to be done, is there anyone willing to do it?  

**Manu Sporny:** I'm trying to parse what they are saying. I guess I said this was ready for PR a year ago...  
… I think the spec was in a different place then.  
… The easiest fix for this is to just point to the `verificationMethod` property in the DI spec, but others in the group might object to us doing that because it's also defined in vc-jose-cose, we don't have a unified controller document spec yet.  
… The other thing we could do here is just delete the note.  
… I don't know if this note is really helping anymore.  
… If folks are ok, we could just delete the note, it came from a time long long ago, where we needed to highlight that the digital signature might include things like the public key associated with it and so on -- and now we have whole specs talking about all of that. I suggest we just delete the note.  

**Brent Zundel:** Big +1 to cleaning up the spec you suggested.  
… I think getting rid of some things that aren't necessary now that we're on version 2.  
… The suggestion is to resolve this issue by removing the linked note and move forward in that way.  

**Dave Longley:** +1 to that path forward.  

> *Phillip Long:* +1 to that path.

**Brent Zundel:** Any opposition to that?  
… Let's do that, awesome.  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-02-28-vcwg#section3-6) on 2024-02-28

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.6. Tell a bit more about `verificationMethod` type schema (issue vc-data-model#1274)

_See github issue [vc-data-model#1274](https://github.com/w3c/vc-data-model/issues/1274)._




**Brent Zundel:** Tell a little bit more about verification method type schema. Do you need feedback, Manu?  

**Manu Sporny:** The path forward here is to delete the note and I'll do that.  

**Brent Zundel:** Yes, agree.  

</details>

**Comment by msporny** [comment]
PR #1452 has been raised to address this issue. This issue will be closed once PR #1452 has been merged.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-03-06-vcwg#section2-13) on 2024-03-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.13. Tell a bit more about `verificationMethod` type schema (issue vc-data-model#1274)

_See github issue [vc-data-model#1274](https://github.com/w3c/vc-data-model/issues/1274)._




_See github pull request [vc-data-model#1452](https://github.com/w3c/vc-data-model/pull/1452)._




**Brent Zundel:** 1274, PR1452 - large number of approvals, ready to be merged.  

</details>

**Comment by msporny** [comment]
PR #1452 has been merged, closing.
