### ISSUE TITLE
Prefer Arrays and Objects.

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-model#1292]
RDF will automatically handle different JSON-LD syntaxes the same, and there are changes you can make to a W3C Verifiable Credential that won't result in a broken Data Integrity Proof.

These changes can be surprising to developers, and lead to interoperability and security issues.

This experience can be improved by making recommendations, here are some examples, and some suggested recommendations:

### Representing Roles (Issuers, Subjects and Holders)

The following JSON-LD snippets are equivalent:

#### A
```json
{
  "issuer": "https://university.example/issuers/565049",
}
```

#### B
```json
{
  "issuer": {
    "id": "https://university.example/issuers/565049",
  }
}
```

### Representing Types (VerifiableCredential, DataIntegrityProof, etc...)

The following JSON-LD snippets are equivalent:

#### C
```json
{
  "type": "VerifiableCredential"
}
```

#### D
```json
{
  "type": ["VerifiableCredential"]
}
```

In absence of concrete text, expect developers to treat all the examples in the spec as recommendations.

For example, see our first spec example:

```json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
    "https://www.w3.org/ns/credentials/examples/v2"
  ],
  "id": "http://university.example/credentials/1872",
  "type": ["VerifiableCredential", "ExampleAlumniCredential"],
  "issuer": "https://university.example/issuers/565049",
  "validFrom": "2010-01-01T19:23:24Z",
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "alumniOf": {
      "id": "did:example:c276e12ec21ebfeb1f712ebc6f1",
      "name": "Example University"
    }
  },
  "proof": {
    "type": "DataIntegrityProof",
    "cryptosuite": "eddsa-2022",
    "created": "2023-06-18T21:19:10Z",
    "proofPurpose": "assertionMethod",
    "verificationMethod": "https://university.example/issuers/565049#key-123",
    "proofValue": "zQeVbY4oey5q2M3XKaxup3tmzN4DRFTLVqpLMweBrSxMY2xHX5XTYV8nQApmEcqaqA3Q1gVHMrXFkXJeV6doDwLWx"
  }
}
```

^ This is missing an opportunity to show why `issuer` is "better" than `iss`.

## Recommendations

It is recommended that roles be expressed with objects instead of strings.

It is recommended that types be expressed with arrays instead of strings.

Strings are recommended when ... (working group consensus needs to fill in this blank).

**Comment by gobengo** [comment]
Seems reasonable. Caveats:
* If possible it is nice to have a rationale with any recommendations, both to help noobs understand why they were recommended in the average case while also helping advanced users understand why/when it may be appropriate to deviate from the recommendations
  * @OR13 since you filed the issue proposing these recommendations, would you be willing to include your rationale for recommending them?
* these recommendations will make the VCs have more bytes (e.g. compared to JWTs with `iss` and string value), so these recommendations shouldn't be used later as part of any argument about which VC serialization costs more bytes/processing time.

**Comment by dmitrizagidulin** [comment]
@gobengo 

> * @OR13 since you filed the issue proposing these recommendations, would you be willing to include your rationale for recommending them?

I think @OR13's point is more -- it would make developers' lives easier if we picked ANY combination, and enforced it (via json schema, etc). The individual choices matter less, if devs don't have to constantly be like "if this field is a string, do this, if it's an array, do this" etc. 

👍 to this issue, @OR13. I don't know if we have time for this change, CR-wise, but I think it would be better for the spec.

**Comment by gobengo** [comment]
I'm +1 on all of the above too because I've also had to write tedious code to check for the polymorphism.

Thanks @OR13 for elaborating on the rationale, which includes some reasons I hadn't thought of.

One reason I asked is I didn't understand what this meant `This is missing an opportunity to show why issuer is "better" than iss`

**Comment by brianorwhatever** [comment]
@gobengo issuer in data integrity is "better" than jwt `iss` as it can be extended as an object whereas `iss` is always a string. He thinks the example should be
```
"issuer": {
  "id": "https://university.example/issuers/565049"
}
```
as it shows off it can be extended.

I tend to agree adding code for finding the issuer did has always bothered me.

I think `issuer` should always be an object with an `id`

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-10-25-vcwg#section2-3) on 2023-10-25

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.3. Prefer Arrays and Objects. (issue vc-data-model#1292)

_See github issue [vc-data-model#1292](https://github.com/w3c/vc-data-model/issues/1292)._




**Brent Zundel:** Prefer Arrays and Objects.  
… labeled as Before CR, no assignment. there's a bit of a conversation between folks. Orie - can you give us status?  

**Orie Steele:** as you all know, our conforming docs are compact JSON-LD docs. So, in lots of cases, the JSON is polymorphic -- either a string or an array object, etc.  
… any of the predicates (schema, proof, subject, etc) can either be string, object, or array.  
… reason for that is how RDF data model treats graph representation.  
… unfortunately, this causes problems for strongly typed languages.  
… these are very common bugs.  
… I've run into them hundreds of time. Can we reduce this sort of thing?  

**Brent Zundel:** other thoughts?  

**Dave Longley:** brief comment - we had a number of issues where we said, to increase interop, we should do a few of these things,.  
… without normatively requiring.  
… so maybe non-normative advice would suffice, for interop?  

> *Orie Steele:* dlongley maybe you can propose some normative SHOULD language?

**Brent Zundel:** suggestion before the group - can we address non-norm / post-CR, for future us to deal with?  

> *Dave Longley:* Orie: normative "SHOULD" hasn't worked in other places...

**Manu Sporny:** I'm a bit on the fence about this. might be good to go all the way to SHOULD, I'd be -1 for MUST.  
… we could put SHOULD normative language for objects, for arrays for single values, etc.  
… the problem is (and we've tripped over this in the past), you don't want it so that systems that aren't written to be robust when you DON'T do it, fail.  
… so, should we urge everyone to support polymorphism (like with accessor functions)?  
… it's dicey.  
… one alternate approach is to go the other way, and enforce all those variations in our test suites.  
… I'm fine with either route - SHOULD, or non-normative advice.  

**Dmitri Zagidulin:** How do people about "always require arrays"?  

> *Orie Steele:* I would be +1 to always requiring arrays, based on our implementation experience.

> *Dave Longley:* -1 some software already doesn't do that...

> *Dmitri Zagidulin:* I'd +1.

> *Orie Steele:* ... we do that in other specs.

> *Manu Sporny:* I'd be -1 to that ... 'cause there will be people that don't want to do that and we can't make them.

> *Dmitri Zagidulin:* `@dlongley` - what do you mean?

> *Shigeya Suzuki:* +0.5.

> *Benjamin Young:* -1 to new shape requirements...

> *Dmitri Zagidulin:* +1.

> *Andres Uribe:* I'm not sure what the implications are.

**Michael Jones:** this seems odd. what would this possibly accomplish?  
… if stuff is naturally a singleton, it should be represented as such.  

> *Manu Sporny:* Agree with selfissued.

> *Dave Longley:* +1 to Mike.

> *Dmitri Zagidulin:* `@manu` - amend the proposal to 'require arrays when it's NOT a functional item' (single-only).

**Orie Steele:** it wouldn't be issuer (since you're not allowed multiple), but it would mean multiple subjects.  
… so, if you're only allowed to have an object or a string, you'd still see singleton.  
… remember, this compact JSON-LD doc is an instance of the RDF data model, so we get the array polymorphism from that.  

> *Dave Longley:* not sure if there's a "net improvement" here... we might improve in one direction and cause harm in another.

> *Orie Steele:* in the real world there are multiple issuers.

**Dmitri Zagidulin:** To respond to all 3... Mike - reason we're discussing is this is a cause for a bunch of bugs, singleton vs. array... Orie - disagree that we're inheriting polymorphism from RDF data models, we're inheriting it from the real world -- sometimes it's a singleton, sometimes it's an array. Manu - you have a point, but it's amenable - require arrays only when arrays are possible (single items only require singletons).  

> *Orie Steele:* we are inheriting from using JSON-LD for conforming documents.

> *Orie Steele:* one place this is very likely to cause bugs is credentialSchema and credentialStatus.

**Manu Sporny:** people are suggesting 'require arrays whenever arrays are possible'. we don't have expressions of arity except in spec.  
… the vast majority of the vocabularies don't specify arity; people don't go through the trouble of doing that.  
… we can say "in OUR specification, we do specify the arity" for the fields defined in VC DM.  
… but that falls apart the moment you extend the core DM.  
… so, this might be brittle.  
… I don't think we can require enforceable arity.  

> *Dave Longley:* push this to credentialSchema <--.

> *Dave Longley:* if you want it, use `credentialSchema`... that's one thing it's for, right?

**Manu Sporny:** unless we require JSON Schemas for all VCs, this is non-enforceable.  
… we can provide non-norm guidance for people not to do it.  

**Brent Zundel:** counter-proposal, if I understand, is 'Do nothing'.  
… turning mike over to Kristina.  

> *Orie Steele:* I am fine closing the issue.

</details>

**Comment by OR13** [comment]
based on the comments on the call, I am closing this issue.
