### ISSUE TITLE
Clarify evidence section to point to OBv3 evidence property usage

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1293]
We should update the evidence section of the specification to use 1EdTech specifications that have utilized the `evidence` property. Namely, OBv3 and CLR:

*  https://www.imsglobal.org/spec/clr/v2p0/#evidence
    * There 7 companies that have committed to implement CLRv2 with this extension
* https://1edtech.github.io/openbadges-specification/ob_v3p0.html#evidence
    * There are 8 companies that have committed to implement OBv3 with this extension

We should update the example in the evidence section to use an OBv3 example (instead of the fictitious example we have in the spec today).

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-01-31-vcwg#section2-7) on 2024-01-31

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.7. Clarify evidence section to point to OBv3 evidence property usage (issue vc-data-model#1293)

_See github issue [vc-data-model#1293](https://github.com/w3c/vc-data-model/issues/1293)._




**Brent Zundel:** Clarify the evidence section to point to OBv3 evidence property issue, raised by Manu and assigned to no one, Manu, walk us through this?  

**Manu Sporny:** The current evidence property doesn't use real examples and this is just about updating it to use real examples to use an OpenBadge v3 example of evidence.  

**Brent Zundel:** So this is about updating examples to make use of OpenBadges v3 examples -- and changing the text or not?  

**Manu Sporny:** Just to update the examples.  

> *Phillip Long:* +1 to that ;-) I'll make a stab at that/.

**Brent Zundel:** Can anyone be assigned to update those examples?  
… I see Phil Long will work on it.  

**David Chadwick:** It was just to say that the other real example is the one from New York customer work -- the OpenID foundation work. Similar examples in the CCG.  
… If you want to refer to that as well, as another solid example you could.  

**Brent Zundel:** If you have links to either of those that would be really helpful.  

**David Chadwick:** How should I get those across?  

**Brent Zundel:** Add them directly to the issue, excellent, thank you very much, David.  

> *Phillip Long:* Thanks David.

</details>

**Comment by decentralgabe** [comment]
fixed by #1444
