### ISSUE TITLE
address normative statements in non-normative sections

### ISSUE THREAD

**Issue by Sakurann** [w3c/vc-data-model#1299]
from Issue #1285

> 1.3 Use Cases and Requirements
> 
> As this section is non-normative, it's best to avoid using the normative keywords like "Issuers revoking verifiable credentials should distinguish…" even if those keywords are kept lowercase so that RFC8174 says they don't have their normative meanings. Alternatively, you could move these statements to a section of conformance requirements for issuers (or their other subjects).

consider paraphrasing of moving certain sentences to normative sections.

**Comment by brentzundel** [comment]
I think adjusting the language to clarify that the statements are not normative is the best approach

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-02-07-vcwg#section4-3) on 2024-02-07

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.3. address normative statements in non-normative sections (issue vc-data-model#1299)

_See github issue [vc-data-model#1299](https://github.com/w3c/vc-data-model/issues/1299)._




**Brent Zundel:** maybe this is unnecessary since we have a PR to delete this section (use cases and requirements).  

**Manu Sporny:** I think removing the section addresses the issue. If this affects any other sections, we should open another PR and be more specific. +1 to close.  

**Brent Zundel:** 1429 is the other PR that deletes this section.  
… marking as pending close.  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-02-28-vcwg#section3-8) on 2024-02-28

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.8. address normative statements in non-normative sections (issue vc-data-model#1299)

_See github issue [vc-data-model#1299](https://github.com/w3c/vc-data-model/issues/1299)._




**Brent Zundel:** Address normative statements in non-normative sections.  
… We talked about this three weeks ago. I should have marked it pending close last time, sorry folks.  
… A PR addressed this, that happened, this has been addressed.  

> *Manu Sporny:* +1 to close because it's been addressed.

**Brent Zundel:** I will close this after the meeting today.  

</details>

**Comment by brentzundel** [comment]
The section in this issue has been removed from the spec. Closing as it has been addressed.
