### ISSUE TITLE
Add "revocationAuthority" property

### ISSUE THREAD

**Issue by Drabiv** [w3c/vc-data-model#130]
Proposal to add "revocationAuthority" property into "revocation" object. Please, see below.
```
...
"revocation": {
    "id": "http://example.gov/revocations/738",
    "type": "SimpleRevocationList2017"
     "revocationAuthority": "did:example:ebfeb1f712ebc6f1c276e12ec21"
  },
...
```

The idea is to have explicitly stated who has the right to revoke credential. Usually it will be issuer, but it can also be other DIDs.

**Comment by dlongley** [comment]
I don't think this would appear inside of a credential, but rather, if you dereferenced the ID of the list to get the full list description, it could appear there. Furthermore, I think there's a Linked Data Object Capability pattern that could be employed here for handling delegating the ability to do list updates.

That being said, I think list management is potentially out of scope -- we just want to be able to reference the list and specify how to query it for credential status.

**Comment by Drabiv** [comment]
@dlongley, btu how would you know that identity that revoked the credential had the right to do so? If revocation was done by issuer that is clear - it is a valid revocation, but if revocation was done by some other identity how would we know that revocation is valid? (e.g. prescription issued by doctor, revoked by hospital or by pharmacy or by police) Would it not be beneficial to add something like "allowedRevocationAuthority" in the credential? 
```
...
"revocation": {
    "id": "http://example.gov/revocations/738",
    "type": "SimpleRevocationList2017"
    "allowedRevocationAuthority": "did:example:ebfeb1f712ebc6f1c276e12ec21"
  },
...
```

**Comment by dlongley** [comment]
@Drabiv,

> btu how would you know that identity that revoked the credential had the right to do so?

Because that identity was able to update the list. More specifically, because they were able to put an entry on that list for that particular credential. I'm suggesting that the management of that list be decoupled from the verifiable credential entirely -- so that issuers need only specify the list in the credential. I would expect, for example, the issuer to employ a capabilities system to ensure that only an entity with a capability to revoke a specific verifiable credential would be permitted to update the list.

I think this maintains a cleaner separation of concerns. This decoupling enables experimentation with list management techniques and reduces verifier complexity. It also means you don't have to reissue the credential when the issuer wants to change who is permitted to perform revocation (and it doesn't force an ACL model).

All the verifier needs to know is: "If the list says the credential is revoked, it is." IMO, it's up to the issuer to use a list with the appropriate controls; the verifier shouldn't need to care about those details.

**Comment by Drabiv** [comment]
Thanks for clarification @dlongley I agree with you. It would be better to manage revocations only via the list. 
Although, "allowedRevocationAuthorities" approach should not be prohibited also, for those who want to manage revocations this way.

**Comment by dlongley** [comment]
@Drabiv,

> Although, "allowedRevocationAuthorities" approach should not be prohibited also, for those who want to manage revocations this way.

Well, that approach involves the verifier so it introduces interoperability considerations. The verifier needs to understand that field and use it in order to be implemented properly. If this is a desirable feature, then I think we should introduce another type of list for it -- so that verifiers that want to support it can key off that:

```js
"revocation": {
    "id": "http://example.gov/revocations/738",
    "type": "SomeOtherTypeOfRevocationList2017"
    "allowedRevocationAuthority": "did:example:ebfeb1f712ebc6f1c276e12ec21"
  },
```

**Comment by Drabiv** [comment]
All right, makes sense! I think this should be added to spec someday.

**Comment by dlongley** [comment]
Closing this out as we don't plan on doing anything with it at the moment -- that's the policy the group has agreed to. Issues can always be reopened in the future when we plan to address them.
