### ISSUE TITLE
Clarify what conformance means to the issuers/verifiers

### ISSUE THREAD

**Issue by Sakurann** [w3c/vc-data-model#1300]
from Issue #1285

> 1.4 Conformance
>
> I think you have 2 or 3 conformance classes that aren't mentioned here. Since the spec includes statements like "An issuer MUST" and "A verifier SHOULD", software can conform to this spec by being a conforming issuer or a conforming verifier. And you should probably have more statements that constrain verifiers, for example to enforce the properties desired in 7.10 Validity Checks. I suspect that holders (or credential repositories?) don't need to be a conformance class, but you might want to turn statements like "Holders should be warned by their software" into active requirements on the repositories, which would make them a conformance class.

consider new sections that clarify what conformance to the spec requires from verifiers and/or issuers

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-11-01-vcwg#section2-4) on 2023-11-01

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.4. Clarify what conformance means to the issuers/verifiers (issue vc-data-model#1300)

_See github issue [vc-data-model#1300](https://github.com/w3c/vc-data-model/issues/1300)._




**Brent Zundel:** clarify what conformance means to issuers and verifiers. Assigned to Manu and Joe. What is the status?  

**Manu Sporny:** Still needs a PR written. I intend to do this, but cannot give a timeline. We should try to address this. Maybe someone else can get to it before I do.  

**Brent Zundel:** thank you. Agree we should not close and it should have a PR.  

</details>

**Comment by msporny** [comment]
PR #1336 has been raised to address this issue. This issue will be closed once PR #1336 has been merged.

**Comment by msporny** [comment]
PR #1336 has been merged, closing.
