### ISSUE TITLE
add explicit notes where terminology in the spec diverges from things elsewhere

### ISSUE THREAD

**Issue by Sakurann** [w3c/vc-data-model#1301]
from Issue #1285

> 1.2 Ecosystem Overview
>
> It's unfortunate that the different efforts in this space use different terminology. E.g. the verifier would probably be called the "relying party" in an OAuth or FedCM context. An issuer might be an "attester" in a privacy pass context. Would it be possible to mention those translations in this section next to the synonyms that are used in this document? I see that they're defined in 2 Terminology, but I think this might all be clearer if the definitions were in the sections where they naturally appear instead of being duplicated into a single Terminology section.

regardless whether we agree to change the definitions themselves to align with the terms defined elsewhere, when the term we end up using has a diverging definition, need to add a note to mention that.

jfyi all the issues labelled `terminology`: https://github.com/w3c/vc-data-model/issues?q=is%3Aissue+label%3Aterminology+

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-02-07-vcwg#section4-2) on 2024-02-07

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.2. add explicit notes where terminology in the spec diverges from things elsewhere (issue vc-data-model#1301)

_See github issue [vc-data-model#1301](https://github.com/w3c/vc-data-model/issues/1301)._




**Brent Zundel:** This is related to the other terminology issues. We had other discussions about evidence and NIST, and it seemed the consensus of the group is that we have defined terminology in the specifications and folks that are concerned with the differences can do their own comparison.  
… it feels like this is an unending task; what is the scope of everywhere else.  

> *Dave Longley:* +1 to Brent.

**Manu Sporny:** agrees that feels like unending work. The places where we have don't this does not seem to improve the spec. Even within NIST documents they are not consistent with their terminology.  
… sometimes we can all this out, but picking NIST is arbitrary; this is a global standard. I would like to stop doing this type of work unless its unclear.  

**Ted Thibodeau Jr.:** There are two flavors of this. They way this is written, its about other organizations using other terms with the same meaning as a term we are using. Such as verifier and Relying party. That is never ending.  
… in the case where we use a term in common use elsewhere and the definitions diverge, I think it does make sense to say what we mean.  
… I don't think that is common, nor that we need to search them out. just where we run into it.  

**Brent Zundel:** my read is that there is not appetite to do this and we should mark this pending close. Any object?  
… hearing no objections, marked as pending close.  

</details>

**Comment by brentzundel** [comment]
no objections raised since marking `pending close`, closing.
