### ISSUE TITLE
Make Section 4.1 non-normative

### ISSUE THREAD

**Issue by Sakurann** [w3c/vc-data-model#1310]
from the issue #1285 

> 4.1 Getting Started
>
> This section should probably be non-normative.

**Comment by Sakurann** [comment]
This sub-section 4.1 feels out of place. all other sub-sections in section 4 define a property, while this one is a guidance. I think this section should be moved somewhere else.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-02-07-vcwg#section4-4) on 2024-02-07

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.4. Make Section 4.1 non-normative (issue vc-data-model#1310)

_See github issue [vc-data-model#1310](https://github.com/w3c/vc-data-model/issues/1310)._




**Brent Zundel:** making getting started section non normative. It is already marked as such, so I think this is done. Suggests moving it to the introduction. or deleted. Comments? We could close as its marked non normative.  

**Manu Sporny:** getting started is in a section called basic concepts. Moving it to introduction doesn't make sense as its conceptually high level. Getting started is about syntax and a first example.  

**Ivan Herman:** I think its fine as it is. There is no question about normative-ness.  

**Brent Zundel:** proposal is to close the issue because the section is marked non-normative. If folks object, speak up.  
… no objections, closing this after the call.  

</details>

**Comment by brentzundel** [comment]
Closing, per the conversation during the call today.
