### ISSUE TITLE
Use a better example for bidirectional text (Editorial)

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-model#1313]
This is an editorial remark in case #1264 gets resolved, and some text goes into the text. I just do not want to forget about this.

https://github.com/w3c/vc-data-model/issues/1264#issuecomment-1712807665 uses a number of examples that might end up as part of the specification. In particular, this includes (a variation of):

```
{
  "@context": ["https://www.w3.org/ns/credentials/v2", "https://language.example/contexts/v1"],
  "type": ["VerifiableCredential", "MyHumanReadableCredential"],
  "credentialSubject": {
    "myHumanReadableProperty": [{
      "value": "This is some human-readable text.",
      "lang": "en"
  }, {
      "value": "هذا بعض النص الذي يمكن قراءته بواسطة الإنسان.",
      "lang": "ar",
      "dir": "rtl"
  }]
}
```

My feeling (but I have to rely on the opinion of @aphillips) is that the second, Arabic, example is not the good one. Indeed, the value contains an Arabic text, with Arabic characters only. For such a case, the `"dir":"rtl"` is unnecessary, just as a `"dir":"ltr"` is unnecessary for the first, English example. The Unicode specification makes it clear that the characters are Arabic and therefore right-to-left; the simple algorithm relying on the directionality of the first character in the string would therefore assign the "rtl" attribute to the full text. Which is fine.

The reason of having the "dir" attribute is for _bidirectional_ texts, where this simple approach goes wrong. An example can be found in the [Publication Manifest spec](https://www.w3.org/TR/pub-manifest/#example-2-set-the-language-and-the-base-direction-of-a-string):

```
{
    "value"     : "HTML היא שפת סימון.",
    "lang"  : "he",
    "dir" : "rtl"
}
```

The reason the `dir` attribute is necessary, is because the first character in the value string is the letter "H", which is set to be "ltr", and the Unicode algorithm would then assign this value to the whole string. And in this case it is wrong, because the text is a bona fide Hebrew text, ie, "rtl", just using an English abbreviation at the beginning. 

(I am not saying we should use the Publ. Manifest example for VCDM; we may want to find something more close to what VCDM is all about.)

**Comment by aphillips** [comment]
Base direction is useful, even if the text is unambiguous, since it can be used as part of bidi isolation.

Notice that the Arabic example has a neutral `.` at the "end", but it is displayed incorrectly on the right side of the string. This is what happens if the Arabic is displayed in a left-to-right context without setting the base direction. Of course, this isn't as visually obvious as the Hebrew example from ePub.

It would be a good idea to have a more obvious mixed direction string in examples, though, and probably one that is consistent with other examples in VC, e.g. "2015 درجة البكالوريوس في العلوم والآداب" (2015 Bachelor of Science and Arts Degree) [[play with](https://w3c.github.io/i18n-discuss/explainers/bidi-html-demo.html?text=2015%20%D8%AF%D8%B1%D8%AC%D8%A9%20%D8%A7%D9%84%D8%A8%D9%83%D8%A7%D9%84%D9%88%D8%B1%D9%8A%D9%88%D8%B3%20%D9%81%D9%8A%20%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85%20%D9%88%D8%A7%D9%84%D8%A2%D8%AF%D8%A7%D8%A8)]

**Comment by iherman** [comment]
> Base direction is useful, even if the text is unambiguous, since it can be used as part of bidi isolation.

Of course. But this becomes relevant, I presume, only if some default direction is set for the data as a whole (and is not `rtl`, which is not the case for these examples.

> 
> It would be a good idea to have a more obvious mixed direction string in examples, though, and probably one that is consistent with other examples in VC, e.g. "2015 درجة البكالوريوس في العلوم والآداب" (2015 Bachelor of Science and Arts Degree) [[play with](https://w3c.github.io/i18n-discuss/explainers/bidi-html-demo.html?text=2015%20%D8%AF%D8%B1%D8%AC%D8%A9%20%D8%A7%D9%84%D8%A8%D9%83%D8%A7%D9%84%D9%88%D8%B1%D9%8A%D9%88%D8%B3%20%D9%81%D9%8A%20%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85%20%D9%88%D8%A7%D9%84%D8%A2%D8%AF%D8%A7%D8%A8)]

I am out of my depth, @aphillips, so I may be wrong with this. But isn't it correct that a number is, formally, "neutral" in terms of deciding the directionality of the text? This is why I believe a better example would be mixing Latin and Arabic or Hebrew characters.

Also, we may want to alternate Hebrew and Arabic language examples if we can. Just to avoid being accused of bias either way...

**Comment by TallTed** [comment]
> alternate Hebrew and Arabic language examples

I might hope that the I18n WG would have a stockpile of samples, including at least Hebrew and Arabic (in addition to English) if not several others (Chinese, Russian, Greek, and Slovak leapt to mind before I thought to search out a page like [The World's Most Popular Writing Scripts](https://www.worldatlas.com/articles/the-world-s-most-popular-writing-scripts.html)).

**Comment by aphillips** [comment]
(tracking this issue but not adding needs-resolution, since it is entirely editorial and since there is nothing that "needs resolution" about the examples currently in use)

--

@iherman 
>But isn't it correct that a number is, formally, "neutral" in terms of deciding the directionality of the text? This is why I believe a better example would be mixing Latin and Arabic or Hebrew characters.

Actually, in most (but not all) writing systems, numbers are weakly directional. They don't break up a directional run, but themselves run in the left-to-right direction. Numbers can generate spillover effects as a result. However, you're right that mixed Latin and Arabic/Hebrew/etc. can make directional issues clearer.

**Comment by iherman** [comment]
Looking at the current spec, more exactly, at [Example 40](https://www.w3.org/TR/vc-data-model-2.0/#example-arabic-text-with-a-base-direction-of-right-to-left) this issue is now moot. Closing.
