### ISSUE TITLE
Update 4.9 Securing Verifiable Credentials

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-model#1316]
It was requested to update this section to clarify that it is only relevant to Data Integrity and not VC JOSE COSE.

https://github.com/w3c/vc-data-model/pull/1308#pullrequestreview-1662838622

**Comment by OR13** [comment]
![Screen Shot 2023-10-13 at 1 37 58 PM](https://github.com/w3c/vc-data-model/assets/8295856/9f3b7e04-5016-4dd6-905b-931cc9855aaa)

https://w3c.github.io/vc-data-model/#securing-verifiable-credentials

We didn't get all the change needed in #1308 and we will need to do a follow up PR to align the text above the examples

**Comment by msporny** [comment]
> It was requested to update this section to clarify that it is only relevant to Data Integrity and not VC JOSE COSE.

That section is relevant to both Data Integrity and VC JOSE COSE. Not clear what this issue is attempting to address.

**Comment by OR13** [comment]
@Sakurann can add details, essentially we removed proof from the first and second examples of the spec, the sections around those examples need to be updated, and since `proof` (the JSON-LD property of a conforming document) is only required  / recommended for use with data integrity proofs, this issue tracks completing the requested updates regarding `proof` that started on #1308

**Comment by brentzundel** [comment]
Chair hat off, I do not agree with removing the proof property from VCDM.
I see it as an extension point, which has been utilized by Data Integrity, but which could be utilized by any other mechanism that wishes to. 

IMO, section 4.9 does not only apply to Data Integrity and it should not be modified to make it only apply to Data Integrity.

**Comment by brentzundel** [comment]
What is the relationship between this issue and #1312 ?
Are both needed?

**Comment by OR13** [comment]
I suggest we attempt to resolve this after all the "verificaton algorithm" issues are resolved

**Comment by msporny** [comment]
PR #1389 has been raised to address the "before-CR" portion of this issue.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-12-19-vcwg-special#section2-8) on 2023-12-19

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.8. Clarify that "proof" is an extension point (pr vc-data-model#1389)

_See github pull request [vc-data-model#1389](https://github.com/w3c/vc-data-model/pull/1389)._




**Brent Zundel:** Clarify that `proof` is an extension point. This PR is addressing issue 1316. I'm going to let Manu talk about it.  

_See github issue [vc-data-model#1316](https://github.com/w3c/vc-data-model/issues/1316)._




**Manu Sporny:** There was a part of #1316 that I thought we could potentially address before CR. This PR attempts to clarify that `proof` is an extension point and always has been, and DI uses it in a way that's compatible, but DI isn't the only way. Other specs can use it too.  
… The only requirement is that you specify the `type` of the `proof`.  
… The concern here is that if we make `proof` only about DI then it's bound explicitly to that and we wanted to avoid that.  
… It makes some non-normative and small normative changes to clarify that. This PR also splits the securing mechanism section into two parts, one is to talk about securing mechanisms generally.  
… We talk about envelope and embedded proofs. The separate part we create the `proof` extension section explicitly.  
… It makes it much clearer that it's non-exclusive.  
… There are some concerns that Ivan has and Mike has concerns, but we shouldn't look at this as an either-or with the PRs that Mike raised and this one. I think we can merge this one and Mike can come back in an make his edits.  
… The key split here is that to talk about securing mechanisms and their specs wholly separately from the `proof` extension point.  

**Brent Zundel:** Thank you, Manu.  

**Michael Jones:** The strange thing I ran into when doing my PR was a statement that all embedded proofs must use the `proof` property. Which seems it's overly tying the hands of people writing proof mechanisms that we haven't thought of.  
… You could easily imagine some future ZKP mechanism embedding a different identifier that's specific to the mechanism. It's fine for it to be an extension point, but it shouldn't be a mandatory one for all embedded proofs. I'll review with that hat on.  

**Manu Sporny:** Totally agree, that is exactly the normative change I was hoping we could make. We're in agreement on that.  
… The previous text forced anyone doing an embedded securing mechanism to utilize proof and we should relax that and +1 to that, Mike says he agrees.  

**Michael Jones:** Ok, we're violently agreeing again, that's good news.  

**Brent Zundel:** Makes me happy.  

</details>

**Comment by msporny** [comment]
PR #1389 has been merged, removing "before-CR' label.

**Comment by TallTed** [comment]
It's unclear to me what the "post-CR portion" of this issue is. Could that be restated/summarized, or maybe made into a new issue?

**Comment by msporny** [comment]
The Securing Mechanisms section and the Securing Mechanism Specifications sections have been largely reworked:

https://www.w3.org/TR/2024/WD-vc-data-model-2.0-20240106/#securing-mechanisms

The `proof` section no longer exists in the specification.

I'm asserting that we've made the changes necessary to close this issue and am marking it pending close.

**Comment by brentzundel** [comment]
no objections raised since marked `pending close`, closing
