### ISSUE TITLE
W3C Caused by: com.apicatalog.jsonld.JsonLdError: Unexpected response code [429] 

### ISSUE THREAD

**Issue by tuanphampmt** [w3c/vc-data-model#1330]
My name is Tuan, I am getting the following error:
```
Caused by: com.apicatalog.jsonld.JsonLdError: Unexpected response code [429].
JsonLdError[code=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED]., message=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].]
```
According to my understanding of this error, I seem to have sent many requests to two urls:
"https://www.w3.org/2018/credentials/v1",
"https://catenax-ng.github.io/product-core-schemas/SummaryVC.json",
1.	Can I ask if the w3.org organization seems to have limited my request?
2.	Can you help me solve this problem? I really need help to complete my work
Sincerely thank

**Comment by davidlehn** [comment]
- If you have a legit application and your code is operating properly, it's unlikely you hit that error on w3.org or github.io, at least not permanently.
- How many requests did you send to cause that error response?
- Which URL is the problem?  Those contexts are on completely different services.
- `"summary": "https://w3id.org/2023/tractusx/credentials/summary/"` should be changed.  `w3id.org` is also a different service, and `2023` or `tractusx` is not mapped, so that's a 404 link.  As a maintainer of that service, I'm not even sure how much traffic would cause a 429, but if you did get that response, you're doing something wrong.
- You need to provide more details to get help with this issue.  And it probably has nothing to do with `vc-data-model`.  You might have better luck asking the authors of the JSON-LD processor you are using.
- Please add context caching to your application and/or JSON-LD processor document loader so you reduce or eliminate any network traffic.

**Comment by msporny** [comment]
This is not a support repository for 3rd party software libraries. Marking as pending close. You can continue to discuss the issue here, but there is nothing for the W3C Verifiable Credentials Working Group to do here (unless you can tie the request to the "https://www.w3.org/2018/credentials/v1" URL).
