### ISSUE TITLE
Add validation to lifecycle details image

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1331]
This issue was raised by @jandrieu in PR #1297. The lifecycle details image needs to include the concept of validation.

**Comment by jandrieu** [comment]
Whoops. We should reopen this.

The issue I created #1328 is different that this one.

**Comment by TallTed** [comment]
I *think* a single dashed line (like the one now labeled "Delete" from Holders) going from Verifiers to upper-right, labeled as "Validate (repeatable)" would serve?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-02-07-vcwg#section4-6) on 2024-02-07

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.6. Add validation to lifecycle details image (issue vc-data-model#1331)

_See github issue [vc-data-model#1331](https://github.com/w3c/vc-data-model/issues/1331)._




**Brent Zundel:** it was closed as completed but Joe re-opened it. I don't know what is going on with this PR.  

**Manu Sporny:** we don't have this in the image now. We have verify but we don;t have validate. This is not done.  

> *Manu Sporny:* See [the diagram's location](https://w3c.github.io/vc-data-model/#lifecycle-details).

**Brent Zundel:** It would be a loop from verifier to verifier that says validate?  

**Manu Sporny:** I don't know but I would expect something like that.  

**Brent Zundel:** Suggest we add a loop from verifiers to verifier that says validate. Anyone want to volunteer?  

**Ivan Herman:** I am not volunteering. but it may be a good opportunity to look at all the figures. We have problems if the document is seen in dark mode.  

**Brent Zundel:** I suggest opening an issue to track image dark-mode compatibility and raised separately.  

**Ivan Herman:** agreed.  

**Brent Zundel:** did not hear anyone volunteer. If no one volunteers, its not going to happen.  
… We are on track with a small extension. Pay atttention as meeting times may change. Closing the meeting.  

---

</details>

**Comment by msporny** [comment]
PR #1441 was raised to address this issue, that PR has been merged, closing.
