### ISSUE TITLE
Define algorithm for verification

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1337]
In issue https://github.com/w3c/vc-data-model/issues/1285#issuecomment-1731724138 @jyasskin wrote:
> The serious issue is the one about defining the algorithm for verification. The definition of [validation](https://www.w3.org/TR/vc-data-model-2.0/#dfn-credential-validation) in this spec says that [verification](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verify) is in scope: "This specification is constrained to [verifying](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verify) [verifiable credentials](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verifiable-credential) and [verifiable presentations](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verifiable-presentation) regardless of their usage. _Validating_ [verifiable credentials](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verifiable-credential) or [verifiable presentations](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verifiable-presentation) is outside the scope of this specification." To be clear, I'll encourage Google to formally object to this spec if an algorithm for verification isn't moved to [Proposed REC](https://www.w3.org/2023/Process-20230612/#RecsPR) at the same time as this spec. It's fine for this algorithm to call out to algorithms in other specs, or to look up subroutines in a registry, but the top-level algorithm needs to be defined. That's for two reasons:
> 1. It's hard to be confident of interoperability if implementations have to gather verification requirements from many places across this and other specifications. If an implementation misses one or finds an extra one, it won't interoperate with implementations that found a different set of requirements.
> 2. The security and privacy properties of VCs depend critically on the exact algorithm that a verifier follows. Privacy, for example, gets compromised if a verifier fetches an extra URL that happens to identify the credential that it's verifying. In order for security and privacy reviewers to check that this spec meets its goals, they have to be able to read the verification algorithm.

**Comment by msporny** [comment]
PR #1338 has been raised to address this issue. This issue will be closed once PR #1338 has been merged.

**Comment by jyasskin** [comment]
I don't expect #1338 to be sufficient to close this. It's a good start, but it calls other algorithms that haven't been written yet, or which are missing important checks and type-consistency. This list is probably incomplete, but I see:

- [ ] https://github.com/w3c/vc-jose-cose/issues/187
- [ ] https://github.com/w3c/vc-data-integrity/issues/222

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-12-13-vcwg#section2-1) on 2023-12-13

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.1. Define algorithm for verification (issue vc-data-model#1337)

_See github issue [vc-data-model#1337](https://github.com/w3c/vc-data-model/issues/1337)._




**Brent Zundel:** some have PRs exist.  

**Manu Sporny:** this one needs to be closed, we merged related PRs, and filed follow up issues.  

</details>

**Comment by msporny** [comment]
@jyasskin we're tracking improvements to the verification algorithm in more specific issues/PRs. The WG decided that it would be best to close this PR as the verification algorithm now exists (it's imperfect, but it's there). Refinements to the algorithm will be performed via other existing issues/PRs.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-12-20-vcwg#section4-1) on 2023-12-20

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.1. Define algorithm for verification (issue vc-data-model#1337)

_See github issue [vc-data-model#1337](https://github.com/w3c/vc-data-model/issues/1337)._




**Brent Zundel:** 1337 Define Alg for Verify. Main PR has been merged. I will close after call today.  

</details>
