### ISSUE TITLE
Issuer appears to be defined using a non-JSON-LD data model

### ISSUE THREAD

**Issue by jyasskin** [w3c/vc-data-model#1342]
https://w3c.github.io/vc-data-model/#issuer says

> The value of the issuer [property](https://w3c.github.io/vc-data-model/#dfn-property) MUST be either a [URL](https://w3c.github.io/vc-data-model/#dfn-url) or an object containing an id [property](https://w3c.github.io/vc-data-model/#dfn-property).

But unless I've misunderstood how JSON-LD works, `"some:url"` is exactly equivalent to `{"@id": "some:url"}`, and the VC context makes `"id"` a shorthand for `"@id"`.

**Comment by msporny** [comment]
Your interpretation is correct. I'm struggling to see where you see the misalignment with JSON-LD?

Maybe you were expecting us to say more about what the value of the `id` property should be?

**Comment by jyasskin** [comment]
No, I think it's that I'm not expecting it to say the property MUST be ~"X or something-equivalent-to-X". An "or" in a spec makes me think there will be two different things there. In the terminology from https://www.w3.org/TR/json-ld11/#data-model-overview, I think you're requiring that the value has to be a [resource](https://www.w3.org/TR/rdf11-concepts/#dfn-resource) that is not a [blank node](https://www.w3.org/TR/rdf11-concepts/#dfn-blank-node). There might be a shorter way to say that, or you could introduce a local "non-blank resource" term to cover it.

Going down to the terminology from https://www.w3.org/TR/rdf11-concepts/#section-rdf-graph, I think you're saying that the value has to be an [IRI](https://www.w3.org/TR/rdf11-concepts/#dfn-iri) rather than a [literal](https://www.w3.org/TR/rdf11-concepts/#dfn-literal) or a [blank node](https://www.w3.org/TR/rdf11-concepts/#dfn-blank-node) ... but that terminology is very bad, because it says both that ["An IRI ... is a Unicode string"](https://www.w3.org/TR/rdf11-concepts/#dfn-iri) and that ["http://example.org/ as a string literal is [not] equal to http://example.org/ as an IRI"](https://www.w3.org/TR/rdf11-concepts/#dfn-rdf-term), which if we substitute in the definitions says "http://example.org/ as a string literal is [not] equal to http://example.org/ as a Unicode string".

**Comment by msporny** [comment]
> I think you're requiring that the value has to be a [resource](https://www.w3.org/TR/rdf11-concepts/#dfn-resource) that is not a [blank node](https://www.w3.org/TR/rdf11-concepts/#dfn-blank-node).

Yes, your interpretation is correct. I'll try to raise a PR that makes that a bit easier to understand. All we're trying to say there is that you can do this:

```json
"issuer": "https://issuer.example/"
```

or you can do this:

```json
"issuer": {
  "id": "https://issuer.example/",
  ... more claims, like name and image, go here ...
}
```

**Comment by msporny** [comment]
PR #1349 has been raised to address this issue. This issue will be closed once PR #1349 is merged.

**Comment by seabass-labrax** [comment]
Because JSON-LD is used as a fundamental construct of the VC data model, I feel that the language relating to this should be somewhat harmonised throughout the specification. For instance, I see nothing particularly special about the `issuer` property that should require it to be dereferencable more so than, say, the `credentialSubject` property.  We have had discussions in the past about the extent to which JSON-LD should be explained, and I wonder how this issue fits into that wider context. Consider, for instance, that the shorthand for `@id` is defined directly in JSON-LD specification and dereferencable identifiers are already something of a best practice for the RDF ecosystem.

I don't consider my thoughts above to be blocking concerns, but if we as a group are able to find a compromise and agree upon an overarching strategy about the description of RDF-related aspects of the specification, I think we would be doing a great service to future implementers.

In light of these more recent edits, if the chair considers there to be adequate available time, to debate this topic separately from reviewing individual pull requests could be beneficial.

**Comment by jyasskin** [comment]
Re @seabass-labrax, one thing that the discussion in https://github.com/w3c/vc-data-model/pull/1349#discussion_r1391685319 and https://github.com/w3c/vc-data-model/pull/1346#discussion_r1391861257 pointed out is that VCs need to be first processed as JSON to check that properties have the right names as strings and things serialized in the right places, and only then parsed into RDF quads by a JSON-LD processor. As you say, this isn't specific to `issuer` or `credentialSubject`, and it'd be nice to define some central terminology so that each individual property can focus on its individual requirements.

This probably deserves a dedicated issue, but the resolution of that issue will also benefit from having first figured out how the WG wants it to work for some individual properties.

**Comment by msporny** [comment]
PR #1349 has been merged, closing.
