### ISSUE TITLE
Ensure `credentialStatus` `id` field is optional

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-data-model#1398]
It is currently required and should be made optional to work with BitStringStatusList and other privacy-preserving statuses. This should be a quick and minor (but normative) change.

**Comment by msporny** [comment]
This just requires a PR that makes the `id` field optional.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-12-20-vcwg#section4-5) on 2023-12-20

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.5. Ensure `credentialStatus` `id` field is optional (issue vc-data-model#1398)

_See github issue [vc-data-model#1398](https://github.com/w3c/vc-data-model/issues/1398)._




**Brent Zundel:** Issue 1398 credential status id field is optional. Required id property not necessary.  

**Manu Sporny:** I'll raise the PR. Its fairly straightforward.  

</details>

**Comment by msporny** [comment]
PR #1401 has been raised to address this issue. This issue will be closed once PR #1401 has been merged.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-01-03-vcwg#section2-2) on 2024-01-03

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.2. Ensure `credentialStatus` `id` field is optional (issue vc-data-model#1398)

_See github issue [vc-data-model#1398](https://github.com/w3c/vc-data-model/issues/1398)._




**Brent Zundel:** 1398. Ensure credentialStatus id field is optional. Believe this is on track to be closed. PR 1401 is raised and on track.  

</details>

**Comment by msporny** [comment]
PR #1401 has been merged, closing.
