### ISSUE TITLE
Clarify embedded proof extension point

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1400]
@iherman [requested that we more generally specify the enveloped and embedded proof extension mechanisms](https://github.com/w3c/vc-data-model/pull/1389#issuecomment-1867545181), and then continue to normatively refer to the securing mechanisms that the WG has defined as RECOMMENDED mechanisms. @msporny [clarified some guidelines around doing that](https://github.com/w3c/vc-data-model/pull/1389#issuecomment-1867865744). 

This issue is being raised to track that concern.

**Comment by msporny** [comment]
PR #1403 has been raised to address this issue. This issue will be closed once PR #1403 has been merged.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-01-03-vcwg#section2-3) on 2024-01-03

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.3. Clarify embedded proof extension point (issue vc-data-model#1400)

_See github issue [vc-data-model#1400](https://github.com/w3c/vc-data-model/issues/1400)._




**Brent Zundel:** 1400 Clarify embedded proof extension point. also on track with this. expect it to be addressed by EOW.  

</details>

**Comment by msporny** [comment]
PR #1403 has been merged, closing.
