### ISSUE TITLE
phrasing and/or punctuation for input "inputBytes or inputDocument and inputMediaType" needs work

### ISSUE THREAD

**Issue by TallTed** [w3c/vc-data-model#1402]
As written, it's unclear whether it's "(`inputBytes` or `inputDocument`) and `inputMediaType`" or "`inputBytes` or (`inputDocument` and `inputMediaType`)"; i.e., whether `inputMediaType` is always present (which I believe is correct), or only travels with an `inputDocument` (which I believe is incorrect).

This applies to at least two instances of these inputs (circa lines 2022 and 4540), possibly more.

This can be assigned to me. I wanted to get confirmation of my belief above before going to PR.

**Comment by msporny** [comment]
`inputMediaType` is always present. Implementers can choose if their verification functions take `inputBytes` or `inputDocument` (or both) as input. 

@dlongley was concerned that implementers that chose to take `inputDocument` plus an `inputMediaType` would be marked as non-conforming. 

Note that there are cases where `inputBytes` is the only thing that makes sense (JWT, CBOR, etc). There are other cases where `inputDocument` makes sense... like for any Data Integrity-protected content.

**Comment by TallTed** [comment]
> Implementers can choose if their verification functions take `inputBytes` or `inputDocument` (or both) as input.

I *think* it only makes sense for a single verification action to involve one of these (`inputBytes` or `inputDocument`), but an implementation could accept each at different times. So inputs are a pair of an `inputMediaType` and either an `inputBytes` or an `inputDocument`, and a given verification function implementation could choose to only ever accept one of these pairs, or to accept whichever pair a client fed it.

Yes?

**Comment by msporny** [comment]
@TallTed wrote:
> Yes?

Correct.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-02-14-vcwg#section2-4) on 2024-02-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.4. phrasing and/or punctuation for input "inputBytes or inputDocument and inputMediaType" needs work (issue vc-data-model#1402)

_See github issue [vc-data-model#1402](https://github.com/w3c/vc-data-model/issues/1402)._




**Brent Zundel:** first, #1402 phrasing and/or punctuation for input "inputBytes or inputDocument and inputMediaType" needs work.  
… raised to and assigned to TallTed. how is it going?  

**Ted Thibodeau Jr.:** on my list. not a complex thing, just needs to be done. hope to get it done in the next couple days.  

</details>
