### ISSUE TITLE
Does the specification need a normative "Credential Type Specifications" section?

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1410]
Based on comments from @jyasskin in https://github.com/w3c/vc-data-model/issues/1388#issuecomment-1875788296 :+1: 
> We have a recent precedent for non-testably "MUST"ing specifications in https://w3c.github.io/vc-data-model/#securing-mechanism-specifications. I think it's reasonable to write similar requirements for specifications for credential types.

This issue has been opened to track whether or not the WG desires to write such a section, they believe the current statements in the specification are good enough, or if an entry in the implementation guide would be more appropriate.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-01-17-vcwg#section2-1) on 2024-01-17

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.1. Does the specification need a normative "Credential Specifications" section? (issue vc-data-model#1410)

_See github issue [vc-data-model#1410](https://github.com/w3c/vc-data-model/issues/1410)._




**Brent Zundel:** We're going to start with a non-triaged issue.  
… Is this something we feel is an issue that needs to be addressed, if so, who is going to work on it?  

**Manu Sporny:** Yes, I can provide insight but Jeffrey is here too.  
… We're trying to provide guidance on things that ... people who extend the data model and write specifications about credentials, like specific types of credentials like driver's licenses, passports, coupons, whatever.  
… I think Jeffrey's concern was that there are times when it's ok using credential type-specific processing and there may times when that's not ok. I think Jeffrey you wanted us to give clearer guidance on that -- on things you should and shouldn't be doing. Like avoid these features / throw errors on this stuff, you should be producing a JSON schema that should be doing xyz and whether the VCDM gives guidance to people writing credential.  
… specs and what they should say about type-specific processing.  
… We give guidance on securing specs and this would give guidance for credential spec writers that say things like "provide a JSON schema for type-specific processors, provide a semantically immutable context, etc.".  

**Jeffrey Yasskin:** Yeah, that does basically capture what I'm worried about. My core worry was broader. If you secure something w/ JSON-LD and process it w/ JSON there are footguns, or vice versa, I didn't find attacks but doesn't mean there aren't any. So guidance so people don't write vulnerabilities.  

**Brent Zundel:** It seems like this is something important to work on, is this something that could be handled editorially, or does it require normative changes?  

**Manu Sporny:** I'm pretty sure we need normative text. This is normative text for credential specifications.  

> *Jeffrey Yasskin:* +1.

**Manu Sporny:** I think you should argue that the text you could write would not affect software implementations, but it would affect credential spec writers / specs. I think it's arguable. I think we need to write normative text about it, but I don't know how CR is handled with respect to normative text that only applies to specs and not implementations.  
… That's it.  

**Brent Zundel:** Yes, I also don't have a good answer there. This is something that shouldn't implement the implementations of the core data model, that's main concern during CR, but would affect implementations for credential type specifications.  

**Manu Sporny:** It wouldn't affect securing specs. It would affect credential type specs.  
… Like IMS global, etc.  

> *Manu Sporny:* pdl-ASU: The HR Open standards organization is in the process of trying to move their schema for HR standards, and orgs that use them, into form to issue Verifiable Credentials. This would apply directly to 21 or more JSON objects that are a part of their resume WG's scope. It would be valuable to them.

**Jeffrey Yasskin:** With respect to HR Open standards specs, I would hope that any requirements in this document either don't affect them, or will point out security concerns that they would like to have pointed out.  

> *Phillip Long:* +1 Jeffrey.

**Manu Sporny:** Not opposed, we might want CR-2, CR-3, CR-4 tags to better track this. They might go back and check and we are supposed to highlight in our revision history.  

**Brent Zundel:** Let's create a "CR2" label for this, then.  

> *Jeffrey Yasskin:* [https://www.w3.org/2023/Process-20231103/#revising-cr](https://www.w3.org/2023/Process-20231103/#revising-cr).

**Brent Zundel:** who's willing to take a shot at this issue?  

**Manu Sporny:** I can take the issue if Jeffrey can help me.  

**Jeffrey Yasskin:** ok, happy to help review.  

**Brent Zundel:** The question here -- is this something we need to do? Who will work on it?  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-01-31-vcwg#section2-1) on 2024-01-31

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.1. Does the specification need a normative "Credential Type Specifications" section? (issue vc-data-model#1410)

_See github issue [vc-data-model#1410](https://github.com/w3c/vc-data-model/issues/1410)._




**Brent Zundel:** Does this spec need a normative credentials specification section... we talked about this a couple of weeks ago.  
… If we do this, it's likely it will require some normative text. We created a CR-2 label for it and so it's triaged and Manu has accepted an assignment for it... can you speak to this Manu?  

> *Manu Sporny:* Jeffrey's concerns are here: [https://github.com/w3c/vc-data-model/issues/1388#issuecomment-1875788296](https://github.com/w3c/vc-data-model/issues/1388#issuecomment-1875788296).

**Manu Sporny:** Jeffrey Yaskin raised a number of concerns -- saying he would like to see specifications that define new credential types like ... types for driver's licenses, or employment authorization documents, or digital coupons, or whatever ... that we have guidance to those specs in the core data model.  
… So we established things securing specs must do and he's saying we should establish things that credential type specs must do.  
… He suggested some items in the comment I linked to. One way to do that is to have a section that is like the securing specs ... and specify requirements there. I'm still a bit fuzzy on what we'd write in that section. We don't have to write that section, it's not clear that if we wrote something Jeffrey would be happy with it, I could try to make an attempt... I need direction from the group.  
… Is this worth doing this at this point? Do we do one PR and try to make it work and if we don't just close it?  

**Brent Zundel:** So this issue is asking for, suggesting that the core data model needs a section of normative requirements aimed toward potential credential type spec authors that would guide those authors and tell them what their specs are required to include to be best compliant with the core data model. Is that right?  

**Manu Sporny:** Yes, I think that's close.  

> *Phillip Long:* I like the idea of giving one PR a shot for normative requirements for type specification authors per [https://github.com/w3c/vc-data-model/issues/1388#issuecomment-1875788296](https://github.com/w3c/vc-data-model/issues/1388#issuecomment-1875788296).

**Brent Zundel:** So kind of what the DID spec did with DID methods.  

**Manu Sporny:** Yes.  

**Joe Andrieu:** I think this is a form of centralization that is probably not going to be good for us. It would mean that if your new type of credential doesn't fit and we're trying to stand in that way.  
… The difference with DID methods is we're running a registry, which I also oppose, and we don't have a similar registry and I don't think we should add one, so we shouldn't try to do this.  

**Manu Sporny:** I think Jeffrey is talking about security requirements, so things that a spec would need to say to be processed as regular JSON -- so you can process as JSON-LD or as JSON ("credential type-specific processing").  
… I don't think this creates a centralization concern.  

**Brent Zundel:** So, in addition to your credential spec needing a security considerations section, what other normative guidance might be necessary for it to work with the core data model?  

> *Manu Sporny:* [https://github.com/w3c/vc-data-model/issues/1388#issuecomment-1875788296](https://github.com/w3c/vc-data-model/issues/1388#issuecomment-1875788296).

**Brent Zundel:** So what, specifically, might we provide in terms of guidance?  

**Manu Sporny:** He's got like three things in an issue. Like "you must use enveloping proofs", I don't agree with that one. He also has "never create a claim that says: 'this other claim means some other claim means nothing if this one exists'.  

> *Manu Sporny:* Here are some normative requirements that we could write into this section: [https://github.com/w3c/vc-data-model/issues/1388#issuecomment-1875788296](https://github.com/w3c/vc-data-model/issues/1388#issuecomment-1875788296).

**Brent Zundel:** Where is this?  

**Manu Sporny:** Again -- I think it would be very challenging writing the language, willing to give it a shot, but not expecting success.  

**Joe Andrieu:** They seem pretty arbitrary, the first one Manu didn't even agree with -- trying to establish these things, I think we don't have a good enough understanding to get to consensus and limiting what people are allowed to say with VCs I would oppose.  

**David Chadwick:** I find number 3 is problematical given our data model where we have claims that invalidate others.  

</details>

**Comment by jyasskin** [comment]
Note that the three options I listed in https://github.com/w3c/vc-data-model/issues/1388#issuecomment-1875788296 are _alternatives_. If the WG wants to recommend just one as the way for credential designers to avoid security vulnerabilities, that would still solve the problem. I listed 3 because I don't have the WG's expertise about which options are best.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-02-28-vcwg#section3-7) on 2024-02-28

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.7. Does the specification need a normative "Credential Type Specifications" section? (issue vc-data-model#1410)

_See github issue [vc-data-model#1410](https://github.com/w3c/vc-data-model/issues/1410)._




**Brent Zundel:** Do you need feedback on this one, Manu?  

**Manu Sporny:** The proposal here is "no", we should not add a normative credential types spec, it would be extra work, it's not clear what we would put in it; unless people feel strongly about this, my proposal is to mark pending close and say we won't be adding it.  
… Saying we won't add that section this time around.  

**Brent Zundel:** Anyone disagree and think we should get normative in the credential types specification?  
… No objections.  
… Especially since we'll have another PR that adds some clarity here.  

</details>

**Comment by brentzundel** [comment]
No objections raised since being marked `pending close`, closing
