### ISSUE TITLE
`Type-Specific Credential Processing` is better phrasing than `Credential Type-Specific Processing`

### ISSUE THREAD

**Issue by TallTed** [w3c/vc-data-model#1415]
As it says on the tin... 

`Credential Type-Specific Processing` has bothered me since it was coined, and it just hit me that this simple word flip to `Type-Specific Credential Processing` would fix it.

This will need to be changed at several locations, and possibly in multiple documents and/or repos, so I'm starting with an issue.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-01-31-vcwg#section2-2) on 2024-01-31

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.2. `Type-Specific Credential Processing` is better phrasing than `Credential Type-Specific Processing` (issue vc-data-model#1415)

_See github issue [vc-data-model#1415](https://github.com/w3c/vc-data-model/issues/1415)._




**Brent Zundel:** We're looking primarily for triage.  
… This one is about credential-type specific processing vs. type-specific credential processing.  
… That sounds better to me.  

**Manu Sporny:** I agree.  

**Ted Thibodeau Jr.:** I can also take this one.  

**Brent Zundel:** I will assign Manu and Ted, and whoever gets there first wins.  
… Labeling that one CR-2.  

</details>
