### ISSUE TITLE
EnvelopedVerifiablePresentation missing in data model

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-model#1431]
prevents consistent RDF interpretation of presentations secured without data integrity proofs.

- https://w3c.github.io/vc-data-model/#enveloped-verifiable-credentials

```
{
   "@context": "https://www.w3.org/ns/credentials/v2",
    "id": "data:application/vp+ld+json+sd-jwt;QzVjV...RMjU",
    "type": "EnvelopedVerifiablePresentation"
}
```

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-02-14-vcwg#section2-5) on 2024-02-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.5. EnvelopedVerifiablePresentation missing in data model (issue vc-data-model#1431)

_See github issue [vc-data-model#1431](https://github.com/w3c/vc-data-model/issues/1431)._




**Brent Zundel:** next is #1431 EnvelopedVerifiablePresentation missing in data model.  

> *Gabe Cohen:* prevents consistent RDF interpretation of presentations secured without data integrity proofs.

**Manu Sporny:** today we have this concept of an enveloped verifiable credential, with a presentation inside of it. this would add a presentation. should be fine to do this. it is something that is missing. it is a normative change. saying "if you want to, you can wrap it in multiple b64 payloads" to get a blob that secures the entire data model using any media type.  

**Brent Zundel:** clarifying...the enveloped cred was 'I want to use vc-jose-cose to sign a credential' this is 'I want to use vc-jose-cose to sign a presentation'.  

**Manu Sporny:** yes correct and I can take it.  

**Ivan Herman:** I will take the vocab part.  

**Brent Zundel:** thanks to both. time for at least one more...#1408.  

</details>

**Comment by iherman** [comment]
@msporny we should not do the relevant PR (at least on the vocabulary) before closing #1436...

**Comment by msporny** [comment]
PR #1453 has been raised to address this issue. This issue will be closed once PR #1453 has been merged.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-03-06-vcwg#section2-14) on 2024-03-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.14. EnvelopedVerifiablePresentation missing in data model (issue vc-data-model#1431)

_See github issue [vc-data-model#1431](https://github.com/w3c/vc-data-model/issues/1431)._




_See github pull request [vc-data-model#1453](https://github.com/w3c/vc-data-model/pull/1453)._




**Brent Zundel:** 1431, PR1453 which has approvals and on track to be merged.  
… we're headed toward wrapping this up.  
… so expect to be bothered by us to get the work done...probably weekly.  

</details>

**Comment by msporny** [comment]
PR #1453 has been merged, closing.
