### ISSUE TITLE
first example contains an http url identifying a credential

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-model#1432]
https://w3c.github.io/vc-data-model/#example-a-simple-example-of-the-contents-of-a-verifiable-credential

```json
{
  
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
    "https://www.w3.org/ns/credentials/examples/v2"
  ],
  
  "id": "http://university.example/credentials/1872", // bad idea to recommend this
  
  "type": ["VerifiableCredential", "ExampleAlumniCredential"],
  
  "issuer": "https://university.example/issuers/565049",
  
  "validFrom": "2010-01-01T19:23:24Z",
  
  "credentialSubject": {
    
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    
    "alumniOf": {
      
      "id": "did:example:c276e12ec21ebfeb1f712ebc6f1",
      
      "name": "Example University"
    }
  }
}
```

**Comment by decentralgabe** [comment]
Other examples reference URNs (e.g. `urn:uuid:<uuid-value>` perhaps the first should do this too. 

But, is it worth adding language to the identifiers section on the risk of a publicly resolvable credential URI?

**Comment by decentralgabe** [comment]
Will add language on when you might want to use an ID that's public, and other cases may want to not be public. Use cases for both. There may already be privacy considerations for this.

Will also add examples with URNs.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-03-13-vcwg#section4-2) on 2024-03-13

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.2. first example contains an http url identifying a credential (issue vc-data-model#1432)

_See github issue [vc-data-model#1432](https://github.com/w3c/vc-data-model/issues/1432)._




**Brent Zundel:** Gabe agreed to do a PR, he's not here... I'm marking pending close. Will reach out to Gabe.  

</details>

**Comment by decentralgabe** [comment]
pr opened #1466
