### ISSUE TITLE
Remove at risk issue markers for property extension points.

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1437]
The WG discussed the process for removing "AT RISK" issue markers for properties and property sections during the call today. The following was the agreed-upon process (see transcript below). In order for an "AT RISK" marker to be removed, and the property to remain in the specification, the section MUST:

1. Update the example to use an extension specification that has been implemented, and values that utilize the extension point.
2. Have the `type` field specified, using a type specified by the extension specification.
3. A test in the VCDM v2.0 test suite that tests the example by issuing a VC that contains the example.
4. Result in at least two implementations issuing a conforming VC that contains the example.

The following property extension points are currently at risk:

* confidenceMethod
* evidence
* refreshService
* renderMethod
* termsOfUse

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-02-14-vcwg#section2-1) on 2024-02-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.1. Remove the at risk issue marker for `Evidence` (issue vc-data-model#1303)

_See github issue [vc-data-model#1303](https://github.com/w3c/vc-data-model/issues/1303)._




**Michael Jones:** looking at 1303 first Remove the at risk issue marker for Evidence.  

> *Manu Sporny:* See [section in the spec](https://w3c.github.io/vc-specs-dir/#evidence).

**Manu Sporny:** question for the group: Jefferey Yaskin asked for a mini-registry and to be done with this. we could do that. w.r.t tests what did we say we would do? I have two recollections.  
… have to demonstrate there is a spec using the property. there are multiple impls. 1EdTech have an evidence property. thought the tests we were writing were just testing the 'type' for evidence. need to ask what are we testing for these extension points.  
… normative guidance we give is : it can't be empty, have to specify it's type, id should be a URL, ... 1EdTech has multiple impls. at what point do we remove the at risk marker? when we create tests?  
… is that the bar we're trying to hit?  

**Ivan Herman:** from a practical point of view, the only obligation we have is to remove these markers and feature itself when we go to PR. at this point there is no rush. at some point we'll have to look at the whole test suite report and then risk markers.  
… issue was raised before CR. why bother at this point? went to CR with marker in.  

**Brent Zundel:** less a post-CR and then a pre-PR?  

**Ivan Herman:** yes.  

> *Manu Sporny:* [https://github.com/w3c/vc-data-model/pull/1295#pullrequestreview-1657956871](https://github.com/w3c/vc-data-model/pull/1295#pullrequestreview-1657956871).

**Manu Sporny:** agree, but still need clarity. Orie said the example needs to be updated and covered in tests. what does 'covered' mean? ... having input/output that looks like the example. then we can remove the at risk flag. concretely we update the example to use the IMS Global evidence property.  
… there will be a test for that in the core data model. to make sure there's a type and to make sure nobody throws an error (or at least 2 don't.) and then at if at the end of CR two impls are doing this, we remove the issue marker.  

> *Gabe Cohen:* +1 to that proposal.

**Manu Sporny:** does anyone disagree with that proposal?  

> *Manu Sporny:* +1 for it being for how we evaluate /all/ properties.

> *Manu Sporny:* (all "at risk" properties).

**Ivan Herman:** fine with that. need to be clear this is not for the evidence property only. what's being described is 'how do we accept that a given property/term stays in the spec as a normative thing' need a general approach to do that.  

**Brent Zundel:** labeled as before-PR. manu has outlined a clear course of action. no one assigned yet.  

**Ivan Herman:** Manu has outlined ... but needs to be documented somewhere.  
… will there be some document that says this is the way we remove the markers?  

**Brent Zundel:** do you have a proposal?  

**Ivan Herman:** at the end of the CR process we need a report. to say whether we are fine or not. criteria may differ, this is not in the same category as other issues. my proposal is to have a document and record this in it.  

**Manu Sporny:** I have raised an issue to track this (#1437), will add details. to remove at risk issue markers & properties. will be a before-PR thing. will document the process and track at risk properties.  

_See github issue [vc-data-model#1437](https://github.com/w3c/vc-data-model/issues/1437)._




**Brent Zundel:** can anyone take the issue?  

**Manu Sporny:** yes, I will.  

</details>

**Comment by msporny** [comment]
PRs #1495, #1496, #1497, and #1498 have been merged to address this issue. This issue will be closed once those PRs have been merged.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-12-vcwg#section3-4) on 2024-06-12

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.4. Remove at risk issue markers for property extension points. (issue vc-data-model#1437)

_See github issue [vc-data-model#1437](https://github.com/w3c/vc-data-model/issues/1437)._




**Brent Zundel:** next - 1437 - remove at risk issue markers for property extension points. related to the TOU conversation we just had. all extension points we have clarification. those PRs are either merged or ready to merge. we have a path for termsOfUse--we will axe the VP part, open the doors for hearing about impls for VCs.  
… question to the group - who will reach out to folks from EBSI?  

**David Chadwick:** I can try to do that. Is there someone in the group better placed to do this? The PR that is there will need editing, who will do that? We can do that now and merge it, or we can wait and hear back from EBSI.  

**Brent Zundel:** manu has been assigned to address this, will leave it to him whether or not to raise a 2nd PR for termsOfUse in VPs or see if we can get EBSI folks here.  
… not hearing anyone say they work closely with EBSI, at this point DavidC you are best positioned to do this. Would be appreciated.  

**David Chadwick:** ack will do this.  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-07-03-vcwg#section1-1) on 2024-07-03

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.1. Remove at risk issue markers for property extension points. (issue vc-data-model#1437)

_See github issue [vc-data-model#1437](https://github.com/w3c/vc-data-model/issues/1437)._




**Brent Zundel:** we have 10 open issues. many are addressed. #1437 - Remove at risk issue markers for property extension points.  

**Manu Sporny:** We are waiting for the charter to up for AC vote for the PRs to go in. Waiting to hear from EBSI so that we can see their usage and cite it in the spec.  

</details>

**Comment by msporny** [comment]
PRs #1495, #1496, #1497, and #1533 have been removed. All at risk issue markers for property extension points have been removed, closing.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-07-17-vcwg#section1-1) on 2024-07-17

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.1. Remove at risk issue markers for property extension points. (issue vc-data-model#1437)

_See github issue [vc-data-model#1437](https://github.com/w3c/vc-data-model/issues/1437)._




**Manu Sporny:** to speak to some of these, don't need to go into depth, 1437 remove at risk issue markers: waiting on EBSI to give us concrete examples.  

</details>
