### ISSUE TITLE
consider merging 3.4 and 5.1 as both sections are about the credential lifecycle.

### ISSUE THREAD

**Issue by brentzundel** [w3c/vc-data-model#1465]
Both sections 3.4 and 5.1 are details of the credential lifecycle.
I propose merging content from 3.4 into 5.1 so that the spec only has one lifecycle section, also removing the concrete example and instead pointing to the Use Cases note.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-04-10-vcwg#section2-5) on 2024-04-10

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.5. consider merging 3.4 and 5.1 as both sections are about the credential lifecycle. (issue vc-data-model#1465)

_See github issue [vc-data-model#1465](https://github.com/w3c/vc-data-model/issues/1465)._




**Manu Sporny:** in the respec vc library, would allow you to choose on an example-by-example basis which securing mechanisms you'd want to show.  

**Brent Zundel:** thanks.  
… I raised this. I was reading through spec, and noted that two different sections both talk about the credential lifecycle.  
… so the split is not great.  
… let's merge them into one section. take 3.4, put it inside of 5.1.  
… also remove the concrete example, say - "we have use cases, they're over there", like we've done in the path.  
… would love to hear feedback.  

**Manu Sporny:** strong +1 to that. I'm wondering if we should go a step further, and merge that section into the Use Cases document.  

**Brent Zundel:** proposal on the table is, in as minimal fashion as possible, merge those two sections, and reference the Use Cases doc, like Joe said.  

> *Manu Sporny:* +1.

**Joe Andrieu:** sounds right.  

**Brent Zundel:** ok, I'll do that.  
… Joe, does the Use Cases doc have this lifecycle stuff?  

**Joe Andrieu:** I think it's there, but we'll check.  

</details>
