### ISSUE TITLE
`credential repository` vs `repository`, and definitions in _1.2  Ecosystem Overview_ vs _2. Terminology_

### ISSUE THREAD

**Issue by TallTed** [w3c/vc-data-model#1475]
_Originally posted by @TallTed in https://github.com/w3c/vc-data-model/issues/1467#issuecomment-2048172492_

We define `repository` but not `credential repository`. Bare `repository` is used 3 times in the text; `credential repository` is used 4 times. I think all occurrences of the bare `repository` should be changed to `credential repository`.

While investigating the above, I discovered that we have two competing definitions for `holder` (and several other things) — in [1.2 Ecosystem Overview](https://w3c.github.io/vc-data-model/#ecosystem-overview) (which I think should either point to the other section, or exactly duplicate the other definition) and [2. Terminology](https://w3c.github.io/vc-data-model/#terminology) (which I think is meant to be authoritative).

Then, the definition of repository — "A program, such as a storage vault or personal [verifiable credential](https://w3c.github.io/vc-data-model/#dfn-verifiable-credential) wallet, that stores and protects access to [holders'](https://w3c.github.io/vc-data-model/#dfn-holders) [verifiable credentials](https://w3c.github.io/vc-data-model/#dfn-verifiable-credential)." Can I not store a VC in a simple filesystem directory, that is on my personal storage device? I thought I could...

**Comment by msporny** [comment]
@TallTed wrote:
> I think all occurrences of the bare repository should be changed to credential repository.

Agreed.

> Can I not store a VC in a simple filesystem directory, that is on my personal storage device? I thought I could...

You can. I think we were presuming some functionality would have to exist for that thing (like digital signature capability), which is why we picked "program" before. Perhaps we should replace "A program" to "A location" and include "file system", "database", and/or "website" as a place that could be a credential repository?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-05-01-vcwg#section3-2) on 2024-05-01

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.2. `credential repository` vs `repository`, and definitions in _1.2  Ecosystem Overview_ vs _2. Terminology_ (issue vc-data-model#1475)

_See github issue [vc-data-model#1475](https://github.com/w3c/vc-data-model/issues/1475)._




**Brent Zundel:** Ted, could you jump on the queue and walk us through this -- and to the group, who would be willing to be assigned to make it happen?  

**Ted Thibodeau Jr.:** One item here is a quick search and replace PR, another is rephrasing a sentence, the third is rationalizing some competing definition of things. Ecosystem and terminology do the same thing partly -- but with different definitions.  
… That one I hadn't resolved at all. That's not in the comment from Manu either.  

**Brent Zundel:** Is this something you could begin to address in a PR?  

**Ted Thibodeau Jr.:** I don't think it needs discussion, just heads down.  

**Brent Zundel:** Can I assign you?  

**Ted Thibodeau Jr.:** Sure.  

</details>

**Comment by TallTed** [comment]
> While investigating the above, I discovered that we have two competing definitions for holder (and several other things) — in [1.2 Ecosystem Overview](https://w3c.github.io/vc-data-model/#ecosystem-overview) (which I think should either point to the other section, or exactly duplicate the other definition) and [2. Terminology](https://w3c.github.io/vc-data-model/#terminology) (which I think is meant to be authoritative).

I'm sure the definitions in [1.2 Ecosystem Overview](https://w3c.github.io/vc-data-model/#ecosystem-overview) and [2. Terminology](https://w3c.github.io/vc-data-model/#terminology) should first be synchronized. I will address that, once I know how to handle what's below.

Then, should [1.2 Ecosystem Overview](https://w3c.github.io/vc-data-model/#ecosystem-overview) continue to hold the full wording of these definitions (which must be thenceforth kept in sync with [2. Terminology](https://w3c.github.io/vc-data-model/#terminology)), or should there be some link from the terms used in [1.2 Ecosystem Overview](https://w3c.github.io/vc-data-model/#ecosystem-overview) to their definitions in [2. Terminology](https://w3c.github.io/vc-data-model/#terminology)? Assuming the latter, what markup should be used in [1.2 Ecosystem Overview](https://w3c.github.io/vc-data-model/#ecosystem-overview)? (Hoping @msporny has a quick and easy answer, here.)

**Comment by msporny** [comment]
> Assuming the latter, what markup should be used in 1.2 Ecosystem Overview? (Hoping @msporny has a quick and easy answer, here.)

Use the `<dfn>term</dfn> syntax in Terminology and the`[= term =]` syntax when using the term in Ecosystem Overview. Did that answer your question, @TallTed?

**Comment by msporny** [comment]
> We define `repository` but not `credential repository`. Bare `repository` is used 3 times in the text; `credential repository` is used 4 times. I think all occurrences of the bare `repository` should be changed to `credential repository`.

Fixed in 29f431d5387d81e385144ad46d2fb103a25f8d76.

> Then, the definition of repository — "A program, such as a storage vault or personal [verifiable credential](https://w3c.github.io/vc-data-model/#dfn-verifiable-credential) wallet, that stores and protects access to [holders'](https://w3c.github.io/vc-data-model/#dfn-holders) [verifiable credentials](https://w3c.github.io/vc-data-model/#dfn-verifiable-credential)." Can I not store a VC in a simple filesystem directory, that is on my personal storage device? I thought I could...

Fixed in 27d2761258861326ecdd146da7e85e9d07714eb8.

> While investigating the above, I discovered that we have two competing definitions for `holder` (and several other things) — in [1.2 Ecosystem Overview](https://w3c.github.io/vc-data-model/#ecosystem-overview) (which I think should either point to the other section, or exactly duplicate the other definition) and [2. Terminology](https://w3c.github.io/vc-data-model/#terminology) (which I think is meant to be authoritative).

Fixed in 9ecd2c112455ccb3bdd02038e8a326635e133ded.

**Comment by msporny** [comment]
The first fix was done in a reviewed PR. The other two fixes were purely editorial, literally just adding uncontroversial text or moving existing text around, I just committed them to `main`.

This issue has been addressed, if you disagree, please re-open the issue.
