### ISSUE TITLE
VC-JWT examples are out-of-date

### ISSUE THREAD

**Issue by vincentkelleher** [w3c/vc-data-model#1485]
Hi again 👋 

While reading the [Verifiable Credentials Data Model v2.0 specification](https://w3c.github.io/vc-data-model/) and the [Securing Verifiable Credentials using JOSE and COSE specification](https://www.w3.org/TR/vc-jose-cose/), I've noticed discrepancies about VC-JWT encoding.

If I understand well (after reading some issues, discussions and PRs) the latter specification is the new reference for VC-JWT encoding. It states the following sentence in the [JOSE Header and JWT Claims part](https://www.w3.org/TR/vc-jose-cose/#jose-header-parameters-and-jwt-claims):

> The JWT Claim Names vc and vp MUST NOT be present.

Looking at [Example 3](https://w3c.github.io/vc-data-model/#example-usage-of-the-id-property) of the VC Data Model v2.0 specification, I noticed that the `vc` claim is used.

<img width="639" alt="image" src="https://github.com/w3c/vc-data-model/assets/4272277/898dd8b6-ed44-478c-84a5-76af5483a021">

I imagine this is an outdated example ? If so, here are the parts of the specification that need to be updated:
- https://w3c.github.io/vc-data-model/#example-usage-of-the-id-property
- https://w3c.github.io/vc-data-model/#example-usage-of-the-type-property
- https://w3c.github.io/vc-data-model/#example-usage-of-the-name-and-description-property
- https://w3c.github.io/vc-data-model/#example-usage-of-the-credentialsubject-property
- https://w3c.github.io/vc-data-model/#example-usage-of-issuer-property
- https://w3c.github.io/vc-data-model/#example-usage-of-issuer-expanded-property
- https://w3c.github.io/vc-data-model/#example-usage-of-validfrom-and-validuntil-property
- https://w3c.github.io/vc-data-model/#example-a-simple-credential
- https://w3c.github.io/vc-data-model/#example-usage-of-issuer-properties

**Comment by msporny** [comment]
Yes, we need to fix this. We finally updated the version of respec-vc to use the new code base, we need to update the vc-jose-cose portions of that code base now.

**Comment by decentralgabe** [comment]
I will take an action to update respec-vc.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-05-29-vcwg#section5-3) on 2024-05-29

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.3. VC-JWT examples are out-of-date (issue vc-data-model#1485)

_See github issue [vc-data-model#1485](https://github.com/w3c/vc-data-model/issues/1485)._




**Brent Zundel:** VC JWT examples are out of date.  

**Manu Sporny:** good news is we released a new version of respec-vc.  
… but the new jose/cose stuff is not in there yet.  
… it should be a copy/paste into respec-vc.  
… or decentralgabe can send a PR there.  

**Gabe Cohen:** it's on my list.  
… and given the update to remove YAML from the jose/cose spec, it should be simpler to do now.  

**Manu Sporny:** just to make sure we're aligned, what are you planning to implement?  
… SD-JWT, JOSE, COSE, something else?  

**Gabe Cohen:** I was going to do all 3, but not automatically render them.  
… I'll put up a PR.  
… I'd prefer to start by fixing what is currently labelled VC-JWT.  

**Manu Sporny:** you can pick which tabs to show per example.  

**Brent Zundel:** with that, we are out of time.  
… great consensus building. we love our volunteers.  
… bye for now.  

---

</details>

**Comment by decentralgabe** [comment]
After https://github.com/w3c/respec-vc/pull/30 is merged this will be ready

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-12-vcwg#section3-5) on 2024-06-12

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.5. VC-JWT examples are out-of-date (issue vc-data-model#1485)

_See github issue [vc-data-model#1485](https://github.com/w3c/vc-data-model/issues/1485)._




**Brent Zundel:** Next 1485 - VC JWT examples are out of data. we have 3 folks assigned. I believe a solution is under way.  

**Ivan Herman:** Gabe has a PR in respec-vc (https://github.com/w3c/respec-vc/pull/30) which will solve this.  

**Gabe Cohen:** linked the PR that will fix this. I will update the examples after it is merged.  

</details>

**Comment by msporny** [comment]
w3c/respec-vc#30 was merged, respec-vc v3.2.0 was released, and commit 0a82f17f58898001e87fe47baba1e0b41a58018c enabled it for vc-data-model. This issue is now resolved. Closing.
