### ISSUE TITLE
Origin-bound claims are more privacy-aware

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#15]
Single-use, origin bound claims are generally safer than long-lived claims. We should mention this in the privacy considerations section.

**Comment by David-Chadwick** [comment]
I am not sure what you mean by origin bound? Can you explain please.
Also we should differentiate between short lived, (un)revocable, and single use claims. A claim can be long or short lived, one time or many time use, and revocable or not. But in practice it does not make sense to have short lived revoked certs and long lived unrevocable certs. So there are 4 types in practice rather than 6 types.

**Comment by msporny** [comment]
> I am not sure what you mean by origin bound?

We're using the W3C definition of "origin", which effectively means a domain (DNS name). So a claim that is only ever shared with one domain, and only ever shared once ("I am over 21", for instance). 

There are ways to re-share the "I am over 21" claim again, but in a way that is impossible for the site to determine if you're the same person sharing the same claim or not. Note: this requires some impressive crypto-network gymnastics to accomplish the feat.

**Comment by David-Chadwick** [comment]
A single use over-21 credential in a bar makes little sense, since you are physically present in the bar and your face does not change. So short lived (eg an evening) multiple use origin bound is much better in this case, since the issuer has much less knowledge about what you are doing.
There seems to be a conflict between privacy leakage to the issuer vs. to the inspector and single use vs. multiple use (regardless of the duration of the credential).
