### ISSUE TITLE
Comments/Suggestions on Privacy Considerations

### ISSUE THREAD

**Issue by zoracon** [w3c/vc-data-model#1502]
For 8.19 [Private Browsing](https://w3c.github.io/vc-data-model/#private-browsing)

It is my suggestion that Private browsing should not be relied on at all and implementers should be aware that all major browsers support modern mechanisms like Encrypted Client Hello and secure DNS. And they should utilize these modern data transport tools to ensure that Holder metadata and PII transferred over the wire be protected from leaks.

I don't see anything addressing law enforcement access and believe that should be addressed under Privacy.

For 8.16 [Data Theft](https://w3c.github.io/vc-data-model/#data-theft)

>Alternatives include keeping logs that the information was collected and checked, as well as random tests to ensure that compliance regimes are operating as expected. 

I would like to see a note addressing compliance regimes have guidelines on law enforcement access whose terms of access are transparent to the Holder in case of situations like a warrant is issued.

IRL Example: https://www.404media.co/hacker-accesses-internal-tile-tool-that-provides-location-data-to-cops/

For 8.9 [The Principle of Data Minimization ](https://w3c.github.io/vc-data-model/#the-principle-of-data-minimization)

>such that a [holder](https://w3c.github.io/vc-data-model/#dfn-holders) can push back on the over-collection of information that is unnecessary for the transaction.

In the case where a Holder was coerced into giving more info than desired to a Verifier, there should be a log of what items were disclosed available locally to the user (They can choose to not have this done/opt out/ etc.) for future accountability measures.

**Comment by msporny** [comment]
Thank you for those suggestions @zoracon. I will take an action to write up a PR to address each concern you raised above with some spec text for you to review.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-19-vcwg#section2-6) on 2024-06-19

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.6. Comments/Suggestions on Privacy Considerations (issue vc-data-model#1502)

_See github issue [vc-data-model#1502](https://github.com/w3c/vc-data-model/issues/1502)._




**Manu Sporny:** 1502 is important because of submission from Electronic Frontier Foundation.  
… Happy to raise a PR to address the issue.  
… Shouldn't only depend on private browsing mode, also want things to ensure that compliance regimes have guidelines about law enforcement access and that they are transparent to the holder.  
… Also want logs that wallets would keep so that holder could see what was shared.  
… No objections from group to Manu taking on PR.  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-19-vcwg#section2-4) on 2024-06-19

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.4. Comments/Suggestions on Privacy Considerations (issue vc-data-model#1502)

_See github issue [vc-data-model#1502](https://github.com/w3c/vc-data-model/issues/1502)._




**Brent Zundel:** Next is 1502, comments/suggestions on privacy considerations.  
… Manu has assigned himself to raise a PR.  
… May have lost Manu, not on Zoom anymore. Just editorial changes.  

</details>

**Comment by msporny** [comment]
PR #1504 has been raised to address this issue. @zoracon, it would be good to get your feedback on that PR in the next 7 days, which is our typical merge window. This issue will be closed once PR #1504 has been merged.

**Comment by mccown** [comment]
Great suggestions.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-26-vcwg#section2-3) on 2024-06-26

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.3. Comments/Suggestions on Privacy Considerations (issue vc-data-model#1502)

_See github issue [vc-data-model#1502](https://github.com/w3c/vc-data-model/issues/1502)._




**Manu Sporny:** these are comments from EFF.  
… EFF has reviewed the PR and says it addresses their concerns.  
… only other thing is edit from TallTed.  

</details>

**Comment by msporny** [comment]
PR #1504 has been merged, closing.
