### ISSUE TITLE
SD-JWT fields in the v2 context should use `"@type": "@json"`

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-data-model#1503]
For example, see: https://github.com/w3c/vc-data-model/blob/main/contexts/credentials/v2#L59-L67

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-19-vcwg#section2-5) on 2024-06-19

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.5. SD-JWT fields in the v2 context should use `"@type": "@json"` (issue vc-data-model#1503)

_See github issue [vc-data-model#1503](https://github.com/w3c/vc-data-model/issues/1503)._




**Brent Zundel:** Next is 1503. Issues like this are a good sign. Means people are finding little nits like this.  
… Dave Longley is not on the call. There need to be a couple of modifications to the context because of this issue.  
… Manu assigned 1502 and 1503.  

</details>

**Comment by msporny** [comment]
PR #1505 has been raised to address this issue. This issue will be closed once PR #1505 has been merged.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-26-vcwg#section2-4) on 2024-06-26

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.4. SD-JWT fields in the v2 context should use `"@type": "@json"` (issue vc-data-model#1503)

_See github issue [vc-data-model#1503](https://github.com/w3c/vc-data-model/issues/1503)._




**Brent Zundel:** if I remember correctly this issue should be addressed.  
… PR#1505 addresses this.  

_See github pull request [vc-data-model#1505](https://github.com/w3c/vc-data-model/pull/1505)._




</details>

**Comment by msporny** [comment]
PR #1505 has been merged, closing.
