### ISSUE TITLE
consider registering `application/vc-ld` and `application/vp-ld` 

### ISSUE THREAD

**Issue by bc-pi** [w3c/vc-data-model#1509]
As discussed in https://github.com/w3c/vc-jose-cose/pull/279#issuecomment-2183197001, https://github.com/w3c/vc-jose-cose/pull/279#issuecomment-2183160606, [etc.](https://github.com/w3c/vc-jose-cose/pull/279), please consider updating the [recently updated media types](https://github.com/w3c/vc-data-model/pull/1478) from `application/vc` to `application/vc-ld` and `application/vp` to `application/vp-ld` respectively.

**Comment by selfissued** [comment]
I agree that this is the right path forward, as it will enable consistent and intuitive media type naming.

**Comment by dlongley** [comment]
-1, I disagree that this will result in intuitive media type naming, rather I expect it to create more confusion overall in the market.

VCs are already a thing, were invented here at W3C, and another group using the VC terminology for something that is not a W3C VC is a source of confusion that we should not feed by further confusing the branding.

We do not control other groups that may choose to repurpose the VC branding for their own benefit. I understand that another group plans on registering `application/vc-sd+jwt` for a data format that does not represent W3C VCs, against the advice of members of the VCWG. This is the actual source of confusion and the fundamental problem. I think it is that group that should rethink their approach. That it sounds like some have decided to deploy some software using that unregistered media type is unfortunate, but is a problem that they should try to address instead of pushing this group to acquiesce to their rebranding efforts.

If that group does not relent and attempts registration of `application/vc-sd+jwt` anyway, we should not react by increasing further confusion on VC branding here by inventing yet another thing. We should consider other alternatives to `application/vc-sd+jwt` for the vc-jose-cose work's media type in that case, not change `application/vc` nor `application/vp`.

**Comment by jandrieu** [comment]
I'm sorry, my recollection is that in Miami we agreed that we would have a single base media type which became ```application/vc``` and ```application/vp```.

-1 to revisiting the conversation. This PR does not reflect prior or emerging consensus.

**Comment by decentralgabe** [comment]
Given the collisions on terms like `vc` and `vp` I see the angle to make it clear that this is an `ld` model. However, what @jandrieu states is correct -- the base media types imply that LD is used.

This seems to be about _reducing_ confusion but also (potentially) squatting in a 'who registers the vc term first' sense.

I can see it going either way, but in general I favor reducing confusion, which is why I am +1 to @bc-pi 's suggestion. It's valuable feedback that the plain `vc` and `vp` types introduce room for confusion as they are.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-26-vcwg#section1-1) on 2024-06-26

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.1. update updated media types to `application/vc-ld` and `application/vp-ld`  (issue vc-data-model#1509)

_See github issue [vc-data-model#1509](https://github.com/w3c/vc-data-model/issues/1509)._




**Brent Zundel:** have had lots of discussions already about this.  
… . decided we would just register vc and vp.  
… but some folks want ld adding as well.  

> *Dave Longley:* -1 to change the core media types again, please move forward with `application/vc` and `application/vp`.

> *Joe Andrieu:* I'm also -1 to revisiting this conversation.

> *KevinDean:* -1.

**Manu Sporny:** strong -1 for revisiting this topic again.  
… people who want to use sd-jwt as well actually have nothing to do with our VC DM.  
… it duplicates the typing mechanism but is incompatible with VCDM.  
… we should contact Oauth group at IETF and ask them to stop creating specs that will confuse people with our W3C VCDM spec.  

> *Dave Longley:* +1 to everything Manu said.

> *Ted Thibodeau Jr.:* +1 msporny.

**Gabe Cohen:** I am concerned about us being blocked from registering our media types.  

**Brent Zundel:** of the two media types we want to register (application vc and vp) should not be a problem.  
… it is the addition of sd-jwt that may cause problems.  

> *Dave Longley:* +1 to brent, yes.

**Brent Zundel:** we should register our base two types first.  

**Manu Sporny:** we need to move on, so lets not discuss further unless our initial registrations are blocked.  
… its not clear to me how many sd-jwt data types there are, and they all seem to be incompatible with one another.  

> *Gabe Cohen:* +1 to Brent's suggestion to register the base types first.

> *Steve McCown:* +1 for proceeding with the 1st 2 base types. It doesn't sound like doing that and discussing the others later hinders anything.

**Ted Thibodeau Jr.:** we should not pre-determine that our registrations will be blocked.  
… lets wait to see the outcome.  
… I see a lot of sloppiness in what media types are being discussed, with the + and - signs flipped or otherwise incorrectly used.  

**Anil John:** feedback on ARF may suggest changes to media types are needed.  

**Manu Sporny:** I will volunteer to submit the registration request for the two data types in our VC DM.  
… application/vc and application/vp.  

> *Dave Longley:* +1 to that plan.

> *Gabe Cohen:* +1 thanks Manu.

> *Joe Andrieu:* +1 to that plan.

</details>

**Comment by selfissued** [comment]
The attempted registrations of `application/vc` and `application/vp` were just rejected with the comment "This subtype name is way too short. Spell it out."

I replied asking if the names `application/vc-lc` and `application/vp-ld` would be acceptable.  Cross your fingers...

**Comment by msporny** [comment]
> The attempted registrations of application/vc and application/vp were just rejected with the comment "This subtype name is way too short. Spell it out."

@selfissued, stop misrepresenting what is being said on the media type mailing list.

If others want to follow along in the discussion, it is here:

https://mailarchive.ietf.org/arch/msg/media-types/7OSKJbpbiQECyz6zGRXMyuNT-TM/

**Comment by selfissued** [comment]
You know, this is the only working group I participate in in which personal attacks like this are common.  We all know that it's not helpful and undermines both the cohesion of the working group and the morale of the participants.   People shouldn't try to put me on the defensive for communicating pertinent facts to involved parties.  This MUST stop.  Please issue a public apology, @msporny.

Furthermore, this is a case of the pot calling the kettle black.  In particular, to try to be helpful, I'd written to the media-types group that "The other names being considered by the working group are application/vc-lc and application/vp-ld.  Would those be acceptable?".  Indeed, it's being considered in this very issue, which is open and has received some support (and yes, some opposition).  And yet you wrote to the MediaMan group "No, the group is not considering application/vc-lc or the -ld suffixes."  Your statement is outright false, as this issue being open and active demonstrates.  @brentzundel could authoritatively say that in his role as chair, but you cannot.  Please stop misrepresenting what's happening in the working group to others and presuming to speak for the working group.

**Comment by msporny** [comment]
> You know, this is the only working group I participate in in which personal attacks like this are common.

It wasn't a personal attack, it was an assertion of a number of facts:

1. The VCWG [made a decision](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-26-vcwg#section1-1) to register `application/vc` and `application/vp`. Those are the only media types that the WG has approved for presentation to IANA and the Designated Experts at the IETF at this time.
2. The ["make it shorter" comment](https://mailarchive.ietf.org/arch/msg/media-types/Xkuv4UGcKQbQuzxX-WQeqtu1hWI/) was from someone that is NOT one of the designated experts for media type registrations and thus could not make a determination. The Designated Experts are: [Alexey Melnikov, Darrel Miller, Murray Kucherawy](https://www.iana.org/assignments/media-types/media-types.xhtml)
3. You then reported to this group that the media type had been rejected, which was a misrepresentation.
4. You then offered `application/vc-lc` as a media type, which the group has never discussed nor approved, which was another misrepresentation. You also offered `application/vp-ld` as a media type, which the group discussed and rejected (one of the reasons being that "Linked Data" has multiple different serializations).
5. One of the designated experts has chimed in and said that there is [no such requirement on length](https://mailarchive.ietf.org/arch/msg/media-types/OXvudT2DAoIg5edXI-eG1wGW0Ts/). The subtype ABNF has no minimum length requirement.

**Comment by brentzundel** [comment]
@msporny @selfissued I will be reaching out to both of you as chair to schedule a meeting where your points of view can be discussed. In the meantime, please leave discussion in this issue to others.

**Comment by jandrieu** [comment]
@selfissued I concur with @msporny here that in multiple cases you have substantially misrepresented the facts.

I'd like to remind you that the W3C Code of Conduct explicitly requires that you avoid misstatements of fact:
> Be honest. Be truthful, sincere, forthright and, unless professional duties require confidentiality or special discretion, candid, straightforward, and frank.

And, in the section on Unacceptable Behavior:
> Deliberate misinformation.

It does appear that the misrepresentation of the response from the registration request was specifically designed to misinform the working group in advancement of your position.

Whether we restrict our attention to your representations here (1) or at the media type mailing list (2), your statements constitute a fairly straightforward violation of the Code of Conduct.

1) That the registration has just been rejected. 

This is demonstrably false.

2) That the VC WG is considering application/vc-ld and application/vp-ld. 

IMO, the group is not. You might be. Other members of the group might be. But you are not authorized to speak on behalf of the group and unless you can demonstrate the evidence for the Working Group having accepted that option it's inappropriate to represent it as the "under consideration".  In contrast, it appears that you were simply acting on your own cognizance and misrepresenting your opinion as that of the group.

The group had a clear resolution on exactly this issue (what media types to register) and gave clear direction as to what was to be filed with IANA and you stepped beyond your remit because you didn't like the group's decision. 

Just because you create an issue in a WG repo does not, IMO, constitute "consideration by the group" especially when representing the group's intention to other organizations like the IETF. It simply makes no sense that anyone could raise an issue and immediately claim that that issue represents "consideration by the WG."

We can argue over (2); its a debatable point as to whether or not consideration by one or a few members of a group constitute consideration by the group. However (1) seems to be an exceptionally straightforward misrepresentation designed specifically to advance your particular agenda.

Further, I want to rebut your accusation that this is a personal attack. You, @selfissued, were not attacked. Rather, your actions--which I find to be a violation of the CEPC--were called out in a civil and professional manner. @msporny requested you to "Stop continuing to misrepresent what is being said on the media type mailing list." While this may not be the most polite way to make that request, it is not a personal attack. No aspersions or accusations were made about your character or your personal capability. Your violations of the CEPC were called out--in your misrepresentation of fact--as is appropriate and indeed called for by the CEPC itself.

I will repeat @msporny's request: Please stop misrepresenting what is being said on the media type mailing list.

Further, as a clear violation of the CEPC, I would like you to withdraw or correct your comment.

**Comment by brentzundel** [comment]
The topic of this thread is whether or not the VCWG should consider registering `application/vc-ld` and `application/vp-ld`

If comments here cannot keep themselves to that topic I will be forced to lock the thread.
This is not the proper venue for the conversation that has emerged.

**Comment by msporny** [comment]
> If comments here cannot keep themselves to that topic I will be forced to lock the thread.

Apologies, @brentzundel, I want to get an apology out to @selfissued before the thread is locked.

> @msporny requested you to "Stop continuing to misrepresent what is being said on the media type mailing list." While this may not be the most polite way to make that request, it is not a personal attack. 
>
> @msporny @selfissued I will be reaching out to both of you as chair to schedule a meeting where your points of view can be discussed. 

Alright, I've clearly overstepped, I can see that now.

@selfissued I apologize for the words I used to convey my frustration; I fired the comment off in between meetings and did not put the thought and care into it that I should have. One reading of those words is that I insinuated that you were acting in bad faith and attempting to undermine the work that this group is doing. In the future, I will presume good faith, write my responses as if I am presuming good faith, and try to convey the correction in a more polite manner.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-07-03-vcwg#section1-4) on 2024-07-03

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.4. update updated media types to `application/vc-ld` and `application/vp-ld`  (issue vc-data-model#1509)

_See github issue [vc-data-model#1509](https://github.com/w3c/vc-data-model/issues/1509)._




**Brent Zundel:** updated media types - 1509. don't want a big discussion. we are trying to register application/vc and /vp - we are still on that path. if it gets accepted we're done. if not, we will revisit and talk about other options. at this stage I do not think it is a fruitful topic to have a conversation about.  

</details>

**Comment by msporny** [comment]
The media types for `application/vc` and `application/vp` have been approved by the Designated Experts and IANA and are now included in the media types registry:

https://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by msporny** [comment]
This issue is now addressed in the sense that the base media types for VCs and VPs are now registered with IANA. I'm marking this with a pending close label; the issue will be closed in 7 days.

**Comment by TallTed** [comment]
@brentzundel -- Please consider retitling (as Chair) this issue to reflect [your comment](https://github.com/w3c/vc-data-model/issues/1509#issuecomment-2197361793), i.e., ``` consider whether to register media types `application/vc-ld` and `application/vp-ld` ```.

As it stands, the title suggests the conclusion of such consideration was already reached, which is inaccurate and seems likely to have contributed to the vehemence of the discussion above.

**Comment by selfissued** [comment]
We should apply this change to make the media types specific to JSON-LD, which they already are in vc-jose-cose.

**Comment by brentzundel** [comment]
The WG had a number of long discussions about this in PR #1478 and during calls. 
The path that found consensus: Try to register `application/vc+ld+json` and `application/vp+ld+json`, and if that fails, register `application/vc` and `application/vp`.

That's what we did:
Our attempt to register `application/vc+ld+json` and `application/vp+ld+json` failed.
PR #1478 was approved and merged. 
`application/vc` and `application/vp` were then successfully registered for the VCDM.

There has been no indication of any consensus to change the registration to `application/vc-ld` and `application/vp-ld`.

**Comment by brentzundel** [comment]
Closing, per https://github.com/w3c/vc-data-model/issues/1509#issuecomment-2221558964
