### ISSUE TITLE
Pin down the input type of verification algorithms

### ISSUE THREAD

**Issue by jyasskin** [w3c/vc-data-model#1517]
https://w3c.github.io/vc-data-model/#securing-mechanism-specifications says

> A securing mechanism's verification algorithm MUST provide an interface that receives inputs of a media type ([string](https://infra.spec.whatwg.org/#string) inputMediaType) paired with either a sequence of bytes ([byte sequence](https://infra.spec.whatwg.org/#byte-sequence) inputBytes) or a document ([map](https://infra.spec.whatwg.org/#ordered-map) inputDocument)

Does this require that the securing mechanisms accept whichever of byte-sequence or map their caller wants to provide, or does it require the caller to send whichever the securing mechanism prefers? If the latter, how does the caller figure out which one the mechanism prefers, since that's not included in the [associated registry](https://w3c.github.io/vc-specs-dir/#securing-mechanisms)?

**Comment by msporny** [comment]
It's the latter, and the presumption here is that human readable documentation for the cryptosuite library clearly defines what input types it supports. I could add a comment to that effect (and try to figure out how to align the input options so they're used in the algorithms), but at this point, I'm questioning if we should just say that it's up to the library author to pick one or both and understanding what the library supports is implementation specific.

**Comment by jyasskin** [comment]
If you handle #1518 by parsing to an Infra map early, then I think it's easiest to have the securing specs take that map. Otherwise, you could have the call sites in this spec include something like "if the securing mechanism expects bytes, pass _theBytes_, otherwise pass the result of [=parsing JSON bytes to an Infra value=] given _theBytes_".

**Comment by msporny** [comment]
> If you handle #1518 by parsing to an Infra map early, then I think it's easiest to have the securing specs take that map.

I don't think we can do this since we have some securing mechanisms (JOSE and COSE) that take opaque bytes, which are not JSON bytes, as input.

> Otherwise, you could have the call sites in this spec include something like "if the securing mechanism expects bytes, pass theBytes, otherwise pass the result of [=parsing JSON bytes to an Infra value=] given theBytes".

Yes, good, this is what I was hoping to do. Thank you for reaffirming that doing so will work for you. PR incoming.

**Comment by msporny** [comment]
PR #1522 has been raised to address this issue. This issue will be closed once PR #1522 has been merged.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-07-17-vcwg#section3-4) on 2024-07-17

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.4. Pin down the input type of verification algorithms (issue vc-data-model#1517)

_See github issue [vc-data-model#1517](https://github.com/w3c/vc-data-model/issues/1517)._




**Brent Zundel:** Part of our edits over the last year were to refine the algorithm for verification. This is further iteration on that.  
… PR 1522 is response to the issue.  

**Manu Sporny:** it's really just editorial.  
… I just need to figure out how to do what he wants us to do.  

**Brent Zundel:** where's the PR that puts it somewhere else?  

**Manu Sporny:** 1523. We merged that.  
… I need to check with Jeffrey about closing.  
… he raised two issues, but maybe we addressed it with 1523.  

</details>

**Comment by msporny** [comment]
PR #1522 has been merged, closing.
