### ISSUE TITLE
Publish undefined-terms context URI

### ISSUE THREAD

**Issue by PatStLouis** [w3c/vc-data-model#1534]
With #1520 and #1525 merged, we need to ensure `https://www.w3.org/ns/credentials/undefined-terms/v2` is publicly accessible as this was part of the requirements. @iherman 👀

**Comment by msporny** [comment]
We should also update the description of the vocabulary there as well as I think it still talks about "issuer defined" terms.

**Comment by iherman** [comment]
#1536 has been raised to handle that. If and when that PR is merged, this issue can be closed.

**Comment by OR13** [comment]
Sounds like perhaps this page may also need to be updated: 

- https://www.w3.org/ns/credentials/issuer-dependent

Or taken down / made 404.

**Comment by iherman** [comment]
@OR13 if and when #1536 is merged, the relevant .htaccess file will also be updated on the W3C site. At that point, issuer-dependent will become a 404

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-07-17-vcwg#section1-3) on 2024-07-17

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.3. Publish undefined-terms context URI (issue vc-data-model#1534)

_See github issue [vc-data-model#1534](https://github.com/w3c/vc-data-model/issues/1534)._




_See github pull request [vc-data-model#1536](https://github.com/w3c/vc-data-model/pull/1536)._




**Manu Sporny:** for next item Ivan has raised a PR, once those three are done, no more issues on VCDM.  
… only thing waiting on then is for test suites to demonstrate multiple independent implementations for every feature in specification.  

</details>

**Comment by msporny** [comment]
PR #1536 has merged, closing.
