### ISSUE TITLE
Add reference to DID Core

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#1552]
Should DID Core be added to the Normative References?

**Comment by msporny** [comment]
The Verifiable Credentials Data Model does not have any normative dependencies on DID Core.

That said, I was surprised to see that we don't even have an informative reference on DID Core (which we should, because we use DIDs in a number of examples in the specification). I'll raise a PR to do that.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-08-21-vcwg#section4-1) on 2024-08-21

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.1. Add reference to DID Core (issue vc-data-model#1552)

_See github issue [vc-data-model#1552](https://github.com/w3c/vc-data-model/issues/1552)._




**Gabe Cohen:** Looking at the issues... 1552, add reference to DID core.  

**Manu Sporny:** I just noted that we do not depend normatively on DID Core in the VC Data Model so we should not add it as a normative reference. At some point during the editorial process we removed all references. We should add an informal reference. I can raise a PR to do so.  

> *Phillip Long:* +1 to raise that informative reference re: DID core in the VCDM.

> *Dave Longley:* +1.

> *Ivan Herman:* +1.

</details>

**Comment by msporny** [comment]
Fixed in 1b4adf1c4f342edea878e27ea8938873e10bc7e7. Closing.
