### ISSUE TITLE
Can we change `Usage Patterns` to `Patterns of Use` throughout?

### ISSUE THREAD

**Issue by TallTed** [w3c/vc-data-model#1555]
I know, there are lots of `hrefs` and `[=...=]` to change as well as the visible text. And probably some number of other documents that we cannot change (now, if not ever), but which can be supported by secondary `<a id="">` elements. (I think there are some special ReSpec things related to this, but cannot immediately recall the syntax.)

Motivation is that `use` is generally preferred over the almost perfectly synonymous `usage`, largely because it substantially lowers the reading level.

**Comment by davidlehn** [comment]
Potentially relevant, or maybe not:
https://books.google.com/ngrams/graph?content=usage+patterns%2Cusage+pattern%2Cpatterns+of+use%2Cpattern+of+use&year_start=1800&year_end=2022&case_insensitive=true&corpus=en&smoothing=3

Didn't occur to me to even question "usage pattern[s]".

**Comment by longpd** [comment]
+1 for this simple change

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-08-28-vcwg#section3-3) on 2024-08-28

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.3. Can we change `Usage Patterns` to `Patterns of Use` throughout? (issue vc-data-model#1555)

_See github issue [vc-data-model#1555](https://github.com/w3c/vc-data-model/issues/1555)._




**Brent Zundel:** question - can we change 'Usage Patterns' to 'Patterns of Use' throughout the spec?  

> *Ted Thibodeau Jr.:* See [usage pattern ngram](https://books.google.com/ngrams/graph?content=usage+patterns%2Cusage+pattern%2Cpatterns+of+use%2Cpattern+of+use%2Cusage%2Cuse&year_start=1800&year_end=2022&case_insensitive=true&corpus=en&smoothing=3).

**Ted Thibodeau Jr.:** pretty simple and straightforward, 'use' is preferred over 'usage', it's one of those words that seems more sophisticated, but is not, leads to more confusion.  

> *Ted Thibodeau Jr.:* See [another usage pattern ngram](https://books.google.com/ngrams/graph?content=usage+patterns%2Cusage+pattern%2Cpatterns+of+use%2Cpattern+of+use%2Cusage&year_start=1800&year_end=2022&case_insensitive=true&corpus=en&smoothing=3).

**Brent Zundel:** folks, if you think this is a good idea or not, let us know.  

> *Manu Sporny:* +1 to making the change, it'll be easy.

**Brent Zundel:** we also need someone to volunteer to do the work.  

**Manu Sporny:** I'll do it, should be an easy change.  

**Brent Zundel:** we also have 1 PR.  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-09-04-vcwg#section3-1) on 2024-09-04

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.1. Can we change `Usage Patterns` to `Patterns of Use` throughout? (issue vc-data-model#1555)

_See github issue [vc-data-model#1555](https://github.com/w3c/vc-data-model/issues/1555)._




**Brent Zundel:** we will look at 1555.  
… a question from TallTed.  
… can we say "patterns of use" instead of "usage patterns".  

**Manu Sporny:** I said last time I would. I just haven't gotten to it yet.  

**Brent Zundel:** thank you all for the conversation and bigbluehat for scribing today.  
… see you on the special topic call at 5pm ET and 2pm ET tomorrow.  

> *Ivan Herman:* rssagent, draft minutes.

> *Geunhyung Kim:* quit.

---

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-09-11-vcwg#section3-7) on 2024-09-11

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.7. Can we change `Usage Patterns` to `Patterns of Use` throughout? (issue vc-data-model#1555)

_See github issue [vc-data-model#1555](https://github.com/w3c/vc-data-model/issues/1555)._




**Brent Zundel:** next is 1555, last time we talked nobody objected to change "usage patterns" to "patterns of use".  
… waiting for that PR.  

> *Manu Sporny:* yes, I will do that PR :).

> *Manu Sporny:* (or anyone else can too! ) :).

**Manu Sporny:** last week was controller document focused, this weekend hopefully can get back to VCDM queue.  

**Brent Zundel:** editorial change, straightforward, anyone can take this PR.  

**Will Abramson:** I can take that one.  

</details>

**Comment by msporny** [comment]
PR #1561 has been raised to address this issue. This issue will be closed once PR #1561 has been merged.

**Comment by msporny** [comment]
PR #1561 and PR #1569 have been merged, closing.
