### ISSUE TITLE
A wrong VCDM 2.0 context URL

### ISSUE THREAD

**Issue by filip26** [w3c/vc-data-model#1556]
Hi,
a wrong, non-existent,  context is used at three places. I guess it's typo.

`https://www.w3.org/2018/credentials/v2` 

please see:
 * [Example 30](https://w3c.github.io/vc-data-model/#example-verifiable-credential-using-the-data-integrity-bbs-cryptosuite-with-a-base-proof)
 * [Example 31](https://w3c.github.io/vc-data-model/#example-verifiable-presentation-using-the-data-integrity-bbs-cryptosuite-with-a-derived-credential-and-proof)
 * [Step 2](https://w3c.github.io/vc-data-model/#media-type-precision)

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-09-11-vcwg#section3-6) on 2024-09-11

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.6. A wrong VCDM 2.0 context URL (issue vc-data-model#1556)

_See github issue [vc-data-model#1556](https://github.com/w3c/vc-data-model/issues/1556)._




**Brent Zundel:** next is 1556, allowing VCDM 2.0 context URL, fixed in PR 1557, issue will be closed today.  

</details>

**Comment by msporny** [comment]
PR #1557, raised by @filip26, has been merged to fix this issue. Thank you for the PR @filip26! Closing issue as resolved.
