### ISSUE TITLE
Make Terminology section normative

### ISSUE THREAD

**Issue by selfissued** [w3c/vc-data-model#1558]

**Comment by selfissued** [comment]
That the Terminology is normative is a matter of fact. It would be strange and confusing for us to say otherwise in the specification.

This PR is the result of yesterday's discussions on the VCWG call in which consistency between specifications was an agreed-upon goal.

This is related to https://github.com/w3c/controller-document/pull/91.

**Comment by msporny** [comment]
I will make this change across all specs.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-09-11-vcwg#section3-8) on 2024-09-11

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.8. Make Terminology section normative (issue vc-data-model#1558)

_See github issue [vc-data-model#1558](https://github.com/w3c/vc-data-model/issues/1558)._




**Brent Zundel:** next up 1558, summary of discussion is that it doesn't really matter but might as well do it since it will make some people happy.  

**Michael Jones:** PRs are done.  

**Manu Sporny:** can I make this change across all specs.  

**Brent Zundel:** any objections to manu making this change across all specs.  
… hearing no objections, that is a reasonable course of action, thanks manu, please make a note when it is done so we can close the issue.  

</details>

**Comment by msporny** [comment]
Turns out we made this change 10 months ago based on @jyasskin's feedback: https://github.com/w3c/vc-data-model/commit/b3654a980787f4dbfe8173d9d0b97292cacf46e2 ... closing.
