### ISSUE TITLE
Are CredentialStatus, TermsOfUse, and Evidence useful types?

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#182]
There are PRs pending that establish `CredentialStatus`, `TermsOfUse`, and `Evidence` as types in the data model. It is argued that these types 1) do not result in any code being written that utilizes them, and 2) are already encoded in the `credentialStatus`, `termsOfUse`, and `evidence` properties.

**Comment by David-Chadwick** [comment]
I think we are talking at cross purposes. I am not talking about what a VC or a VP must contain. I am talking about properties with embedded types. If we have a property named X, that contains an embedded type, then that type either should or should not contain type X. I am trying to be consistent, and currently have suggested that the type should contain X. But if we decide X is redundant in the (set of) type value(s), because it is known from the encapsulating property name, then we should be consistent and remove it from all occurrences of embedded types.

**Comment by dlongley** [comment]
The presence of type tells you something about the kind of thing you've encountered and is often a strong signal to expect certain other properties. In other words, the value of "type" has some semantics and/or utility.

A property can also convey some of this information -- essentially the "range" of a property sets expectations for what value you'd expect to find it linking to. A property is a very specific relationship that links two nodes in a graph together. But there is no rule that says a property of "foo" must link to an object with type "Foo". A good counterexample to this would be something like a property "child", "parent", or "friend" linking to an object of type "Person". There are many kinds of relationships of this sort.

If "TermsOfUse" actually told you something about the kind of thing you're dealing with or enabled you to have certain expectations from which you could take some action, then it would be a useful type. But it seems like it has no semantics and creates no expectations. What could I do by knowing an object was a "TermsOfUse"? What conclusions could I draw from that? What properties could I expect to see? What actions could I take? What does it mean? If there are good answers to these questions then I have no issue with adding the type.

**Comment by David-Chadwick** [comment]
@dlongley What could I do by knowing an object was a "TermsOfUse"? 
Ans. First I would know that I cannot accept the VC without fully understanding all the contents of the object (assuming of course that this is a standards conformant implementation)

What conclusions could I draw from that? 
That I cannot ignore this object or accept the VC for further processing without first fully processing this object.

What properties could I expect to see? 
Next I retrieve my copy of all the terms of use that I understand (have preconfigured), and I check the type field to see if I know all of the types that are present. If not, I must reject the VC. If I understand all the types, then I now know what other properties to expect in this object.

What actions could I take? 
If I do not know any terms of use (i.e. dont have any preconfigured terms of use), then I must reject the VC.

What does it mean?
It means there are some obligations being placed on me (the verifier) by the issuer of the holder

**Comment by dlongley** [comment]
@David-Chadwick,

Hmm, I should have been more clear in my questions so I apologize for that. I think every response you gave was in relation to an object (a VC) which the terms of use were linked via the property "termsOfUse". Correct? If so, I believe you can do all of the above without the type "TermsOfUse"; it does not enable those behaviors. In fact, it seems to me that a standalone object (not linked to another object via its "termsOfUse" property) of type "TermsOfUse" could not enable any of the above.

So, is processing a "TermsOfUse" object useful without the object it is linked to (via the property "termsOfUse")? If knowing the type "TermsOfUse" for a *standalone object* can produce reasonable answers to the questions, then I agree it should have such a type.

**Comment by David-Chadwick** [comment]
@dlongley In another thread (#182) you said that you cannot infer the type of the object from the property, which is why you need the type, quote "The presence of type tells you something about the kind of thing you've encountered and is often a strong signal to expect certain other properties. In other words, the value of "type" has some semantics and/or utility."
You also said " But there is no rule that says a property of "foo" must link to an object with type "Foo". "
For these reasons, which you have articulated, it seems to me to be essential that the terms of use object has the type 'TermsOfUse' as this cannot be inferred from the property.

**Comment by David-Chadwick** [comment]
OOPs. The above should have read " @dlongley . Further up this thread (#182) you said...."

**Comment by dlongley** [comment]
@David-Chadwick,

> In another thread (#182) you said that you cannot infer the type of the object from the property, which is why you need the type, quote "The presence of type tells you something about the kind of thing you've encountered and is often a strong signal to expect certain other properties. In other words, the value of "type" has some semantics and/or utility."

But "TermsOfUse" doesn't tell you anything. So it's not helpful. The type you need is like "OdrlTermsOfUse" or "SomeOtherSpecificTermsOfUse" -- which would be defined in another vocabulary. Yes, you do need a type here in order to do some processing ... but "TermsOfUse" isn't it.

You said this above:

> Next I retrieve my copy of all the terms of use that I understand (have preconfigured), and I check the type field to see if I know all of the types that are present. If not, I must reject the VC. If I understand all the types, then I now know what other properties to expect in this object.

This is exactly right. The problem is that "TermsOfUse" won't be in that "preconfigured list" -- it's not useful. You'll look at the type field looking for something else, namely, the *specific* terms of use types you understand. You'll never be looking for "TermsOfUse".

**Comment by David-Chadwick** [comment]
My implementation will have several preconfigured lists, one for each type of object. One of these lists will be termsOfUse. So I use the TermsOfUse type to tell me which preconfigured list to consult. I surely dont want to consult them all.

**Comment by David-Chadwick** [comment]
I accept that the lists can be hung from the terms of use property and that the "TermsOfUse" type can be regarded as duplication. But this is no different to the duplication inherent when you insert a VC into a VP. I cannot see why you are arguing for the model to be different in these two cases.

**Comment by dlongley** [comment]
`VerifiableCredential` provides utility when you're not using a `VerifiablePresentation`. That's the difference. You may see a `VerifiableCredential` appear somewhere else (off of some other property) -- and it provides its own information about what properties to expect (`claim`, `proof`, `issuer`, so on). `TermsOfUse` does not do the same.

**Comment by David-Chadwick** [comment]
Agreed. So if there is a common field that all TermsOfUse must have, then this would be the rationale for having the TermsOfUse type in a TermsOfUse object.

**Comment by dlongley** [comment]
@David-Chadwick,

> Agreed. So if there is a common field that all TermsOfUse must have, then this would be the rationale for having the TermsOfUse type in a TermsOfUse object.

+1

**Comment by msporny** [comment]
Has anyone identified a common field for these types: CredentialStatus, TermsOfUse, and Evidence ... if not, I suggest we close this issue and will do so in 7 days.

**Comment by David-Chadwick** [comment]
Continuing the discussion about types only being there if they define a common property that all objects of that type must contain, then let us turn to the examples in #187. Here we are modelling passports as VCs. Note that we are adding the type "PassportCredential" **not** to the claim object, but to the credential object. However the type "PassportCredential" does not say anything about properties in the credential object, but rather defines the properties that the claim object must contain. I would therefore suggest that to fix this apparent anomaly, we modify the VC model document to either:
a) remove all types from the credential object, apart from "VerifiableCredential" (unless of course they are adding additional properties to credential objects), and instead add them to the claim object, since they are defining what properties claims must contain, 
OR
b) add a section to say that encapsulating objects, such as credential, may contain the types of embedded objects, such as claim or termsOfUse, so that the verifier can quickly determine the entire contents of the VC based on the type of the credential.
One thing I think we are all agreed upon is that the verifier must know from reading the various type fields present in a VC, what properties to expect in the VC and its encapsulated objects (based on the type definitions).

**Comment by msporny** [comment]
I made an attempt to address this issue in https://github.com/w3c/vc-data-model/pull/189 with simpler language. Does this work for you @David-Chadwick?

**Comment by David-Chadwick** [comment]
I find your "simpler" language ambiguous, indirect and unclear viz: "unless the type is not known or not including the type would not result in ambiguity when processing the credential. " It leaves far too much wiggle room for people to wrongly interpret it i.e. such as, "we don't need to include type properties because we do not know it".

My text is simpler, more direct, and easier to understand, viz: 
"encapsulating objects, such as credential, may contain the types of embedded objects, such as claim or termsOfUse, so that the verifier can quickly determine the entire contents of the VC based on the type of the encapsulating object"

**Comment by David-Chadwick** [comment]
To support my text, think of selling a house. Houses are not advertised simply as "house for sale" because in that case prospective purchases would need to inspect each house to see if its embedded rooms were what they wanted. Instead they are advertised as (at least in the UK) as "4 bedroom house for sale", "two bedroom, two bathroom house for sale". I.e. the types of the embedded objects are published along with the type of the encapsulating object.

**Comment by msporny** [comment]
> encapsulating objects, such as credential, may contain the types of embedded objects, such as claim or termsOfUse, so that the verifier can quickly determine the entire contents of the VC based on the type of the encapsulating object

I'm fine with this text (with minor editorial changes). It's weaker than the text in PR #189, but if you're happy with it, I am as well. I'll update PR #189.
