### ISSUE TITLE
Value of Type Property

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#183]
The Type property must be a URI according to the data model specification, viz : "The value of this property MUST be one or more URIs."

Implementors of VCs do not need to know JSON-LD, and indeed there is a section that says how to encode VCs in pure JSON.

However, all the examples of the <code>type</code> property in the data model spec use strings such as "VerifiableCredential" as examples of type values. Presumably some JSON-LD context turns these strings into URIs. However, these strings will not be interpreted as URIs by implementations that use pure JSON, as they are unaware of JSON-LD contexts. 

So am I correct in saying that a JSON implementation will reject these VCs, and therefore there cannot be interworking between JSON-LD and JSON implementations?

**Comment by dlongley** [comment]
The simple fix for this is to say that the types defined in the core spec are acceptable. Any other types must be URIs (or JSON-LD terms if using JSON-LD).

**Comment by David-Chadwick** [comment]
I dont see how this fixes the interworking problem because the core types are insufficient for virtually all interworking, save declaring someone's age.

**Comment by dlongley** [comment]
@David-Chadwick,

Please give an example of where it does not work (if we apply my proposed fix) so we can analyze it.

**Comment by David-Chadwick** [comment]
Issuer A uses JSON-LD so issues a VC of type "VerifiableCredential" and "UniversityStaff". The JSON-LD maps the latter into a URI that verifiers who understand JSON-LD can use and look up the URI for its definition.
Verifier B does not understand JSON-LD and receives the VC of type "VerifiableCredential" and "UniversityStaff". It understands the former as it written into the standard, but not the latter. Since it is not a URI it rejects the VC.

**Comment by dlongley** [comment]
@David-Chadwick,

You're talking about what I believe to be a protocol level problem. If a verifier requests a VC that uses `application/json` (as opposed to `application/ld+json`) then the presenter must share a VC that uses the default JSON-LD `@context`. This would result in "UniversityStaff" being represented as a URI in the JSON syntax. Again, this is a protocol level concern -- which we're not doing here. Perhaps we should add a non-normative section to the spec to clarify how this would work?

**Comment by David-Chadwick** [comment]
I think it would be very useful to add something to the spec, because we have a section on how to encode VCs as JSON, or as JSON-LD. 

I guess my concern is at least twofold:
i) all the early examples are in pure JSON and dont have any JSON-LD constructs in them (implying that this is just fine) when in fact they are not, as @contexts are needed.
ii) The latest text on extensibility seems to mandate the use of JSON-LD : "The requirement to provide all of the extensibility mechanisms outlined above in a data format that is popular among software developers and web page authors is enabled via the use of [JSON-LD]". 
iii) the examples in extensability section are not correct as they are adding new properties to VCs without adding new types to the type property that define these properties.

There needs to be equivalent text in the extensability section on how to extend VCs that are encoded in pure JSON.

**Comment by dlongley** [comment]
@David-Chadwick,

>  i) all the early examples are in pure JSON and dont have any JSON-LD constructs in them (implying that this is just fine) when in fact they are not, as @contexts are needed.

Just a quick note - We mention that if an `@context` is not present then a default one is assumed. From the current spec:

> If an application is processing a verifiable credential or verifiable presentation, and a @context property is not present at the top-level of the JSON-LD document, then a @context property with a value of https://w3id.org/credentials/v1 MUST be assumed.

**Comment by msporny** [comment]
This PR exists now: https://github.com/w3c/vc-data-model/pull/189 ... what are the remaining issues you are concerned about @David-Chadwick?

**Comment by msporny** [comment]
We've been internally debating the proper way to address this issue over the past couple of weeks. We were able to agree on a set of principles that would be desirable:

1. In general, do not require application developers to understand JSON-LD.
2. Push any heavy lifting wrt. software development to issuers first, verifiers second.

There is also one thing that is inescapable:

Everyone will have to use some JSON-LD tooling to generate and verify the current types of signatures we're placing on Verifiable Credentials. The data needs to go through canonicalization and signing -- all of which is encapsulated in a library that provides a "the signature is valid/invalid" return value. This does not mean application developers need to understand JSON-LD just as they don't need to understand TLS or x.509 certificates in order to build their applications on top of HTTPS.

Given that basis, the question is: "How do we enable application developers that want to stick with simple JSON processing at the application layer to do so safely without having to understand JSON-LD?"

There are a few simple rules we could add to the specification that would enable the question above to be answered in a way that may achieve consensus:

1. When extending the base verifiable claims data model, `@context` MUST be specified with the VC JSON-LD Context as the first item in the array, and the extension JSON-LD Context as the second item in the array. The second JSON-LD Context MUST NOT override terms in the first JSON-LD Context. This does mean that the issuer needs to understand JSON-LD to create the context, but since there will be far fewer issuers than there will be verifiers, this is most likely an acceptable compromise. This would make the following a standard pattern when extending the JSON-LD:

```
"@context": [
  "https://w3id.org/credentials/v1", 
  "https://extensions.example.org/extension/v1"
]
```

2. When sending data to a verifier, the proper compaction MUST be performed before sending the data to the verifier. This is automatically done at the issuer, so as long as middleware doesn't touch the verifiable credential issued by the issuer, no processing is necessary. That said, if anything is done in between, it is the job of the system modifying the credential to reformat it into a form that the verifier expects it to be in... and that form is one where a simple JSON processor can operate on the data structure w/o doing JSON-LD transformations.

This approach means that all verifiers just need to do two things to process extended objects as pure JSON:

1. Verify the digital signature of the incoming object.
2. Work with the object as JSON, checking types and then expected properties based on the type.

There is a JSON-LD 1.1 feature called "sealed contexts" that would enforce this sort of thing in the JSON-LD processor, but that feature will most likely not be standardized by the time this group finishes, so we can craft language that pushes the enforcement into the VC Data Model spec and then enables it to be enforced in JSON-LD in time (if the feature gets in there).

I'm going to stop here for now to see if there is general buy in on the approach. Comments @David-Chadwick, @dlongley, @nage, @cwebber, and anyone else that wants to weigh in?

**Comment by David-Chadwick** [comment]
Higher up this posting @dlongley said that whether the VC was encoded as pure JSON or JSON-LD was a protocol level issue (I will call it a transfer syntax issue) and the two are not-interoperable, in much the same was as JSON or XML encodings are not (although software can clearly translate between the two). Thus ?all/some/most? the current examples, which assume JSON-LD transfer syntax, should also have a pure JSON version as well. As a minimum the section on JSON encoding should specify clearly, and normatively, how a VC must be encoded in pure JSON for transfer.
The pure JSON examples  cannot contain @context (by definition) and the types will need to be full URIs, not user friendly strings. VCs can be extended by adding new URI values to the type parameters without needing to specify @context. So I am not currently persuaded by @msporny argument that @context must be specified. The primary requirement of the URI is that it is globally unique. That's all.

The type URIs may point to web pages where the new types are defined, but how these pages are encoded, of if they exist, is a secondary issue. For example they might be JSON-LD encoded allowing JSON-LD implementations to automatically, and without human involvement, automatically configure new schemas (although I would argue that in the area of security this could be very dangerous). They might be human readable only, allowing administrators to read them and decide whether they want to include these new features in their verifier software. Or they might simply be unique strings, that do not point to anywhere on the web, so that only a select few who want to interwork know what they mean. All other implementations will reject VCs containing these types.

**Comment by msporny** [comment]
> Higher up this posting @dlongley said that whether the VC was encoded as pure JSON or JSON-LD was a protocol level issue (I will call it a transfer syntax issue) and the two are not-interoperable, in much the same was as JSON or XML encodings are not (although software can clearly translate between the two). 

You're starting from a false premise... There is a subset of JSON/JSON-LD constructs that do not require translation in order to achieve interoperability.

> Thus ?all/some/most? the current examples, which assume JSON-LD transfer syntax, should also have a pure JSON version as well. 

That is not required, as nothing changes between the JSON-LD and JSON versions.

Now, we may want to change minor things in the examples (like the ones in the extensibility section), but the goal here is that the JSON and JSON-LD expressions, in the general case, are completely interoperable and not a byte of content needs to change.

> As a minimum the section on JSON encoding should specify clearly, and normatively, how a VC must be encoded in pure JSON for transfer.

It does.

> The pure JSON examples cannot contain @context (by definition) and the types will need to be full URIs, not user friendly strings. 

-1, that approach will only lead to divergence between the JSON and JSON-LD markup. We should be going for convergence in our solutions, not two completely different expressions that could have been compatible were it not for incompatible/non-interoperable decisions made by the WG.

> VCs can be extended by adding new URI values to the type parameters without needing to specify @context. 

-1, this approach has failed time and time again to provide a solid extensibility foundation and has been the topic of debate during the 2000s. This approach is an evolutionary dead-end and is a mistake we don't want to repeat in this group.

> The type URIs may point to web pages where the new types are defined, but how these pages are encoded, of if they exist, is a secondary issue. 

Replace `type` with `@context` and you've just re-invented JSON-LD.

> For example they might be JSON-LD encoded allowing JSON-LD implementations to automatically, and without human involvement, automatically configure new schemas (although I would argue that in the area of security this could be very dangerous). 

It would be dangerous, and as far as I understand it, no one is currently suggesting that path for VCs.

> They might be human readable only, allowing administrators to read them and decide whether they want to include these new features in their verifier software. Or they might simply be unique strings, that do not point to anywhere on the web, so that only a select few who want to interwork know what they mean. All other implementations will reject VCs containing these types.

... leading to a non-interoperable ecosystem. I think that puts us on a very dangerous path.

Instead, we could implement a much simpler rule:

* JSON and JSON-LD encodings MUST provide the contexts that they're using. The order of the contexts matter.

For example:

```
  "@context": [A, B, C, D],
```

This means that JSON processors can just check the value of `@context` and that `[A, B, C, D]` exists and then hard code everything else. There are some edge cases where you may do something like this:

```
  "@context": [A, B],
  claim: {
    "@context": [C, D]
  }
```

... but effectively, pure JSON processors would just check to make sure the active context is `[A, B, C, D]`, which can be done via a simple convenience function and a simple if statement:

```
  if(_activeContext([A, B, C, D])) { ... do hardcoded stuff ... }
  else { ... throw error ... }
```

This makes it such that "JSON extensions" are not relegated to second class constructs and can use short strings without the downside of adding ambiguity.

**Comment by David-Chadwick** [comment]
@msporny  said "The data needs to go through canonicalization and signing -- all of which is encapsulated in a [JSON-LD] library that provides a "the signature is valid/invalid" return value."

Do open source zero-cost licences exist for verifying the proposed signature format?

I know that several different ones exist for JWT (see for example http://openid.net/developers/jwt/).  

In order to gain wide acceptance of VCs, it is important that multiple open source libraries exist.

**Comment by David-Chadwick** [comment]
@msporny said "... leading to a non-interoperable ecosystem. I think that puts us on a very dangerous path."

I disagree. In order to ensure the wide acceptance of VCs, different communities of interest will want to ensure that their eco-system does not interoperate with other VC eco-systems e.g. consider the SWIFT network migrating to VCs - it will only want banks to be able to interoperate with it.

Note that there is a difference between software interworking and eco-system interworking. The same software can be used in two different eco-systems. But they won't interwork because they have different VC types and roots of trust configured into them.

So our objective should be software interoperability, not eco-system interoperability.

Concerning software interoperability, we should ensure that VCs can be encoded using popular open source JSON libraries.

**Comment by msporny** [comment]
@msporny said: "The data needs to go through canonicalization and signing -- all of which is encapsulated in a [JSON-LD] library that provides a "the signature is valid/invalid" return value."
@David-Chadwick said: Do open source zero-cost licences exist for verifying the proposed signature format?

Yes, of course... we generate zero-cost open source software for every standard that we're involved in. The specific libs you're looking for are:

https://github.com/digitalbazaar/jsonld.js/
https://github.com/digitalbazaar/jsonld-signatures/
https://github.com/digitalbazaar/forge/

**Comment by David-Chadwick** [comment]
@msporny said ... but effectively, pure JSON processors would just check to make sure the active context is [A, B, C, D], which can be done via a simple convenience function and a simple if statement:

  if(_activeContext([A, B, C, D])) { ... do hardcoded stuff ... }
  else { ... throw error ... }

This makes it such that "JSON extensions" are not relegated to second class constructs and can use short strings without the downside of adding ambiguity.

Ordered contexts sounds like a good compromise to me.
