### ISSUE TITLE
Add renewalService URL to standard data model

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#19]
We may want to provide a verifiable claim refresh/renewal service to a verifiable claim such that it may be automatically renewed upon revocation or expiration. This could help smooth out  the experience around "expired credential" use cases such that expired credentials with a renewal service URL could still be considered for use without the individual explicitly having to renew the credential.

**Comment by David-Chadwick** [comment]
I think this is primarily an implementation issue rather than a protocol one. In our implementation, the client knows which attributes the user is able to assert, and whether there is a current credential available or not. But the user is never pestered to renew his credentials. They are automatically renewed when the attribute needs to be asserted and the existing credential has expired. There is no point in renewing a credential prior to it being used. It may never be used before it expires.

**Comment by msporny** [comment]
> they are automatically renewed when the attribute needs to be asserted and the existing credential has expired. 

Yes, that's exactly what this issue is driving at. We need a way to represent this renewal URL in the data model. We will also need to define a protocol for doing so (eventually).

**Comment by stonematt** [comment]
What are the next steps on this issue?    This should have clarity early in our process.

**Comment by msporny** [comment]
@stonematt next steps are that we need a concrete proposal as a PR. So, someone needs to volunteer to do that. @dlongley might be the best person to do that PR.

**Comment by David-Chadwick** [comment]
I still do not see the need for this feature. Given that the user already has the VC that will need renewing sometime in the future, then the user's client already knows how to get the VC (otherwise the user would not have it). So why does it need to be told something it already knows?

**Comment by stonematt** [comment]
seems related to #139 we'll try to address them together!

**Comment by msporny** [comment]
There is a PR now that adds this feature: https://github.com/w3c/vc-data-model/pull/199

**Comment by dlongley** [comment]
Closed via #210.
