### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by CipherQueen** [w3c/vc-data-model#201]
Attached please find a nine-page document with typos, spelling errors, and nits.

[Verifiable Credentials Data Model notes, V2.docx](https://github.com/w3c/vc-data-model/files/2188576/Verifiable.Credentials.Data.Model.notes.V2.docx)

**Comment by stonematt** [comment]
There are a couple items in the attached document that aren't addressed in pr #219. I'll follow up on those and open new issues if necessary.

**Comment by dlongley** [comment]
@stonematt, any updates here? Can we close this out?

**Comment by rhiaro** [comment]
**The following issues are fixed in https://github.com/w3c/vc-data-model/pull/389**

> Section: 1. Introduction
> * Change “machine-verifiable” to “machine verifiable”

✔

> Section 9.9 Fitness for Purpose
> * Suggestion: “**it** may accept”

✔ (The exact sentence has now changed but the principle of the comment holds.)

> Section 9.11.5
> * Current (title of the section): “Long Lived Identifier-based Correlation”
> * Suggestion: “Long-Lived Identifier-Based Correlation”

✔

> Section 9.11.10 Validity Checks
> * Current: “a variety of business process specific checks”
> * Suggestion: “a variety of business-process-specific checks”

✔

> Section 9.11.12 Aggregation of Credentials
> * Current: “Two pieces of information about the same subject almost always reveals more”
> * Suggestion: “Two pieces of information about the same subject almost always reveal more”

✔ Rephrased to:

> **Holding** two pieces of information about the same <a>subject</a> almost always 
> reveals more about the <a>subject</a> than just a single piece of information, 
> even when **the information is** delivered through different channels.

**The following can't be fixed:**

> Section: Status of This Document
> * Add a comma after “replaced”

We can't modify the SotD, it's automatically generated W3C boilerplate.

**The following have not yet been addressed, but I can do so with some feedback.**

> Section: 1. Introduction
> Current: “Verifiable Credentials can be revoked by the issuer.”
> Question: Are holders notified when an issuer revokes the holder’s credentials?

I can't find text in the spec that answers that question. Should it be answered here? (Or it's out of scope?)

> Section 1.1 What is a..
> Current: “The addition of digital technologies, such as digital signatures, also make verifiable credentials more tamperproof and therefore more trustworthy than their physical counterparts.” 
> [...] Just because something is more tamperproof does not mean it is more trustworthy. [...]
> Suggestion: “The addition of digital technologies, such as digital signatures, supports the goal to make verifiable credentials more tamperproof and more trustworthy than their physical counterparts.” 

This has since been rephrased to say "tamper-evident" rather than "tamperproof", so I think in this case the "therefore" is probably fine to be left in.

> Section 2. Terminology
> Add the following terms to the terminology section, along with definitions.
> * Anonymous
> * Authenticity
> * Bearer Credential
> * Content-Addressed Identifier
> * Counter Signature
> * Credential Identifier
> * Credential Metadata
> * Credential Status
> * Dispute
> * Disputed Credential
> * Evidence (Evidence object)
> * Expiration Date
> * Id (id property)
> * Issuance Date
> * Issuer Signature
> * Linked Data Signature
>   * Properties:
>    * Created property
>    * Creator property
>    * Proof Purpose property
> * Permissionless Innovation
> * Persona
> * Presentation Identifier
> * Principle of Minimal Disclosure
> * Privacy-Enhancing
> * Proof
> * Proof Property
> * Properties
>   * Expiration Date Property
>   * Issuer Property
>   * Proof Property
>   * Status Property
>   * Type Property 
> * Psuedo-Anonymous?
> * Pseudonymous
> * Relying Party
> * Revocation
> * Signature
> * Single-Use Credentials
> * Suspension
> * Terms of Use
> * Trust
> * Trust Model
> * Type
> * Type Property 
> * Value
> * Verifiable Credential
> * Verifiable Presentation

I think most of these terms are either not core to the spec, or are very specialist to the spec and thus described inline when they are first introduced. Could someone who knows the spec well could run through this list and confirm if anything on it should be included in section 2?

> Section ~~8.~~ 9 Verification
> * Current: “This metadata is pertinent when checking the proofs **on** the verifiable credential.”
> * Suggestion: “This metadata is pertinent when checking the proofs **of** the verifiable credential.”

I think "on" is the right language?

> Section ~~8.8~~ 9.8 Revocation
> * There is only one sentence in this section, and it is confusing. Please elaborate. Please beef up this section with more detail and current thoughts on this critical topic.

Perhaps less confusing phrasing:

> "Revocation instructions MUST NOT be present if the credential has been revoked."

.. but I'd like someone to confirm this doesn't drastically change the meaning.

> Section 9.11.13
> Suggestion: “When the same subject identifier of a credential refers to the same subject across presentations or verifiers**, then loss of privacy is possible.**”

The current ED matches the suggestion, but it is undone in https://github.com/w3c/vc-data-model/pull/387

---

The rest have been fixed or obsolesced since the issue was raised, listed here for the record:

> Section: Title Page
> * “File a bug” has 404 error
> * “Commit history” has 404 error
> * “Pull requests” has 404 error

> Section: 1. Introduction
> * Suggestion: (add period):
>   * the use cases and requirements that informed this specification.
> * Figure 1
>   * Arrow from Issuer to Identifier Registry
>    * Clarify the actions between the Issuer and Identifier Registry, right now it looks just like the actions between the Verifier and the Identifier Registry
>    * Change arrow label from “Verify Identity Ownership” to “TBD”
> * Suggestion: (add space): The Verifiable Credentials Use Cases [VC-USECASES] document
> * Suggestion: (deleted be): “Holders are able to freely choose and change the agents they employ to help them manage and share their verifiable credentials.”
> * Suggestion: “a presentation that is made tamper resistant”

> Section 3: Core Data Model
> * Use “metadata” instead of “meta data”
> * Use “issuer” instead of “who”

> Section 4. Trust Model
> * Change “un-corruptible” to “incorruptible”

> Section ~~6.1~~ 7 Advanced Concepts
> * Suggestion: often called an "open world assumption," meaning
\
> Section ~~8.~~ 9 Verification
> * Use consistent spelling throughout the document: implementers versus implementors
> * Suggestion: “For example, an issuer may publish information that contains the public keys it uses to digitally sign verifiable credentials that it has issued.”
> * Align the titles for sections 8.5 and 5.3
> * Suggestion: The proofPurpose property ensures that the reason the entity created the signature, such as for the purposes of authentication or creating a verifiable credential, **is** clear and protected in the signature.
> * Suggestion: change the title [from "Issued"] to “Issuance Date”
> * s/resturant/restaurant

> Section ~~10~~ 9.11 Privacy Considerations
> * What is pseudo-anonymous?
> * key words are capitalized .. Either the key words are linked to the definition, or they are simply lower case.
> * Section Device Fingerprinting: Entire first paragraph: many words are capitalized unnecessarily, fix accordingly
> * Suggestion: “the id property that is nested”
> * Suggestion: “Verifiable credentials that are bearer credentials ”
> * Suggestion: “the following verifiable credential is”
> * Suggestion: “birthdate and zip code”
> Section ~~11~~ 9.12 Security Considerations
> * Suggestion: “A verifier may need to ensure that it is”
> * Suggestion: “and is not the target”
> * Suggestion: ?? what is an inspector-verifier?

Plus *all* hyphen-related feedback!

**Comment by msporny** [comment]
>> Section: 1. Introduction
>> Current: “Verifiable Credentials can be revoked by the issuer.”
>> Question: Are holders notified when an issuer revokes the holder’s credentials?

> I can't find text in the spec that answers that question. Should it be answered here? (Or it's out of scope?)

That's a protocol issue, thus out of charter scope.

>> Section 1.1 What is a..
>> Current: “The addition of digital technologies, such as digital signatures, also make verifiable credentials more tamperproof and therefore more trustworthy than their physical counterparts.” 
>> [...] Just because something is more tamperproof does not mean it is more trustworthy. [...]
>> Suggestion: “The addition of digital technologies, such as digital signatures, supports the goal to make verifiable credentials more tamperproof and more trustworthy than their physical counterparts.” 

> This has since been rephrased to say "tamper-evident" rather than "tamperproof", so I think in this case the "therefore" is probably fine to be left in.

Either is fine since the distinction will most likely go unnoticed by the average reader. Suggest using @CipherQueen's "and" language since she had a stronger feeling about it than other readers. I don't expect

>> Section 2. Terminology
>> Add the following terms to the terminology section, along with definitions.

Bombarding the reader w/ a massive list of terminology will give the impression that the specification is more complex than it is, so -1 in general to adding terminology that is not absolutely required as those reading the specification are expected to have at least some background in terms of art.

> I think most of these terms are either not core to the spec, or are very specialist to the spec and thus described inline when they are first introduced. Could someone who knows the spec well could run through this list and confirm if anything on it should be included in section 2?

Many of these are defined in line, elaborated upon in sections, or are not central to understanding the focus of the section. I ran through the list and didn't come across anything that people have raised a concern about not understanding (based on their reviews of the specification).

>> Section ~~8.~~ 9 Verification
>> * Current: “This metadata is pertinent when checking the proofs **on** the verifiable credential.”
>> * Suggestion: “This metadata is pertinent when checking the proofs **of** the verifiable credential.”

>I think "on" is the right language?

Correct, "on" is the right language since the proofs co-exist with the credential in most cases. We could also use "attached to", or "associated with".

>> Section ~~8.8~~ 9.8 Revocation
>> * There is only one sentence in this section, and it is confusing. Please elaborate. Please beef up this section with more detail and current thoughts on this critical topic.

>Perhaps less confusing phrasing:

>> "Revocation instructions MUST NOT be present if the credential has been revoked."

>.. but I'd like someone to confirm this doesn't drastically change the meaning.

I believe that wording is incorrect. This section is now the status section, which I think is fine. Basically, if you want to make sure the credential can be revoked, you have to have a status on the credential.

>> Section 9.11.13
>> Suggestion: “When the same subject identifier of a credential refers to the same subject across presentations or verifiers**, then loss of privacy is possible.**”

> The current ED matches the suggestion, but it is undone in https://github.com/w3c/vc-data-model/pull/387

I think the change in PR #387 is fine, so we can close this sub-item out.

**Comment by rhiaro** [comment]
https://github.com/w3c/vc-data-model/pull/389 is now updated with @msporny's feedback (thanks!) and merging will resolve this issue.
