### ISSUE TITLE
Default namespace URL

### ISSUE THREAD

**Issue by burnburn** [w3c/vc-data-model#206]
From @ianbjacobs  on 20 July 2018:

> I have one observation: section 9.2 (JSON-LD) defines a default namespace URL which is https://w3id.org/credentials/v1 
> 
> Would it be possible to use a W3C namespace instead following this policy?
>  https://www.w3.org/2005/07/13-nsuri

**Comment by msporny** [comment]
> Would it be possible to use a W3C namespace instead following this policy?

The URL for the credentials JSON-LD context has a number of requirements:

1. It's easy for developers to remember.
2. It can be dereferenced, and the file may be requested hundreds of millions to billions of times a day.
3. The hosting provider for the URL finds the second requirement acceptable.

When discussing this with W3C Staff before (I think we talked w/ @sandhawke the most), it was the third item that was difficult to resolve. Note that we expect most uses of this URL to aggressively cache the document and not go out to the network (most implementations ship with a static file instead of going out to the network)... but there is always the chance that a big implementation won't do that and thus hammer the URL.

I would expect the W3C VCWG to welcome a JSON-LD context at any of the following URLs:

https://www.w3.org/ns/credentials/v1
https://w3.org/2018/credentials/v1

@ianbjacobs, do you think either of the two URLs above are workable given the requirements listed above?

**Comment by ianbjacobs** [comment]
Hi @Msporny,

Thank you for enumerating requirements. I would add a fourth (if acceptable): 
 
 * W3C should host the resource.

We have had experience with widely referenced resources (namely, DTDs) and managed them reasonably well despite rogue software that should have cached but didn't.

I recommend that the Working Group write a proposal for the Team Contact to bring to the management team, since I am hearing this is a question of resources and maintenance.

I hope that helps,

Ian

**Comment by msporny** [comment]
> I recommend that the Working Group write a proposal for the Team Contact to bring to the management team

Thanks @ianbjacobs, that gives us a concrete next step.

@stonematt and @burnburn, can we put this on an upcoming VCWG agenda?

**Comment by msporny** [comment]
ping -- Chairs of VCWG:
> @stonematt and @burnburn, can we put this on an upcoming VCWG agenda?

**Comment by burnburn** [comment]
From TPAC 2018:
- [ ] Reference proposed URLs (https://w3.org/2018/credentials/v1 and https://w3.org/2018/credentials) in the specification
- [ ] Request proposed URLs above from W3C web team
- [ ] Document resource integrity proofs for these in the Implementation Guidance NOTE
- [ ] Document static caching for Credentials JSON-LD context

**Comment by jonnycrunch** [comment]
my issues is that it is an www URL.  there are other formats including the `@content` being an object using a CID as in IPLD.

**Comment by jonnycrunch** [comment]
see my pull request: https://github.com/w3c/vc-data-model/pull/261

**Comment by dmitrizagidulin** [comment]
@jonnycrunch Can the IPLD style CID be modeled using [Hashlinks](https://tools.ietf.org/html/draft-sporny-hashlink-02)?

**Comment by brentzundel** [comment]
Decision at Barcelona F2F: Tasks complete or accommodated, close issue.
