### ISSUE TITLE
Image Descriptions requested by Accessibility Group

### ISSUE THREAD

**Issue by stonematt** [w3c/vc-data-model#225]
Source email: https://lists.w3.org/Archives/Public/public-vc-comments/2018JulSep/0001.html

1.)	Please provide appropriate image descriptions throughout. Please
note that alt tags are not always sufficient. Guidance on describing
more complex images can be found at:

**Comment by stonematt** [comment]
URL attached: 
https://www.w3.org/WAI/tutorials/images/complex/

**Comment by dhh1128** [comment]
I think this is a good idea, but it can't be baked directly into the data model because the data model doesn't require any images, let along descriptions. Perhaps the best action would be to update the spec with a short paragraph noting that where images are embedded in a VC, we endorse the embodiment of accessibility recommendations at the specified URL.

**Comment by stonematt** [comment]
@dhh1128 my interpretation of the feedback is to include image descriptions of the images in the DM document itself.  I don't think it's a request to modify the data model.  Is that how you're reading it?

**Comment by TzviyaSiegman** [comment]
@stonematt is correct. The recommendation from WAI is to add image descriptions to the images that are included in the DM itself, no need to change the DM.

**Comment by brentzundel** [comment]
Decision at Barcelona F2F: @stonematt and @TzviyaSiegman will get this done.

**Comment by burnburn** [comment]
This was actually required for CR, so I added alt text for every image in commit 92abf9f94a624389d445494f9cdbaa07d3c25e38.  If it needs improvement that can occur after CR entry in a new issue/PR, so closing now as complete.
