### ISSUE TITLE
Confused by json-ld inclusions in JSON examples 3 and 5 -- is this correct?

### ISSUE THREAD

**Issue by stevenrowat** [w3c/vc-data-model#23]
See section:
4.1.2  Expressing Entity Credentials in JSON

Why is json-ld used in two examples under this JSON section, in Examples 3 and 5?

I'm not versed in either json-ld or JSON more than the small amount I've seen while on the Web Payments and VC mailing lists, which isn't a lot, so I'm coming to this section relatively cold. And I find it confusing: in fact they look like full-blown json-ld examples, and if so, it must be an error, and they should be in the following section, 4.2. 

A second possibility: is json-ld and @context actually **required** within JSON, in section 4.1.2, to achieve Examples 3 and 5? It seems odd if that's true, and the naive reader might need a little explanation of that, considering that the next section, 4.2, is supposedly the json-ld section.

Third, if it's not an error, yet not a necessary part of JSON code, then my last guess is that json-ld in those examples was merely chosen as an (aribtrary) instance of a type of code or organization; and if so then I believe a different one should be used, since, again, that is confusing as regards the actual json-ld examples in the following section, 4.2.  

And finally, if none of those are true, then people reading this document who don't write these types of code are still going to need some help in understanding what those json-ld code bits are doing under the JSON heading.  :-)

**Comment by jtibbetts** [comment]
I think there is a problem in this document with the way that JSON and JSON-LD are shown to relate with one another.  And you're seeing one manifestation of that problem in this section.  I intend to write further about this either in another issue or in some other posting to the group. 

In the meantime let me make a best effort at explaing this given inferences that I've made from the discussions so far.

1. The signing mechanism of the Verifiable Claim is **not** done by analyzing the JSON-LD itself.  It turns out that JSON-LD is quite flexible in the ways that the very same information model can be syntactically represented.  For instance, the same model (that is the identical data) can be manipulated to be more human-readable or more machine-readable.  Yet these variant syntactic forms need to generate the same signature.  Consequently you can't just do stuff like hashing the source to get a reliable signature.

2. What is done instead is that source JSON-LD is internally converted to a graph; that is, a set of information atoms; i.e., NQuads.  An NQuad is like an RDF triple but it has an extra field that specifies which graph the triple resides in.  These NQuads are further normalized to handle other issues, most notably so-called blank-nodes which need a carefully controlled identifier.  Then these NQuads generate the signature.  Note: since all the variant JSON-LD representations reduce to the identical set of NQuads the signature generated is the same.  (This is actually pretty cool).

3. Here's the heart of your question: raw JSON is a syntax for representing **data**.  It has no first-class mechanism for describing **references** (or **links**) to other data.  That is what JSON-LD (JSON for Linked Data) is for.  Therefore, JSON is great at creating information models that express data hierarchies, but it is terrible at expressing graphs.  On the other hand, JSON-LD natively expresses a graph.  Since it takes the graph to generate the signature Examples 3 and 5 (which are signed) are in JSON-LD.  But Example 1 and 2 (which are unsigned) can be adequately expressed in JSON.

There's more to say about this.  I think maybe we should only show JSON-LD in a document that's about Verifiable Claims.  But I also think we should soft-pedal the LD-ness of the JSON.  But I'll make that argument elsewhere.

p.s. I'm acutely aware that there are **really** knowledgeable people in this group about JSON-LD.  So I'm a bit bashful about sounding too confident on this topic.  But I do have a lot of experience working with standards people who develop an animosity for anything that that is not pure JSON.

**Comment by BigBlueHat** [comment]
FWIW, in the [Web Annotation Data Model](https://www.w3.org/TR/annotation-model/) we required the `@context` key, but mapped `@id` and `@type` to simpler `id` and `type` variations, and made (at some level) the JSON serialization valid JSON-LD. You can see the that in the [required properties of an Annotation](https://www.w3.org/TR/annotation-model/#annotations).

The objective was to have a Web Annotation Data Model document be "plain ole JSON" that included just enough awesome to also be processed/understood as a JSON-LD document.

However, in our case, a expanded JSON-LD document (one that uses `@graph` etc) is *not* a valid "Web Annotation Data Model" document as the JSON-level shape is different.

The reasoning was that JSON is more familiar to most developers, but JSON-LD provides the hypermedia meaningfulness necessary for annotations to actually be webby (since the JSON media type does not actually do links...).

The catch with this spec, though, is that the signing mechanisms might be different. You can see the JSON in Example 3 in [Expressing Entity Credentials in JSON](https://w3c.github.io/vc-data-model/#h-expressing-entity-credentials-in-json) actually includes the `LinkedDataSignature2015` object--which may just mean that it's been previously signed as Linked Data, but is now being provided as JSON. Then there's the JWT example, which is a signed copy of the JSON structure...

If the JSON-level shape is dictated (as in Web Annotation Data Model) and the required keys/shape of the default (at least) JSON-LD representation are equivalent, then a JWT of a JSON-LD (in the default shape) would be equivalent to a JWT of the JSON-level shape (because they'd be identical).

Again, I'm only just booting up in my VC plans/knowledge here, so please take this with appropriate amounts of salt. :grin:

**Comment by msporny** [comment]
> (most importantly) the different signing mechanisms used: JWT or LinkedDataSignature2015.

Just to provide an update on where we are with JWT and LDS. I met with the spec authors for the JOSE JWS/JWT work and worked through a mechanism that enables LDS to use the JOSE stack for signatures while keeping all the benefits of JSON-LD. That is, we figured out a way to merge the technologies in a complementary way. That work led to this spec:

https://w3c-dvcg.github.io/lds-rsa2017/#examples

While the spec above isn't implemented yet, we do expect to implement it in the next couple of months since it doesn't force people to use the JOSE stack vs. the LDS one, you can use LDS and JOSE JWS together.

The Editors still need to update the Verifiable Claims spec to use the new signature algorithm in the examples and remove the JWT section of the spec.

**Comment by msporny** [comment]
The JSON-LD Context has been removed from all JSON examples:

https://github.com/w3c/vc-data-model/blob/700263aca114f2d06a64762d2502e39686d409e5/index.html#L973-L975

This resolves the original issue raised in this thread. Closing.
