### ISSUE TITLE
Indy's needs for ZKPs

### ISSUE THREAD

**Issue by mikelodder7** [w3c/vc-data-model#237]
I'm adding this as a reference for how indy credential and proof structures are serialized and processed.

[Credential Schemas](https://github.com/hyperledger/indy-sdk/blob/master/libindy/src/domain/anoncreds/schema.rs) are read by all to know what information can be stored in a given credential
```
{
    "id": String,
    "name": String,
    "version": String,
    "attrNames": [AttributeNames: String],
    "seqNo": Option<u32>,
}
```
[Credential definitions](https://github.com/hyperledger/indy-sdk/blob/master/libindy/src/domain/anoncreds/credential_definition.rs) reference a schema and contain an issuer's public key. Option means if its null its left out.
```
{
    "id": String,
    "schemaId": String,
    "signatureType": SignatureType = "CL",
    "tag": String,
    "value": {
       "primary": {
           "n": DecimalString,
           "s": DecimalString,
           "r": [{"attr_name": DecimalString}],
           "rctxt": DecimalNumber,
           "z": DecimalNumber
       },
      "revocation": Option<{
         "g": EllipticCurvePointString,
         "g_dash": EllipticCurvePointString,
         "h": EllipticCurvePointString,
         "h0": EllipticCurvePointString,
         "h1": EllipticCurvePointString,
         "h2": EllipticCurvePointString,
         "htilde": EllipticCurvePointString,
         "h_cap": EllipticCurvePointString,
         "u": EllipticCurvePointString,
         "pk": EllipticCurvePointString,
         "y": EllipticCurvePointString,
      }>
    }
}
```
[Primary Credential](https://github.com/hyperledger/indy-crypto/blob/master/libindy-crypto/src/cl/mod.rs) line 555 is the credential with attributes signed by the SignatureType
```
{
    "m_2": DecimalString,
    "a": DecimalString,
    "e": DecimalString,
    "v": DecimalString,
}
```
[Non Revocation Credential](https://github.com/hyperledger/indy-crypto/blob/master/libindy-crypto/src/cl/mod.rs) line 563 is the corresponding credential used to check for revocation. Indy uses CKS signatures
```
{
    "sigma": EllipticCurvePointString,
    "c": GroupOrderElementString,
    "vr_prime_prime": GroupOrderElementString,
    "witness_signature": WitnessSignature = {
        "sigma_i": EllipticCurvePointString,
        "u_i": EllipticCurvePointString,
        "g_i": EllipticCurvePointString
    },
    "g_i": EllipticCurvePointString,
    "i": u32,
    "m2": GroupOrderElementString
}
```

[Proofs](https://github.com/hyperledger/indy-crypto/blob/master/libindy-crypto/src/cl/mod.rs) line 801
```
{
    "proofs": [
        {
            "primary_proof": {
                "eq_proof": {
                    "revealed_attrs": [AttributeNames],
                    "a_prime": DecimalString,
                    "e": DecimalString,
                    "v": DecimalString,
                    "m": DecimalString,
                    "m2": DecimalString 
                }
                "ge_proofs": [
                    {
                        "u": [{"attr_name": DecimalString}],
                        "r": [{"attr_name": DecimalString}],
                        "mj": DecimalString,
                        "alpha": DecimalString,
                        "t": [{"IndexString", DecimalString}],
                        "predicate": Predicate = {
                            "attr_name": String,
                            "p_type": "<GE, GT, LE, LT>",
                            "value": i32
                        }
                    }
                ]
            },
            "non_revoc_proof": {
                "x_list": {
                    "rho": GroupOrderElementString,
                    "r": GroupOrderElementString,
                    "r_prime": GroupOrderElementString,
                    "r_prime_prime": GroupOrderElementString,
                    "r_prime_prime_prime": GroupOrderElementString,
                    "o": GroupOrderElementString,
                    "o_prime": GroupOrderElementString,
                    "m": GroupOrderElementString,
                    "m_prime": GroupOrderElementString,
                    "t": GroupOrderElementString,
                    "t_prime": GroupOrderElementString,
                    "m2": GroupOrderElementString,
                    "s": GroupOrderElementString,
                    "c": GroupOrderElementString
                },
                "c_list": {
                    "e": EllipticCurvePointString,
                    "d": EllipticCurvePointString,
                    "a": EllipticCurvePointString,
                    "g": EllipticCurvePointString,
                    "w": EllipticCurvePointString,
                    "s": EllipticCurvePointString,
                    "u": EllipticCurvePointString
                }
            }
        },
    ]
    "aggregated_proof": {
        "c_hash": DecimalString
        "c_list": [
            [<byte numbers>],
            [<byte numbers>]
        ]
    }
}
```
Let me know if you need any other information

**Comment by dlongley** [comment]
I think the flow, in general, for any ZKP/selective disclosure style credentials that must present "derived" credentials, rather than those received directly from the issuer, should be this:

1. The holder receives a VC `vc_from_issuer` from an issuer. This VC will have a proof of type `some_issuer_zkp_style_proof`. This type of proof includes all the cryptographic information necessary for a holder to create a proof of possession of a VC from the issuer. This VC uses the VC data model and looks like any other VC would, modulo the specific proof type. For example:

```js
{
  "@context": ["https://w3id.org/credentials/v1", "https://w3id.org/some-extension/v1"],
  "type": ["VerifiableCredential", "SomeSpecificCredential"],
  "issuer": "...",
  "claim": {
    "id": "did:example:1234",
    "propertyA": "valueA",
    "propertyB": "valueB",
    "propertyC": "valueC"
  },
  "proof": {
    "type": "some_issuer_zkp_style_proof",
    /* whatever is needed to generate proofs for derived VCs */
  }
}
```

2. The holder prepares to present to a verifier. The holder creates a VC called `derived_vc` that is derived from the VC in their wallet (`vc_from_issuer`). This VC has a proof of type `DerivedCredentialProof`. This VC uses the VC data model, but includes only those properties that the holder wishes to disclose, such that it looks just like a non-ZKP style VC, modulo the proof. The proof's type indicates that the proof on the VC is insufficient to prove the VC alone; the proof from its encapsulating VP is required. This proof can be linked to via the VC's proof:

```js
{
  "@context": ["https://w3id.org/credentials/v1", "https://w3id.org/some-extension/v1"],
  "type": ["VerifiableCredential", "SomeSpecificCredential"],
  "issuer": "...",
  "claim": {
    "id": "did:example:1234",
    // note: only revealing propertyA
    "propertyA": "valueA"
  },
  "proof": {
    "type": "DerivedCredentialProof",
    "presentationProof": "id_of_vp_proof",
    /* potentially other proof-specific info for verifying this derived VC */
  }
}
```

3. The holder wraps `derived_vc` in a VP with a proof of type "some_holder_zkp_style_proof". This proof includes all of the necessary information to verify the VP and its derived VCs.

```js
{
  "@context": ["https://w3id.org/credentials/v1", "https://w3id.org/some-extension/v1"],
  "type": ["VerifiablePresentation"],
  "credential": [{
    "@context": ["https://w3id.org/credentials/v1", "https://w3id.org/some-extension/v1"],
    "type": ["VerifiableCredential", "SomeSpecificCredential"],
    "issuer": "...",
    "claim": {
      "id": "did:example:1234",
      // note: only revealing propertyA
      "propertyA": "valueA"
    },
    "proof": {
      "type": "DerivedCredentialProof",
      "presentationProof": "id_of_vp_proof",
      /* potentially other proof-specific info for verifying this derived VC */
    }
  },
  "proof": {
    "id": "id_of_vp_proof",
    "type": "some_holder_zkp_style_proof",
    /* other proof-specific info for verifying this VP and the derived VCs */
}
```

4. Using all of the proof information in the VP and its VCs, a verifier will take the information from the VC data model and construct whatever data structures (such as fixed arrays of properties, etc) that are required to run proof-specific verification code.

This approach allows proof-specific verifiers to do what they need to do to ensure data is verified before handing it off to other application-specific code that only cares about the VC data model, not about how the VC was verified. It enables us to establish appropriate layers for handling data, design reusable software components, and gives us a pathway for adding whatever other kinds of ZKP-style proofs we need to in the system as the ecosystem evolves, without having to change the core data model.

Furthermore, I would also recommend that we don't expose all of the above information as fields in the data model within the proof. I don't think that's necessarily helpful -- and could instead be more likely harmful. It would be better to encapsulate all of the above into some kind of COSE-style container that is expressed as a single base58-encoded signature value. The verifiers can decode that and break it apart into its constituent parts internally.

**Comment by mikelodder7** [comment]
I will take a look at COSE. I don't foresee any problems from a high level as long as the libraries are implemented correctly.

**Comment by brentzundel** [comment]
Result from W3C TPAC:

- [ ] Need small changes to PR-217 and review (modify presentation image)
- [ ] Add examples and text to data model that highlights zkp and privacy issues.
- [ ] version of test suite working

**Comment by stonematt** [comment]
@msporny and @mikelodder7 , as a review blocker, we need this done before we ask for wide review.  I can't tell if these referenced PRs complete this issue or not?  Can you review and help dispose of this issue.

thanks.

**Comment by stonematt** [comment]
@brentzundel says we can remove "review blocker" tag.

**Comment by msporny** [comment]
Both @dlongley and @msporny have performed a review on the proposal from Sovrin/Evernym and have suggested minor changes. At this point, we're confident that the VC Data Model can support Sovrin and Evernyms needs wrt. ZKPs. Closing this issue, please re-open if you disagree.

**Comment by brentzundel** [comment]
I didn't get a chance until this morning to look at this. I did see Manu's email that he was planning to close this, but was not able to respond.
I am confident that the data model can support Sovrin ZKPs, but we still need to determine if the test suite will work. Not sure where that will be tracked if not here, or how that fits with the schedule for releasing a CR.

**Comment by msporny** [comment]
> I am confident that the data model can support Sovrin ZKPs

Good, as that's the only thing we need to start the process of entering CR.

> we still need to determine if the test suite will work.

I'm confident that it will, and that's what CR is for. We'll figure that out during CR. It would have been nice to have figured it out before CR... but during CR would be fine as well. We definitely need to have it figured out before exiting CR.
