### ISSUE TITLE
Should terms like ageOver be in the context?

### ISSUE THREAD

**Issue by cwebber** [w3c/vc-data-model#245]
(See also #231.)

We currently have examples using such terms as `ageOver` which are not currently in the context.  We could argue either way whether they they should or should not be:

* Maybe the credentials context should be minimal enough just include the base functionality.  In that case, we should define another context for common terms, or at least include some `example.org` type imaginary context in such examples in the spec to make clear that these are not defined terms.
* Alternately maybe we know everyone is going to use these a lot, so it's worth including some of the most common ones in the spec.

(While working on the test suite I converted the suite over to the latest context and discovered these terms were not in there, so currently I have "dumped them" back in, even though this does not reflect the current context, so I'll need to update that once we make a decision.)

**Comment by msporny** [comment]
> Maybe the credentials context should be minimal enough just include the base functionality.

Yes, let's do this.

> In that case, we should define another context for common terms, or at least include some example.org type imaginary context in such examples in the spec to make clear that these are not defined terms.

The WG should publish an "examples" context (https://www.w3.org/2018/vc-examples/v1), so all of the examples actually do work.

**Comment by msporny** [comment]
> Alternately maybe we know everyone is going to use these a lot, so it's worth including some of the most common ones in the spec.

If we do this, we will get it wrong. The set of use cases is just too broad for us to do a good job with king making "common terms". I suggest we defer to schema.org for "common terms". /cc @danbri

**Comment by David-Chadwick** [comment]
Perhaps we should go even further, as @msporny asked me to do when creating examples with addresses in them, and that is to use schema.org terms in all our examples as far as possible, instead of inventing similar terms that dont quite mesh with schema.org ones. So instead of having an example containing the address property, with address in the examples context, instead we use the address, streetAddress, postalCode etc properties from schema.org and add that to the context.
See example 14 in the current DM doc as an example of this approach.

**Comment by burnburn** [comment]
From TPAC-2018:
- [ ] Create an example JSON-LD context for the spec.  Use example.{org,com} for this.
- [ ] Document that the context should not be used for anything other than examples
