### ISSUE TITLE
An alternate approach to expressing JSON formulations with VC

### ISSUE THREAD

**Issue by jtibbetts** [w3c/vc-data-model#27]
In at least two parts of the Data Model document there are sections which demonstrate using JSON formulations vs JSON-LD formulations.  That is, section 4.1.1 "Expressing an Identity Profile in JSON" vs section 4.2.1 "Expressing an Identity Profile in JSON-LD".  There are parallel sections 4.1.2 and 4.2.2 dealing with Entity Credentials.  In each case the difference is minor--the JSON version documents the various type assignments, then the JSON-LD says something like "just like the JSON except there is an additional @context value".

Do we really need this parallelism?  Why not just have a JSON section that gives the full description (include the @context)?  Many newbies don't realize that JSON-LD is still pure JSON and adds no syntax to JSON whatsoever.  (In other words, pure JSON parsers work fine on it).

We could still say something to the effect that the JSON boiler-plate is carefully crafted so that folks with specific needs can use it in its JSON-LD.  Perhaps in an appendix we could give a further deep dive on what it means to use true linked data concepts and tools.

Our experience is that 80% of standards folks don't need the full power of JSON-LD.  They're willing to follow a templated approach.  Application coders can use the JSON tools they're familiar with in accompaniment to specialized libraries to do stuff like signing.  

The 20% that do need / use / appreciate JSON-LD are those that 1) create the libraries, 2) define the basic templates for a particular set of claims, 3) need more exotic transformations that are provided by JSON-LD libraries or 4) just love the linked data stuff like the true nerds among us.

Once people get comfortable using the JSON level stuff it's much easier to add the extra concepts as they need them.

Net-net: lead with the JSON and soft-pedal the -LD until it's needed and wanted.

**Comment by cwebber** [comment]
We talked more or less about this on the call today.  The above isn't too far off from what was said on the call... while there were a variety of points raised, most seemed to converge on "we don't want people overwhelmed with the -LD side of things if all they're familiar with is JSON, but we also don't want to drop the -LD".

One option discussed is how ActivityStreams, ActivityPub, and Web Annotations to a lesser extent have taken the "this can be understood as just JSON" approach, and at least as in the former two you can pass in an implied context so that even more naively written JSON can be read as JSON-LD.  Maybe mentioning how to apply the context can happen later in the document, or as more of a side-note earlier, and have a section at the end explaining how to read it as JSON-LD, as well as some other formats.

**Comment by BigBlueHat** [comment]
Just said similar things over at https://github.com/w3c/vc-data-model/issues/23#issuecomment-308158783

**Comment by msporny** [comment]
I think we more or less do what the original issue raised said to do. Lead with JSON, soft pedal JSON-LD (although probably not as much as you may have wanted us to @jtibbetts, but only because people wanted to see full JSON-LD examples):

https://github.com/w3c/vc-data-model/blob/700263aca114f2d06a64762d2502e39686d409e5/index.html#L973-L980

There is still a bit of repetition, but I don't quite know what to do about that.

I'm closing this issue. Please re-open it or raise a new issue with more specific requests if you don't agree.
