### ISSUE TITLE
Is the WebIDL expression necessary?

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#4]
Do we need to specify the WebIDL expression of Verifiable Claims in the same document? Should it be in a separate document? It feels pretty heavy-weight in the current document.

**Comment by dlongley** [comment]
I vote separate document.

**Comment by jtibbetts** [comment]
+1 on separate document.

But related question: I don't see that WebIDL has the representational horsepower to construct a graph.  So how does a LinkedDataSignature2015 get generated for it?

**Comment by burnburn** [comment]
Why should it be in a separate document?  I thought we wanted to show that WebIDL was a valid syntax.

**Comment by msporny** [comment]
@burnburn Reasons that it might make more sense to have it in a separate document:

1. WebIDL is for the browsers, primarily, therefore the WebIDL should be in a "Browser API" spec (this is 1-2 years down the road, btw).
2. There may be many other supported syntaxes, for example, we've successfully converted the data model to YAML and XML, and we probably wouldn't put those in the data model spec.
3. We may want to focus on the most likely serialization and then point to other serialization specs if it makes sense to do so.
4. WebIDL isn't really a syntax, right? It's more like a way of expressing a programming data model.

**Comment by burnburn** [comment]
@msporny Reason 1 makes sense, since we are particularly interested in making clear that no browser support or modifications are required for this first effort.
Reason 2 is circular, since you are assuming that those would not go into the data model spec without discussion to make that decision.  Personally I don't believe they need go in, but others might disagree.
Reason 3 I agree with.  However, whether or not WebIDL belongs depends on whether it will be "one of the most likely" syntaxes.  Based on reason 1, probably not.
Reason 4 I disagree with.  WebIDL is a fairly concrete syntax with defined implementation behavior.  If your statement were true, then would could just agree to define our data model in WebIDL and be done.

I am not arguing for WebIDL to remain.  I merely want the reasons for removing it to be clear so we can begin developing our criteria for why certain syntaxes will go into the document and others won't.

**Comment by ottonomy** [comment]
I support having one syntax in all the examples in the spec document (JSON-LD would be my preference) but being very clear in the language that multiple syntaxes are possible and providing examples in other syntaxes as an appendix or other related resource.

**Comment by msporny** [comment]
@burnburn the WebIDL has been commented out in the spec (but not removed). Should we close this issue and move the WebIDL to its own spec? Granted, most of the WebIDL is now out of date (as the data model has shifted slightly and will probably continue to shift over time.

**Comment by burnburn** [comment]
Just remove it.  We can always pull it from history if needed.

**Comment by msporny** [comment]
Ok, will do. I'll submit a new PR for that.

**Comment by msporny** [comment]
The spec no longer includes WebIDL and there are no plans to include it for 1.0. Closing this issue as the group seems to have reached consensus on this. We can always add WebIDL back in to the spec (or create a separate spec w/ WebIDL definitions).
