### ISSUE TITLE
Non-agreed change in conformance language

### ISSUE THREAD

**Issue by burnburn** [w3c/vc-data-model#413]
PR #397, which I wrote, was modified by @msporny beyond what I agreed with, then merged.

You added back in the definition of a _conforming processor_, which is acceptable if you do not then define additional processing beyond the statically-verifiable constraints in the document.

Unfortunately, that appears to be what you did.  The language I believe should be removed is "and also enforces all relevant normative statements in the § 9. Verification section of this document when performing verification".

If the statements in that section apply to a document, regardless of when that document is "processed", then they belong as document conformance statements referenced in the _conforming document_ text.  Otherwise, they don't belong at all.  It is the "when performing verification" that concerns me.  Either the statements in section 9 must apply, independent of when checked, in order for the document itself to be conforming, or they are statements about the processor and DO NOT belong in our doc.

**Comment by msporny** [comment]
> You added back in the definition of a _conforming processor_, which is acceptable if you do not then define additional processing beyond the statically-verifiable constraints in the document.

I think the goal was that there would be no additional processing necessary beyond the statically-verifiable constrains in the document. I think the challenge may be that we have old language that does do that, so that language would need to change.

The intent was to define a _conforming processor_ as something that generates and consumes valid documents. We would draw the line at market vertical specific stuff that would use data outside of the conforming document to make a decision.

> Unfortunately, that appears to be what you did. The language I believe should be removed is "and also enforces all relevant normative statements in the § 9. Verification section of this document when performing verification".

Well, that's the problem. We have a very large section that has a lot of normative language that we must now either:

1. Mark the entire section as non-normative (which would probably create a ton of push back).
2. Hand wave over somehow and say that is normative, but for what? (my assertion is that it's normative for a _conforming processor_)
3. Remove the section entirely (it's a very large section) and move the normative statements into the rest of the text.
4. Reconfigure so that it talks about document conformance and the steps a _conforming processor_ MUST take to ensure it is dealing with a conforming document.

I'm leaning toward item 4 above, but clearly this is going to need some discussion.

> If the statements in that section apply to a document, regardless of when that document is "processed", then they belong as document conformance statements referenced in the _conforming document_ text. Otherwise, they don't belong at all. It is the "when performing verification" that concerns me. Either the statements in section 9 must apply, independent of when checked, in order for the document itself to be conforming, or they are statements about the processor and DO NOT belong in our doc.

There is a middle ground, which is what I was attempting to suggest... that a conforming document processor is one that processes documents according to the document conformance assertions in the specification.

**Comment by stonematt** [comment]
@burnburn (tickler)

**Comment by burnburn** [comment]
@msporny has modified text in spec, I need to review.

**Comment by brentzundel** [comment]
Decision from F2F Barcelona:
- [ ] @burnburn will review data model text and close

**Comment by msporny** [comment]
Tagging @rhiaro and @ken_ebert to review these non-normative changes after they go in.

**Comment by burnburn** [comment]
I reviewed the changes and reported on 12 March 2019 that there are still normative statements about processors in the conformance section and multiple normative statements in section 7.  Once those are fixed (which @msporny volunteered to do) I will sign off.

**Comment by msporny** [comment]
I've refactored the spec in https://github.com/w3c/vc-data-model/commit/cd4d5fc39a94ac7d0e9ed49bab11f12fbb76629b in the following way:

* Removed duplicated conformance statements that are expressed earlier in the specification. Things like "you MUST express the document in a valid syntax", which is clearly stated earlier in the document.
* Removed conformance statements related to what issuers/holders/verifiers MUST/SHOULD/MAY do and reworded to "are expected to". This made the entirely of the "Verification" section non-normative (as expected).
* Renamed the "Verification" section to "Validation", because that's really what that section was about. Noted that the spec doesn't make any normative statements about validation, but expressed how the ecosystem is expected to operate.
* Moved the "Validation" section to an appendix, as it's purely informative now.

I believe that doing all of these things address @burnburn's concerns. I'm closing this issue, please re-open if there are still concerns (or submit a PR to fix the concerns).
