### ISSUE TITLE
Sorting out @contexts

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#429]
First I am not able to retrieve any of the context definitions. The URLs fail.
Secondly we should ensure that all the contexts, when published, match the examples in the specification. Here is one that appears not to.

In the Extensibility section, Example 13 says this new type of VC is "CustomExt12" but what or how is this type linked to the @context specification, since the @context definition does not contain this type. In other words, how does a verifier know, when reading this new type of credential, that it will contain referenceNumber and favouriteFood properties? Surely the @context should could the definition of "CustomExt12"

**Comment by BigBlueHat** [comment]
The `https://www.w3.org/2018/credentials/v1` URL will (at publication time at the very latest) resolve to the JSON-LD context defined by the final data model spec. You can read more here:
https://www.w3.org/TR/verifiable-claims-data-model/#contexts

The `example.com` URLs (which represent example extension) won't ever resolve to anything--by design. 😃 They are examples, and not meant to be used in anything but examples.

Consequently, [Example 13](https://w3c.github.io/vc-data-model/#example-13-a-verifiable-credential-with-a-custom-extension) includes a reference to `https://example.com/contexts/mycontext.jsonld` as the example extension. Per the text just prior to that example, that extension context URL would resolve to [Example 12](https://w3c.github.io/vc-data-model/#example-12-a-json-ld-context) as it's context.

If someone were to replicate that example specifically, they would need to store the [example 12](https://w3c.github.io/vc-data-model/#example-12-a-json-ld-context) context file at a URL, and put the URL they stored that file at into the [example 13](https://w3c.github.io/vc-data-model/#example-13-a-verifiable-credential-with-a-custom-extension) credential data document. 

The end result would be an extended credential document containing the extensions referenced in the [example 12](https://w3c.github.io/vc-data-model/#example-12-a-json-ld-context) context file.

> how does a verifier know, when reading this new type of credential, that it will contain referenceNumber and favouriteFood properties?

The verifier knows (or rather learns) the extension terms by dereferencing the extension URL. Once dereferenced, the verifier can read that `referenceNumber` and `favouriteFood` terms are defined in that [example 12](https://w3c.github.io/vc-data-model/#example-12-a-json-ld-context) context file.

Hope that clarifies it a bit!

**Comment by brentzundel** [comment]
Decision from F2F in Barcelona:
We should not use schema.org
we should not have an embedded context. This will make the examples too complicated.
- [ ] @msporny will submit a PR that fixes the definition of '@context' in the data model to support objects.
- [ ] @chaals will allocate and publish the JSON-LD context used for examples.

**Comment by jonnycrunch** [comment]
This could be related to the MIME type discussion. see: https://github.com/w3c/vc-data-model/issues/421#issuecomment-470582105

**Comment by msporny** [comment]
The data model now supports objects when associated with the @context property (via https://github.com/w3c/vc-data-model/commit/4dab1345c5ac3d71aedea9f6e2f0a5c0c0d18f61). Thanks to @jonnycrunch for catching that bug in the spec.

The examples JSON-LD Context will be published at:

https://www.w3.org/2018/credentials/examples/v1

and will contain the following content (which may change during CR based on implementer feedback):

https://github.com/w3c/vc-data-model/blob/gh-pages/contexts/credentials/examples/v1

This means that all examples in the spec will actually work when copy-paste dumped into a JSON-LD processor, such as the [JSON-LD Playground](https://json-ld.org/playground/).

This also means that @chaals now owes me a beer for finishing his action item. :P
