### ISSUE TITLE
Multiple proofs

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#430]
Make clear in the Proofs section that multiple proof properties can be present. Change

For a credential or presentation to be verifiable, the following property MUST be present: 

to

For a credential or presentation to be verifiable, at least one instance of the following property MUST be present:

**Comment by dlongley** [comment]
Yes, this was just an oversight -- I mentioned to Manu the other day, he was going to fix up once he pulled in the other changes to the proof description section.

**Comment by brentzundel** [comment]
I want to make sure I'm understanding you correctly @David-Chadwick. Are you saying that a credential or presentation cannot be verified without the verifier knowing whom it was issued to, and the only way to do that is by requiring the "to" property? 
Because if that is what you are saying, that is not the case for Sovrin credentials. The prover is able to prove to the verifier that the credential was issued to them without revealing whom it was issued to.

**Comment by dlongley** [comment]
@brentzundel,

I thought @David-Chadwick was just saying that we need to accept both `"proof": {...}` and `"proof": [{...}, {...}]` so you can have more than one proof on a VC. Nothing more than that.

**Comment by brentzundel** [comment]
gotcha, thanks

**Comment by David-Chadwick** [comment]
@brentzundel I think your comment is being addressed to a different issue than this one. 
This issue is simply pointing out that the current text implies that only a single proof must be present, whereas in other areas of the spec it says that multiple proofs may be present. This issue is requesting an alignment of the texts

**Comment by brentzundel** [comment]
Yeah, this is what happens when I try to read and respond to email on my
phone.

**Comment by brentzundel** [comment]
Decision from F2F Barcelona:
This is an editorial issue. @msporny will continue to lead it.
