### ISSUE TITLE
Please provide citation to 0xcert

### ISSUE THREAD

**Issue by fulldecent** [w3c/vc-data-model#450]
Hello, thank you for publishing this document, I'm happy to follow along and see where it leads.

It appears that certain concepts in this paper are derived directly from the 0xcert white paper and/or technical paper (from 0xcert). This includes exposing partial information inside a cryptographically secure claim.

Please provide the due citation by referencing 0xcert and the authors of the whitepaper/techpaper, which are Kristijan Sedlak, Jure Zih, Mitja Pirc, Urban Osvald.

**Comment by brentzundel** [comment]
As the author of most of the sections of the data model that deal with zero-knowledge proofs, I can assure you that no part of this paper is derived from 0xcert. I have never heard of 0xcert before this moment, but look forward to learning more about you, due to the potential similarities in our principles.

I am a strong proponent of individual privacy and work closely with a number of others who are trying to build the foundational elements of self-sovereign identity. The verifiable credentials data model is one of these elements. My efforts with the data model have focused primarily on trying to ensure that it will be compatible with zero-knowledge proof systems such as selective disclosure of claim data.

My background with selective disclosure comes from Camenisch and Lysyanskaya's anonymous credentials as they have been implemented as part of the Hyperledger Indy project. Though all of the concepts in the paper related to zkp and selective disclosure are derived from that source, the data model attempts to be general enough in this area to support multiple zero-knowledge proof systems.
 
It is thrilling to meet another group that seeks to improve the privacy-respecting attributes of credential exchange. Yours is the third scheme I have been introduced to that supports exposing partial information inside a cryptographically secure claim, and I'm sure there are more out there.

In my opinion, there more we work together to support zero-knowledge proofs and the principles of minimal disclosure, including selective disclosure, the better and healthier will be the outlook for personal privacy.

**Comment by fulldecent** [comment]
Pinging the people mentioned @xpepermint @jurezih

**Comment by xpepermint** [comment]
Nice discussion and thank you @fulldecent for opening this issue.

I'm aware of this proposal and I think it's great to see others recognize the same benefit! We are interested to reconsider the current algorithm and to somehow align it with this standard.

@brentzundel would you help us upgrade the algorithm for the https://github.com/0xcert/framework?

**Comment by brentzundel** [comment]
@xpepermint I will certainly help where I can.

**Comment by brentzundel** [comment]
This is an editorial change, recommend we discuss this in the WG.

**Comment by brentzundel** [comment]
@fulldecent @xpepermint @uosvald
If you are interested in community efforts around digital identity, data privacy, SSI, etc. you might like to check out [the CCG](https://w3c-ccg.github.io/) and [RWoT](https://www.weboftrust.info/index.html).

**Comment by brentzundel** [comment]
This was discussed in the VCWG meeting on 19 March, 2019. The group determined that the responses here were adequate and this issue should be closed.

**Comment by burnburn** [comment]
Closing.
