### ISSUE TITLE
Refreshing questions

### ISSUE THREAD

**Issue by ken-ebert** [w3c/vc-data-model#458]
In section 5.5 Refreshing, there are two topics I have trouble understanding:

1.      "The issuer can include the refresh service as an element inside the verifiable credential if it is intended for either the verifier or the holder (or both), or inside the verifiable presentation if it is intended for the holder only."

It is my understanding that the holder is the one who generates a verifiable presentation, therefore an issuer would not be able to include a refresh service inside a verifiable presentation, only the holder would be able to do so.

2.      "Including the refresh reference inside the verifiable presentation enables the holder to refresh the credential details before creating a presentation to share with a verifier, while including the refresh reference inside the verifiable credential enables both the holder and the verifier to perform future updates of the credential."

Since the issuer is the one who creates and signs the credential, is it more correct to say "enables the holder to request that the issuer refresh the credential details..."

If a verifier requests an update to the credential, how does the verifier receive the updated credential, since issuers only know the identity of the holder and don't know the identity of a verifier. Or how is the holder notified to produce a new presentation based on the updated credential requested by a verifier?

**Comment by David-Chadwick** [comment]
The issuer may generate a VP in order to send the VC to the holder, so would include refresh info in this VP that is specifically for the holder. Better wording might be

 The issuer can include the refresh service as an element inside the verifiable credential if it is intended for either the verifier or the holder (or both), or inside the verifiable presentation if it is intended for the holder only. In the latter case, this enables the holder to refresh the verifiable credential before creating a verifiable presentation to share with a verifier. In the former case, including the refresh reference inside the verifiable credential enables both the holder and the verifier to perform future updates of the credential.

**Comment by David-Chadwick** [comment]
This has now been addressed in PR#501

**Comment by David-Chadwick** [comment]
Revised text is now in PR#544

**Comment by msporny** [comment]
PR #544 has been merged. Are there further non-normative changes you would like to make to the specification text @ken-ebert?

**Comment by msporny** [comment]
Ping @ken-ebert -- are you happy with the changes made in PR #544 as a result of the issue you raised?

**Comment by stonematt** [comment]
From VCWG call on April 30, 2019: 
RESOLUTION: Issue #458 is addressed by PR #544, which makes non-normative changes noting when it is and is not appropriate to use the refresh service. The PR has been approved by multiple parties and has been merged. Issue #458 should be closed.
