### ISSUE TITLE
Does 'subject' relate to credentials or to claims?

### ISSUE THREAD

**Issue by RieksJ** [w3c/vc-data-model#464]
The definition of credential says that it is a set of claims about one or more subjects. Also, section 1 mentions "Information related to the subject of _**the**_ credential", suggesting that there is precisely one. 

'Subject' is defined as 'An entity about which claims are made.', and - as mentioned already in #106 - it is not self-evident that a credential is issued to an entity that is also the subject in any of the claims. Therefore, we need another term to refer to the (single) entity to which a credential is issued. Note that the term 'holder' may not qualify, as it is defined as a _role_ that an entity can perform by possessing VCs, rather than that it refers to the entity itself. 

Whatever term we may decide on, this issue requests for using that term at any place where the entity to which (a) credential(s) are issued is being referred.

**Comment by brentzundel** [comment]
The 'holder' is an entity that possesses a VC. When an issuer issues a VC, the entity to which the credential is issued is a holder. This does not prohibit the concept that the holder may pass the VC to another holder, nor does it imply that the holder is one of the subjects of the credential. The subject(s) of the credential are the entities about whom claims are made. 

The reason 'holder' is defined as a role that an entity can perform, rather than the entity itself, is that the ecosystem is deliberately fluid. An entity that is a 'holder' may also be an 'issuer' and a 'verifier.'

Perhaps the sections that talk about the 'holder' as an entity could be re-worded to make it more clear that 'holder' is a role the entity is performing, but I think that is necessary.

**Comment by David-Chadwick** [comment]
We are pretty clear that there can be multiple subjects in a credential. SO if there is any text that tends to fuzzy this, like the one you highlighted, then the solution is simply to fix these occurrences, e.g.
"Information related to the subject(s) of the credential",

**Comment by RieksJ** [comment]
I agree with fixing occurances of text that fuzzy stuff that should be clear. However, the issue I tried (and apparently failed) to bring up isn't fixed by replacing "Information related to the subject of the credential" with "Information rlated to the subject(s) of the credential". The problem is with the meaning of the phrase "the subject of the credential". There is no such thing. You can have the subject of a claim, and many claims in a credential, but "the subject of the credential" is simply undefined. 

One might suggest to replacing it with "the holder of the credential". While this is better already, it still doesn't do the whole trick, as 'holder' is defined as a role that someone may perform, and as is obvious from theater (but we tend to forget that if we like the play that is performed), a role is not the same thing as the actor playing it.

**Comment by David-Chadwick** [comment]
@RieksJ replacing "subject of the credential" with "holder of the credential", certainly does not cut it because they are not conceptually the same entity. The holder is the entity that currently holds the VC, and may or may not be one of the subjects. The holder may change. However a subject of the VC never changes, regardless of who holds the VC.
So replacing "the subject of the credential" with either "a subject of the credential" or "the subject(s) of the credential", depending upon context, should cut it.

**Comment by David-Chadwick** [comment]
PR#512 fixes this issue

**Comment by msporny** [comment]
PR #512 has had multiple reviews and has been merged. The next step is to see if the WG agrees with these changes.

**Comment by stonematt** [comment]
Resolved on VCWG call 4/16/2019.
RESOLVED: Issue #464 is addressed by PR #512, which makes non-normative changes related to the subject of the credential as requested by the reviewer. The PR has been approved by multiple parties and has been merged. Issue #464 should be closed.

Plan to close in 7days
