### ISSUE TITLE
Faulty description of the issuer role

### ISSUE THREAD

**Issue by RieksJ** [w3c/vc-data-model#466]
Section 1.2, specifies the role of issuer as: "A role an entity might perform by creating a verifiable credential, associating it with a specific subject, and transmitting it to a holder."

This text is wrong, since a (verifiable) credential is (amongst other things) a set of claims that may pertain to multiple subjects, none of which would need to represent the holder. I suggest to strike out the part "associating it with a specific subject".

**Comment by chaals** [comment]
The text says "...might perform..." - i.e. it is an example. Furthermore the section is non-normative. I suggest closing this issue with no further action.

**Comment by RieksJ** [comment]
@chaals: I object to your suggestion because (to me) a standard should not contain any texts that are obviously inconsistent.

**Comment by chaals** [comment]
I agree that there should not be obviously inconsistent texts. However, there aren't here. An issuer might associate a credential with a specific subject. In many examples, like driver's licences, degrees, and so on, that is exactly what happens.

It could help clarify the text to put the words "for example" into the sentence.

Is it necessary to add another example showing multiple subjects? I would argue not here, since this describes the role of the issuer, and subjects are dealt with elsewhere.

(In general I am opposed to trying to provide examples of every possibility - that's the role of a primer or tutorial, not a spec. But sufficient examples to convey the range of options do help - see my half-done pull request #469 as a case in point).

**Comment by RieksJ** [comment]
This is not a question of examples, it is a question of wrong texts.

I object to your argument "_The text says "...might perform..." - i.e. it is an example. Furthermore the section is non-normative. I suggest closing this issue with no further action._", because it applies equally well apply to a definition in which the word 'subject' were to be replaced by any other term defined in the text, e.g. Identity Provider, Verifier, Credential, etc., some of which are obviously not what you would want in a standard.

But perhaps there is a better way to state the case. I would say that an entity performs the role of issuer **if and only if** it creates a verifiable credential and transmits it to a holder. If that is what we really mean, the word 'might' should be removed from the definition (and by consequence also from every other role-definition).

**Comment by David-Chadwick** [comment]
I suggest that we replace "might perform" by "performs" for verifier and issuer, and "can perform" by "performs" for holder. But I also suggest that we only enact the PR after the CR has been published, as this is a minor editorial correction that should not cause a delay to the publishing of the CR

**Comment by stonematt** [comment]
+1 to @David-Chadwick in this case.  While I'm not sure we have to agree on whether it's correct or not as it stands, we could tweak it for clarity.  

We will definitely wait until after the  CR is approved.

**Comment by msporny** [comment]
The PR had multiple positive reviews and has now been merged. The next step is to get approval from the WG and close the issue.

**Comment by stonematt** [comment]
Resolved on VCWG call 4/16/2019.
RESOLVED: Issue #466 is addressed by PR #477, which makes minor non-normative changes by changing "might perform" to "performs" for certain roles as requested by the reviewer. The PR has been approved by multiple parties and has been merged. Issue #466 should be closed.

Plan to close in 7days
