### ISSUE TITLE
Implied lack of governance Requirement in issuer/holder/verifier

### ISSUE THREAD

**Issue by mavarley** [w3c/vc-data-model#471]
Section 1.3:
_“Acting as issuer, holder, or verifier requires neither registration nor approval by any authority.”_

Although from a technology perspective this may be true, ecosystems may very much require approval from an authority in order to accept these parties (practically speaking). I think it should just be called out as “out-of-scope” for this spec. (consistent with  _5.1 "Not sufficient on its own for steps 1, 7, and 8 because an authorization framework is needed as well."_)

**Comment by jandrieu** [comment]
Respectfully, you've just described a requirement for your ecosystems, not for the technology.

**Comment by mavarley** [comment]
Agreed - but the language in this section of the doc implies more than technology - the suggestion is to add the "ecosystem (or trust framework, etc...) requirements are out of scope". It's already stated later in the document.

Hmm... unless you think adding the above clarification makes the requirement too 'weak' - like saying "anyone is allowed to write software to meet these specs...". What is the intention of this requirement?

**Comment by mavarley** [comment]
Actually - I reflected a bit more on this, and maybe the requirement around trust frameworks is not entirely "out of scope" - because (I think) one important aspect of this (and other) spec(s) is there doesn't need to be a cohesive (authoritative) trust framework for entities to trust each other - if that is the intention of this requirement, maybe the clarification is "trust may be established on an entity by entity basis" - meaning each entity is free to choose who it 'accepts'. Is that the intention of the requirement?

**Comment by jandrieu** [comment]
@mavarley 
> there doesn't need to be a cohesive (authoritative) trust framework for entities to trust each other 

and
> each entity is free to choose who it 'accepts'

That is precisely correct. It is a slightly different problem space if we are willing to allow issuers / verifiers to mandate who can participate. This spec is intentionally designed to work with any issuer, any verifier, any holder. The trust involved--whether by formal trust framework or just selected brands--is entirely bilateral between parties. Issuer trusts the holder is the intended holder (through whatever means they use for authentication) and the holder trusts the issuer to not lie in the credential. The verifier understandably has trust issues with the holder (because people will fake credentials if it gets them something of value), yet the holder has the opportunity to not disclose the credential to any given potential verifier, so there is a trust by the holder that the verifier is an appropriate recipient (a stark contrast to ad networks where the user has no choice about who gets the analysis of their likely buying intention). Finally, while verifiers may receive claims (in presentations) from any number of issuers, it's entirely up to the verifier to decide which claims are meritorious from which issuers. You might be fine with my seating preferences being self-asserted while requiring something stronger for my digital passport.

The point is that at the architectural level, the data can be anything and can go from anywhere to anywhere else. The business rules for interpreting that data, once the presentation is verified, are entirely up to the verifier.

**Comment by mavarley** [comment]
@jandrieu: completely support the model, and I think you nailed it language wise: "_The trust involved is entirely bilateral between parties_". This makes the current 'anti-requirement' into a clear requirement, while conveying the 'decentralized' architecture.

Consider this a +1 for the above wording being added for clarity, and thank-you!

**Comment by brentzundel** [comment]
@mavarley let me know if PR #507 addresses this issue.

**Comment by msporny** [comment]
PR #507 has been independently approved by multiple parties and is now merged. The next step is to see if the WG agrees with the change.

**Comment by stonematt** [comment]
Resolved on VCWG call 4/16/2019.
RESOLVED: Issue #471 is addressed by PR #507, which makes non-normative changes pointing out that trust is bilateral between issuers and verifiers as requested by the reviewer. The PR has been approved by multiple parties (including the reviewer), and has been merged. Issue #471 should be closed.

Plan to close in 7days
