### ISSUE TITLE
Terms of Use for credentials should not be at risk, but requires better purposes

### ISSUE THREAD

**Issue by RieksJ** [w3c/vc-data-model#479]
Section [5.6 Terms of Use](https://w3c.github.io/vc-data-model/CR/2019-03-26/#terms-of-use) specifies a way in which an issuer can specify terms of use policies under which it issued the credential. The examples that are given  are plausible yet theoretical, and there is a `FEATURE AT RISK` warning at the end of the section, because there might not be sufficient implementer support.

Here I would like to make the case that this feature is necessary from a market perspective, and call for the creation of an inventory that lists such market needs. This list would not only show the need for this feature, but also provide guidance to the further design thereof. 

Here are two examples:

1. I forgot where this came from, but I remember someone voicing the concern that when everyone has wallets with loads of verfiable credentials, this may result in governments (and particularly the US government was mentioned) requiring you to provide them with the content of your wallet when you request an entry visa, thereby coercing you to give up your privacy.
2. In a chat I had recently had with people from the Dutch ministry of interior, it became clear that they are not going to issue verifiable credentials unless they can prevent citizens from supplying such credentials to e.g. Facebook, arguing that they not only need to facilitate their citizens, but also to protect them.

**Comment by ken-ebert** [comment]
I think that Terms of Use are at risk because of lack of implementer support. I am one who feels that they have not been specified in a way that can be cryptographically enforced and therefore will not implement them.

In this version of the specification, I think that they are ill-advised because they could mislead a participant in the verifiable credentials ecosystem to believe that terms of use are somehow binding, when in most cases they have fuzzy technological support. 

If refined and given teeth to enforce them, I could support terms of use.

**Comment by msporny** [comment]
Hey @RieksJ, what @ken-ebert said wrt "at risk" is correct. It is a W3C term of art that says that "if implementers choose not to implement the feature during the Candidate Recommendation phase, it will be removed."

Since you submitted the issue, we have put in further clarifications for the refreshService and termsOfUse properties, but not to the extent that @ken-ebert had requested.

I am also confused by your "call for the creation of an inventory that lists such market needs". I don't know what that would look like, could you please provide examples? We are under severe time pressures to get this specification done before the charter for the group runs out and without more guidance from you, I expect this issue will be closed w/ no changes to the specification.

Please provide concrete specification text that you would like added to the document.

**Comment by RieksJ** [comment]
Ok about how the process works - it is a practical way of doing things. Also, I agree with @ken-ebert that it should be further elaborated and 'be given teeth'. 

I'm good with removing 'Terms of Use' for credentials from this version of the document, provided it can be revived in a future version. Reviving it would then require that we show purpose and relevance for this feature. One example is the Dutch government that needs this as a means to protect her citizens against (possible/perceived) credential guzzling entities such as the US Government, but I would think there is more. Also we would need (technical) means to enforce this. This is one of the topics on the list of future research for the TNO SSI group, but perhaps there are other, more 'community aware' ways to help this forward. 

@msporny: you said the charter of the group runs out. What does that mean? Will the group cease to exist, or will it have a renewed/revised charter? What's this pressure?

**Comment by msporny** [comment]
> @msporny: you said the charter of the group runs out. What does that mean? Will the group cease to exist, or will it have a renewed/revised charter? What's this pressure?

When a charter for a W3C WG expires, all work stops. If the group didn't publish a final specification in this time frame, too bad, they lose the opportunity to do so and will almost certainly not be rechartered to do so (because they failed to do so the first time). So, if we don't finish, the entire spec is abandoned as a global standard... it's the ax above one's head that W3C Membership uses to make sure the group produces something.

At some point, we have to draw a line and say the specification is good enough (even though it's always imperfect). Yes, this section isn't good enough, but we're out of time and it's not clear how we would change it in the time we have to address your concerns.

The WG discussed this issue during the last call and it was not clear how we could resolve the issue to your satisfaction, @RieksJ ... therefore, I'm proposing a "no change and close". If you have concrete specification text you would like, please suggest it. If not, this issue will be closed in 7 days.

**Comment by RieksJ** [comment]
Sounds like this is the best thing that can be done at this point in time.

**Comment by burnburn** [comment]
PR merged, closing.
