### ISSUE TITLE
4.7 Proofs

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#486]
A JWT/CWT should be first class, that is making a JWT/CWT an embedded proof. There is no valid  Linked Data Signature specification (which would also require a C14N specification to serialize the JSON-LD, whereas JWT/CWT have well deployed implementations for proofs, requiring no C14N. 

Also I did not see any way to encrypt a structure in this specification, a JWT can be signed and encrypted, as claims may contain PII and thus may need to be protected so no PII data is exposed.

**Comment by brentzundel** [comment]
There are many ways to sign the data in a credential. The signature suite chosen by an implementer depends almost entirely on the protocol they have developed which makes use of the data model specified here. This group was prohibited by its charter to specify protocol, so the general rule we followed in designing the specification was to avoid prohibiting a signature type that an implementer may use in designing his protocol.

Two signature types are mentioned as examples in the data model as possible signature that may be chosen by an implementer. The examples provided that show one way in which JWTs may be used (by wrapping the entire credential) were submitted by @awoie who represents uPort in the working group. He provided examples that match the way that uPort intends to sign verifiable credentials using JWTs.

My questions to you:
- does the way the data model has been specified prohibit you from using it in your protocol? 
- If so, how specifically would you need the data model to change in order to support the signatures you would use?

In addressing your second point, perhaps we should address the possible desire of an entity to encrypt verifiable credentials as a means of not exposing PII in the privacy considerations section. I believe that an actual recommendation in the specification for how to encrypt a verifiable credential is outside of the scope of the working group charter.

**Comment by awoie** [comment]
@brentzundel @nadalin I agree that encryption is outside of the scope of the specification. There is also a reference in the JWT section. However, it is possible to use JWS first and then encrypt it using a JWE.

**Comment by nadalin** [comment]
@awoie Why is encryption out of scope as it can be a proof mechanism

**Comment by nadalin** [comment]
@brentzundel JWS does not require C14N, so this will rule out JSON-LD this the requirement that when using JWT no JSON-LD just base64 encoded JSON

**Comment by msporny** [comment]
@nadalin wrote:
> Why is encryption out of scope as it can be a proof mechanism

While encryption mechanisms prevent tampering, they also require you to share the symmetric key with the recipient (or do some sort of Diffie-Hellman key exchange) so that the receiver can decrypt the data. The Verifiable Credentials Data Model is interested in mechanisms that authenticate the issuer as well as mechanisms that detect tampering with the message. Encryption is typically something that is layered on top of the Verifiable Credentials Data Model and as such, isn't used as a proof mechanism.

More specifically, using TLS, JWE, or COSE is fine, expected, and perfectly compatible with the Verifiable Credentials Data Model secured with either JWS or LD-Proofs.

**Comment by msporny** [comment]
@nadalin wrote:
> JWS does not require C14N, so this will rule out JSON-LD

You don't have to canonicalize (C14N) JSON-LD to use JWS. You can stick JSON-LD in a JWT and JWS it, which is exactly what the spec currently does. Doing that does have drawbacks (which are the same ones that placing JSON data in a JWT has), but folks that use JWTs don't seem to care about those drawbacks so you should be just fine doing that.

**Comment by msporny** [comment]
@nadalin wrote:
> A JWT/CWT should be first class, that is making a JWT/CWT an embedded proof.

JWT is an external/enveloping proof format. It literally cannot be used as an embedded proof format w/o wholly duplicating the entire payload that it is attempting to protect. I would be very interested in a concrete example to the contrary.

**Comment by msporny** [comment]
@nadalin wrote:
> JWT/CWT have well deployed implementations for proofs, requiring no C14N.

Yes, the group has discussed this and supports the expression of the Verifiable Credentials Data Model using JWT/CWT.

**Comment by msporny** [comment]
@nadalin wrote:
> There is no valid Linked Data Signature specification (which would also require a C14N specification to serialize the JSON-LD

Linked Data Proof/Signature mechanisms have existed since 2011, gaining maturity over the years. That said, you are correct in that no W3C Recommendations exist to date. Since the majority of the WG participants are deploying this technology using LD-Proofs/Signatures, we will request that the group officially supports the creation of a W3C Working Group to create Recommendations for RDF Dataset Canonicalization, LD-Proofs, and LD-Signatures.

The benefits of using LD-Proofs over JWTs are documented here:

https://w3c.github.io/vc-imp-guide/#benefits-of-json-ld-and-ld-proofs

**Comment by nadalin** [comment]
@msporny there is no standard yet, you can't rely on these, there are standards for JSON, JWS/E/K which require no C14N. So unless the specification states a normative (a actual stamndard) way to do proofs this would have to all be non-normative. 

I have suggested that the s[specification allow the usage of existing JWT including the claims data model as valid "vc" and use JWS/E as the interoperable proof mechanism so this can be a normative section.

I don't understand the push back, you can always add the JSON-LD proof mechanisms in a level 2 document when they all are standardized

**Comment by David-Chadwick** [comment]
I have proposed a resolution of this in #498

**Comment by brentzundel** [comment]
Added PR #536 to address @nadalin's second point about protecting PII in a verifiable credential.

**Comment by stonematt** [comment]
VCWG Teleconference Resolution: https://www.w3.org/2019/04/09-vcwg-minutes.html#resolution03

RESOLUTION: JWTs are an external/enveloping digital signature format and cannot efficiently be embedded in data. Encrypting digitally signed (and proofed) expressions of the Verifiable Credentials Data Model are expected via the use of JWEs, COSE, TLS, and other encryption mechanisms and a fully supported by the Verifiable Credentials Data Model. Issue #486 should be closed after non-normative changes to the specification are made #536.

PR is merged, pending close.

**Comment by nadalin** [comment]
@stonematt If all you need is a what a JWS provides then that is fine and should be stated, if you need more than you will have to reference  a specification that can actually be implemented as specified and achieve interoperability. so don't agree with closure

**Comment by burnburn** [comment]
The outstanding request by @nadalin to mandate support by all implementations of the JWT format will be tracked by issue #634.  Closing.
