### ISSUE TITLE
4.7 Proofd

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#487]
How can there be interoperability if there is no standardized proof mechanism? Suggest that JWS become that standard proofing mechanism

**Comment by brentzundel** [comment]
I completely agree with the question of how there can be interoperability without a standardized proof mechanism. Unfortunately, this working group is prohibited by its charter to specify protocol. Standardizing the proof mechanism would be a protocol specification. We can only specify the data model. As far as how the data model may be **used**, we are limited to providing non-normative guidance.

The members of the working group are well aware of the limitations inherent in not being allowed to specify protocol. Long discussions have been held about the potential difficulties for true interoperability due to this limitation.

It is my sincere hope that a future working group be chartered to address this.

**Comment by brentzundel** [comment]
As this issue raises a concern that can only be addressed by specifying protocol, recommend we defer.

**Comment by David-Chadwick** [comment]
This issue should be closed because it is a repeat of #498, #489 and #490

**Comment by msporny** [comment]
Also note PR #539, which clarifies a number of items raised in this issue.

**Comment by msporny** [comment]
VCWG Teleconference Resolution: https://www.w3.org/2019/04/09-vcwg-minutes.html#resolution04

RESOLUTION: The specification is clear wrt. using JWT and JWS with the VC Data Model. The VCWG acknowledges that a W3C Recommendation for RDF Dataset Canonicalization, Linked Data Proofs, and Linked Data Signatures does not exist, and that the Verifiable Credentials Data Model specification, as well as a number of Linked Data Working Groups at W3C, would benefit from such a set of standards. The VCWG strongly recommends the creation of a W3C Working Group to create.

**Comment by msporny** [comment]
Close of this issue is waiting on PR #539 to be merged, which is only waiting on a few editorial changes at this point.

**Comment by nadalin** [comment]
@msporny It should also be noted that if using JSON then no C14N is needed and that JWS can be used, only when using JSON-LD are you limited

**Comment by burnburn** [comment]
The outstanding request by @nadalin to mandate support by all implementations of the JWT format will be tracked by issue #634.  Closing.
