### ISSUE TITLE
4.7 Proofs

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#489]
Suggest that this section be marked at risk if there is no interoperable proof mechanism since JSON-LD Signature is not a complete specification, would also suggest the removal of JSON-LD from the specification since this is not in a standards body

**Comment by brentzundel** [comment]
We are limited by our charter to specifying a data model. Specifying a particular proof mechanism is a protocol decision and therefore, unfortunately, out of scope, regardless of how beneficial that would be for interoperability.
The goal of the working group in specifying the data model was to make it as inclusive of different proof mechanisms as we felt it was possible to be.

**Comment by brentzundel** [comment]
@nadalin, this issue raised two suggestions:
1. "Suggest that this section be marked at risk if there is no interoperable proof mechanism since JSON-LD Signature is not a complete specification"
2. "suggest the removal of JSON-LD from the specification since this is not in a standards body"

These have been responded to:
1. "We are limited by our charter to specifying a data model. Specifying a particular proof mechanism is a protocol decision and therefore, unfortunately, out of scope, regardless of how beneficial that would be for interoperability."
2. "The goal of the working group in specifying the data model was to make it as inclusive of different proof mechanisms as we felt it was possible to be."

If there are any further points you would like to raise concerning this issue, please let us know.

I recommend discussing the second suggestion as a working group to determine if a PR should be raised. 

The first suggestion recommends specifying protocol, which is out of scope for our working group.

**Comment by nadalin** [comment]
@brentzundel You can't specify proofing w/o specifying a mechanism for interop, not how the W3C works. If you are fine with this being non-normative and not required that is fine but then you will never have verifiable claims/credentials which seems to be the goal here.

**Comment by msporny** [comment]
@nadalin wrote:
> would also suggest the removal of JSON-LD from the specification since this is not in a standards body

If by "this", you mean JSON-LD -- "this" is a W3C Recommendation -- https://www.w3.org/TR/json-ld/

**Comment by msporny** [comment]
> You can't specify proofing w/o specifying a mechanism for interop, not how the W3C works. 

It is perfectly reasonable to specify, in a data model specification, a data field whose purpose is to contain extensible proof mechanisms. The Verifiable Credentials Data Model specification has been designed by the Working Group to be proof mechanism agnostic and this is one of the mechanisms that was settled on by the Working Group.

With respect to whether this mechanisms works in practice, there have been implementations since 2011 that demonstrate (via working code) that this mechanism works with a variety of different cryptographic systems. One such implementation, which our organization uses is: https://github.com/digitalbazaar/jsonld-signatures

In any case, the WG has asserted multiple times that it's charter limits it to data model and not protocol and the test suite reflects that. The normative tests in the test suite are performed on the data model fields. There will be optional tests that test the interop on the cryptography, but again, the WG is not requiring those as they go outside of the data model and thus, our charter.

**Comment by nadalin** [comment]
@mspory There are no mechanisms defined in the specification that would allow interop, if there is no test suite then this has to be non-normative

**Comment by David-Chadwick** [comment]
this issue should be closed since it covers the same issue as #498

**Comment by stonematt** [comment]
VCWG Teleconference Resolution: https://www.w3.org/2019/04/09-vcwg-minutes.html#resolution07

RESOLUTION: The VCWG does not support the removal of JSON-LD from the specification. For Section 4.7: Proofs, interoperability is defined as at least two implementations implementing the normative statements in the section. Specifically, that the data model specifies a mechanism to express an embedded proof and the type of proof. The VCWG does not believe that it is appropriate to make this section non-normative. Issue #496 should be closed with no change to the
... specification.

Plan to close in 7 days.

**Comment by nadalin** [comment]
@stonematt Disagree as someone reading specification needs to be able to implement a proof mechanism that is fully described as a normative reference in the VC specification so that interop can be achieved. So disagree with closing

**Comment by burnburn** [comment]
The outstanding request by @nadalin to mandate support by all implementations of the JWT format will be tracked by issue #634.

The outstanding concern by @nadalin regarding JSON-LD will be tracked by issue #633.  Closing.
