### ISSUE TITLE
5.2 Trust Model

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#490]
I suggest that this section be marked at risk since there is no standard embedded proof mechanism to obtain interoperability on

**Comment by brentzundel** [comment]
As mentioned elsewhere, the determination of which features are marked at risk was made based on feedback from parties who plan to implement the data model. This feature has enough implementation support, therefore it is not at risk.
Specifying a standard embedded proof mechanism is beyond the scope of this working group's charter, as we are limited to specifying a data model. It is our hope that implementers work together to make their implementations interoperable, and my particular hope that a future working group be chartered to address the interoperability concerns caused by a there being no specification of a common protocol for using verifiable credentials.

**Comment by brentzundel** [comment]
@nadalin, this issue raised a single point:
1. "there is no standard embedded proof mechanism to obtain interoperability on"

this point was addressed:
1. "Specifying a standard embedded proof mechanism is beyond the scope of this working group's charter, as we are limited to specifying a data model."

You made a suggestion:
1. "this section be marked at risk"

which was also addressed:
1. " the determination of which features are marked at risk was made based on feedback from parties who plan to implement the data model. This feature has enough implementation support, therefore it is not at risk."

If there are further points you wish to make regarding this issue, we look forward to addressing them.

**Comment by nadalin** [comment]
@brentzundel "which was also addressed:
" the determination of which features are marked at risk was made based on feedback from parties who plan to implement the data model. This feature has enough implementation support, therefore it is not at risk.""
There is no mechanism specified thus this section will not be able to be interop and thus will be at risk and will be non-normative. Its a W3C requirement to show interop on mechanisms detailed in the specification.

**Comment by brentzundel** [comment]
Ah, true. Thank you for reminding me that this section is informative and has no implementation burden.
It is a W3C requirement to show interop on mechanisms detailed in the specification, and this section does not detail any.

**Comment by David-Chadwick** [comment]
This issue should be closed because it covers the same topic as issue #498

**Comment by stonematt** [comment]
WG resolution: https://www.w3.org/2019/04/02-vcwg-minutes.html#resolution09
RESOLUTION: Section 5.2: Trust Model is a non-normative section on the specification. Issue #490 asserts that it should be marked at risk. Non-normative sections contain no normative statements and thus are not at risk during or after the Candidate Recommendation phase. Issue #490 should be closed with no changes to the specification.

Will close 7 days from today if no new concerns or evidence are raised by then in this issue.
