### ISSUE TITLE
TITLE- Verifiable Credentials Data Model 1.0

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#498]
There are no interoperable parts of this specification that make these “verifiable” thus this should be just a claims/credential specification, suggest the name be changed as this is very miss leading to the implementor, so maybe just Credentials Data Model 1.0 unless this is changed to make JWT/CWT the base and JSON-LD structures optional.

**Comment by brentzundel** [comment]
It seems to me that the parts of the specification you seem to be looking for, that in your view are required for it to be interoperable and therefore 'verifiable,' are normative statements about a protocol that should be used for verification. This is a data model specification, and therefore does not make normative statements about protocol.

This group has produced, in agreement with its charter, a verifiable credential data model. The specification makes clear the difference between a credential and one that is verifiable. This data model provides properties that may be used for verification, and provides examples and implementation guidance for those who wish to use them, but it cannot make normative statements about protocol.

The limitation of the charter that prohibits the group from making normative statements about protocol, and the resulting lack of normative statements about protocol in the data model, cannot be used to discredit the data model the group was chartered to create.

**Comment by nadalin** [comment]
This is an non-interoperable specification, you don't know if you have done the proper data model for signatures using JSON-LD, as there are C14N requirements, that work is questionable if this work will finish or be corrrect, So my comment stands IMHO. You don't need a protocol to be verifiable.

**Comment by brentzundel** [comment]
It sounds like what you are saying is that we can't know if we have done a proper data model until that data model is used. Is that accurate?

**Comment by David-Chadwick** [comment]
@nadalin makes an interesting point here. The data model specifies that certain properties MUST exist, and that other properties MAY exist, but if they do exist, they MUST contain certain properties. I think from a data model conformance perspective this is fine. As to whether this is a verifiable credentials spec or a credentials spec is debatable. I would argue that if the spec says the Proof property MUST exist, and its Type MUST also exist to say what type of proof the VC contains, then we can say that this is a verifiable credentials data model, that is extensible to support **any type** of proof mechanism.
At the moment the spec does not quite say this (but a previous version did). The current version says that
 _"at least one proof mechanism MUST be expressed. This specification identifies two classes of proof mechanisms: external proofs and embedded proofs."_ 

However external proofs are outside the data model, so one could argue (and perhaps this is what @nadalin is arguing) that it is only a verifiable credentials data model for embedded proofs and a credentials data model for external proofs.

Perhaps we could solve this be reverting to an earlier version of the text that said the Proof MUST exist and it MUST contain a Type property, and we can then define the JWT type for external JWT signatures (and perhaps also an X509 type for external X.509 signature).

**Comment by stonematt** [comment]
WG resolution: https://www.w3.org/2019/04/02-vcwg-minutes.html#resolution06
RESOLUTION: The specification clearly defines the meaning of "verifiable credential" and the VCWG has spent a considerable amount of time discussing and running surveys on the proper name for the specification. The VCWG believes the name of the specification is appropriate. Issue #498 should be closed with no change to the title of the specification.

Will close 7 days from today if no new concerns or evidence are raised by then in this issue.

**Comment by nadalin** [comment]
@stonematt There is no defined definition of "Verifiable Credential" in tbhe specification, there is a non-normative section on what a "Verifiable Credential" is and there is also this this statemen "Verifiable credentials represent statements made by an issuer in a tamper-evident and privacy-respecting manner" and since this is out of scope of this specification you can't have a "verifiable credential" since there is no "verifiable" mechanism defined 

So I have concerns

**Comment by nadalin** [comment]
@stonematt so looking at the charter 
Terminology
verifiable claim
A machine-readable statement made by an entity that is cryptographically authentic (non-repudiable).

The specification can't achieve this definition since proofs are non-normative

**Comment by brentzundel** [comment]
The title for this specification is exactly correct.
`Verifiable Credentials Data Model 1.0` describes exactly what the spec contains, which is a **data model** for **credentials** that that can be **verified**. The data model specifies extension points for enabling verifiability such that a **Verifiable Credentials Protocol** may later be defined.

The definition for `verifiable credential` is in [Terminology](https://w3c.github.io/vc-data-model/#terminology), where it says:
> **credential**
> A set of one or more claims made by an issuer. A **verifiable credential** is a tamper-evident credential
> that has authorship that can be cryptographically verified. Verifiable credentials can be used to build 
> verifiable presentations, which can also be cryptographically verified.

You point out that "The specification can't achieve this definition since proofs are non-normative." 
What you seem to be missing is that the specification does not attempt to define the protocol for proofs, because the specification only defines a data model. The specification defines a data model that supports proofs.

The specification does not attempt to define a protocol, it only defines a data model.

The specification defines a **data model** that may be used to store **credential** data.
The specification defines a **data model** that supports **verification** of that **credential** data.
Therefore the specification is a **Verifiable Credentials Data Model**

The title makes it clear that this is a **data model** for **credentials**, and that the data model supports **verification** of those **credentials**; changing the title would only lead to greater confusion.

**Comment by burnburn** [comment]
@brentzundel provided clarification 20 days ago, with no further comments since then from anyone.  The title of the specification has been affirmed as appropriate by many parties over many months.  Any concerns with interoperability will be tracked via issue #632.

Closing.
