### ISSUE TITLE
4.9 Status

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#500]
There is a mention of a [VC-STATUS-REGISTRY]. Where is this? Who runs this? Why isn't an IANA registry created as there is a whole process in place to register these formats, schemas, etc.

How will interop be achieved if these  are not standardized in a registry accessible to all implementations? This seems to negate a need for a standardized data model?

**Comment by brentzundel** [comment]
I'm not sure what this issue has to do with the validity of the data model. We have chosen an open model for potential registration of status types.
I believe any such registries will be just as accessible as an IANA registry (both can be accessed vie the web), unless the registry creator intends to create a private registry, which seems nonsensical to me, but if that is the use case within which VCs fit for that implementation, I do not see the benefit of prohibiting it.

**Comment by msporny** [comment]
@nadalin wrote:
> There is a mention of a [VC-STATUS-REGISTRY]. Where is this?

The link is in the appendix of the specification and points to this URL: https://w3c-ccg.github.io/vc-status-registry/

> Who runs this? 

The W3C Credentials Community Group.

> Why isn't an IANA registry created as there is a whole process in place to register these formats, schemas, etc.

For a few reasons:

1. While IANA does have a process of creating registries, it's a bit premature to go there (yet)... especially since most IANA registries point to RFCs and rarely to W3C documents.
1. The extensibility mechanism is decentralized, so anyone may publish a new status scheme by minting one at a URL, so the registry is advisory and optional, not mandatory.
1. The group opted for a lighter-weight, community-run process to start. Adding something to the current registry is a fairly simple spec + pull request. This registry may be run by a WG in time, or may transition to one run by IANA, but for now, the group is starting w/ a lightweight process.

> How will interop be achieved if these are not standardized in a registry accessible to all implementations? This seems to negate a need for a standardized data model?

Interop at that particular extensibility point is still being actively worked on in the W3C Credentials Community Group. The registry exists at a well defined URL and thus all implementers can see it and study its contents (even if it's a bit experimental at present). Having a standardized data model is useful because it explicitly points out the extensibility points, refers to a registry which can be studied, which in turn points to specification text that can be implemented in an interoperable way (including test suites). In time, the expectation is that these extension specifications will be brought into a future W3C WG.

**Comment by nadalin** [comment]
@msspory Thanks, this is a at risk item and will be non Normative since no interop can be shown on the mechanism.

**Comment by stonematt** [comment]
VCWG Teleconference Resolution: https://www.w3.org/2019/04/09-vcwg-minutes.html#resolution09

RESOLUTION: The VCWG has delegated the management of all extension registries associated with the Verifiable Credentials Data Model to the W3C Credentials Community Group in order to support continuity in the extension work as well as a ensuring a light-weight process for managing the registry. The W3C is incubating a registry process as well, and we are in discussions with the Advisory Board on that. The VCWG believes that this approach strikes the right balance
... of formalism and flexibility at this stage of the specifications deployment into the market. With respect to the 'status' field, the group has defined an extension point and a mechanism to identify specific extensions, which are the normative statements in that section. Issue #500 should be closed with no changes to the specification.

Pending close

**Comment by nadalin** [comment]
@stonematt Since there is no decision on a registry this needs to be at risk. The extensions need to be able to actually have implementations that interoperate, merely having a field to place any value in is not interoperability. So this is still an at risk item and non-normative

**Comment by burnburn** [comment]
The outstanding concern by @nadalin regarding interoperability will be tracked by issue #632.  Closing.
