### ISSUE TITLE
Make a JWT  a VC and not to encapsulate the VC inside a JWT

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#520]
Makes more sense to use a JWK as a VC since the data model for JWT is fully open, this all claims in a JWT can be specified.

**Comment by awoie** [comment]
The JWT representation defined in 6.3.1 JSON Web Token describes **how a VC can be encoded as a JWT**. I agree that the description of the `vc` attribute might be a bit misleading. The `vc` is currently described as:

> JSON object, which MUST be present in a JWT verifiable credential. The object contains the verifiable credential according to this specification.

It is misleading because the JWT contains other attributes of the VC at the top level (outside of the `vc`) as well, e.g.,`exp`, `iss`, ...

The same applies to the `vp` attribute.

In fact, the whole JWT is considered a VC rather than the information contained in the `vc` attribute.

@nadalin Would you agree that if changing the language to describe the `vc` and `vp` attributes could resolve your issue?

**Comment by nadalin** [comment]
@awoie I don't think so since there is a defined VC that is not a JWT

**Comment by awoie** [comment]
The following is a valid VC which is encoded as part of the JWT payload. JWS is used as an `external proof`:
```
{
  "sub": "did:example:ebfeb1f712ebc6f1c276e12ec21",
  "jti": "http://example.edu/credentials/3732",
  "iss": "did:example:abfe13f712120431c276e12ecab",
  "iat": "1541493724",
  "exp": "1573029723",
  "nonce": "660!6345FSer",
  "vc": {
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://www.w3.org/2018/credentials/examples/v1"
    ],
    "type": ["VerifiableCredential", "UniversityDegreeCredential"],
    "credentialSubject": {
      "degree": {
        "type": "BachelorDegree",
        "name": "<span lang='fr-CA'>Baccalauréat en musiques numériques</span>"
      }
    }
  }
}
```

@nadalin My proposal is to change the semantics of the `vc` attribute into something like "the claims about the subjects of the VC". Besides the `context` which is a separate discussion, what would you like to change to address your issue?

**Comment by nadalin** [comment]
@awoiw This is getting close, the VC would be a registered IANA Claim and there would have to be a requirement of no JSON-LD so we can use JWS/E

**Comment by msporny** [comment]
@nadalin wrote:
> the VC would be a registered IANA Claim 

This was the expectation of the group.

> and there would have to be a requirement of no JSON-LD so we can use JWS/E

There is no JSON-LD processing requirement at the top-level (or within `jwt.vc` claim), and no requirement to use LD-Proofs or canonicalization or anything else if encapsulated in a JWS/E.

I think the specification already allows you to do what you want, @nadalin -- what am I missing here?

**Comment by nadalin** [comment]
@msporny The spec has to be clear on the IANA registration, the requirement not to use JSON-LD  as this will break the JWK parsers, and if you encounter a @Context you don't have to de-reference or process

**Comment by msporny** [comment]
@nadalin wrote:
> The spec has to be clear on the IANA registration

The spec does have an IANA considerations section that outlines this:

https://w3c.github.io/vc-data-model/#iana-considerations

Do you have a pointer to a specific W3C IANA registration template that you would prefer the group to use?

> if you encounter a @context you don't have to de-reference or process.

Where does the specification state that you have to dereference the @context URLs? As you have pointed out, the specification does state the following

> It is RECOMMENDED that dereferencing the URIs results in a document containing machine-readable information about the context.

However, that does not state that you MUST dereference the `@context` URIs. We could add clarification text around this point since you seem to have misinterpreted this part of the specification.

The spec does state that @context MUST be processed by JSON-based VC processors, but that does not break JWT implementations as the `@context` lives in the `jwt.vc` property, which is expected to be passed to a Verifiable Credentials library. Thus, JWT implementations can continue to be oblivious to `@context` with no harm done to the ecosystem or interoperability. This point is further elaborated upon in https://github.com/w3c/vc-data-model/issues/491#issuecomment-478990012.

**Comment by nadalin** [comment]
@msporny if the VC is put into the IANA registry as needed, then I suspect that claims processors will pick this up and process it thus they will ignore what they don't understand and thus the dereference should be a little clearer than it is. I interpret a RECOMMEND something that a conformance test would test as having to be there.

**Comment by chaals** [comment]
I strongly disagree with the core premise of this proposal, for reasons already outlined in other issues - it would break significant interoperability, is a major breaking change to the architecture at a ridiculously late stage, and doesn't seem to offer any important practical benefit.

**Comment by chaals** [comment]
@nadalin 

> I interpret a RECOMMEND something that a conformance test would test as having to be there.

You apparently continue to misunderstand the text. It does not say "it is RECOMMENDED the the URL is dereferenced". It merely suggests that the URL, **IF dereferenced** has actual content.

I think we can clarify that text, but that isn't the purpose of this particular issue, so I will file a separate one. 

(I think we should close this issue without action, for the reasons noted above)

**Comment by nadalin** [comment]
@chaals How would this break the specification interop tests ?

**Comment by brentzundel** [comment]
@chaals, if I'm understanding the conversation in this thread properly, no
one is suggesting here that JWT be the only encoding method for verifiable
credentials.
The issue as I understand it, is the "vc" property inside of a JWT encoded
verifiable credential and the need for that property to be put in an IANA
registry so that JWT processors can use it.

**Comment by nadalin** [comment]
@brentzundel I'm not suggesting that you don't support what is in the specification relative to the "vc" what I'm proposing is the requirements on how a JWT could be a processed and have a "vc" claim in it that would be JSON and that JWS/E would be used as the proof mechanism when you have this scenario. This could also allow portions of the specification to be normative relative to proofs since there is a mechanism that works and fully specified

**Comment by stonematt** [comment]
VCWG call April 16, 2019
RESOLVED: A JWT is not a Verifiable Credential as the data models differ. A JWT can be used to secure a Verifiable Credential as described in Section 6.3.1. The language related to @context processing for JWT-based processors should be clarified to note that dereferencing @context values is not required, which is a non-substantive clarification to the existing text in the specification. The IANA registration for the vc and vp JWT claims should be separated into
... an IANA Considerations section. Issue #520 should be closed after the PR is merged.

Plan to close in 7 days.

**Comment by nadalin** [comment]
@stonematt Don't agree with closing as the point is that the VC data model should allow JWT

**Comment by msporny** [comment]
> Don't agree with closing as the point is that the VC data model should allow JWT.

It does, why do you think it doesn't?

**Comment by msporny** [comment]
The final PR #590 is in for this issue and addresses this text in the resolution: "The IANA registration for the vc and vp JWT claims should be separated into an IANA Considerations section."

**Comment by burnburn** [comment]
The Working Group has now made clear via multiple responses (here and elsewhere) that while any arbitrary JWT is not automatically a VC, the Working Group believes that any Verifiable Credential satisfying the data model defined in the specification can be represented using the JWT syntax as defined in the specification.  The addition of the IANA considerations section addresses the request that the 'vc' and 'vp' properties in a JWT be defined to have their meanings presented in this specification.
Closing.
