### ISSUE TITLE
5.3.1 Semantic Interoperability

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#525]
This is a confusing section as there is no motivation for this section as most JSON processors don't necessary parse and understand the @Context yet this section says that they MUST, I don't see any rational for this, can someone explain?

Current JWT parsers don't know what to do with an @Context and thus would ignore

**Comment by David-Chadwick** [comment]
If you think a bit deeper about this, your message indicates precisely why @context or something similar is needed - JSON processors have no idea how to support any property that they have not already been told about, so have no support for extensibility except by out of band means.

**Comment by nadalin** [comment]
@David-Chadwick sorry that does not process for me, as i'm talking about JWT processors

**Comment by msporny** [comment]
@nadalin wrote:
> This is a confusing section as there is no motivation for this section as most JSON processors don't necessary parse and understand the @context yet this section says that they MUST

The intent of that conformance statement is to state that Verifiable Credential processors that are operating in JSON mode MUST ensure that the array of values associated with @context are in the expected order for the particular use case (and that's it). It specifically does not mean that they must dereference @context URLs or anything of the sort.

This rule is there to ensure that JSON-based Verifiable Credential processors do not need to use any JSON-LD libraries to be conformant with the specification AND ensure semantic interoperability w/ Verifiable Credentials processors that DO process in JSON-LD mode.

We can suggest that this normative statement is elaborated upon so that it's easier to understand the reasoning behind the requirement for implementers.

**Comment by stonematt** [comment]
Resolved on VCWG call 4/16/2019.
RESOLVED: Editors will non-normatively elaborate on the rules that ensure that the array of values associated with @context should be in the expected order. Close issue #525 after the PR has been merged.

Plan to close issue 7days following merge

**Comment by nadalin** [comment]
@stonematt Will wait to see final wording as I'm not convinced this will be adequate

**Comment by burnburn** [comment]
The outstanding concern by @nadalin regarding JSON-LD will be tracked by issue #633.  Closing.
