### ISSUE TITLE
JSON-LD Reference

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#537]
Should this specification actually be built on JSON-LD 1.1 to better align with JSON structures which would align better with JWT

**Comment by chaals** [comment]
This seems like a rehash of #491, and other related issues. The answer to the question has been provided repeatedly:

- https://github.com/w3c/vc-data-model/issues/491#issuecomment-478031097
- https://github.com/w3c/vc-data-model/issues/491#issuecomment-478823560
- https://github.com/w3c/vc-data-model/issues/483#issuecomment-477310938
- https://github.com/w3c/vc-data-model/issues/483#issuecomment-477970532

as well as discussed at the last face to face meeting and various other places.

I believe this issue brings nothing new and should be closed without action.

**Comment by nadalin** [comment]
@chaals not a rehash at all as specification lists JSON-LD 1.0 and my comments is that some issues may be resolved if this specification is based upon JSON-LD 1.1

**Comment by msporny** [comment]
JSON-LD 1.1 isn't a REC yet, only 1.0 is. That said, in reality, most of the implementations that we know are already using the JSON-LD 1.1 features that have shipped in processors for the `@protected`, which would address some of @nadalin's JSON-LD processing concerns.

In a previous WG, we published a REC that noted that it would upgrade to the latest version of a dependent spec when it hit REC. The WG closed, but the W3C staff updated the REC after it had been published and the dependent spec became a REC. So, there is precedent to do this even though the process is a bit shaky.

In any case, the group is already using JSON-LD 1.1 in practice... it would be good if we could align the spec w/ this reality rather than be limited by W3C Process.

**Comment by nadalin** [comment]
@msporny We did this with WebAuthn and the CredMan support as it's not REC yet and we went to the WebAppSec folks and gota statement from them

**Comment by msporny** [comment]
> @msporny We did this with WebAuthn and the CredMan support as it's not REC yet and we went to the WebAppSec folks and gota statement from them

Ok, then happy to do that wrt. the VC spec. I expect the JSON-LD 1.1 WG will support this, we will bring it up wrt. processing this issue during one of the next calls.

To front run a bit... hey, @iherman @bigbluehat @azaroth42 -- could we schedule a call (in the next two months) with the JSON-LD 1.1 WG to get a statement  from the WG that you intend to take the following features through to REC: `@protected`, scoped `@contexts`, and `"@container": "@graph"? We would like to cite the JSON-LD 1.1 spec as the normative spec for Verifiable Credentials instead of the JSON-LD 1.0 spec (with extensions, which is what we do today).

**Comment by chaals** [comment]
Yeah, there are other precedents for relying on spec stuff that isn't a REC yet - it's more a question of explaining why the reference is reliable enough and important enough to use, rather than being bound by a formal set of rules.

**Comment by burnburn** [comment]
From VCWG call on 7 May 2019:
Issue #537 should be addressed by referencing JSON-LD 1.1 instead of JSON-LD 1.0. This is a non-substantive change since the Verifiable Credentials Data Model specification included JSON-LD 1.1 features inline for JSON-LD based processors and thus implementers would not have to change their implementations as a result of the updated reference. Issue #537 should be closed after the PR is merged.

**Comment by nadalin** [comment]
@burnburn No closure until PR is created to see if this address issue

**Comment by burnburn** [comment]
Yep.  The 7 Day Close clock doesn't start until the PR is available.

**Comment by msporny** [comment]
PR #677 has been merged, which updates the reference from JSON-LD 1.0 to JSON-LD 1.1 per the WG resolution above.

**Comment by burnburn** [comment]
No objections raised during the 7 day close time.  Closing.
