### ISSUE TITLE
Decoding rules for jti and sub are mixed up

### ISSUE THREAD

**Issue by awoie** [w3c/vc-data-model#541]
The current spec mixes up JWT decoding rules for `jti` and `sub`. `jti` must be added to the VC (top level) and `sub` to `credentialSubject`.

**Comment by awoie** [comment]
PR was created: https://github.com/w3c/vc-data-model/pull/542

**Comment by brentzundel** [comment]
I believe this is what you are saying, please correct me if I have misunderstood:

- `jti` is used as an identifier for the JWT, so it maps more appropriately to the `id` property of the credential itself.
- `sub` is used to identify the subject of the JWT, so it maps more appropriately to the `id` property of the `credentialSubject` object.
- Right now the spec has this backwards and your PR corrects this.

**Comment by awoie** [comment]
Exactly

**Comment by stonematt** [comment]
Resolved on VCWG call 4/16/2019.
RESOLVED: Issue #541 is addressed by PR #542, which makes a non-substantive change that fixes a bug in the specification related to JWT jti/sub values being swapped. This is a non-substantive change because there were two conflicting normative statements in the specification, the examples were clearly the intent, and any reasonable implementer would have implemented the feature correctly based on the existing JWT encoding rules in the specification. The PR has
9:58 AM been approved by multiple parties as a non-substantive change and should be merged. Issue #541 should be closed after the PR is merged.

Plan to close in 7 days
