### ISSUE TITLE
Disputes

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#545]
There are no conformance statements in the Disputes section. If we want there to be a standard disputes mechanism, then we should have conformance statements that say the following:
i) if a subject wants to dispute a VC he/she MAY issue a disputes VC
ii) the credentialSubject of a disputes VC MUST contain the "currentStatus" property with the value set to "Disputed"
iii) the id of the credentialSubject MUST be set to the id of the disputed VC
iv) the credentialSubject of a disputes VC MAY contain the "statusReason" and "disputedClaim" properties

**Comment by msporny** [comment]
I expect that the group clearly meant this to be a non-normative section (and I could swear I wrote normative text for this at some point... perhaps that got removed in a series of edits?). The examples show what properties we intended to be used (at the very least, type `DisputeCredential`).

`statusReason` and `disputedClaim` were meant to be examples that we'd verify during implementation.

We'll check to see what the expectation from the WG was for this section. Specifically, confirm that it was supposed to be normative, and then confirm the intended normative text, which would align with the non-normative text in the section.

**Comment by msporny** [comment]
Looking at this a bit more deeply, we did warn implementers that the feature might change during the CR period, so that provides more leeway than normal to modify the feature. I think we can do the following two things that @David-Chadwick mentioned w/o issue:

> i) if a subject wants to dispute a VC he/she MAY issue a disputes VC

> ii) the credentialSubject of a disputes VC MUST contain the "currentStatus" property with the value set to "Disputed"

> iii) the id of the credentialSubject MUST be set to the id of the disputed VC

This one is a bit more difficult:

> iv) the credentialSubject of a disputes VC MAY contain the "statusReason" and "disputedClaim" properties

Saying it may contain `statusReason` is fine.

The "disputedClaim" property name is problematic (for the same reason that `claim` was problematic). We could do something like `disputedSubject`, but that feels weird. We could re-use `credentialSubject`, but again... feels a bit strange. Need someone else to weigh in on this last item. If we can't get to consensus wrt. what to rename it to, then I suggest we don't put any normative statements in about it and instead write about it in the implementation guide or in the VC Extensions Registry.

**Comment by David-Chadwick** [comment]
I suggest we use disputedProperty since this is what is being disputed

**Comment by stonematt** [comment]
From VCWG call on April 30, 2019: 
RESOLUTION: Issue #545 should be addressed by moving the majority of at risk Disputes section to the Implementation Guide and referring to that section from the Data Model specification, and making the Disputes section in the VC Data Model specification non-normative. Issue #545 should be closed after the PR is merged.

**Comment by burnburn** [comment]
PR #629 has been merged. Closing.
