### ISSUE TITLE
verifiable presentation

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#559]
There numerous points on "verifiable presentations" but verifiable presentations are non-normative but there are normative statements about these like "Clarified that verifiable credentials and verifiable presentations MUST include the @context property and that for a VC or VP to be verifiable at least one proof mechanism MUST be expressed: external or embedded. "

There should be no normative statements about "verifiable presentations"

**Comment by brentzundel** [comment]
Are you proposing that the wording of the list of changes be amended?

**Comment by jandrieu** [comment]
@nadalin Verifiable Presentations are normative. What's how holders present a VC.

Why do you think they aren't?

**Comment by nadalin** [comment]
@jandrieu Because Presentations are non-normative in specification which verifiable presentations seem to inherit

**Comment by jandrieu** [comment]
They are defined in the normative section on presentations https://w3c.github.io/vc-data-model/#presentations-0
as the means by which a holder presents claims from VCs to verifiers. That language is definitive. They ARE normative because the spec that defines them says they are.

**Comment by nadalin** [comment]
@jandrieu Section 3.3 defines presentations as non-normative

**Comment by jandrieu** [comment]
Section 3.3 just says that section is non-normative. It doesn't say anything about other sections.

**Comment by nadalin** [comment]
@jandrieu Since this is titled "presentations" I assume that all parts of presentations are non-normative since the introduction to them is non-normative. The specification is confusing in this regard. There still remains the question about making them normative and interoperability issues.

**Comment by brentzundel** [comment]
The normative presentation section is 4.10

**Comment by msporny** [comment]
> Since this is titled "presentations" I assume that all parts of presentations are non-normative since the introduction to them is non-normative. The specification is confusing in this regard. 

It is common practice, both at W3C and IETF, to introduce concepts in a non-normative fashion and then provide normative statements in the more technical parts of the specification.

**Comment by stonematt** [comment]
From VCWG call on April 30, 2019: 
RESOLUTION: It is common practice, both at W3C and IETF, to introduce concepts in a non-normative fashion and then provide normative statements in the more technical parts of the specification. Readers are urged to note whether sections are marked as non-normative and should not assume that other sections discussing the same concept are non-normative as well. Issue #559 should be closed with no changes to the specification.

**Comment by nadalin** [comment]
@stonematt WOW

**Comment by burnburn** [comment]
@nadalin I will affirm the VCWG resolution here.
It is impossible to read and understand virtually any specification at W3C if one assumes that a section marked as 'non-normative' is to be interpreted as 'not to be implemented' rather than as 'no statements regarding implementation are being made here'.

In W3C specifications only the normative statements matter, and having concepts listed elsewhere in non-normative sections is irrelevant.  From a conformance perspective implementers effectively do the following:

1. Ignore any section marked as non-normative (as in, don't even read it).  It is incorrect to assume non-normative has any meaning whatsoever with respect to what you must, or must not, implement.  You may draw no conclusions whatsoever from the text.
2. Ignore any text within a normative section that explicitly says that that text is non-normative, following the same rules as above.


I must be misunderstanding you here, because in your role as a Working Group Chair this distinction and manner of working should be beyond second nature for you.  If you would like to discuss this further, please contact me directly.  Closing.
