### ISSUE TITLE
(editorial) problem with the trust model

### ISSUE THREAD

**Issue by TallTed** [w3c/vc-data-model#560]
https://github.com/w3c/vc-data-model/blob/acec79f7944aa7ad3b6efe86d34855a24b646e15/index.html#L1901

```
The <a>subject</a> and <a>verifier</a> trust the <a>issuer</a> to issue
true (that is, not false) <a>credentials</a> about the <a>subject</a>, and to
revoke them quickly when appropriate.
```

Any entity can say anything about anything.

The **subject** need not trust any entity, need not know about any **issuer** which is making verifiable claims about the subject.  The **subject** is not involved in this trust chain (unless the **subject** happens to also be the **holder**, and even then, the trust is based on their status as **holder**).  Only the **holder**, **issuer**, and **verifier** are involved in the trust chain.

I think the necessary change here is simply to change the initial **subject** to **holder**, i.e., --

```
The <a>holder</a> and <a>verifier</a> trust the <a>issuer</a> to issue
true (that is, not false) <a>credentials</a> about the <a>subject</a>, and to
revoke them quickly when appropriate.
```

This change is to an informative (non-normative) section, and appears to match the content of the remainder of the document, so I think it should be considered non-controversial and editorial.

**Comment by TallTed** [comment]
This has been nagging at me all weekend.

I think that actually the **holder** trusts only that the **issuer** will be issuing **verifiable credentials** that say what the holder wants those credentials to say to a **verifier** — without the **holder** necessarily having any concern for their veracity!  Which is rather different than what the model now says...

The point of this data model is simply to allow **verifiers** to confirm/verify that **claims** (**assertions**, in a **credential**, in a **presentation**) about a **subject** were made by an **issuer**.

**Comment by David-Chadwick** [comment]
@TallTed you make some good points, and they are finely nuanced.

Speaking with an honest Subject hat on, I want the VCs to contain factually true assertions about me.

Speaking with a dishonest Subject/Holder hat on I want the VCs to say anything that will give me access to the precious online resources of the verifier (so that I can plunder them).

Speaking with a verifier hat on, if I am to let a holder access my precious online resources using the credentials that he/she possesses, then I need to know that the credentials are valid (for this purpose). I also need to know who I can sue if something goes wrong and I lose out on the interaction. I therefore need the assertions in the VC to be true so that I am not duped into accepting a holder or subject masquerading as someone else. Who or what do I trust in this situation? If I do not trust anything or anyone (other than myself) then I will be the issuer of the VCs. But I still have to trust the issuer of the VCs, even if this means trusting only myself. If the issuer is another entity then I have to trust it to the same extent that I trust myself. 

What does it mean that the VC is valid? It means that the VC is authentic i.e that the issuer issued the VC and it has not been tampered with since it was issued. But it means more than that. For example, I have an AMEX card which is authentic, but it is not valid for paying tolls on French motorways, but it is valid for paying for groceries in French supermarkets. I assert that valid means that the verifier trusts the issuer to issue VCs for the purpose in hand (i.e. accessing my precious online resources). This necessarily means that the VCs contain honest information. So I assert that honesty and veracity are part of the trust model.

Concerning the disputes situation, you make a good point about the Eiffel tower. But if someone is acting on behalf of the Eiffel tower i.e. subject NE holder, then the verifier needs to know under what authority the holder is acting, and in this case will be willing to accept a disputes credential from a valid holder, which I think you will find the current text caters for.

**Comment by TallTed** [comment]
Honesty and veracity may be a part of an (I suggest that "the" is not appropriate here) intangible trust model.> Speaking with a verifier hat on, if I am to let a holder access my precious online resources using the credentials that he/she possesses, then I need to know that the credentials are valid

Well... you want (I think "need" is too strong) to *believe* that the credentials are valid.  There is no *knowing* possible.  So, yes, the verifier _wants_ the credentials they verify to have emanated from a trustworthy issuer.

**Comment by TallTed** [comment]
> I have an AMEX card which is authentic, but it is not valid for paying tolls on French motorways, but it is valid for paying for groceries in French supermarkets

You're using validity in an odd way.  I assert that your example AMEX card is fully *valid,* even if it is not *accepted,* for payment of the French tolls.

This is because AMEX is not deciding that it will not honor your payment, but the French toll-collecting authority who is determines they will not accept that payment method.  I'm quite confident that the French determination that they will not accept payment via AMEX is not based on AMEX being an untrustworthy issuer, nor on any judgement about the honesty of you as presenter.

Verifiable Credentials hold Assertions about Subjects, that can be Verified as having been emanated by an Issuer.  That is the extent of the Verification -- that the content of this Credential (possibly but not necessarily including some meta-assertions which might include the date of assertion emanation and/or a date of assertion expiration, among other *possibilities* which are not *requirements*) was indeed emanated by the Issuer.

Evaluating the *Veracity* of those Assertions/Claims/Credentials is entirely out of scope, and talking about that Veracity in the Data Model spec as if it were in scope is problematic, even in a non-normative section.

Evaluating the *Honesty* of either the Holder or the Issuer is equally out of scope, and talking about that Honesty in the Data Model spec as if it were in scope is problematic, even in a non-normative section.

This chunk is not about a software protocol, but I am thinking more and more that it is about some broader human, business, and/or other protocol(s), which are just as out of scope for this spec.
