### ISSUE TITLE
misleadingly and confusingly named issuanceDate

### ISSUE THREAD

**Issue by TallTed** [w3c/vc-data-model#584]
Regrettably timed, but I only just noticed this.  (previous discussion was in #184)

`issuanceDate` (20,500 Google hits) is a rather odd construct, especially alongside `issuer` (27,500,000 Google hits) and `expirationDate` (1,220,000 Google hits).

The differences in scale of use is even more pronounced if you search for these as phrases, e.g., "issuance date" (736,000 hist) and "expiration date" (41,600,000 hits), rather than as the compound terms.

I know it would cause code changes for all implementors including the test suite, but this would be *much* better changed to `issueDate` (325,000 Google hits) or `issuedOn` (11,500 Google hits) -- potentially also changing `issuer` (27,500,000 Google hits) to `issuedBy` (472,000 Google hits).

(Had I noticed sooner, I would have pushed for `issuedAt` and `expiresAt` which I think also better conveys the datetime nature of these attributes.)

This may get closed out-of-hand as too late, but I felt it better to speak now than not at all.

**Comment by msporny** [comment]
When selecting terms for most Linked Data libraries, we attempted to pick the words based on their common dictionary definition rather than how popular the term is on Google. Google term popularity is one data point, but more importantly, the meaning of the term when searched for in a common dictionary is far more important. Here's what comes up for Merriam-Webster:

> issuance: 1) the action of supplying or distributing something, especially for official purposes, 2) the action of formally making something known.

> expiration: 2)  the fact of coming to an end or the point at which something ends.

I agree that "Date" isn't great (the fields started as pure dates w/ no time, but things changed over time w/ the definitions w/o the property names being updated), but suggest that the two words that we have at present are accurate words to describe the properties.

A change of these property names would require implementations change and would require the test suite to change. That's a substantive change, and our charter extension is such that it would be incredibly difficult to go through another CR at this point... even if that were not the case, this alone doesn't feel like a compelling enough reason to go through a CR. Yes, yes, we shouldn't let W3C Process affect doing "The Right Thing(tm)", but that's where we are today... and if we were to have this discussion, the presumption is that the group would agree to "issuedAt" and "expiresAt" and "issuedBy" without having to result to an Instant Run Off naming poll where we collect all options, run the poll, keep it open for 1-2 weeks, for a total of 4 weeks of time spent on this one issue (which is what these things typically devolve into).

**Comment by David-Chadwick** [comment]
I think that issuanceDate is conceptually wrong. It is not the date that the VC is issued that is most important to a verifier, but rather the date that the VC becomes valid for presenting to verifiers. I often get posted credit cards in one month (the date of issuance) that do not become valid until the next month (the start date). We should give issuers the possibility of issuing a VC before the date that it starts to be valid/usable with verifiers. This does not prevent an issuer from making the issuaceDate equal to the startDate, but the current definition forbids this. I suggest we change it to startDate

**Comment by David-Chadwick** [comment]
By the way startDate has  88,400,000 google hits and is defined in schema.org
https://schema.org/startDate
as The start date and time of the item (in ISO 8601 date format).
This is a much better definition for the field

**Comment by TallTed** [comment]
@msporny - I hear you about the challenges and issues and perils. I think they may be worth weathering.

@David-Chadwick - you make some good points, but I don't agree with `startDate`.

I am thinking that [`validFrom`](https://schema.org/validFrom) and [`validUntil`](https://schema.org/validUntil) would be a better pair (though schema.org is stupidly inconsistent once again, expecting the former to be a datetime and the latter just a date) -- and would both communicate the important semantics in their names, and suggest the possibility (not requirement) of datetime (and a bare date could be used when applicable).

`issuanceDate` could remain as metadata about (though included within) the VC, and `validFrom` could be defined to be treated as equal to `issuanceDate` if not explicitly set.

**Comment by David-Chadwick** [comment]
I support the addition of validFrom as an optional term. This should not necessitate the re-issuing of the CR. And its definition can say that if it is missing, then its value is the same as issuanceDate.

**Comment by David-Chadwick** [comment]
Added PR #620 to resolve this issue according to the minutes of VC WG meeting on 7 May

**Comment by msporny** [comment]
I've added PR #646 to address this issue. Suggest we merge and close.

**Comment by burnburn** [comment]
WG resolution on 28 May 2019 call:

RESOLUTION: Issue #584 is resolved via PR #646, which updates the specification with non-normative language noting that the properties will change to validFrom and validUntil in the future. Close issue #584 after the PR has been merged.
