### ISSUE TITLE
Section 4.3

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#608]
"The value of the type property MUST be, or map to (via interpretation of the @context property), one or more URIs. If more than one URI is provided, the URIs MUST be interpreted as an unordered set. Syntactic conveniences, such as JSON-LD terms, SHOULD be used to ease developer usage. It is RECOMMENDED that each URI in the type be one which, if dereferenced, results in a document containing machine-readable information about the type."

It is unclear as written since JSON-LD is NOT required why a SHOULD is used. This information would be better served in a non-normative note

**Comment by nadalin** [comment]
"Verifiable credentials and verifiable presentations MUST have a type property. " is stated then it goes on to list more … "With respect to this specification, the following table lists examples of objects that MUST have a type specified. " I would suggest removing the 1st sentence ""Verifiable credentials and verifiable presentations MUST have a type property" and just having 1 place and list them all

**Comment by David-Chadwick** [comment]
All the examples in the table have duplicate statements about the type property being mandatory. For VCs and VPs the duplicate statement is in section 4.3. For the other properties the duplicate is in the appropriate section. If you want to remove anything it should be the table, which is only providing examples. It is not the definitive list.

**Comment by nadalin** [comment]
@David-Chadwick The issue is they are not all inclusive, there is a mismatch is what the Statement provides and what the table provides

**Comment by TallTed** [comment]
@nadalin - 

To the initial comment in this issue, would that be sufficiently addressed by rewording --

>Syntactic conveniences, such as JSON-LD terms, SHOULD be used to ease developer usage.

-- to the following (which says exactly the same thing) --

>Syntactic conveniences SHOULD be used to ease developer usage; such conveniences may include JSON-LD terms.

----

I wonder if your second concern here could be addressed by adding entries for verifiable credentials and verifiable presentations (and any others that are missing, if there are any such) to the table (i.e., making it a complete list of all objects (rather than "examples of objects") in the spec that require type specification, and thus a summary presentation of details laid out in the other sections), rather than removing the initial sentence?

**Comment by msporny** [comment]
PR #631 has been merged. Suggest we close this issue since the issue submitter's concerns have been addressed with PR #631.

**Comment by burnburn** [comment]
WG resolution on 28 May 2019 call: 

RESOLUTION: Issue #608 is addressed via PR #631 which adds non-normative clarification around the SHOULD of concern to the reviewer. Issue #608 will be closed after a 7 day wait period.
