### ISSUE TITLE
Tracking Issue: Interoperability

### ISSUE THREAD

**Issue by burnburn** [w3c/vc-data-model#632]
This is a tracking issue to make sure a particular concern is clearly recorded.  Duplicates will be closed.

The primary issue that has been raised by @nadalin is a claim that the specification cannot achieve interoperability. This stems from a stated belief that a data model specification that defines extension points but does not define and mandate the implementation of at least one specific extension at each extension point cannot test for interoperability.  Per the charter [1], the specification is NOT permitted to contain _normative statements regarding protocol, API, nor execution_, something the Working Group believes would be necessary if such extensions were to be defined.

The Working Group has discussed this extensively and stated in the specification that “The Working Group seeks implementation feedback, having set the requirement of at least two implementations of each feature as the exit criteria for the Candidate Recommendation phase. The group aims to obtain reports from two producers and two consumers for each feature if possible.”  This approach for a data model and syntax specification, with no execution component defined, is consistent with that used to successfully produce the EMMA Recommendation [2] and others.

[1] https://www.w3.org/2017/vc/WG/charter.html#ooscope
[2] https://www.w3.org/TR/emma/

**Comment by nadalin** [comment]
@burnburn There would have to be a set of usecases that demonstrate interoperability

**Comment by burnburn** [comment]
In the 16 July 2019 VCWG call:

RESOLVED: Tracking issue #632 is hereby deferred due to the nature of the request, which is to work on protocol which is specifically out of scope for the WG Charter.

**Comment by msporny** [comment]
Some of this work is being done in places like this -- https://github.com/w3c-ccg/vc-http-api-test-suite ... and this http://vaxcert-interop-reports.s3-website.us-east-2.amazonaws.com/

**Comment by kdenhartog** [comment]
We discussed this on the working group call and at this point believe this issue is no longer a point of major concern given the number of protocols showing evidence of interoperability at this point. We've opted to close it and if anyone feels this should be addressed they can open a new issue which can be discussed in V2.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-08-11-vcwg#section4-7) on 2021-08-11

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.7. Tracking Issue: Interoperability (issue vc-data-model#632)

_See github issue [#632](https://github.com/w3c/vc-data-model/issues/632)._




**Wayne Chang:** I think this is out of scope for us and probably also for V2  
… I move to close  

> *Manu Sporny:* +1 to close

**Kyle Den Hartog:** I think this is because Tony had raised a bunch of issues and this is a way to track those, so I think we can close it  

**Wayne Chang:** We should also link to incubating protocols  

</details>

**Comment by clehner** [comment]
Interoperability is also being pursued in https://github.com/w3c-ccg/community/issues/198
