### ISSUE TITLE
credentialSubject of Verifiable Credentials Data Model 1.0

### ISSUE THREAD

**Issue by enuoCM** [w3c/vc-data-model#659]
The definition of credentialSubject in [Verifiable Credentials Data Model 1.0](https://w3c.github.io/vc-data-model/#credential-subject)

> The value of the credentialSubject property is defined as a set of objects that contain one or more properties that are each related to a subject of the verifiable credential. Each object MAY contain an id as described in Section § 4.2 Identifiers.

I don't quite understand this.  Is the **credentialSubject** a JSON object or a JSON array?
According to  [issue#518](https://github.com/w3c/vc-data-model/issues/518#issuecomment-486502179), it seems that **credentialSubject** can be either.

But [EXAMPLE 36](https://w3c.github.io/vc-data-model/#example-36-the-relationship-property-in-a-child-s-credential), it seems that the **credentialSubject** merges the properties (ageUnder & parent) of **AgeCredential** and **RelationshipCredential** and is set as one JSON object other than an Array.

I have four questions: 
1.  Dose it because that **AgeCredential** and **RelationshipCredential** in above example are about one [subject](https://w3c.github.io/vc-data-model/#dfn-subjects), then it can be merged into one **credentialSubject** JSON object?
2.  If two different Credentials, such as **XXXCredential** and **YYYCredential**, both have a same associated property **ZZZ**, what should be the merged **credentialSubject**? In this case, it should use Array instead?
3. Is there any multiple different **Credential**s types example about two or more different [subject](https://w3c.github.io/vc-data-model/#dfn-subjects)s?  [issue#518](https://github.com/w3c/vc-data-model/issues/518) has only one **Credential** type.
4. Why not put the **Credential** type into the **credentialSubject**? Then the relation between subjects, properties and the **Credential** types is more clear.

**Comment by brentzundel** [comment]
The value of the `credentialSubject` property may be an object or an array. Each `credentialSubject` object should contain claims about a single subject.
In example 36, the subject of the credential is the child. The value of the `credentialSubject` property is the object:
```
  {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "ageUnder": 16,
    "parent": {
      "id": "did:example:ebfeb1c276e12ec211f712ebc6f",
      "type": "Mother"
    }
  }
```
this may be read as:
"the child has id did:example:ebfeb1f712ebc6f1c276e12ec21"
"the child has age under 16"
"the child has a parent of type mother with id did:example:ebfeb1c276e12ec211f712ebc6f"

All of the claims in the `credentialSubject` are about the child, even though they refer to other entities.

> 1. Dose it because that AgeCredential and RelationshipCredential in above example are about one subject, then it can be merged into one credentialSubject JSON object?

Yes

> 2. If two different Credentials, such as XXXCredential and YYYCredential, both have a same associated property ZZZ, what should be the merged credentialSubject? In this case, it should use Array instead?

This depends on the subject of XXXCredential and YYYCredential. 
If they have the same single subject, then a new WWWCredential that merges the attributes from both credentials should have a single `credentialSubject` object. If XXXCredential and YYYCredential each have a ZZZ property about the same subject, then the value of that property in each credential should be the same.
If they have different subjects, then a new WWWCredential that merges the attributes from both credentials should have a `credentialSubject` that is an array with an object for each of the original subjects. Each object could then have its own ZZZ property.

> 3. Is there any multiple different Credentials types example about two or more different subjects? issue#518 has only one Credential type.

There are currently no examples in the specification of a verifiable credential with multiple `credentialSubject`s

> 4. Why not put the Credential type into the credentialSubject? Then the relation between subjects, properties and the Credential types is more clear.

This is because the `type` field inside of a `credentialSubject` object would indicate the type of subject, not the type of credential.

**Comment by enuoCM** [comment]
@brentzundel Thanks for your answers. 
`This depends on the subject of XXXCredential and YYYCredential.
If they have the same single subject, then a new WWWCredential that merges the attributes from both credentials should have a single credentialSubject object. If XXXCredential and YYYCredential each have a ZZZ property about the same subject, then the value of that property in each credential should be the same.`
Must it use a merged WWWCredential ？Or it can always choose XXXCredential and YYYCredential Array? 
According to the context, the same ZZZ property in different credentials may have different meanings. Is it right?

`This is because the type field inside of a credentialSubject object would indicate the type of subject, not the type of credential.`
Then why not add some new property such as **credentialType**?

**Comment by brentzundel** [comment]
> Must it use a merged WWWCredential ？Or it can always choose XXXCredential and YYYCredential Array?

I'm not sure what you mean exactly. In the example we went through, the "merging" of XXXCredential and YYYCredential to create WWWCredential was a thought experiment to help clarify the relationship between different subjects in a single credential. There is no mechanism (that I am aware of) which supports the actual "merging" of two credentials by a holder. WWWCredential would need to be a wholly new credential, received by a holder from an issuer.

With verifiable presentations, an array of multiple credentials may be presented, and in this way proofs from multiple credentials may be combined into a single presentation.

> According to the context, the same ZZZ property in different credentials may have different meanings. Is it right?

Yes

> Then why not add some new field such as **credentialType**?

There is a `type` property for the credential already.
There is also a `credentialSchema` property, which may be used to add more clarity about the properties used to make claims about a credentialSubject.

**Comment by burnburn** [comment]
From the VCWG call on 11 June 2019:

RESOLUTION: Issue #659 has not and does not appear likely to result in any suggested changes, the issue should be closed after a 7 day wait period. Notify the issue submitter that we are moving the discussion to the public-vc@w3.org mailing list.

**Comment by brentzundel** [comment]
@enuoCM, we're happy to continue the conversation using the working group mailing list. 
If you have more questions, please send an email to:
`public-vc@w3.org`
with the subject line:
`Issue #659 - credentialSubject of Verifiable Credentials Data Model 1.0`

**Comment by enuoCM** [comment]
@brentzundel Thanks for the information.
