### ISSUE TITLE
Implicit Types Insertion

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#682]
Implicit types have only been inserted into the data model during June/July 2019. Prior to this there was no mention of implicit types in the data model document, and the understanding (at least by many in the group if not all) was that all the types are explicit i.e. the data model is strongly typed as opposed to weakly typed. 

The facts that support this are as follows:

i) the  minutes of 19 June 2018 (https://www.w3.org/2018/06/19-vcwg-minutes.html) where types were discussed, it was clear that explicit typing was to be used. Quote by @TallTed "Implicit typing mandates inference/reasoning in tools that consume the data. Explicit typing lowers the bar for verifying, etc. I believe there are other reasons to encourage explicit typing; the only reason I know of to discourage explicit typing is the "extra" triple."

ii) the original CR text (March 19) of the data model document contains several MUST clauses about typing, and there is no mention of implicit typing or optional typing.

iii) #PR658, and in particular the comment of @brentzundel of 6 June 2019 starting with "Intro" and saying "My interpretation of the text" makes it clear that explicit typing was intended and understood by him. Further in the conversation @brentzundel then said "@David-Chadwick that was my interpretation of the text as well, but I can see potential value in the notion of implicit sub-types as **@TallTed has introduced them**."

So it is clear that @TallTed changed his opinion and introduced the notion of implicit typing in June 2019, a year after he first strongly argued for explicit typing. After that, the majority of the working group accepted the concept of implicit typing, and it has been added to the data model.

This is not to say that implicit typing could not be supported by the data model or is better or worse than explicit typing. But it is a substantive and normative change to the original CR specification, and the inclusion of this concept has not been fully worked through in the specification.

The only clause in the original CR that caused some ambiguity was the phrase "All credentials, presentations, and encapsulated objects MUST specify, **or be associated with**, additional more narrow types (like UniversityDegreeCredential, for example) so software systems can process this additional information". Some members stated that **or be associated with** referred to higher types in the document in line with the explicit typing requirement, whilst others said that it implied weaker typing. The former opinion was supported by the following sentence in the specification, which attempted (rather badly) to describe what **associated with** meant "When processing encapsulated objects defined in this specification, (for example, objects **associated with** the credentialSubject object or deeply nested therein), software systems SHOULD use the type information specified in encapsulating objects higher in the hierarchy".  There was no text in the original CR to support the concept of implicit typing or that **associated with** meant implicit typing.

In an attempt to clarify the meaning of **associated with** the following rewording was suggested "The specification of these additional more narrow types could be done in the object within which the additional information is found, rather than at a higher level such as the type property of the credential or presentation." Furthermore the following sentence was also suggested  "It is also possible for the additional more narrow types to be implicit."

Both clarifications were accepted by the WG. But it is clear from @brentzundel's remarks above that implicit typing is a new concept introduced into the specification by @TallTed in June 2019, and unfortunately, this clarification significantly affects the data model, and in fact, invalidates some of the original text e.g. the table in section 4.3

"With respect to this specification, the following table lists the objects that MUST have a type specified.

Object | Type
-- | --
verifiable credential object (a subclass of Credential object) | VerifiableCredential and, optionally, a more specific verifiable credential type. For example, "type": ["VerifiableCredential", "UniversityDegreeCredential"]
Credential object | VerifiableCredential and a more specific verifiable credential type. For example, "type": ["VerifiableCredential", "UniversityDegreeCredential"]

The introduction of implicit typing invalidates the mandatory requirement for Credential object to contain a more specific type. Consequently we now have an inconsistent and ambiguous data model document. If implicit typing is to be a full feature of the data model then the implications of this need to be made clear. It is not appropriate to slip it in via the new sentence that has been added because the implications of implicit typing are potentially huge. E.g. every VC can now legitimately be issued with type VerifiableCredential only, and no further subtyping need be added by any issuer to any VC. In other words, the type parameter becomes effectively obsolete. I asked for a definition of implicit type to be added to the specification, to which the answer was:

-> to be implicit. Such implicit types may be implied by the Issuer by including, and inferred by the Verifier by evaluating the presence and/or value(s) of, properties of the implied type which are not described as part of the explicitly declared type(s).

to which I replied

"From the above explanation, then I infer that every issuer can issue VCs of just the type VC, and from the properties in the VC, the verifier can infer what type of VC this is. Thus negating the need for the type property to ever be anything other than single valued."

to which @TallTed replied

Yes.

However,
1. The standard does not yet contain a definition of the implicit type, nor 
2. Does the standard explain the implications of having implicit types, nor
3. Does the standard say that the type can always be single valued

**Comment by David-Chadwick** [comment]
Note that I would formally like to object to the progression of the CR to PR until the issue of implicit typing is properly nailed down in the standard (and not in the implementation guide, which is only a guide)

**Comment by TallTed** [comment]
@David-Chadwick -- 

Please remember that comments dashed off during a teleconference are an imperfect communication, and not a full revelation of anyone's thoughts or feelings.

Yes, I did indeed write --
> I believe there are other reasons to encourage explicit typing; the only reason I know of to discourage explicit typing is the "extra" triple.

Note that my words here were "enourage" and "discourage," not "require" nor "forbid."  Note also that I said "the only reason I know of" (where I should probably have said "can think" instead of "know"), by which I (clearly, to me) meant that there could be reasons I did not know of.

The Working Draft of 2018-07-18 included the following segment, which may have been introduced previously. I was not able to locate the commit which delivered it, only [this tagged version of the document](https://github.com/w3c/vc-data-model/blob/c7b6c2f2fbc98bbfb5b1fa2af2c80dc91c1ddc34/WD/2018-07-18/index.html#L1529).

```pre
All <a href="#dfn-credential" class="internalDFN" data-link-type="dfn">credentials</a>, <a href="#dfn-presentations" class="internalDFN" data-link-type="dfn">presentations</a>, and encapsulated objects <em class="rfc2119" title="MUST">MUST</em>
specify or be associated with additional, more narrow <a href="#dfn-type" class="internalDFN" data-link-type="dfn">type</a>s
(e.g. <code>ProofOfAgeCredential</code>) such that software systems can use
the additional information to more easily process the data.
```

Part of why I *accepted* the "associated with" phrasing, is that I understood it to allow for implicit typing by advanced users (both Issuers and Verifiers). I probably should have pushed for the type declaration `MUSTs` to become `SHOULDs`, even on the base type declaration, but that's water under the bridge.

Part of why I *accepted* the paragraph as written above is that the explicitly stated reason for the base type declaration was to enable software to "more easily process" the data -- not to make that processing *possible*, just *easier*.

I did not think it necessary to explicitly state that "specify or be associated with" meant "specify or imply" to me, because I didn't think I was the only person who understood that meaning to be there. More recently, I learned there was at least one person who understood that meaning to be the contradicted by the text -- with which understanding I adamantly disagree -- so in recent editing, I added the explicit statement about "implicit typing" because I absolutely wanted to preserve this flexibility.  In further discussion about that edit, it became clear that many had not fully appreciated the meaning or ramifications of this "or be associated" phrase, but it also became clear that my arguments in favor of my interpretation held weight once elaborated.

Again -- I have not "changed [my] opinion." Saying so mischaracterizes my thoughts on the matter, and, I believe, willfully misinterprets my words, especially as I've provided significant expansion on what I intended to be understood then, and which I believe is fully understood by all now.

-----

All that said.

The Implementation Guide provides the means by which to explain to implementers and users, that Verifiers *can* require strong sub-typing in all VCs they Verify, and Issuers *can* use it in all VCs they Issue.  Warnings (or suggestions...) about relying on (or including...) unresolvable URIs for either types or properties, among other things on which I've written rather a lot lately, should equally be included here.

Verifier Policies may be written to act on implicit typing by refusing those VCs, and to act on strong sub-typing by acting only on those properties which are explicitly a part of VCs of such sub-type, and only those when the sub-type's URI can be dereferenced to a machine-readable description which includes machine-readable descriptions of those properties.

Verifier Policies may *also* be written to not care about the sub-type, nor whether they can dereference the type or property URIs, and only care whether the property URI matches their list (which might be comprised of lexical strings representing URIs), and whether the value of that property matches their evaluation criteria.

Interoperability does not require that both sides are always built perfectly for the other.  Adapters can be used to translate many differences.  I can use a 1/4" ratchet handle to drive a 1/2" socket, if I have a suitable step-up adapter; and vice versa, if I have a suitable step-down adapter.  These tools are interoperable, though they do not fit perfectly out-of-the-box.  

The same applies to software, and especially to things like a Data Model, which can and should allow for far more flexibility than might be provided by any given Protocol which makes of that Data Model.  One Protocol may require all VCs to be strongly typed.  I would not recommend this, and I would generally argue against using such if specified, but it could be done -- and it may be appropriate for a specific use case.  It is not and will not be appropriate for *all* use cases.

**Comment by dlongley** [comment]
@David-Chadwick,

I've always thought that there was room for expressing credentials that do not have additional specific type information. There are specific use cases where you want to do just that, as I said on the previous call. You may want to, for example, reveal an attribute about yourself without saying the type of credential it came from. This is a privacy consideration.

I also thought that you did a good job of convincing the group to recommend that it's best practice to include additional type information *whenever you can*. I still agree with that -- but I do not think (nor did I think) that we were making it *impossible* to create a compliant VC if it did not *explicitly* declare a special subtype.

Furthermore, I don't believe that having explicit subtyping as a hard requirement for the reasons you've expressed will produce the result you want. Someone will inevitably become frustrated with creating what they consider superfluous types -- and they will create the "AnyCredential" type. This credential type, by definition, will allow all properties, but they are all optional. Then we will just be burdened with the technical debt of VCs with `"type": ["VerifiableCredential", "AnyCredential"]`.

Simply adding this "any" type to a credential would make it compliant with the way you interpreted the spec but it would totally fail to achieve the goals for strict typing you desire. As argued by the group, those goals can only be achieved by verifier policy. Furthermore, the use of `@context` already provides semantics for the properties in a VC -- guaranteeing that any application that chooses to accept a particular `@context` (again, a matter of policy) should understand the meaning of the attributes and types found in the VC.

If your application already only understands a specific set of VCs with particular subtypes and requires those subtypes to be present -- what is the problem? Wouldn't your application similarly reject both a VC with no additional subtype and one with a subtype it does not understand? Is the concern that you want your application to be able accept VCs that have attributes it does understand but subtypes it does not? If that is the case, what if there is as VC with a subtype that is not understood but that has attributes that are understood by the application? A hard requirement for an explicit subtype would not help you here.

Therefore, I just don't see how such a rigid requirement is useful. I also have use cases in mind (going back years) where it would cause a problem. To be clear, I'm perfectly ok with giving the advice that it is helpful to include more type information when possible -- and that type information is a perfectly reasonable thing to require as a matter of verifier policy. I think *most* VCs should be authored this way, particularly if you're not creating a "derived" VC from other ones. However, it would be a mistake to make it such that the spec does not allow VCs with type information that can be inferred (implied) without its explicit presence.

An example of "implied" type information is a VC that includes an "ageOver" claim but no "type" ... and no other claims. The type for this VC could be inferred to be a "VerifiedAgeCredential" (should someone define this type). It may be the case that this information actually came from a driver's license credential -- but I've used an anonymization service that has repackaged only the attributes I wanted to share... so I can present it to a website for bicyclers who may bully or discriminate against drivers.

**Comment by David-Chadwick** [comment]
@TallTed and @dlongley I think both of you are missing the point now. It is not about whether implicit types should be added to the specification or not. The WG voted to add them last week (and indeed I produced some text (PR#674 is almost it) indicating where implicit typing could be allowed). The point now is about whether this is a substantial change to the March CR or not. I am suggesting it is, and PR#685 also indicates it is, as a mandatory feature in the March CR is now being reduced to an optional feature. We need to properly document in the revised specification what implicit typing is (i.e. definition) and the implications of using the feature. One might even argue that the credential type parameter is no longer needed since it can be inferred from all the other properties in the JSON-LD structure.

**Comment by TallTed** [comment]
As this discussion continues, it seems to me that the only element of a Credential that is *really* required for it to be Verifiable, is the Proof portion (and any properties necessary for that Proof to be processed).  Without a Proof, nothing is Verifiable, whether or not the Tye is declared to be VerifiableCredential.  *With* a Proof, some if not all can be Verified, and in that process, the Credential may be inferred to be Verifiable, even if it has not been declared as such.

We made a lot of things MUSTs because of assertions and perceptions that only MUSTs can be tested, and not because they really *are* MUSTs to make the systems work.  Many of these probably ought to have been SHOULDs, which can be treated as MUST for individual test writing, with failures leading to explanation of the justification for disobeying the SHOULD.  If there's a wholesale revisiting of the spec, revisiting these MUSTs will play a big part for me.

**Comment by David-Chadwick** [comment]
@TallTed and if JWT is used there isnt even a Proof property :-)

**Comment by TallTed** [comment]
`MUST ... be be associated with` (which was in the March CR, and many months of previous drafts) is not the same as `MUST explicitly state` (which is what you want to have now).

Changing to the latter _would_ be a substantive and normative change, and one to which I (and I believe others) would object.

----

Note that I said "Proof *portion*" not "Proof *property*", which remains true with JWT (where the Proof portion would be JWS).

**Comment by David-Chadwick** [comment]
@dlongley  "An example of "implied" type information is a VC that includes an "ageOver" claim but no "type" ... and no other claims. The type for this VC could be inferred to be a "VerifiedAgeCredential" (should someone define this type)."
I think you are misunderstanding my position. It is perfectly OK for this VC to be only of type VC. If you read my proposed text you should see that it says this. The only time the VC type must be qualified is when new top level properties are entered in the VC that are not defined in the specification.

**Comment by brentzundel** [comment]
My misunderstanding that explicit typing was required by the March CR spec is precisely the reason why the clarification was added to make it clear that implicit types are allowed.
The resulting discussion makes it blindingly clear that the March CR spec language was inadequate and prone to misinterpretation, as both you and @TallTed pointed to the same block of text and interpreted it differently.
The resulting [WG Resolution](https://github.com/w3c/vc-data-model/pull/658#issuecomment-500874767) was that implicit types were always intended to be allowed, even if using them is not a great idea. This clarification is not substantive, as it does not change the intended meaning of the spec (according to the consensus of the WG).

**Comment by burnburn** [comment]
In the 16 July 2019 VCWG call:

RESOLVED: The Working Group has decided to revert the type section related to implicit typing to the text of the March 28 2019 Candidate Recommendation, and in addition we add a sentence which can be wordsmithed later, but the intention is to say "typing is complex so we refer readers to the implementation guide which contains more details.

Additionally, the group proposed the following text for "the sentence" mentioned above:  "The type system used in the data model described in this specification allows for multiple ways to associate types with data, implementers and authors are urged to read the section on typing in the Verifiable Credentials Implementation Guide."

Manu will create a PR using that text.  Once there are at least 3 review approvals (one from DavidC), the group agrees that Manu can merge the PR and close this issue.

**Comment by msporny** [comment]
PR #702 has been merged. Closing issue per unanimous WG consensus and resolution.
