### ISSUE TITLE
Inconsistencies between Figures and examples

### ISSUE THREAD

**Issue by mxshea** [w3c/vc-data-model#727]
In reading through the VC Data Model Proposed Recommendation 1.0, should the values in boxes of Figure 6 & 8 (created, creator, signatureValue) tie too elements in Example 1 & 2?

In Figure 6 in the Proof Graph, the Creator is Example University Public Key 7 and in Example 1- VerificationMethod": "https://example.edu/issuers/keys/1”.  Likewise the Signature Value in Figure 6 is “BavE110…” and in Example 1 - "jws": “eyJhbG…”

Likewise, in Figure 8, the values in the Presentation Proof Graph do not match to any of the values in Example 2, and the attribute 'termsOfUse' is missing in Example 2.

**Comment by brentzundel** [comment]
The chairs believe that improving consistency between figures and examples may be helpful. We do not believe the inconsistency is  considered errata, as the examples are currently independent and therefore consistency between them cannot be assumed. However, we do not oppose improving consistency within the spec if there are folks interested in working on that.

**Comment by TallTed** [comment]
> the examples are currently independent and therefore consistency between them cannot be assumed

It may be worth adding a non-normative note to the spec, expressing the above, nearby and/or linked from each figure and/or example.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-09-08-vcwg#section6-1) on 2021-09-08

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 6.1. Inconsistencies between Figures and examples (issue vc-data-model#727)

_See github issue [#727](https://github.com/w3c/vc-data-model/issues/727)._




**Brent Zundel:** First one to look at is issue 727.  
… "Inconsistencies between figures and examples"  
… This issue shows we have all these examples, and we have all these figures, but there's not uniformity between them.  
… The example text and the figure text are often representing different credentials.  
… If there were a way to unify those and improve the consistency, that would be fantastic.  
… Any comments? If anyone wants to try to fix it, let me know so we can assign it to you.  
… Otherwise we'll move forward.  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-10-27-vcwg#section2-5) on 2021-10-27

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.5. Inconsistencies between Figures and examples (issue vc-data-model#727)

_See github issue [vc-data-model#727](https://github.com/w3c/vc-data-model/issues/727)._




> *Kyle Den Hartog:* +1.

**phil:** assumes intent that this WG never committed to.  

**Kevin Dean:** matching them up would imply more causal or explanatory logic, would be an anti-pattern.  

**Brent Zundel:** as editor, i would say that if someone thinks examples SHOULD line up to figures, they should open a PR but that was never work the group committed to.  
… marking as pending close, not worrying about labels.  

</details>

**Comment by brentzundel** [comment]
no comments since being marked pending close, closing
