### ISSUE TITLE
4.1 Link to going anywhere that makes sense

### ISSUE THREAD

**Issue by vongohren** [w3c/vc-data-model#732]
```The data available at https://www.w3.org/2018/credentials/v1 is a static document that is never updated and SHOULD be downloaded and cached. The associated human-readable vocabulary document for the Verifiable Credentials Data Model is available at https://www.w3.org/2018/credentials. This concept is further expanded on in Section § 5.3 Extensibility.```

This 2018/credentials link in the bottom of 4.1 is just going to an empty folder on a web server. Not sure where it is suppose to point, but wanted to just give a heads up

**Comment by kdenhartog** [comment]
@iherman not really sure what we want to publish at this link, nor do I know if I've got the correct permissions to address this currently. Was the goal to have something like the [citizenship-vocab](https://w3c-ccg.github.io/citizenship-vocab/#the-citizenship-vocabulary) published at that location as an offical WG note that links back to the spec for all of the defined terms in the V1 context?

**Comment by kdenhartog** [comment]
@iherman I think the goal to get this fixed is that we need to get the [credentials.html](https://github.com/w3c/vc-data-model/blob/main/vocab/credentials.html) document published at the following link: https://www.w3.org/2018/credentials/

Is that something that I can do (would need instruction on this if so) or does it need to be done by you?

**Comment by iherman** [comment]
> @iherman I think the goal to get this fixed is that we need to get the [credentials.html](https://github.com/w3c/vc-data-model/blob/main/vocab/credentials.html) document published at the following link: https://www.w3.org/2018/credentials/
> 
> Is that something that I can do (would need instruction on this if so) or does it need to be done by you?

@kdenhartog, this is something only I can do. I would need an approval from the WG, though, that this is indeed the file I should put there.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-10-06-vcwg#section3-7) on 2021-10-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.7. 4.1 Link to going anywhere that makes sense (issue vc-data-model#732)

_See github issue [vc-data-model#732](https://github.com/w3c/vc-data-model/issues/732)._




**Brent Zundel:** [reads title "4.1 Link to going anywhere that makes sense"]  

**Kyle Den Hartog:** Context URLs are failing... that's the empty folder.  
… I think we need Ivan's help with this  
… The basic problem is the ids are not linking to the human-readable descriptions  

**Brent Zundel:** Thank you everyone  
… Chairs and editors will make transition request  

---


</details>

**Comment by kdenhartog** [comment]
@brentzundel can I ask that we add some time to the agenda tomorrow for this issue so that the WG can decide if that's the correct file to publish there.

**Comment by msporny** [comment]
We need to redirect https://www.w3.org/2018/credentials/ to go to https://w3c.github.io/vc-data-model/vocab/credentials.html

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-11-10-vcwg#section5-3) on 2021-11-10

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.3. 4.1 Link to going anywhere that makes sense (issue vc-data-model#732)

_See github issue [vc-data-model#732](https://github.com/w3c/vc-data-model/issues/732)._




> *Manu Sporny:* Should be vocab file that's here -- [https://github.com/w3c/vc-data-model/blob/main/vocab/credentials.html](https://github.com/w3c/vc-data-model/blob/main/vocab/credentials.html).

**Manu Sporny:** the link currently goes to an empty directory. It should be the vocabulary file that is displayed.  

**Ivan Herman:** do we want to copy the file or insert a redirect to the above url.  

**Manu Sporny:** I don't expect it to change much at all.  

**Ivan Herman:** manu please email me the file or link and I will put it there.  

> *Brent Zundel:* See [more details](https://github.com/w3c/vc-data-model/issues/732#issuecomment-937027226).

**Manu Sporny:** I suggest we do a redirect so that we don't have to ask W3C staff to make updates should there be any.  
… specifically, [https://w3c.github.io/vc-data-model/vocab/](https://w3c.github.io/vc-data-model/vocab/).  

> *Brent Zundel:* we need to redirect [https://www.w3.org/2018/credentials/](https://www.w3.org/2018/credentials/) to point to [https://github.com/w3c/vc-data-model/blob/main/vocab/](https://github.com/w3c/vc-data-model/blob/main/vocab/).

**Ivan Herman:** will ask the system people to set up a proxy.  

---

</details>

**Comment by brentzundel** [comment]
this has been addressed, closing

**Comment by kdenhartog-mattr** [comment]
It appears the link is now working - https://www.w3.org/2018/credentials/

Thanks for raising @vongohren and thanks for fixing @iherman

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-01-vcwg#section4-6) on 2021-12-01

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.6. 4.1 Link to going anywhere that makes sense (issue vc-data-model#732)

_See github issue [vc-data-model#732](https://github.com/w3c/vc-data-model/issues/732)._




**Kyle Den Hartog:** I think this was in Ivan's hands, link looks right -- vocab definitions have been published at the right link..  

**Brent Zundel:** any objections to closing?.  

> *Manu Sporny:* No objections..

**Brent Zundel:** We're done - thanks everyone for coming, be sure to jump in -- conversation happening on draft charter as well as v1.1 issues that we have agreed to get in some time after v1.1.  

> *Phil Archer:* RRSAgent: draft minutes.

> *Phil Archer:* Zakim: end meeting.

**Brent Zundel:** Thanks for coming, thanks Manu and Dmitri for scribing, looking forward to seeing you all next week..  

---

</details>
