### ISSUE TITLE
Example uses a timestamp for what should just be a (floating) date value (editorial nit)

### ISSUE THREAD

**Issue by aphillips** [w3c/vc-data-model#733]
Section 4.10, Example 9
https://w3c.github.io/vc-data-model/#presentations-0

> A basic claim expressing that Pat's date of birth is 2010-01-01T19:23:24Z. Date encoding would be determined by the schema. 

This example shows timestamp being used for a floating time value. Date of birth should normally be just a date (without time-of-day units or time zone). The example given is actually January 2nd in much of the world.

_This comment was an I18N comment that we forgot to send to you previously. This is a minor editorial nit, potentially addressed by the sentence about "date encoding"_

**Comment by kdenhartog** [comment]
Partially addressed in #806 the related SVG also needs to be updated still

**Comment by kdenhartog** [comment]
I believe this one has been addressed in multiple PRs, but want to dig up the links before closing. Going to label pending close for this for now.

**Comment by kdenhartog** [comment]
This issue was originally addressed via #806 and #807 and then due to the way in which we were handling branching, the easiest solution for getting both PRs through was to take the commits from #807 and add them to the PR on #806. The following commit in #806 that brought it in can be found here: https://github.com/w3c/vc-data-model/pull/806/commits/8bdafc118bd810860fb478dceeebd4daebbc091d

I believe this one is properly addressed at this point and can be closed. The Editorial and Errata labels have been included on this issue as well so I'll be removing them from the PRs
