### ISSUE TITLE
URIs or URLs for ids

### ISSUE THREAD

**Issue by clehner** [w3c/vc-data-model#748]
The `id` property for `credentialStatus`, `refreshService`, and `evidence` objects are specified as URLs:

- "Each refreshService value MUST specify its type [...] and its id, which is the URL of the service"
- "The value of the credentialStatus property MUST include the [...] id property, which MUST be a URL."
- "The value of the evidence property MUST be one or more evidence schemes [...] The id property is optional, but if present, SHOULD contain a URL"

Other `id` properties are specified as URIs:
- (§4.2) "The value of the id property MUST be a single URI"
- "The value of the `@context` property MUST be an ordered set where the first item is a URI with the value https://www.w3.org/2018/credentials/v1"
- (credentialSubject) "Each object MAY contain an id, as described in Section § 4.2 Identifiers."
- "The value of the issuer property MUST be either a URI or an object containing an id property. It is RECOMMENDED that the URI in the issuer or its id [...]" 
- "If present, the value of the holder property is expected to be a URI for the entity that is generating the presentation."
- "Each credentialSchema MUST specify its type [...], and an id property that MUST be a URI"
- (presentations) "The id property is optional and MAY be used to provide a unique identifier for the presentation. For details related to the use of this property, see Section § 4.2 Identifiers."

Could the credential status id, refresh service ids, and evidence object ids be just URIs, like the other id properties? Or is it really meant that they should/must be URLs?

Also, should the `id` property of a `termsOfUse` object or of a credential `issuer` object be expected to be a URI?

Section § 4.2 Identifiers specifies the `id` property - but I am not sure if that is meant to apply to all uses of `id` properties, or only ones which specifically reference §4.2 or are described in §4.2 (like in Example 4).

**Comment by TallTed** [comment]
I would say that the instances of `URL` flagged here should be changed to `URI`.

This is likely true of all occurrences of `URL` in the doc, but I cannot say definitively without seeing each occurrence in context.

**Comment by kdenhartog** [comment]
This seems like it would be a substantive change, but does seem like something we could address within the purview of the V1.1 maintainence WG work. I've labeled it as such for now.

**Comment by brentzundel** [comment]
Reminder, substantive changes that are in scope for the maintenance group should be labeled v1.2, per https://github.com/w3c/vc-data-model#process-overview-for-vc-data-model-pull-requests
also, thank you @kdenhartog for triaging so many issues

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-09-08-vcwg#section5-3) on 2021-09-08

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.3. URIs or URLs for ids (issue vc-data-model#748)

_See github issue [#748](https://github.com/w3c/vc-data-model/issues/748)._




> *Brent Zundel:* [https://github.com/w3c/vc-data-model/issues/748](https://github.com/w3c/vc-data-model/issues/748)

**Brent Zundel:** URIs or URLs for ids. We specify things as URLs in the spec  
… There is some confusion there. Ted has suggested that yes, they should be changed to URI.  
… We would need a PR that goes through and makes those changes.  
… There doesn't seem to be consensus that this is something that needs to be done for sure.  
… But there's a discrepancy, essentially... That discrepancy is confusing.  
… Anyone want to make a PR?  

**David Chadwick:** I have a comment. The standard is saying something should be a URI... This is not a breaking change.  
… If anyone using v1.0 is using a URL, they're still conforming if it's a URI, since a URL is a URI.  

**Brent Zundel:** If an implementer is insisting that a credentialStatus is a URL and not a URI, and doing type checking like that, then their implementation would be flagging v1.0 URLs as incorrect.  

**David Chadwick:** Right, that would break implementations. I withdraw my comment.  

**Charles Lehner:** I can do it, considering I opened the issue.  

**Brent Zundel:** I will add you to the assignee list, and look forward to seeing the PR.  

**Dave Longley:** I don't know if anyone can tell looking at syntax whether something is a URI or URL... might not be something you could implement... given that, it might not be a substantive change.  

**Brent Zundel:** I appreciate that comment.  
… I'm open to - if folks feel the issue is mislabeled - relabeling it; that's no problem.  
… The decision to label it as a substantive change was an editorial decision.  
… What do folks here feel, is it possibly appropriate? ... We should err on the side of caution...  

**Dave Longley:** I don't feel very strongly either way, but thought it was worth making that comment.  

**David Chadwick:** I would not object to it in v1.1  
… You've got a problem if it can't get in next week - if Charles gets the flu, we're sunk...  

**Brent Zundel:** It also has to do with - if we are asserting that this is an editorial change, we don't have to submit for editorial review.  
… Because there were normative statements... will leave it 1.2 for now.  

> *Dave Longley:* +1 to being conservative and doing 1.2

> *Dave Longley:* no reason to jeopardize 1.1 on account of it

</details>

**Comment by kdenhartog** [comment]
Thanks @clehner for taking care of this

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-09-15-vcwg#section5-3) on 2021-09-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.3. URIs or URLs for ids (issue vc-data-model#748)

_See github issue [#748](https://github.com/w3c/vc-data-model/issues/748)._




> *Kyle Den Hartog:* [https://github.com/w3c/vc-data-model/issues/748](https://github.com/w3c/vc-data-model/issues/748)

**Charles Lehner:** This issue was about a variation between URLs and URIs and there's a PR open to address it  

**Brent Zundel:** We discussed earlier that a determination needs to be made around if this is errata or now  
… there's an argument to be made that it's not and I'm happy to here arguments on if it is errata  
… right now it's considered an errata and we need to finalize that decision as a WG  

**David Chadwick:** I don't think we have to resolve this today - can give Manu more time.  

**Kyle Den Hartog:** I agree, and expect he may be able to cover it, although he may be on vacation.  

</details>
