### ISSUE TITLE
Cover "authenticatability" of credential

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#751]
From Paul Knowles:

Add something to this effect to refer to what is meant by "verifiable":

> The characteristic of verifiability refers to the signatures on the credential which are verifiable. It does not refer to the authenticability of the claims within the credential itself. A Verifiable Credential can therefore be thought of as an authenticable credential that can be verified.

**Comment by David-Chadwick** [comment]
On 13/10/2020 02:00, Manu Sporny wrote:
> The characteristic of verifiability refers to the signatures on the 
> credential which are verifiable

No, its more than this. If you are only checking the signature, then 
that is authentication only.

Verifiability means also that the syntax of the entire VC is correct, 
its @context and schema.

Kind regards

David

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-10-06-vcwg#section3-3) on 2021-10-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.3. Cover "authenticatability" of credential (issue vc-data-model#751)

_See github issue [vc-data-model#751](https://github.com/w3c/vc-data-model/issues/751)._




**Charles Lehner:** I looked at this and started trying to write something to address it. It was too difficult, but I could post what I have or link to it.  

> *Dave Longley:* [https://www.w3.org/TR/vc-data-model/#dfn-verify](https://www.w3.org/TR/vc-data-model/#dfn-verify) is what the spec says today

**Ted Thibodeau Jr.:** comment that on the issue  

**Charles Lehner:** thanks, i'll do that  

**Brent Zundel:** We do have a verify definition, but look forward to comments from cel, but don't see reason to take away Manu's assignee status there.  

</details>

**Comment by TallTed** [comment]
In both paragraphs [suggested above](https://github.com/w3c/vc-data-model/issues/751#issuecomment-946074037) by @clehner, `does not necessarily imply` should just be `does not imply`. The `necessarily` implies that the implication which follows is *typically*, but not *always*, intended.

The truthfulness or trustworthiness of the issuer is left to the verifier to decide, by whatever means (another rubric?) they deem sufficient in and for their business logic.

The latter paragraph, expanding on the definition of verification, suggests that there `may be specifically requested by a verifier` some `evaluation of the the truth content of claims encoded in the credential`.  I do not believe there is any way for the verifier to make such request, so that paragraph should lose its closing `except` clause.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-01-vcwg#section4-3) on 2021-12-01

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.3. Cover "authenticatability" of credential (issue vc-data-model#751)

_See github issue [vc-data-model#751](https://github.com/w3c/vc-data-model/issues/751)._




**Manu Sporny:** if there is a PR, it's not linked....  

**Brent Zundel:** PR 829.  

**Manu Sporny:** ah yes, ok. The status is -- hey, there's a PR! :).  
… that Charles wrote. so we should assign him..  

</details>

**Comment by brentzundel** [comment]
The associated PR has been merged, closing
