### ISSUE TITLE
Defining a V2 context here will require an update to normative statements

### ISSUE THREAD

**Issue by kdenhartog** [w3c/vc-data-model#755]
Is it appropriate for us to update the normative statement below under our current maintenance charter?

`The value of the @context property MUST be an ordered set where the first item is a URI with the value https://www.w3.org/2018/credentials/v1.`

to 

`The value of the @context property MUST be an ordered set where the first item is a URI with the value https://www.w3.org/2018/credentials/v1 or https://www.w3.org/2020/credentials/v1`

**Comment by brentzundel** [comment]
The chairs feel that work on this issue is outside the scope of the maintenance working group.
This doesn't mean work cannot continue, but that it would need to be included a future version of the specification.

**Comment by kdenhartog** [comment]
That's alright. It will make the security-vocab v3 work a bit obsolete, but I think we're trending towards smaller contexts (not kitchen sink ones) unline security-v3-unstable is currently.

**Comment by OR13** [comment]
See https://github.com/w3c/vc-data-model/issues/904

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-08-10-vcwg#section4-4) on 2022-08-10

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.4. Define v2 context (issue vc-data-model#755)

_See github issue [vc-data-model#755](https://github.com/w3c/vc-data-model/issues/755)._




> *Manu Sporny:* +1 to keeping it open, it's relevant..

**Kristina Yasuda:** I think the previous WG didn't do this because it was a normative change.  

**Orie Steele:** We definitely need to start a new version of the context file, so we can make changes to it..  
… In favor of getting us capable of making changes to the context asap..  

**Kristina Yasuda:** Is this the right issue to do that?.  

> *Michael Prorock:* +1 to new context file.

**Orie Steele:** I'm requesting we have a v2 context file. This issue asks the question if we have permission to do that..  

> *Dave Longley:* +1 to close the issue, we can now define a v2 context in this WG.

> *Ivan Herman:* +1 to Manu, a v2 context will come up anyway.

**Manu Sporny:** Short answer is yes we can create a v2 context. We should close the issue since it's misleading what it's asking for. v2 context will happen naturally. If we need an issue for that, we should open a new issue dedicated to this..  

_See github issue [vc-data-model#904](https://github.com/w3c/vc-data-model/issues/904)._




</details>

**Comment by kdenhartog** [comment]
+1 to closing this one. I'm the author so I'm going to close this early as well
