### ISSUE TITLE
Add details about difference between contexts and credentialSchemas property 

### ISSUE THREAD

**Issue by kdenhartog** [w3c/vc-data-model#781]
@OR13 has written a very descriptive and detailed point in the [CCG mailing list](https://lists.w3.org/Archives/Public/public-credentials/2021Jun/0126.html) about how the `@context` and the `credentialSchema` properties are intended to be used and the particular problems they should solve. This issue is being added to track distilling the points he raised into an editorial piece of text in order to help people who utilize VCs.

**Comment by kdenhartog** [comment]
@OR13 I can take care of adding this. Thanks for writing it up into the email and answering the question.

**Comment by OR13** [comment]
@kdenhartog thanks!

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-10-06-vcwg#section3-4) on 2021-10-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.4. Add details about difference between contexts and credentialSchemas property  (issue vc-data-model#781)

_See github issue [vc-data-model#781](https://github.com/w3c/vc-data-model/issues/781)._




**Kyle Den Hartog:** I have a partially written branch on this... will get around to it.  
… Trying to editorialize what was stated in that CCG thread, and put it in an appendix  

**David Chadwick:** [offered to help with 781]  

</details>

**Comment by David-Chadwick** [comment]
I have written a (rather wordy) tutorial document describing the differences between the type, @context and credentialSchema properties. It is too long for a PR, but it could form the basis for a PR. Currently it is a word processing document 1.5 pages long
[VCpropertyDescriptions.docx](https://github.com/w3c/vc-data-model/files/7637414/VCpropertyDescriptions.docx)
Let me know what you think

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-01-vcwg#section4-2) on 2021-12-01

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.2. Add details about difference between contexts and credentialSchemas property  (issue vc-data-model#781)

_See github issue [vc-data-model#781](https://github.com/w3c/vc-data-model/issues/781)._




**Kyle Den Hartog:** I still have a partial branch here... need to write a few paragraphs, translate email thread that Orie pointed out wrt. @context purpose what credential schema is for -- status is ongoing, could fit in v1.1, haven't done it yet..  

**Brent Zundel:** anticipated timeline to PR?.  

**Kyle Den Hartog:** in a few weeks..  

**David Chadwick:** For my team, they also wanted to know this -- wrote a document that describes difference between context/schema/type -- I have that document, happy to share it w/ Kyle and the group..  
… If we want to use that as basis for PR, would be happy with that..  
… It's a page of content..  

</details>
