### ISSUE TITLE
RFC 3339 vs ISO8601 vs XSD Date Time 

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-model#782]
IMO, the spec fails to define datetime's correctly.

consider:

> A credential MUST have an issuanceDate property. The value of the issuanceDate property MUST be a string value of an [RFC3339] combined date and time string representing the date and time the credential becomes valid, which could be a date and time in the future.

https://w3c.github.io/vc-data-model/#issuance-date

yet: https://github.com/w3c/vc-data-model/blob/main/contexts/credentials/v1#L44

RFC3339 !== XSD Date Time.

See the differences summarized [here](https://atom-syntax.imc.narkive.com/x8nvl4Bh/xsd-datetime-vs-rfc-3339) and [here](https://medium.com/easyread/understanding-about-rfc-3339-for-datetime-formatting-in-software-engineering-940aa5d5f68a)

Most notably:

>  RFC 3339 allows lower- and upper-case 'T' and 'Z', while
xsd:dateTime requires upper-case only. 

> RFC 3339 allows the replacement of the 'T' with a space which
xsd:dateTime does not. [Note: ISO 8601 doesn't either, hence RFC
3339 isn't actually a "profile of ISO 8601" as it claims].

> RFC 3339 does not allow the hour 24 but xsd:dateTime does (in
xsd:dateTime [as in ISO 8601] 00 & 24 both represent midnight, but
24 means the end of one day while 00 means the start of the next)

>  RFC 3339 gives a different semantic to a timezone offset of -00:00 from
+00:00 and Z which xsd:dateTime (and to the best of my knowledge
ISO 8601) doesn't.

In short, I believe it was an error to point to RFC 3339, and instead we should have referenced ISO 8601 directly...

> RFC 3339 is following the ISO 8601 DateTime format. The only difference is RFC allows us to replace “T” with “space”.

This means that VC that is normatively compliant can have an issuance date which is neither valid ISO 8601 nor valid XSD Date Time.

Most credentials I have observed in the wild use `ISO 8601`.

Additionally, https://w3c.github.io/vc-data-model/#jwt-encoding

> For backward compatibility with JWT processors, the following JWT-registered claim names MUST be used ***instead of, or in addition to, their respective standard verifiable credential counterparts***

> nbf MUST represent issuanceDate, encoded as a UNIX timestamp (NumericDate).

yet:

> A credential MUST have an issuanceDate property. 

https://w3c.github.io/vc-data-model/#issuance-date

This produces an obvious logical impossibility for normative implementations. 

(issuanceDate cannot be omitted as the JWT section claims), 

...however the JWT processing section is at least pointing to a datetime representation that is compatible with practical datetime reality... https://www.unixtimestamp.com/

Adding this up, put yourself in the shoes of a spec implementer... You have 2 extreme possibilities:

1. YOLO `issuanceDate` and treat it as an opaque string based on confusion summarized above.
2. Use ISO 8601, XSD Date Time and Unix Time Stamps instead of RFC 3339.

It might seem obvious that you would choose 2, but you will be forced to fail normatively valid credentials, such as these:

```jsonc
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/security/suites/jws-2020/v1"
  ],
  "id": "http://example.edu/credentials/3732",
  "type": ["VerifiableCredential"],
  "issuer": {
    "id": "did:key:z6MkhRZ7XMcydYWTYGQrVxKXaG9Bpd3LrbA345QGWNMaSxeE"
  },
  // note space is legal to RFC 3339 but not ISO 8601 or XSD Date Time
  "issuanceDate": "2021-07-11 13:32:11.063Z", 
  "credentialSubject": { "id": "did:example:ebfeb1f712ebc6f1c276e12ec21" },
  "proof": {
    "type": "JsonWebSignature2020",
    // legal ISO 8601 AND XSD Date Time
    "created": "2010-01-01T19:23:24Z",
    "verificationMethod": "did:key:z6MkhRZ7XMcydYWTYGQrVxKXaG9Bpd3LrbA345QGWNMaSxeE#z6MkhRZ7XMcydYWTYGQrVxKXaG9Bpd3LrbA345QGWNMaSxeE",
    "proofPurpose": "assertionMethod",
    "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..WGofUrPdHhJG2rxoVDLDynOHcZaqS2g5PJtCqOsvQ4ePKl_so1jZMytBX3sbkbbrzqG03Nhpe_zgymVfDaX6Bw"
  }
}
```

Consider the equivalent VC-JWT representation that happens to also be valid JSON-LD, you are now forced to convey the issuance date as being "XSD Date Time" in JSON-LD, yet its string representation is RFC 3339 and its additional unix timestamp is equivalent to all 3 (legally) even though its JSON-LD term definition is contradicting the normatively term definition.

Again, the problem is referring to RFC 3339.... 

ISO 8601 + XSD Date Time + Unix Timestamps are all happy friends.... RFC 3339 is a mistake.

**Comment by csuwildcat** [comment]
@OR13 I will never ceased to be impressed by your attention to detail and precision

**Comment by dlongley** [comment]
> ISO 8601 + XSD Date Time + Unix Timestamps are all happy friends.... RFC 3339 is a mistake.

@OR13, I agree with you. When this came up before, the i18n group weighed in with a recommendation of RFC3339 here:

https://github.com/w3c/vc-data-model/issues/437

I'd be happy for us to figure out a better way forward.

**Comment by OR13** [comment]
I would pick a string datetime format that is XSD Date Time, ISO 8601 and converts back and forth to unix in a stable manner, and make that string format the required format.

**Comment by kdenhartog** [comment]
I've opted to indicate this as a substantive change that can be addressed in the V1.1 version by the maintainence WG due to the confusion between what's commonly being implemented and what has been defined by the spec. It's a substantive change though due to this likely affecting normative statements.

**Comment by brentzundel** [comment]
Reminder that anything in scope for the maintenance group, but substantial, should be marked v1.2, per https://github.com/w3c/vc-data-model#process-overview-for-vc-data-model-pull-requests

**Comment by kdenhartog** [comment]
Thanks for that reminder. I've gone and re-read through it for a refresher now. I'll go in and fix any of the ones that I mislabeled yesterday.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-09-08-vcwg#section5-1) on 2021-09-08

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.1. RFC 3339 vs ISO8601 vs XSD Date Time  (issue vc-data-model#782)

_See github issue [#782](https://github.com/w3c/vc-data-model/issues/782)._




> *Brent Zundel:* [https://github.com/w3c/vc-data-model/issues/782](https://github.com/w3c/vc-data-model/issues/782)

**Brent Zundel:** RFC 3339 vs ISO8601 vs XSD Date Time  
… At one point, the specification did use ISO8601 dates. In a conversation with the W3, internationalization group came in I believe, and said, hey, you should really be using RFC 3339.  
… So what needs to happen here is a recommendation or determination of what needs to go forward.  
… We can have a conversation... I think the best thing would be if a PR shows up to make a recommendation, and we can have the discussion there.  

</details>

**Comment by kdenhartog** [comment]
@msporny Can I reference non-normative sections of a normative document?

I'm thinking the following phrase would solve this:

```
A credential MUST have an issuanceDate property. The value of the issuanceDate property MUST be a string value of an [ISO8601] combined date and time string and MUST follow the Date and Time Formats defined in [XML Schema 2.0](https://www.w3.org/TR/xmlschema-2/#truncatedformats) for representing the date and time the credential becomes valid, which could be a date and time in the future. It MUST also follow the conventions outlined in 
```

**Comment by msporny** [comment]
@kdenhartog wrote:
> I'm not finding anywhere else that XSD datetime format is being normatively defined

`xsd:dateTime` is normatively defined here: https://www.w3.org/TR/xmlschema11-2/#dateTime

I believe that's the latest standard, but you may want to double check.

@OR13's analysis sounds right to me.

@kdenhartog, rather than write more text, we should simplify and use some variation of the language in DID Core for `datetime` values (that is, don't refer to ISO8601, but XMLSCHEMA11-2):

https://w3c.github.io/did-core/#dfn-datetime

"A date and time value that is capable of losslessly expressing all values expressible by a dateTime as specified in [XMLSCHEMA11-2]"

The suggestion is to use dateTime from XML Schema v1.1 Part 2: Datatypes (latest version is from 2012 vs. 1988 for ISO8601).

/cc @aphillips to tell us if there is some issue w/ changing from RFC3339 to XMLSCHEMA11-2 due to the problems we've hit using RFC3339. Would a11y object to such a change, or are there any gotchas that we're not seeing?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-09-15-vcwg#section5-2) on 2021-09-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.2. RFC 3339 vs ISO8601 vs XSD Date Time  (issue vc-data-model#782)

_See github issue [#782](https://github.com/w3c/vc-data-model/issues/782)._




**Kyle Den Hartog:** Next we have 782  
… Orie found some good details where xsd:dateTime is slightly different from what's defined within RFC 3339, then goes to highlight this.  
… There's currently no PR open. It was my intention to open a PR for this, but not sure how to do it. Manu has dropped some suggestions...  
… We're waiting for someone from i18n since they opened it.  

**Brent Zundel:** My recommendation is if we get in a PR today, we can announce it is under review at the CCG today... then we can refine that PR according to discoveries we make during the two-week PR, and will have addressed the process requirements  
… so that this change can end up as part of our revision.  

**Kyle Den Hartog:** That makes sense.  
… I'm uncertain if I'll get to it today - but in the next day or two.  

**Brent Zundel:** As long as we get a PR whose review period would end by end of September, we should be okay. So today or tomorrow.  

</details>
