### ISSUE TITLE
Clarify the difference between Credential and Verifiable Credential

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#798]
It was agreed at the VC-WG meeting on 18 Aug that the spec should clearly differentiate between credentials/presentations and the verifiable versions of these, and that regardless of how the verifiying component is added (JWT, LD-proof, ZKP) nevertheless in all cases the underlying credential/presentation should be identical. This means that when the verifier removes the proof, it should end up with the same credential/presentation data structure in all cases. This issue is a placeholder to ensure that appropriate PR text is created for v1.1

**Comment by kdenhartog** [comment]
Labelled this as V1.1 under the assumption this issue is focused on "the spec should clearly differentiate between credentials/presentations and the verifiable versions of these, and that regardless of how the verifiying component is added (JWT, LD-proof, ZKP) nevertheless in all cases the underlying credential/presentation should be identical."

If this issue is going to instead focus on making `credentialSubject.id` it should be relabeled as V2 and deferred for later.

**Comment by David-Chadwick** [comment]
This issue is and remains as its title suggests. Therefore it is a 1.1 clarification. Anything else (e.g. credential.id or subject ids or other topics) should be listed in separate issues.

**Comment by mwherman2000** [comment]
> If this issue is going to instead focus on making `credentialSubject.id`...

I don't think this phase/sentence is complete.  Can you clarify it @kdenhartog ?

**Comment by kdenhartog** [comment]
> This issue is and remains as its title suggests. Therefore it is a 1.1 clarification. Anything else (e.g. credential.id or subject ids or other topics) should be listed in separate issues.

Yup agreed. Thanks for filing the PR as well.

> I don't think this phase/sentence is complete. Can you clarify it @kdenhartog ?

Yup, sorry was jumping in and out of different contexts when writing that. Here's what I meant to say. If this issue is going to instead focus on making normative changes to credentialSubject.id like requiring it's usage it should be relabeled as V2 and deferred for later.

I think it's a question that can be considered again (this is how it originally was stated and I believe through integration of ZKPs it was made optional), but let's move it to another issue and defer it to V2. That way this issue can be closed out when #808 is merged.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-10-27-vcwg#section2-4) on 2021-10-27

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.4. Clarify the difference between Credential and Verifiable Credential (issue vc-data-model#798)

_See github issue [vc-data-model#798](https://github.com/w3c/vc-data-model/issues/798)._




**Manu Sporny:** i remember a PR merged that addressed this, i think we're done and good to close here.  

**Brent Zundel:** kyle, i see you commenting on the thread, anything to add?.  

**Kyle Den Hartog:** i can't remember what happened with pull 808.  

**Manu Sporny:** I remember, this PR was mis-targeted to main, commits had to be cherry-picked before walking back from main.  
… in 824... i want us to make sure we're linking the right PR and the PR got merged to the right branch.  

**Kyle Den Hartog:** yup i'm looking at the commit right here, it's on the v1.1 branch, we're good to close.  

</details>
