### ISSUE TITLE
Remove proof property from most examples

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#811]
Now that we have some proposed text to clarify the difference between a credential (presentation) and verifiable credential (presentation), I think it would be a good idea for most of the examples in sections 4 and 5 e.g. for type, issuer, issuanceDate etc. to remover the "proof": {...} property from the examples as: 
i) it wrongly implies that all verifiable credentials will have the proof property, and
ii) it has nothing to do with the property being described.

The place to introduce the proof property  "proof":{..} is in section 4.7 which deals specifically with proofs.

Footnote. When the recommendation was being drafted I for one originally thought that the proof property would always be present for every VC, and if the VC was JWT signed, then the proof property would say something about the JWT. We did discuss this at length, but eventually it was agreed not to have a proof property for JWT signed VCs. Thus I think the right thing to do now is to remove it from all the examples where it is not relevant.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-09-08-vcwg#section4-2) on 2021-09-08

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.2. Remove proof property from most examples (issue vc-data-model#811)

_See github issue [#811](https://github.com/w3c/vc-data-model/issues/811)._




**Brent Zundel:** Next, issue 811  

**David Chadwick:** Right, this is mine that I raised earlier in this meeting.  
… If people agree, we can remove the `"proof": ...` except for the section that talks about proof.  

**Brent Zundel:** The conversation earlier, nobody objected to that.  
… So I would move on with the PR. I'll throw a label on it.  
… Now we can look at the last one - also yours, David.  
… v1.1 or v1.2  

</details>

**Comment by kdenhartog** [comment]
The reason for relabeling this during TPAC was that there's disagreement around how this removal should be represented. Presuming we're able to update the examples to have tabbing included then adding this change wasn't an issue. However, there was some concern around completely removing proof properties from the examples.

I think the solution here is that we hold off on merging #817 and instead go forward with the multi-tabbed approach where credential and verifiable credential objects can be represented with the various descriptive proof objects included.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-10-27-vcwg#section2-7) on 2021-10-27

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.7. Remove proof property from most examples (issue vc-data-model#811)

_See github issue [vc-data-model#811](https://github.com/w3c/vc-data-model/issues/811)._




**Manu Sporny:** seems a lot of work, more than 1.1 timeline allows.  

**Kyle Den Hartog:** +1 from me, manu speaks my mind.  

**Brent Zundel:** for the record, any issue labeled as editorial can be PRd at any time, regardless of version timelines! feel free to do this, if you're listening/reading this and have strong feelings.  

</details>

**Comment by Sakurann** [comment]
vc-data-model v1.1 already has examples of credential and verifiable credential separately, so we can close this issue.

**Comment by brentzundel** [comment]
No comments since marked `pending close`, closing
