### ISSUE TITLE
[VC-DATA-MODEL] This recommendation has no stated purpose, goals, or intended audience statements.

### ISSUE THREAD

**Issue by mwherman2000** [w3c/vc-data-model#813]
The text of the VC data model recommendation has no stated purpose, goals, or intended audience statements.

This has lead to confusion amongst members of the WG in terms of what should/should not be in the recommendation as well as how should the content should/needs to be expressed (e.g. use of JSON-LD in the VC examples).

Lots of folklore but the text of the recommendation itself has:
- no stated purpose
- no stated goals, or 
- no intended audience statements.

Nothing to measure the outcomes or the quality of the recommendation document by.

**Comment by mwherman2000** [comment]
In effect, using consensus, the current WG has selected themselves - a group of early adopter/innovators (https://hyperonomy.com/2019/10/16/technology-adoption-models/) - as their own audience for this recommendation vs. a wider audience of developers at large. 

The intended audience should be the decades and decades of new developers that we're trying to attract.

While not really intentional, I believe what we're seeing is actually an "abuse" of the consensus process best solved by having clearly stated purpose, goals, and intended audience statements written into the text of the recommendation.

**Comment by mwherman2000** [comment]
@FYI: I'm starting on the PR for this.

**Comment by brentzundel** [comment]
@mwherman2000 please don't add labels to issues or PRs. The triage of issues and subsequent labelling is an editor's job and should reflect agreement from the working group.

**Comment by brentzundel** [comment]
Speaking as a working group member, I feel that the introduction already adequately covers the purpose and goals of the recommendation:

> This specification provides a standard way to express credentials on the Web in a way that is cryptographically secure, privacy respecting, and machine-verifiable.

I do not see the necessity of formally describing an intended audience beyond anyone interested enough in web standards to read it. Self-selecting limitations on that potential audience pool doesn't make sense to me.

**Comment by brentzundel** [comment]
> In effect, using consensus, the current WG has self-selected themselves - a group of early adopter/innovators (https://hyperonomy.com/2019/10/16/technology-adoption-models/) - as their own audience for this recommendation vs. a wider audience of developers at large.
> 
> The intended audience should be the decades and decades of new developers that we're trying to attract.
> 
> While not really intentional, I believe what we're seeing is actually an "abuse" of the consensus process best solved by having clearly stated purpose, goals, and intended audience statements written into the text of the recommendation.

Speaking as a VCWG chair, comments like this are antagonistic and not acceptable. They communicate a significant lack of respect and may be construed as a violation of the [Positive Work Environment at W3C: Code of Ethics and Professional Conduct](https://www.w3.org/Consortium/cepc/). Please refrain from insinuations and attacks such as this in the future.

**Comment by mwherman2000** [comment]
> Speaking as a working group member, I feel that the introduction already adequately covers the purpose and goals of the recommendation:
> 
> > This specification provides a standard way to express credentials on the Web in a way that is cryptographically secure, privacy respecting, and machine-verifiable.
> 
> I do not see the necessity of formally describing an intended audience beyond anyone interested enough in web standards to read it. Self-selecting limitations on that potential audience pool doesn't make sense to me.

I had already written the PR and have submitted it to the WG for its consideration: https://github.com/w3c/vc-data-model/pull/814

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-09-15-vcwg#section6-2) on 2021-09-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 6.2. [VC-DATA-MODEL] This recommendation has no stated purpose, goals, or intended audience statements. (issue vc-data-model#813)

_See github issue [#813](https://github.com/w3c/vc-data-model/issues/813)._




**Kyle Den Hartog:** #813. This is actually a non-triaged one - what we want to do in terms of handling the PR that is already opened.  
… We've been able to discuss this now... about making sure that people are reviewing this.  
… I think the general assessment here is that if there is something, it would be a v1.1.  
… My personal take is that these are kind of obvious things that don't need to be statement.  

> *Brent Zundel:* +1

**Kyle Den Hartog:** So I kind of see this as a non-issue if it is anything.  

**Brent Zundel:** Agree... does anyone disagree that this is a v1.1?  

> *Dave Longley:* it if ends up being addressed it's 1.1, IMO

**Brent Zundel:** if it ends up being addressed, that it is non-normative and non-substantive?  
… Okay, I'll go ahead and add the v1.1 label to it, and we can move on.  

**Kyle Den Hartog:** Sweet, thank you. Next one is #815.  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-10-27-vcwg#section2-8) on 2021-10-27

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.8. [VC-DATA-MODEL] This recommendation has no stated purpose, goals, or intended audience statements. (issue vc-data-model#813)

_See github issue [vc-data-model#813](https://github.com/w3c/vc-data-model/issues/813)._




**Brent Zundel:** most of this conversation is between me and issue-raiser, it gets kinda meta at times....  

> *Kyle Den Hartog:* +1 with that plan.

**Manu Sporny:** i would recommend marking it v2 and assign a PR to michael (the raiser).  

**Brent Zundel:** objections?.  

> *Juan Caballero:* (none).

</details>

**Comment by brentzundel** [comment]
recommend closing without further action

**Comment by brentzundel** [comment]
No response since marked `pending close`, closing.
