### ISSUE TITLE
VC-DATA-MODEL: adding more examples of non json-ld credentials

### ISSUE THREAD

**Issue by mwherman2000** [w3c/vc-data-model#815]
Recasting https://github.com/w3c/vc-data-model/pull/803#issuecomment-916128717 as a new issue (at the suggestion of the WG chair (https://github.com/w3c/vc-data-model/pull/803#issuecomment-916284200)):

> RE: I'd be open to you adding more examples of non json-ld credentials, but I'm not interested in removing things that have already been acceptable and around for years now.
> 
> I will create a JSON, non-JSON-LD example for every JSON-LD example. I can submit a PR within the next couple hours.
> 
> Is this seriously what you're asking for @kdenhartog? ...it's completely backwards IMO.
> Read [#803 (comment)](https://github.com/w3c/vc-data-model/pull/803#issuecomment-915634629)

@kdenhartog Can you confirm whether or not you are asking for a JSON example to be added to the VC Data Model v1.1 Recommendation for every JSON-LD example?  

Related: 
- https://github.com/w3c/vc-data-model/issues/813 
- https://github.com/w3c/vc-data-model/pull/814

**Comment by mwherman2000** [comment]
It's 2pm here. I'll wait until this evening to hear back with some feedback. I'll wait until later this evening to give @kdenhartog a chance to reply (he and I are almost exactly 12 hours different timezone wise).  Then I'll start in on the minimal JSON versions of all of the examples.

Question: Is there a W3C HTML mechanism for showing 2 versions of some code (e.g. Java and C# or JSON and JSON-LD) with pasting them linearly into the document one after another? ...hope this question makes sense.

**Comment by kdenhartog** [comment]
>Question: Is there a W3C HTML mechanism for showing 2 versions of some code (e.g. Java and C# or JSON and JSON-LD) without pasting them sequentially into the document one after another? ...hope this question makes sense.

If you're going this route I think showcasing examples in different representations for each one makes a lot of sense. In my mind, this is likely to be the best method of highlight the abstract data model better as well.

As for how it should work, I'm not sure. If you start working on making up those examples and putting them into an appendix section or JSON representation for now, then we can do a follow up PR to make them fit in directly in line once we figure out how the tooling works for it. Does that work for you?

**Comment by TallTed** [comment]
There is W3 markup magic and javascript that can be used to hide or show any or all examples in each of a few languages.  This has been used in the past, for instance, to make specs with inline examples in Turtle, RDF/XML, and JSON-LD show any combination of 1, 2, or 3 of those to a browser-based reader.  I do not know the incantations nor how easy it is to make this happen at this stage of the document(s) in question.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-09-15-vcwg#section6-3) on 2021-09-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 6.3. VC-DATA-MODEL: adding more examples of non json-ld credentials (issue vc-data-model#815)

_See github issue [#815](https://github.com/w3c/vc-data-model/issues/815)._




**Kyle Den Hartog:** This one is a thing that has spawned out of one of the PRs that he raised, I believe. This is about being able to add the tabs in there...  
… I did do some research on how this is possible... Looks like there is some good stuff already written out in the JSON-LD spec that makes this possible...  
… I'll look at it, but unlikely in the next day or two...  
… If we're fine with triaging this as 1.1, I think that gives us a little more time. Is that correct, Brent?  

**Brent Zundel:** Yes, we have a couple more days to produce a static version with all the substantive changes that require a 60-day review.  
… If at the end of the review, we have unsubstantive changes, I believe it is okay to add those... is that right, Ivan?  

**Ivan Herman:** I'm not going to correct you :-)  

**Brent Zundel:** I'll go ahead and label this 1.1.  

</details>

**Comment by mwherman2000** [comment]
> There is W3 markup magic and javascript that can be used to hide or show any or all examples in each of a few languages. This has been used in the past, for instance, to make specs with inline examples in Turtle, RDF/XML, and JSON-LD show any combination of 1, 2, or 3 of those to a browser-based reader. I do not know the incantations nor how easy it is to make this happen at this stage of the document(s) in question.

Is there is tangible example of how to do this?  I can start and finish this, next week?

**Comment by TallTed** [comment]
> Is there is tangible example of how to do this? I can start and finish this, next week?

I don't recall which specific doc(s) included this. I believe it flipped between examples in Turtle, JSON[-LD?], and maybe another. @msporny, @dlongley, or @iherman might be able to link to it?

**Comment by kdenhartog** [comment]
Yeah I was looking into how to get this working in that document. It looks like it requires a few additional HTML classes to be constructed and a bit of JS, but from the looks of it most of should be copy/pastable from that spec. I haven't gotten around to it yet, but I intend to within the time frame of the maintenance WG.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-10-27-vcwg#section2-9) on 2021-10-27

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.9. VC-DATA-MODEL: adding more examples of non json-ld credentials (issue vc-data-model#815)

_See github issue [vc-data-model#815](https://github.com/w3c/vc-data-model/issues/815)._




**Brent Zundel:** sidebar: as yet no volunteers for v1.1 PRs, for better or for worse!.  
… overview: anyone here who chimed in wants to comment?.  

**Manu Sporny:** it feels like this is one in a series of similar issues asking for more things; also, i'm not sure a "non-LD credential" exists?.  
… in the sense its used in this issue?.  

> *Ted Thibodeau Jr.:* +1 to manu's comments.

**Manu Sporny:** this seems like it would be addressed by a tabbed layout for examples in v2.  

> *Ryan Grant:* +1.

**Phil Archer:** I would like to say that a tabbed example layout in v2 would be great and i'd volunteer to contribute.  
… and support it.  

**Kyle Den Hartog:** i think the lift of tabbed parallel-examples is large and that justifies deferring, we should tag it in a way that it gets considered as part of that in v2.  

**Manu Sporny:** i have an idea how it could work, so soft-assign it to me?.  

</details>

**Comment by Sakurann** [comment]
suggest closing this. Tabbed examples already have been implemented in vc-data-model-v1.1 and I think in v2.0 securing VC specs will have examples in each of them.

**Comment by brentzundel** [comment]
No comments since marked `pending close`, closing
