### ISSUE TITLE
Add valid proof and JWT examples throughout specification

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#833]
There are a number of examples in the specification that would benefit from having fully signed versions of those examples. PR #817 attempts to remove the `proof` field from the specification. My suggestion is that we go the other way, provide different "tabs" that show the raw credential, the verifiable credential (using the `proof` field), and the verifiable credential (as a JWT).

I have created an extension to enable this in ReSpec, here is some output from that ReSpec extension:

Raw Credential:
![image](https://user-images.githubusercontent.com/108611/141146564-2ad60ae9-eb14-47f8-8061-f803c9980106.png)

Verifiable Credential with proof:
![image](https://user-images.githubusercontent.com/108611/141146666-8ef14c78-9916-4801-84da-984b7b61b11c.png)

Verifiable Credential as JWT:
![image](https://user-images.githubusercontent.com/108611/141146813-11fdcc8b-8f78-4b9a-a694-da9de50bac6d.png)

I'll raise a PR to merge these examples into the specification.

**Comment by TallTed** [comment]
Any reason not to title the tabs the same as your headings here, i.e., "Raw Credential", "Verifiable Credential (with proof field)", and "Verifiable Credential (as JWT)" (instead of "Unsigned", "Signed (proof)", and "Signed (JWT)")?  (If these labels are too wide, "Verifiable Credential" could probably be abbreviated as "VC".)

It seems that if those are clearer as img labels here, they will continue to be clearer as tab titles there...

**Comment by msporny** [comment]
> It seems that if those are clearer as img labels here, they will continue to be clearer as tab titles there...

Ok, I will rename to:

* Credential
* Verifiable Credential (with proof field)
* Verifiable Credential (as JWT)

I think we have enough space at the top of the example box for that.

**Comment by kdenhartog** [comment]
Addressed in PR #834 - adding the errata label and closing
