### ISSUE TITLE
Determine if JWT pre-signed intermediate-mode output should be in every example in the specification.

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#836]
@David-Chadwick wrote:
> Whilst the JWT example is no doubt correct, it would be more helpful to readers if the additional tab could be (or another one added) which shows the transformation of the credential into the JWT payload (prior to signing and base64 encoding) as in example 28. The reason being is that the transformation is the part that is specified in the VC specification, whilst the signing and base64 encoding are already standardised in referenced RFCs and we do not modify these specs.

**Comment by msporny** [comment]
@David-Chadwick would like to have a comment in the example to the effect of "Note: all of these examples are using "in addition to"

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-01-vcwg#section3-1) on 2021-12-01

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.1. Determine if JWT pre-signed intermediate-mode output should be in every example in the specification. (issue vc-data-model#836)

_See github issue [vc-data-model#836](https://github.com/w3c/vc-data-model/issues/836)._




**Manu Sporny:** this was a request from DavidC (to see the intermediate output). And, I implemented that, in a recent PR.  

**David Chadwick:** thank you, that's great..  
… I would have liked a footnote, something like "Note: all of these examples are using "in addition to"".  

**Manu Sporny:** we could put it as a comment to the example?.  

**David Chadwick:** yeah.  

**Manu Sporny:** I can put it in the example itself, no prob..  
… I'll do that as an editorial change.  

</details>

**Comment by msporny** [comment]
> @David-Chadwick @David-Chadwick would like to have a comment in the example to the effect of "Note: all of these examples are using "in addition to"

This was done in ab187908ea6abdd61aedccc0d9cb16c0cfcf5785 as a purely editorial point release upgrade to respec-vc v1.0.1, which includes the statement that @David-Chadwick asked for. This issue is resolved.
