### ISSUE TITLE
Best way to stay updated about changes in the specs?

### ISSUE THREAD

**Issue by tc-developer01** [w3c/vc-data-model#842]
Hello there,

is there something like a newsletter you can subscribe to to keep up to date with changes in the specs (including the others like did-core)?  
I've wondered if there is a more efficient way to just compare the git diffs from time to time.

I'm very thankful for any resources you can guide me to regarding this topic (staying up to date).

Thank you!

**Comment by OR13** [comment]
@tc-developer01 https://lists.w3.org/Archives/Public/public-credentials/ and subscribe to this repo.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-01-vcwg#section3-6) on 2021-12-01

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.6. Best way to stay updated about changes in the specs? (issue vc-data-model#842)

_See github issue [vc-data-model#842](https://github.com/w3c/vc-data-model/issues/842)._




**Brent Zundel:** I think this has been addressed, any other suggestions? Suggest closing -- objections?.  

> *Manu Sporny:* No objections..

</details>

**Comment by brentzundel** [comment]
no comments since marked pending close, closing.
