### ISSUE TITLE
Determine interoperable way for Holder to make claims directly in VPs

### ISSUE THREAD

**Issue by jandrieu** [w3c/vc-data-model#860]
VPs include a "verifiableCredential" for embedding VCs in the VP.

It's also possible to add properties to the VP that can represent claims made by the holder about the claims presented, thanks to the open world data model.

For example, in the VC Use Cases,  [5.1 Citizenship by Parentage
](https://www.w3.org/TR/vc-use-cases/#citizenship-by-parentage) the holder claims that he is the person born in the birth certificate, his mother is the parent in that birth certificate, that the person in the US passport is his mother, and that one of the subjects in the marriage license is his mother, all using the identifiers in those VCs to describe the relationship between the VCs.

You could of course, have the holder self-issue a VC and include in as any other VC. However, in practice, that is an unfortunate overhead, needing two signatures (the VC and the VP). It's easier just to add a property to the VP and get rid of the extra proof.

I'd like to see this standardized in some way (a candidate for v2.0). I initially considered "holderSubject" for symmetry with "credentialSubject" in the VCs. However, "holderClaims" might be more appropriate as statements about his mother have a different subject.

In a very pseudocode example:
```json
"holderClaims": [{ 
  "id":"did:example.com:mom",
  "sameAs": [
    "did:example.com:momInBirthCertificate",
    "did:example.com:momInMarriageLicense",
    "did:example.com:momInPassport",
   ]
  "parentOf": "did:example.com:holder"
}]
```

**Comment by jandrieu** [comment]
Discussed on WG call 2022.08.24. @msporny and @dlongley advocated for sticking with the use of VCs rather than supporting a different way to make claims.

@jandrieu Suggested that unless we change the open-world data model of the VP itself, this behavior "holderClaims" as a property in the VP is allowed, and as such, is likely be used by developers who find it to be a more convenient solution. I could support a debate about moving away from an open world model (and considering restricting this practice), but if we stay with the current spec, which allows arbitrary properties in the VP, then standardizing the use would increase interoperability.

Note that if a developer wants to stick with the VC-based approach, a standard property for holder asserted claims, such as "holderClaims" would not prevent that approach. However, today, the only interoperable option requires duplicate signatures and duplicate verifications. In some use cases, the additional cryptography is more of a burden than justified, e.g., in IOT devices where computation and data size are both at a premium.

Kristina mentioned there is support for this use case and recommended we leave the conversation open for people to consider.

No resolutions made.

**Comment by agropper** [comment]
This is close to the user-centric authorization request we use for sharing health records. Along with credentials, the signed presentation includes a claim of purpose as well as the scope of the request. Our use-case helps focus the question of open world vs. interop. 

Every request has three orthogonal dimensions:
- the credentials of the requesting party (claims that are signed by others)
- the purpose of the request (claims that are signed by the requesting party themselves)
- the scope of the authorization or transaction requested (description of the transaction to be authorized)

[RAR](https://datatracker.ietf.org/doc/draft-ietf-oauth-rar/07/) is one relevant aspect of this conversation.

**Comment by agropper** [comment]
I wonder how the "User-Centric Request Model" (UCRM) perspective fits into
this discussion.

Briefly, UCRM, assumes that one or more VCs are combined with a stated
purpose and scope of a transaction resulting in a capability /
authorization for the transaction. The party signing the request is held
accountable based on their signature on the request.

Aside from the VCs presented, interoperability of scope seems pretty
trivial since asking for a resource or scope that is not understood by the
verifier is guaranteed to fail even before validating other aspects of the
request. That leaves interoperability of purpose specification which is
probably out of scope for this WG except as it relates to open world
schemas and contexts.

I'm hoping that this UCRM use-case helps drive consensus around the
presentation of VCs.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-12-14-vcwg#section5-3) on 2022-12-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.3. Determine interoperable way for Holder to make claims directly in VPs (issue vc-data-model#860)

_See github issue [vc-data-model#860](https://github.com/w3c/vc-data-model/issues/860)._




**Joe:** had in credential the issuer issued a mDL but nothing about the subject presenting the credential. Is the current presenter the same as the issuer gave the VC to use case individual claiming US citizenship, the birth certificate claims the relationship to his mother, but she's remarried and has changed her name. Need something to connect these changes. This is me; this is my boss, my child, or simply I found this vc.  
… how do we have a standard way to represent these complicated semantic relationships? Having one would be helpful.  

> *Phillip Long:* Kristina - perhaps we should think about this though this issue has been opened back in Jan this year.

**Manu Sporny:** we should think more about this and provide a standard mechanism for representing this relationships.  
… we need concrete guidance for people who want to put these properties in the representation. It could be come a big conversation. We've only had a terms of use in a presentation to date..  
… we'll need to approach this from a "use cases first" perspective..  
… need to be very specific about the use cases..  

> *Dmitri Zagidulin:* +1 to re-using existing VC primitive, vs introducing a new primitive of adding claims to VP.

**Dave:** we should try to leverage the primitives we already have. One way to do that is the VC. Given there is a lot complicated relationships and not have a highly complex reasoning engine to process it we should leverage VCs where the kinds of relationships are modeled. EG. give a parent child assertion yourself offered..  

> *Dave Longley:* +1 to being able to say anything -- but there's a need for the verifier to know what they are saying as well, +1 to common vocabs and an easy way for the verifier to say what they will understand in the first place..

**Joe:** a little confused by what Dave just said. VCs require a separate artifact and different from the flow. Should be an action of the presentation. This is still "openworld" - should express this with some constrained openworld. Need a vocab that expresses common relationships. Good to address nontransferrable property, etc. would help us get rid of babel problem but need to express things as the real world works..  

**Kristina Yasuda:** let's leave this conversation for further thought. Happy New Year for everyone. We've made progress with new V2 WG and working on it..  

---


</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-02-08-vcwg#section4-3) on 2023-02-08

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.3. Determine interoperable way for Holder to make claims directly in VPs (issue vc-data-model#860)

_See github issue [vc-data-model#860](https://github.com/w3c/vc-data-model/issues/860)._




**Brent Zundel:** determine interoperable way to make claims directly in VPs.  
… joe raised issue.  

**Joe Andrieu:** not much convo back and forth. Last time there was some pushback on call.  
… tension is do we want to reuse the VC and require a second sig.  
… or is there a way to use a property in the VP and let signer put some assertions in there.  
… manu and dave thought VC approach better.  

**Manu Sporny:** concern is that we have primitive already. That is the VC.  

> *Dave Longley:* +1 to reusing the primitive we have already and using composition.

**Manu Sporny:** can we compose it. VC allows us to say anything about anyone.  
… Additional VC could contain any of the additional contents that an additional property might contain.  
… is true that it would be an additional thing to be issued and signed.  
… suggested property will eventually become a VC. Why not just use a vc.  

**Joe Andrieu:** separate VC need a way to bind to a VP.  
… a way to say that this VC is specifically about a VP when it is presented.  
… semantics should be part of a VP added when VP is created.  

**Brent Zundel:** how terrible would it be to have property in VP. But specify that the value of that property would be a VC.  

> *Dave Longley:* +1 to what brent said being an option, was having the same thought.

**Brent Zundel:** so property in VP would be in form of a VC.  

**Manu Sporny:** its a good though. I had similar. It is a way of doing this. Still thinking about it.  
… raises Q of why we need an additional property in VP to do that.  
… if the VC is in the VP then it is already bound to VP. Its all bound together.  
… Key thing is lets reuse primitives we already have.  
… Just need to address the binding concern.  

**Michael Prorock:** Going the same direction as brent. Feels like a vocab problem.  
… handling this in supply chain traceability. Extended the type on VC to TraceableVC..  
… this enables linking of VCs together.  
… if the vocab and data models give us ability to define these things for use cases. Lets do that for those use cases.  
… not reinvent the wheel.  

> *Orie Steele:* DIF also extends the RDF type for "VerifiablePresentation"... [https://identity.foundation/presentation-exchange/#presentation-submission---verifiable-presentation-2](https://identity.foundation/presentation-exchange/#presentation-submission---verifiable-presentation-2).

> *Manu Sporny:* +1 to mprorock, we need to have a specific use case someone is building out for to apply this to.

**Michael Prorock:** The tools we need exist.  

**Joe Andrieu:** I like idea of property whose values are credentials. Push back on making the VCs.  
… want to avoid the need for multiple vcs.  
… if we have multiple VCs in a presentation. Which VC defines the semantics of the presentation.  
… trying to figure out and standardise that.  

> *Michael Prorock:* the presentation type does that, not the credentials in it.

**Joe Andrieu:** semantics of VP are about why is this thing being presented and by whom.  

> *Orie Steele:* VP has only 2 requirements... context and type..

**Brent Zundel:** don't have normatively defined way to sign and secure a VP..  
… Might this be a way to bind a VP to the presenter.  

> *Orie Steele:* [https://w3c.github.io/vc-data-model/#presentations-0](https://w3c.github.io/vc-data-model/#presentations-0) see the requirements..

> *Manu Sporny:* [https://w3c-ccg.github.io/vp-request-spec/#did-authentication](https://w3c-ccg.github.io/vp-request-spec/#did-authentication).

**Manu Sporny:** data integrity work covers embedded proofs for presentations.  
… also a VP request spec that talks to this.  
… concern is that some people would think we are now defining protocols. Growth of scope.  

> *Michael Prorock:* +1 manu.

**Manu Sporny:** hard to talk about presentations without going into protocols.  

> *Orie Steele:* OIDC has ways of doing this as well, perhaps someone can cite those items for the minutes as well?.

**Manu Sporny:** agree with mprorock. For us to say this is applicable and useful need to see use cases in the field and then standardise from that.  
… find commonalities instead of generalise too early.  

**Michael Prorock:** I agree with manu.  

> *Orie Steele:* For the minutes: [https://openid.net/specs/openid-4-verifiable-presentations-1_0.html](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html).

**Michael Prorock:** when you start to get into practicalities, start going into protocols..  
… many of this issues we are correcting and improving in vc data model spec are down to how we thought something would/does work in the wild.  
… against adding additional complexity, rather that seeing what happens in implementations.  

**Joe Andrieu:** frustrated to deference to implementations.  
… we have use cases in the use case document that have requirements from start.  

> *Michael Prorock:* then define a vocab.

**Joe Andrieu:** The semantics of what the presentations means is the gap.  
… we have use cases that we haven't been able to address currently because of this.  
… Need to define semantics of a VP.  

**Orie Steele:** joe is getting at 2 possible world views.  
… 1 - purely the responsiblity of the data model. Almost what we have today. Clear that protocols will extend using @context and type to support there use cases.  
… Because it landed like this in 1.1. people are deferring to protocol.  
… also concerned about getting into protocols in this WG.  
… Feel protocols are adding many more requirements to VPs.  
… concerned about VPs in there current form in the spec.  

**Michael Prorock:** agree, there are things we need to improve about VPs in spec. Not sure this is one of them.  
… Deal with gov and regulatory folks. They are relatively happy with it the way it is.  
… worried about getting pulled off on tangents.  

**David Chadwick:** I support JoeAndrieu's view.  
… This is about holder or presenter telling the verifier about the contents of the VP and how they should handle them.  

> *Michael Prorock:* "type".

**David Chadwick:** likely something about holder binding too. Proof of possession.  
… Think we do need to broaden the data model for VPs in a standard way.  
… if do it for your own applications then you are doing it in a non standard way.  

> *Kerri Lemoie:* Part of the confusion with VPs in the ecosystems that VPs are used for things other than presenting VCs.

**Mahmoud Alkhraishi:** Have similar problem with the issuer field.  
… Not very clear to me who gets to define the values in the issuer field and what it looks like.  
… don't want to derail this convo, but tangentially related.  
… suggest extend VP the same way as the traceability vocab.  

**Manu Sporny:** agree with mkhraisha.  
… would help me to understand concretely what the solns look like.  
… we have extensibility model. Nothing to stop anyone creating an extension to solve use cases that JoeAndrieu is talking about.  
… suggest we should do this to create something concrete we can look art.  

> *Orie Steele:* RDF is the extensibility model for Verifiable Presentations... context and type... that is it..

> *Orie Steele:* We've seen several use cases of vocabularies doing this today..

> *Juan Caballero:* (not too much less ambitious).

</details>

**Comment by TallTed** [comment]
@iherman — Please edit your https://github.com/w3c/vc-data-model/issues/860#issuecomment-1423976887 and code fence the now-bare `@context`, changing it to ``` `@context` ```, so that GitHub user is not dragged into our conversations. This likely should be done in myriad other meeting transcripts...

**Comment by Sakurann** [comment]
> You could of course, have the holder self-issue a VC and include in as any other VC. However, in practice, that is an unfortunate overhead, needing two signatures (the VC and the VP). It's easier just to add a property to the VP and get rid of the extra proof.

I understand the need for self-attested claims, and I think we can do it without defining anything new by providing guidance that "to make claims, `the Holder should create a self-signed VC and send it as a VC, without a VP (hence without double signing)`.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-04-11-vcwg-special#section1-1) on 2023-04-11

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.1. Determine interoperable way for Holder to make claims directly in VPs (issue vc-data-model#860)

_See github issue [vc-data-model#860](https://github.com/w3c/vc-data-model/issues/860)._




**Kristina Yasuda:** "Determine interoperable way for Holder to make claims directly in VPs".  
… opened by Joe.  
… currently labeled discuss.  

**Joe Andrieu:** The notion of this issue is that right now the only way to handle this is for holders to extend the model on their own, but no interoperable and normative way. also possible to embed a VC, but no standard way of having a VC referencing a VP.  
… thought was to add a property to the VP like "holder claims" to attach this in and sign it just like you do normally.  

**Kristina Yasuda:** question for this call - is there a resolution, or an assignment to take it on.  

**Joe Andrieu:** volunteers to take the issue on.  

</details>

**Comment by Sakurann** [comment]
"pending-close" unless DavidC's presentation will be an inspiration.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-06-14-vcwg#section2-3) on 2023-06-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.3. Determine interoperable way for Holder to make claims directly in VPs (issue vc-data-model#860)

_See github issue [vc-data-model#860](https://github.com/w3c/vc-data-model/issues/860)._




**Joe Andrieu:** I think we don't have 2 implementations of this.  
… will other people implement this.  
… this issue requests definition for a property about other properties.  
… there is a use case for requesting citizenship documents by providing suplemental credentials.  
… bascially repeat the concept of credentialSubject for holderClaims...  
… there is some conversation on it, I think you can always use an unsigned vC.  

**Orie Steele:** Just a comment on normative requirements, proof is optional, party can include additional fields by relying on JSON-LD context, you don't need two independent implementations to achieve this, you can use reserved terms, if W3C doesn't reserve terms, won't matter in context of standards, if govt. processing, they determine those terms.  

**David Chadwick:** I noticed a similar requirement a couple months ago, but we never presented at the face to face.  
… I will point to the definition we had for this feature.  
… I have defined examples, maybe we have the same idea, take a look at the slides.  
… the slides are follow on related to holder binding.  

**Dave Longley:** seems like the verifier won't accept arbitrary properties.  
… seems like an additional credential use case.  
… where the holder issuers a self asserted credential.  
… and then the verifier will process self signed credentials from the holder wallet.  

> *Michael Jones:* I approved status-list PR #46 with [https://github.com/w3c/vc-status-list-2021/pull/46#pullrequestreview-1479814962](https://github.com/w3c/vc-status-list-2021/pull/46#pullrequestreview-1479814962).

**Dave Longley:** i think we have the tools to make this happen, we don't need new reserved W3C terms.  

**Kristina Yasuda:** maybe leave a comment regarding the proposed paths forward.  

**Joe:** DavidC can you leave a comment on the issue, unless there is something to fight for, we should close it.  

**Kristina Yasuda:** thanks all.  

> *David Chadwick:* see [https://www.w3.org/2017/vc/WG/Meetings/F2F/VCWG_Miami_F2F_2023.pdf](https://www.w3.org/2017/vc/WG/Meetings/F2F/VCWG_Miami_F2F_2023.pdf).

**Kristina Yasuda:** please review PRs and issues outside of call time.  
… next week's special topic call will be status list codes, or 1100 1101 PRs regarding mapping and content types.  

> *David Chadwick:* Slides are titled Alt Holder Binding.

---

</details>

**Comment by Sakurann** [comment]
What is the difference between a self-signed a VP with an unsigned VC versus a self-signed VC?

**Comment by David-Chadwick** [comment]
There is a difference in approach based on the hierarchical  level at which the holder's assertions are placed. These assertions could be placed at the VP level, and relate to the VCs in the verifiableCredential property, or they could be in a separate (unsigned) VC along with the other VCs to which it relates. In my view turning these assertions into an unsigned VC introduces extra baggage that is not needed if they are placed at the VP level, since the VP already includes the extra baggage of validFrom, validUntil, type, issuer etc.

**Comment by agropper** [comment]
Makes sense. Which is why the one flow to use VCs that bears
standardization is Request (as specified by IETF GNAP) instead of VP.

**Comment by OR13** [comment]
https://github.com/w3c/vc-data-model/pull/1181

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-07-05-vcwg#section2-6) on 2023-07-05

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.6. Determine interoperable way for Holder to make claims directly in VPs (issue vc-data-model#860)

_See github issue [vc-data-model#860](https://github.com/w3c/vc-data-model/issues/860)._




**Kristina Yasuda:** This is about self-signed VCs, right?  

**Orie Steele:** Brent has a raised a PR that addresses a lot of this issue.  
… Pull 1181.  
… PR 1181 doesn't currently reflect what you can do with a VP.  
… Brent, can you please revise per the comments.  

_See github pull request [vc-data-model#1181](https://github.com/w3c/vc-data-model/pull/1181)._




> *Orie Steele:* it could address that issue.

**Brent Zundel:** I don't remember if I tried to address the comments or not yet, but I definitely can.  

**Kristina Yasuda:** I've assigned this to you, Brent.  

> *Joe Andrieu:* present?

</details>

**Comment by brentzundel** [comment]
@jandrieu I've attempted a PR #1186 to address this issue and would appreciate feedback from you on it

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-07-11-vcwg-special#section1-9) on 2023-07-11

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.9. Add interoperable way for holder-asserted claims in a VP (pr vc-data-model#1186)

_See github pull request [vc-data-model#1186](https://github.com/w3c/vc-data-model/pull/1186)._




**Brent Zundel:** P.R seeks to address issue #860.  
… provides normative guidance for holder claims in a presentation.  
… a holder can elect to either produce a VC secured on its own and insert into vc array of the presentation.  

_See github issue [vc-data-model#860](https://github.com/w3c/vc-data-model/issues/860)._




**Brent Zundel:** alternatively they can include an unsecured VC in the presented vcs.  
… as long as issuer field of the VC and the holder field of the presentation match. Then the issuer can have confidence that this is self attested claim from the holder.  
… all comments have been responded to. Awaiting final review from TallTed.  
… open to comments.  

> *Phillip Long:* +1 to that PR pertains to issue 860.

**Andres Uribe:** made a comment about enabling forwarding of credentials.  
… not sure how that would be possible using the self asserted type.  
… maybe this isn't a use case that is as important to support.  

**Oliver Terbu:** can see interop issues with this approach in the future.  
… many other ways to achieve the same. Are we saying this is the only approach to achieve this.  
… not sure this is the right approach. Not objecting, just a comment.  

**Dave Longley:** think forwarding use case can be solved by attaching a signature to the VC.  
… using a SelfAsserted type is just a recommendation.  
… think P.R is really around enabling the VP to be the securing for self attested claims.  
… otherwise holder can just act in the role of issuer.  
… this adds a mechanism to secure using proof of the VP itself.  

**Joe Andrieu:** part of this shift has missed some of initial point from issue #860.  
… this was about how you say these claims are about this specific thing right now.  

> *Dave Longley:* perhaps give the VP an ID and include that in your VC claims.

**Joe Andrieu:** not sure how we address that.  

> *Will Abramson:* PL-ASU: this is in relation to the self asserted. The fact that there may be a circumstance where self-asserted claims do not want them to be forwarded.

**Oliver Terbu:** I heard that we have two different issues.  
… JoeAndrieu wanted author of credentials about the VP and the ability to include those in a presentation.  
… then there is the one about self asserted with proof from the VP used to secure.  
… maybe we need separate P.Rs for this.  

**Brent Zundel:** any concrete proposals or changes to this P.R is appreciated. Not sure how to act on the general guidance.  
… responding to JoeAndrieu, should be easy to add a line to the spec that addresses your use case.  

**Joe Andrieu:** think that is pretty good. E.g. if it says if you are making a VP, you could have the ID of a VP that you then refer to.  

**Brent Zundel:** okay I can make that change.  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-07-11-vcwg-special#section1-9) on 2023-07-11

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.9. Add interoperable way for holder-asserted claims in a VP (pr vc-data-model#1186)

_See github pull request [vc-data-model#1186](https://github.com/w3c/vc-data-model/pull/1186)._




**Brent Zundel:** P.R seeks to address issue #860.  
… provides normative guidance for holder claims in a presentation.  
… a holder can elect to either produce a VC secured on its own and insert into vc array of the presentation.  

_See github issue [vc-data-model#860](https://github.com/w3c/vc-data-model/issues/860)._




**Brent Zundel:** alternatively they can include an unsecured VC in the presented vcs.  
… as long as issuer field of the VC and the holder field of the presentation match. Then the issuer can have confidence that this is self attested claim from the holder.  
… all comments have been responded to. Awaiting final review from TallTed.  
… open to comments.  

> *Phillip Long:* +1 to that PR pertains to issue 860.

**Andres Uribe:** made a comment about enabling forwarding of credentials.  
… not sure how that would be possible using the self asserted type.  
… maybe this isn't a use case that is as important to support.  

**Oliver Terbu:** can see interop issues with this approach in the future.  
… many other ways to achieve the same. Are we saying this is the only approach to achieve this.  
… not sure this is the right approach. Not objecting, just a comment.  

**Dave Longley:** think forwarding use case can be solved by attaching a signature to the VC.  
… using a SelfAsserted type is just a recommendation.  
… think P.R is really around enabling the VP to be the securing for self attested claims.  
… otherwise holder can just act in the role of issuer.  
… this adds a mechanism to secure using proof of the VP itself.  

**Joe Andrieu:** part of this shift has missed some of initial point from issue #860.  
… this was about how you say these claims are about this specific thing right now.  

> *Dave Longley:* perhaps give the VP an ID and include that in your VC claims.

**Joe Andrieu:** not sure how we address that.  

> *Will Abramson:* PL-ASU: this is in relation to the self asserted. The fact that there may be a circumstance where self-asserted claims do not want them to be forwarded.

**Oliver Terbu:** I heard that we have two different issues.  
… JoeAndrieu wanted author of credentials about the VP and the ability to include those in a presentation.  
… then there is the one about self asserted with proof from the VP used to secure.  
… maybe we need separate P.Rs for this.  

**Brent Zundel:** any concrete proposals or changes to this P.R is appreciated. Not sure how to act on the general guidance.  
… responding to JoeAndrieu, should be easy to add a line to the spec that addresses your use case.  

**Joe Andrieu:** think that is pretty good. E.g. if it says if you are making a VP, you could have the ID of a VP that you then refer to.  

**Brent Zundel:** okay I can make that change.  

</details>

**Comment by msporny** [comment]
@jandrieu, did PR #1186 address your concern, and if so, can we close this issue?

**Comment by brentzundel** [comment]
PR #1186 was raised to address this issue and has been merged. Closing in 7 days if no objections are raised.
