### ISSUE TITLE
Make images consistent

### ISSUE THREAD

**Issue by chaals** [w3c/vc-data-model#865]
There are some stylistic differences across images - would be good to make them more consistent:

- center all content in the top level containers
- have consistent content border sizes in all the images
- center content within containing shapes
- align text across shapes
- align other center lines and similar
- make arrows flush on either side with source and targets
- use consistent positioning where appropriate for arrow start and end positions with source and target shapes

And also there's some style issues like claims start off with blue subject and tan claims. But the larger pictures have same shapes and different colors. I get why, but would be nice if colors across all images were better aligned.

(This issues is taken from [original comments](https://github.com/w3c/vc-data-model/pull/855#pullrequestreview-862977446) from @davidlehn regarding #855)

**Comment by chaals** [comment]
(If someone assigns this to me, that would be useful)

**Comment by msporny** [comment]
Hrm, having looked at all the SVG diagrams in the latest version of Chromium... all he diagrams as busted in ways that make the images look bad now. Misaligned text that flows outside of the boxes. Bad looking fonts. Mis-sized arrows. All in all, things any graphic designer would have a heart attack over.

@chaals are you seeing how bad these new optimized SVGs look? Here's an example of one of the images:

![image](https://user-images.githubusercontent.com/108611/152272127-e5c4b62d-0817-4ad5-b102-fa1430a65eb9.png)

**Comment by msporny** [comment]
> We're going to be blocked publishing the v1.1 spec until this is fixed... or we revert to the old graphics.

I fixed a number of the issues, very minor tweaks (I was having nightmares of some deep seated rendering bug in Chrome/Firefox/Safari, but nothing of that nature reared its ugly head).

Thank you for putting all of the work into this @chaals ... I finally got a chance to dive deep into your handiwork and it is glorious!

Closing this issue, as I'm about to prep the final REC v1.1 publication.

**Comment by davidlehn** [comment]
@msporny I'm going to reopen this.  The original issues reported still remain.  If there is no interest in addressing these issues, that's one thing, but I think this was closed only due to addressing a different text display issue?

**Comment by msporny** [comment]
@davidlehn @chaals What of the original issues still remain? The Editors need guidance on what to fix.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-08-10-vcwg#section4-8) on 2022-08-10

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.8. Define v2 context (issue vc-data-model#865)

_See github issue [vc-data-model#865](https://github.com/w3c/vc-data-model/issues/865)._




**Kristina Yasuda:** This is about images in the document text. chaals did great work. Can we close it?.  

**Manu Sporny:** I thought it was done and I closed, then it was re-opened. My suggestion is we give David Lehn 30 days to address it, then close if it is not addressed..  
… I will add a comment.  

**Ivan Herman:** I understand we need chaals to do what he is referring to. His points about quality of diagrams, these things are good styling warning..  
… I wouldn't like to lose the bullet items chaals put into the issue. This is editorial styling, we need to be good about this..  
… Now we will have multiple documents in parallel, we need some editorial consistency among the documents. This is part of it..  

**Kristina Yasuda:** Can we leave it to the editors to make sure that this is addressed?.  

**Ivan Herman:** Sounds good if the editors can make sure that this is not forgotten..  

> *Brent Zundel:* or we can leave it open with an editorial tag . . ..

> *Orie Steele:* +1 to closing, i'm in favor of fixing all the diagrams as part of regular review... and addressing that in a case by case basis..

**Manu Sporny:** I went through and made a lot of the changes chaals suggested, I did this as far as I could. It's more complex with some diagrams, this may confuse the diagram and be a step in the wrong direction..  
… Understanding what exactly is remaining would be better. Perhaps we ask David and chaals what exactly the editors need to do..  

**Michael Jones:** In favor of closing in 30 days.  

**Manu Sporny:** Will add a comment.  

</details>

**Comment by brentzundel** [comment]
We believe this has been addressed.
