### ISSUE TITLE
Migrate Section 6.3.1 JSON Web Token to separate normative specification

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#880]
The VC2WG is focusing on standardizing a variety of cryptosuites. The [VC2WG charter](https://www.w3.org/TR/vc-data-model/#json-web-token) specifically calls out "Cryptosuites for VC-JSON Web Token (JWT)". We should migrate Section 6.3.1 JSON Web Token to a separate normative specification and reduce the section on [proof formats](https://www.w3.org/TR/vc-data-model/#proof-formats) to a series of links to the other normative cryptosuite specifications.

**Comment by OR13** [comment]
PR is up here: https://github.com/w3c/vc-jwt/pull/1

**Comment by Sakurann** [comment]
suggest closing this one since there is already an issue addressing this in vc-jwt repository

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-08-03-vcwg#section5-10) on 2022-08-03

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.10. Migrate Section 6.3.1 JSON Web Token to separate normative specification (issue vc-data-model#880)

_See github issue [vc-data-model#880](https://github.com/w3c/vc-data-model/issues/880)._




**Kristina Yasuda:** Not sure if it's done already.  
… or if PR is there but not merged..  
… This is less a move-it and rather a close-it, right?.  

**Manu Sporny:** +1 to that. I think Kristina suggested as much in the last comment on the issue.  

**Michael Jones:** I think this is being accomplished by VC-JWT PR 1.  

**Brent Zundel:** I will take off the vc-jwt? label.  

**Michael Jones:** Maybe reference VC-JWT pull-request 1.  

_See github pull request [vc-jwt#1](https://github.com/w3c/vc-jwt/pull/1)._




**Brent Zundel:** looks like that's in the comment from Orie.  
… Thank you all for going through these.  

> *Michael Jones:* +1.

**Brent Zundel:** After the meeting, anything still labeled "vc-jwt?" will be moved to the vc-jwt repo..  

</details>

**Comment by OR13** [comment]
This issue should be closed.

**Comment by brentzundel** [comment]
The associated PR has been merged, closing
