### ISSUE TITLE
example 2 > sec: prefix

### ISSUE THREAD

**Issue by bertvannuffelen** [w3c/vc-data-model#884]
Hi

after investigating the RDF result from example 2 (obtained via json-ld playground), there is a prefix sec: introduced.

`
_:b5 <sec:proofPurpose> <https://w3id.org/security#assertionMethod> _:b4 .
`
This seems odd to me, as sec:proofPurpose is not a valid URI. Can one add  the prefix expansion the contexts?

A quick search on prefixes in the spec did not resulted in any answer.

kr,

Bert

**Comment by clehner** [comment]
Hi @bertvannuffelen,

This is because of #778.
`sec:proofPurpose`, as a [compact IRI](https://json-ld.org/spec/latest/json-ld/#dfn-compact-iris), should have expanded to `https://w3id.org/security#proofPurpose`. But the [term definintion](https://json-ld.org/spec/latest/json-ld/#dfn-term-definitions) (`sec:` → `https://w3id.org/security#`) is missing from the [scoped context](https://json-ld.org/spec/latest/json-ld/#scoped-contexts) for `RsaSignature2018`.

There is also a similarly missing prefix mapping for `xsd`. `xsd:dateTime` used in the proof `created` property is supposed to expand to `http://www.w3.org/2001/XMLSchema#dateTime`.

As a "quick fix" you could append the mappings to the `@context` array after the Credentials v1 base context, e.g.:
```
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    {
      "sec": "https://w3id.org/security#",
      "xsd": "http://www.w3.org/2001/XMLSchema#"
    }
  ],
```

**Comment by Sakurann** [comment]
Suggest closing this issue, since it is already covered in #778 and continuing discussion there.

**Comment by clehner** [comment]
> why is adding a namespace to a json-ld context a major change?

My understanding is that is substantive because the context file as-is is already published, such that adding this (prefix definition?) could cause errors if users/applications are depending on it the way it is now.

I'm not sure what you mean about hidden dependencies. `"https://w3id.org/security#"` is a URI/IRI prefix, that is represented by (compressed to) `"sec"` by the [prefix](https://www.w3.org/TR/json-ld11/#dfn-prefix) definition in some places in the Credentials base context (but accidentally omitted from the scoped context for RsaSignature2018). There are JSON-LD context files associated with https://w3id.org/security - but those are not depended on or referenced by the vc-data-model v1.0/v1.1 context. This vc-data-model context rather includes all its term definitions in itself. My understanding is that the expanded terms (IRIs) are supposed to be stable. The meaning of the terms though might be implied to be defined at the dereferenced namespace web pages.

There is some more info about the implications of this issue, here: https://github.com/w3c/vc-data-model/issues/778#issuecomment-836846943
https://github.com/w3c/vc-data-model/issues/778#issuecomment-838583370

There is also some more info about the terms defined in the VC Data Model [Base Context](https://www.w3.org/TR/vc-data-model/#base-context) in this Vocabulary Document: https://www.w3.org/2018/credentials/

@bertvannuffelen I hope this helps.

I agree with closing this issue in favor of #778 (or vice versa).

**Comment by brentzundel** [comment]
No objections since marked `pending close`, closing
