### ISSUE TITLE
vc:credentialSubject semantics

### ISSUE THREAD

**Issue by bertvannuffelen** [w3c/vc-data-model#885]
Hi,

I have encountered implementations of VC were vc:credentialSubject is interpreted as "The person about which claims are made and who owns the credential." 

In my understanding of this property this is not the intentional semantics.
But vc:credentialSubject is  a collection of statements (claims) which trust is  cryptographic  proven.
_Subject_ in this property stands for anything in the world: a diploma, apples, cars, ownership of boats, etc. Right?
 
If I am right, this role is even not at all present in VC. 

kr,
Bert

**Comment by bertvannuffelen** [comment]
Thanks a lot for the confirmation.

**Comment by awoie** [comment]
That is one of the reasons why I started this thread https://github.com/w3c/vc-data-model/issues/882 . IMO, it is still a common use case if someone presents VCs as a VP and the verifier needs to check whether at the time of presentment, the original subject (defined by an id or not) of the VC presented the VP.

**Comment by bertvannuffelen** [comment]
After rereading #882, I am still confused with the above definition.

Consider a diploma (as the examples in the VC spec) then the CredentialSubject is for me the "Diploma" and not the person who has got the diploma.

The holders of this claim are the university that issued the credential and the person that has got the diploma. 
The issuer could be the central diploma system of a country.

But the same could be modelled as 

The credentialsubject is the person who got the diploma, the issuer is the university and the diploma is implicit (namely enforced by the credentialtype). 
In this reading the above definition is correct. 

What is the best choice?

**Comment by bertvannuffelen** [comment]
> The way I approach it is, if the credentialSubject claim is about the holder, merge them into one (ie, a Diploma)

In the practice is must be split then always because the Diploma is always historic information and the personal information on it is historic: people do change name, gender, haircolor, id, residence, etc.

Universally, one cannot rely on that the identification properties of a person when the Diploma was registered are still valid today.
Despite in the real world they are the same person, digitally they are very distinct persons.  
Unless the claim data is created with actualized information, one must assume that the owner of the claim and the person in the claim are digitally different.  

> So I would use holder as a possible extension of the credentialSubject, somewhere where you can split the data into something more semantic.

For me holder in abstract VC terminology is the one who holds/own the set of triples (claims), while the credentialsubject is the key entrypoint in the set of triples (claims).

As a Bank, I provided money for John to buy a house. 

Then John can be stated he owns the house, but also the Bank can state it owns the house (if the loan is not payed back).

So for the same triples 
```
    { <John> <owns> <house>.
      <Bank> <finances> <John>
    }
```
one can create many VC's  based on some interpretation of holder and subject: e.g. 
   - John is the holder, and house is the credentialSubject, or 
   - Bank is the holder and  Bank is the credentialSubject
  ...

For me it unclear what the guidelines are for such interpretations, to make it more interoperable.

**Comment by lemoustachiste** [comment]
> Universally, one cannot rely on that the identification properties of a person when the Diploma was registered are still valid today.
> Despite in the real world they are the same person, digitally they are very distinct persons.

If you're going this way then the whole Self Sovereign Identity technology is void by essence. You would need, for it to work,  at any given point in time, and regardless to the fact that you changed gender/family name (the rest does not apply to identity - or anymore because maybe in the 70s you could change haircut, grow a beard and be unrecognizable, ie [Jacques Mesrine](https://www.theguardian.com/world/gallery/2008/oct/23/france-jacques-mesrine-biopic-film)), to be able to prove you were said person digitally. On the contrary I believe digital identity should be persistent to the extent that is desirable for the user.

What shouldn't be is your relationship, if one does not want it to be. If you order something off a website, you may want a one off identity (up until delivery at least). But if you have a diploma, you'd want it to be valid for your whole lifespan (and maybe more).

> For me it unclear what the guidelines are for such interpretations, to make it more interoperable.

But, to your point, and that's what I tried to highlight, it is not clear at this time what is the preferred way from an interoperable perspective. The spec says the concepts of `credentialSubject` and `holder` can be mixed, but `holder` and `credentialSubject` can also be split. Maybe v2 will clarify this point but we will have a whole world of credentials that exist with the previous rule. I believe this is like a language, usage makes the rules, and I was just merely sharing how I approach it at this time.

**Comment by brentzundel** [comment]
The Data Model defines a "property for the expression of claims about one or more subjects."
and defines a subject as "A thing about which claims are made."

This makes it clear to me that @bertvannuffelen is correct when he says that, "Subject in this property stands for anything in the world: a diploma, apples, cars, ownership of boats, etc."

I believe this issue should be closed.

**Comment by brentzundel** [comment]
No comments since marked `pending close`, closing
