### ISSUE TITLE
id property optional

### ISSUE THREAD

**Issue by martyr280** [w3c/vc-data-model#886]
Looking for clarification from the group.  I am sure there was a robust discussion around id property, if there is an issue where I can consume more information regarding the decision to make it optional please direct me.

The 1edtech OB 3.0 and CLR 2.0 currently require id for the AchievementCredential, OpenBadgeCredential = VerifiableCredential.  Does this break compliance with the spec and is there a compelling reason for it to be optional?

**Comment by brentzundel** [comment]
The `id` property was made optional so that the data model could be more easily used with ZKP signatures and other cases that support selective disclosure of the signed properties. In these use cases the originally issued VC may have an `id` property, but the VC contained in the Verifiable Presentation may leave it out. In both cases, the VC is still valid according to the data model.

An implementation that utilizes the VC Data Model may require an `id` property.
