### ISSUE TITLE
Evidence as a Related Credential

### ISSUE THREAD

**Issue by decentralgabe** [w3c/vc-data-model#919]
Looking into how to best make use of the [evidence property](https://www.w3.org/TR/vc-data-model/#evidence).

For our use cases at Block, it's common that pieces of evidence are credentials themselves. We are considering how to represent evidence, some thoughts:
- A reference to the Credential with some related fields (its id, type, schema)
- A URI of some sort that can be externally verifiable. For example, a way to resolve evidence that may be hosted by a 3rd party that may include status/validity checks.
- More broadly, the concept that evidence may 'expire' or have a status that can determine whether it should still be considered as valid evidence

Wondering what ways folks have used evidence thus far, and any solutions they may have. Also interested in the best way to formalize some of these concepts/practices for using evidence.

**Comment by decentralgabe** [comment]
Evidence examples in TBD's use cases around KYC: https://github.com/TBD54566975/credentials-working-group/blob/main/work_items/kyc-vcs/vc1-requirements-to-accept-a-kyc-vc.md#3-identity-verification-evidence-vocabulary

**Comment by decentralgabe** [comment]
cc: @jandrieu

**Comment by OR13** [comment]
We are also interested in this related to supply chain evidence, such as "Site Inspection Credential" as Evidence for "Sustainability Certificates" for example.

**Comment by nadalin** [comment]
There may be different types of Evidence:

evidence of identity (EOI) -evidence that provides a degree of confidence that a subject is represented by the identity being claimed 

authoritative evidence - holds identifying attribute(s) that are managed by an authoritative party

corroborative evidence - holds identifying attribute(s) that are not managed by an authoritative party

**Comment by jandrieu** [comment]
Definitely different types. It would be good to find or create at least a minimal specification for at least a few of these.

**Comment by jandrieu** [comment]
It would also be possible to embed the VC directly.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-11-02-vcwg#section2-3) on 2022-11-02

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.3. Evidence as a Related Credential (issue vc-data-model#919)

_See github issue [vc-data-model#919](https://github.com/w3c/vc-data-model/issues/919)._




**Brent Zundel:** Can you walk us through status of this issue, Gabe?.  

**Kristina Yasuda:** Gabe's not here..  

**Orie Steele:** There are a lot of credentials where you go to an Issuer where you present credential as evidence to receive a new credential. Evidence property supports some of these use cases, optional property of core data model. I believe this question is about making it clear what relationship should be about evidence property where evidence is itself another VC..  
… You can't refer to evidence using ID if original evidence didn't have ID, how can you refer to first VC when issuing second VC?.  
… With version 1.1 we have flexible informative language, but not a lot of concrete guidance to implementers wrt. additional clarity..  

**Michael Prorock:** There are a few use cases we see in practice, two areas -- verification of information on open web and traceability across borders and regulatory compliance across borders. In agriculture case, cross border trade some is digitized, some on paper..  
… Things where you can point to an image and a signature on that, common use case, also external regulatory standards E-Phyto -- exploring putting in evidence or putting in evidence block, types of import credentials. There are things that are outside of JSON/JSON-LD that exist ..  
… This comes up, be mindful about normative statements around evidence..  

> *Orie Steele:* There are a lot of use cases for evidence... I once tried to kill it, and I was shocked by how many people are using it, despite how weekly it was defined in 1.1.... We should invest in providing more clarity regarding the evidence property..

> *Dmitri Zagidulin:* agree, +1 Orie. I was surprised by that, too (by how many people are using 'evidence' despite vague spec).

**Manu Sporny:** There is overlap w/ work that Dmitri and Phil has been doing in this area..  

> *Dmitri Zagidulin:* the related issue Manu mentioned is [https://github.com/w3c/vc-data-model/issues/952](https://github.com/w3c/vc-data-model/issues/952).

**Kerri Lemoie:** We had evidence in open badges for a while, could be a test score, transcript, file, video, some kind of media, demonstrate proof of achievement. Part of openbadges 3.0, we decided to reuse evidence field for this purpose. That is being used like that right now, not that commonly, but it's how its been implemented in the open badges standard.  

**Phillip Long:** As Manu pointed out and Kerri noted, frequent use of evidence field, why a particular achievement was made, in context of hashlink approach that Dmitri propsoed and used in related development of credential -- linked claims, evidence using hashlink you're providing proof of pathway and object itself, then that is a useful mechanism to maintain or present something w/ same authority as original credential..  
… That is a viable mechanism for pointers to these mechanisms, as long as that location is not dynamically generating things so it breaks hash, supplement claim about an issue that's being asserted..  

**Brent Zundel:** Good discussion, concrete next steps for this issue?.  
… We had people point out that linking to credential is one way to do it, where do we go from here.  

**Manu Sporny:** We could suggest raising a PR for the extension spec..  

**Phillip Long:** Myself and Kerri and Dmitri can work on that. Manu's right, there are qualifiers, journalism and journalistic reports -- first person vs. second person to help contextualize the link. We're happy to do that..  

> *Kerri Lemoie:* +1 to working on examples with Phil & Dmitri.

**Shigeya Suzuki:** I'm late to file issue/PR for multilingual discussion, I was talking about how I can externalize some of translation maps to external object. I think there is common structure between what we're discussing now and what I'm going to discuss w/ multilingual objects.  

**Manu Sporny:** Totally agree, shigeya.  

**Shigeya Suzuki:** Trying to create PR for this, will try to rely on part of spec that talks about this external object. This is a good way to use external object..  

**Brent Zundel:** With that we're at time. Thank you to Oliver and Manu for scribing. Always a pleasure to work with each of you. See you next week. Thank you..  

---

</details>

**Comment by RieksJ** [comment]
Can anyone provide a convincing case in which a piece of evidence could NOT be expressed as (a set of) regular claims, which could therefore be placed in the section that contains these claims (rather than in a separate `evidence` section)?

**Comment by decentralgabe** [comment]
@RieksJ to flip the question - what in your mind would necessitate a new section? why not put `issuer`, `credentialStatus`, or `expiryDate` in the claims section too?

**Comment by longpd** [comment]
Evidence can take many forms. It could be simply an example of code written or a paper published relevant to credential. In an education/training use case the credential would be an achievement (a diploma in k12, a degree in HE, etc). In a self-asserted credential it may be a capability that has been learned on-the-job, and evidence, again self-asserted included, or [hashlinked ](https://github.com/w3c/vc-data-model/issues/952) to so it can live elsewhere on the web (assuming that 'elsewhere' is a stable location)

@jandrieu points out you can have a compound credential, one with another inserted within it. The CLRv2 of 1EdTech is doing just that for a combined representation of courses taken in a program of student, aka a transcript, where each course is a separate single-assertion credential following the OBv3 format, and can be individually signed so that when this compound credential is sent the recipient can make use the individually signed course credentials (the OBv3s') to compose a focused subset of their coursework for an application for employment. 

The method introduced by @dmitrizagidulin for multibase hashlinks (#952 referenced above) allows the choice between doing embedding, useful to keep things together but which might make the payload bigger than one might want, or putting evidence as simply digital objects in a third-party location, or hashlinking to another credential entirely, that might be in a Verifiable Presentation or again living independently on the web.

**Comment by OR13** [comment]
I don't think this issue is ready for PR.

**Comment by RieksJ** [comment]
@decentralgabe 

> @RieksJ to flip the question - what in your mind would necessitate a new section? why not put `issuer`, `credentialStatus`, or `expiryDate` in the claims section too?

I would say that anything within a `credentialSubject`-element (i.e.: a claim) represents a characteristic that the issuer has attributed to the subject of that claim. `credentialStatus` is a statement about a credential, so unless that credential is iself the subject of a claim, any attribute, such as `expiryDate` or `credentialStatus` should not be part of the claim (and would not belong in a `credentialSubject`-element).

So: anything that someone considers 'evidence' would be part of a claim (i.e. the specific `credentialSubject-element) if AND ONLY if the evidence proves something about the subject of the claim.

Reverting to your original post: IMHO, you should not be looking for ways to make the 'evidence'-property meaningful. Rather, do it the other way around: find a problem to solve and solve it. If it happens to make use of the 'evidence'-property, that's good. If it does not, that's ok too. Otherwise you're looking for aledged solutions for which there may not be a problem.

I'd rather see someone suggest to remove the 'evidence' section if there are no real use-cases for it, and only reinstating it if such use-cases come along.

**Comment by decentralgabe** [comment]
@RieksJ 

> So: anything that someone considers 'evidence' would be part of a claim (i.e. the specific `credentialSubject-element) if AND ONLY if the evidence proves something about the subject of the claim.

This is where I disagree. Evidence *is not* part of the claim itself, it is auxiliary to the claim and can provide information on the claim's issuance and why it should be considered trustworthy. 

To give a concrete example we are considering credentials around KYC. Depending on the jurisdiction and compliance regulations under which these checks are done there are certain types of evidence that may need to be collected (i.e. a drivers license, selfie, etc.). The evidence _leads to_ the issuance of a KYC claim but is not a part of the claim itself. In fact, in some cases, disclosing the specifics of the evidence that led to the claim's issuance can be highly sensitive. This requires a specific type of evidence that preserves the privacy of both the subject and issuer while providing information to the verifier that a proper evaluation process was observed.

**Comment by longpd** [comment]
Gabe: Isn’t that what selective disclosure cryptography is intended to address?  What gets revealed in a set of ‘claims’ whatever evidence it might include can be withheld from the recipient if it is signed by cryptographic methods that support selective disclosure.  That may be a technical step that isn’t currently supported among the individuals of your use case, but that’s the situation that it is intended to address.

Phil

Phillip Long, Ph.D . Senior Scholar
Center for New Designs in Learning & Scholarship, (CNDLS)
http://cndls.georgtown.edu <http://cndls.georgtown.edu/>
e: ***@***.*** ***@***.***>
Telegram: @RadHertz
Signal: 5129691774
— 
LER Network Facilitator
T3 Innovation Network
US Chamber of Commerce Foundation
***@***.*** ***@***.***>
— 
ICoBC - International Council on Badges & Credentials
https://icobc.net <https://iocbc.net/>
e: ***@***.*** ***@***.***/>

**Comment by decentralgabe** [comment]
@longpd selective disclosure cryptography may very well be an implementation choice that works for the scenario I described. Still, it would be applied to an evidence property, not the claims itself...because it's fundamentally not a claim about the subject, just evidence that led to the claim's issuance.

**Comment by David-Chadwick** [comment]
For reference, this is the working copy of the draft Evidence property that we have proposed to the CCG as a new work item

https://docs.google.com/document/d/1htujrb-_1kh8tkV4MXYRmZ44m_D7yFrY09aFJkAz7io/edit#heading=h.2jvnikt0mew3

But the authors are equally amenable to this being a work item within the VCDM instead

**Comment by decentralgabe** [comment]
Closing, seems to have been solved by the identity assurance conversation cc: @jandrieu

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-09-15-vcwg#section5-7) on 2022-09-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.7.  (issue vc-data-model#919)

_See github issue [vc-data-model#919](https://github.com/w3c/vc-data-model/issues/919)._




**Kristina Yasuda:** What's the status of this, Gabe?.  

**Gabe Cohen:** I don't think there's consensus. I can close it..  

**Joe Andrieu:** I think this has been taken over by the assurance conversation..  

</details>
