### ISSUE TITLE
Add `render` property to a core VC data model

### ISSUE THREAD

**Issue by philarcher** [w3c/vc-data-model#928]
At TPAC 2022, we briefly discussed the need for a presentation layer, or a hook for a presentation layer, so that creds can be presented in a way the issuer wants (branding, layout etc). We may not need to define the presentation layer but we need to consider how they will be presented and may need to include one or more hooks.

**Comment by msporny** [comment]
This issue is related to this RWOT11 [pre-reading paper](https://github.com/WebOfTrustInfo/rwot11-the-hague/blob/master/advance-readings/rendering-verifiable-credentials.md) and this [draft paper](https://github.com/WebOfTrustInfo/rwot11-the-hague/blob/master/draft-documents/rendering-vcs-snapshot-9-27-22.md).

**Comment by melvincarvalho** [comment]
Chiming in late, I hope that's OK

Good to see this discussed here.  I raised this topic in the SWICG last week:

https://lists.w3.org/Archives/Public/public-swicg/2023May/0142.html

During the Social Web Working Group which started in 2014, there was a deliverable in the charter to deliver : 

> A document that defines a specification for a client-side API that lets developers embed and format third party information such as social status updates inside Web applications

IMHO, this was never fully realized, partly because tooling was not there back in 2016.

Do you think these two use cases could be merged into a joint effort, or are they too far apart?

**Comment by Sakurann** [comment]
PR #1035 was closed

**Comment by brentzundel** [comment]
This issue will be resolved when PR #1142 is merged.

**Comment by Sakurann** [comment]
addressed in #1108

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-07-05-vcwg#section2-7) on 2023-07-05

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.7.  (issue vc-data-model#928)

_See github issue [vc-data-model#928](https://github.com/w3c/vc-data-model/issues/928)._




> *Orie Steele:* I suggest closing, we have addressed this in the reserved terms table.

> *Manu Sporny:* +1 to close, agree w/ Orie, we're done here.

**Kristina Yasuda:** I don't understand why this is dependent on a PR 1142.  

> *Orie Steele:* I will drop the confidenceMethod part of [https://github.com/w3c/vc-data-model/pull/1142](https://github.com/w3c/vc-data-model/pull/1142) if CCG does not adopt the proposal.

> *Orie Steele:* +1 manu, it adds links.

**Brent Zundel:** The PR does both confidence method and render method.  

**Manu Sporny:** This issue is about adding render method to VCDM.  
… I think we can close this issue.  

**Kristina Yasuda:** Render method is already in as a reserved property.  
… Closing it.  

> *Manu Sporny:* That's the PR we added renderMethod reservation in [https://github.com/w3c/vc-data-model/pull/1108](https://github.com/w3c/vc-data-model/pull/1108).

</details>
