### ISSUE TITLE
what is attribute ID  in the verifiable credential?

### ISSUE THREAD

**Issue by Muthurajj** [w3c/vc-data-model#946]
1.what is the purpose of the id ?
2.How to create the id url?
3.If the id is refer to identity for the claims in VC then we have storage the claims in server to identify gobally?

**Comment by OR13** [comment]
`id` must be an IRI, see the spec:

- https://www.w3.org/TR/vc-data-model/#identifiers
- https://webmasters.stackexchange.com/questions/98569/what-is-the-use-of-id-in-json-ld-syntax


`@id` is aliased it `id` in https://www.w3.org/2018/credentials/v1

**Comment by msporny** [comment]
We should add text that provides guidance around what an "id" is, whether or not it is required, what is expected to be there, must it be globally unique, there are cases where there isn't an ID for a VC, etc.

**Comment by OR13** [comment]
related issue: https://github.com/w3c/vc-data-model/issues/1031

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-09-15-vcwg#section5-5) on 2022-09-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.5. what is attribute ID  in the verifiable credential? (issue vc-data-model#946)

_See github issue [vc-data-model#946](https://github.com/w3c/vc-data-model/issues/946)._




**Kristina Yasuda:** This needs clarification in the spec.  
… Is anyone willing to write the clarifying text.  

**Manu Sporny:** I can try.  

**Orie Steele:** He's asking about what you should expect it to be and how should you handle it.  
… This is related to the URL vs. URI confusion.  

**David Chadwick:** I have an issue with the "parts of" wording.  

> *Dmitri Zagidulin:* (the question that almost all devs new to VCs ask is - 1) is 'id' required? 2) is it /supposed/ to be globally unique? Or can I use like a database row # for the id?.

**David Chadwick:** The credential schema should be one thing.  
… There's a disagreement there.  
… I don't think there's agreement that Gabe's proposal should be accepted.  

**Dmitri Zagidulin:** Maybe this text belongs more in the Implementation Guide.  
… I think we want to add it in the spec.  
… Is it required and must it be globally unique?.  
… We need guidance to say that it's not required and that it should be globally unique.  
… If absent, use the signature string as an ID.  

**Joe Andrieu:** We call them URIs. We refer to RFC 3986..  

**David Waite:** There's a normative reference to the WhatWG specification.  

**Kristina Yasuda:** If you'd like to revisit, please file an issue.  

**Brent Zundel:** Yesterday we had a discussion about IDs.  

</details>

**Comment by msporny** [comment]
@Muthurajj wrote:
> If the id is refer to identity for the claims in VC then we have storage the claims in server to identify gobally?

This is a specific question that we can't easily answer in the specification, so I'll try to answer it here. 

No, you don't have to store claims on a server if you use an `id` in any part of a VC as long as you express all the claims that you want in the VC itself. If, however, you only provide the `id`, then yes, you would want to store the claims on a server at the `id` specified in the VC. Note that this is not always the case if the `id` points to an image, video, or other non-Linked Data object. 

As for the rest of your questions, I've raised PR #1114 in an attempt to answer them with more text in the specification. Please review the PR and let us know if that addresses your questions.

**Comment by brentzundel** [comment]
I am closing this issue, as it has been addressed with the merging of #1114.
