### ISSUE TITLE
Zero-knowledge packed binary data format

### ISSUE THREAD

**Issue by stenreijers** [w3c/vc-data-model#949]
Following section 5.4 on `Data Schemas` the following example is shown:
 ```
"credentialSchema": {
  "id": "https://example.org/examples/degree.zkp",
  "type": "ZkpExampleSchema2018"
}
```
According to the specification this "credentialSchema" `is pointing to a zero-knowledge packed binary data format that is capable of transforming the input data into a format, which can then be used by a [verifier](https://www.w3.org/TR/vc-data-model/#dfn-verifier) to determine if the proof provided with the [verifiable credential](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-credentials) is valid. `

This sentence is not clear to me, what is a "zero-knowledge packed binary data format"? and how does this work? Can somebody here give an example of such a file and specify how this works exactly? Perhaps the specification can include references on this topic, because it seems highly relevant for use-cases where a ZKP is included in derived VCs.

**Comment by dlongley** [comment]
Possible duplicate / related to #890.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-04-04-vcwg-special#section1-7) on 2023-04-04

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.7. Zero-knowledge packed binary data format (issue vc-data-model#949)

_See github issue [vc-data-model#949](https://github.com/w3c/vc-data-model/issues/949)._




**Kristina Yasuda:** About ZK binary data format. No response on the issue..  

**Brent Zundel:** I'll take this one.  

**Kristina Yasuda:** Thanks Brent..  

**Brent Zundel:** I'll try to answer this question, and that the answer to the question will not be found in the core data model..  

</details>

**Comment by brentzundel** [comment]
The highlighted sentence doesn't really describe what happens in ZKP signatures. it would probably be better to change the sentence to be more general:
> In the example above, the [issuer](https://w3c.github.io/vc-data-model/#dfn-issuers) is specifying a credentialSchema pointing to a means of transforming the input data into a format which can then be used by a [verifier](https://w3c.github.io/vc-data-model/#dfn-verifier) to determine if the proof provided with the [verifiable credential](https://w3c.github.io/vc-data-model/#dfn-verifiable-credential) is valid.
