### ISSUE TITLE
Verification of multiple credential schemas

### ISSUE THREAD

**Issue by matthieubosquet** [w3c/vc-data-model#950]
In the [Data Schema section](https://www.w3.org/TR/vc-data-model-2.0/#data-schemas), the `credentialSchema` definition contains the following statement:

> The value of the `credentialSchema` [property](https://www.w3.org/TR/vc-data-model-2.0/#dfn-property) MUST be one or more data schemas that provide [verifiers](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verifier) with enough information to determine if the provided data conforms to the provided schema.

If more than one schema is provided, then verifiers should probably check the credential against every schema provided rather than making sure that at least one of the schemas provided conforms because it would allow for composability of schemas, for example, a credentialSchema property could point to `https://vc-schema.example.org/UniversityDegree` and `https://vc-schema.example.org/NonTransferable`.

Maybe the statement could be altered slightly to make the intended processing of multiple credential schemas (all valid vs at least one valid) clearer:

> The value of the `credentialSchema` [property](https://www.w3.org/TR/vc-data-model-2.0/#dfn-property) MUST be one or more data schemas that provide [verifiers](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verifier) with enough information to determine if the provided data conforms. Each `credentialSchema` MUST match the provided data for it to be determined as conforming by verifiers.

**Comment by mark-moir** [comment]
I agree that a) it must be clear whether the data is required to conform with *all* schemas or if just one is sufficient, and b) that the natural choice is "all".  In case more flexibility is required for a particular use case, this could be achieved using, for example, [Schema Composition](https://json-schema.org/understanding-json-schema/reference/combining.html) if the schema type is `JSONSchemaValidator*`.

**Comment by decentralgabe** [comment]
Related to #933 agree this should be adjusted to support multiple schemas

**Comment by OR13** [comment]
See:

https://github.com/w3c/vc-data-model/blob/main/contexts/credentials/v1#L23

seems its not an `@container: @graph`use case... like:

https://github.com/w3c/vc-data-model/blob/main/contexts/credentials/v1#L45

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-09-15-vcwg#section5-4) on 2022-09-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.4. Verification of multiple credential schemas (issue vc-data-model#950)

_See github issue [vc-data-model#950](https://github.com/w3c/vc-data-model/issues/950)._




**Gabe Cohen:** There is a PR.  

_See github pull request [vc-data-model#1023](https://github.com/w3c/vc-data-model/pull/1023)._




</details>

**Comment by decentralgabe** [comment]
@matthieubosquet you may be interested in this section of the vc json schema spec which was recently merged https://w3c-ccg.github.io/vc-json-schemas/#credential_schema_schema_multiple

**Comment by decentralgabe** [comment]
See discussion on PR: https://github.com/w3c/vc-data-model/pull/1023

## Recap

Here are the options as I understand them please add commentary if I've missed anything

1. Restrict `credentialSchema` to just 1 value. This reduces complexity and the need to have any talk of processing / validation logic in the VCDM itself. Multiple schemas, if needed, can be defined with a new `credentialSchema` `type.
2. Keep it as JSON-LD allows: a single or multiple values. Include processing logic to state that if ....
  a. Any of the schema validations **passes** then schema validation has passed.
  b. Any of the schema validations **fails** then schema validations has failed.
  c. Provide no guidance and leave this up to specific `type`s.

I am still in favor of 1 because I believe it allows the most configurability and enables decentralization through the creation of new types. I am open to compromise with 2a or 2b, even though I feel these are inferior solutions.

For those who have chimed in I'd like to hear what you're leaning towards and why. cc: @OR13 @dlongley @dmitrizagidulin @iherman @msporny

**Comment by andresuribe87** [comment]
I'm in favor of 1 as well.

**Comment by iherman** [comment]
At the moment, this is a highly theoretical discussion, because only JSON Schema is a real option. SHACL, in its present form, isn't usable (it cannot handle datasets), Json Type definition is (probably) too poor compared to JSON Schemas.

In light of this I am in favor of simplicity, and this is option 1. 

If things evolve, a future WG can extend the possibilities towards 2.x. Due to the way JSON-LD works (ie, on a syntactic level, it blurs the single value vs. multiple value issue), if any of 2.x option is introduced, it will automatically be backward compatible. Ie, we do not put ourselves in a difficult situation if we go with option 1 today by making valid VC-s invalid later.

**Comment by brentzundel** [comment]
[Option 1](https://github.com/w3c/vc-data-model/issues/950#issuecomment-1536493084) was raised in PR #1023, which did not gain consensus.

@decentralgabe what are next steps here? Do we assume that 2c is the answer?

**Comment by decentralgabe** [comment]
The default answer is no guidance - so yes 2C. I believe we can and should do better than that, so I would like to hear from @OR13 @dlongley @dmitrizagidulin who opposed (1).

**Comment by dlongley** [comment]
I don't feel *that* strongly about this -- but I think we should have the data model spec avoid business rules / particular processing decisions as much as possible.

Even if the spec said you could only have a single value for `credentialSchema`, the spec doesn't have any requirements on using that value and it presumes you may not even understand the type. A [verifier can use whatever "schema evaluation criteria"](https://w3c.github.io/vc-data-model/#schema) they want to. That doesn't seem like it would be that different from allowing multiple values, each with types that may not be understood, each that can be ignored.

Creating some meta-type that allowed schema combinations could still be ignored, it would just be additional complexity that perhaps could have been avoided -- and the single value approach may even inhibit useful innovation in some other direction.

It seems that to really get the behavior desired here we would have to, in the data model spec, require verifiers to understand the type or fail schema validation -- which I think would be inconsistent with everything else. Otherwise, just have the schema type processing rules say whatever you want them to -- and it doesn't matter how many other schema values there are.

In the end, I wouldn't stand in the way of option 1 if everyone else wanted that for the 2.0 data model, but I think it's conflating some layers and therefore trying to do both too much and too little in the wrong place. I recommend having another spec that defines a verification protocol that has some consensus default behavior on how to process the field and allows for configuration options where necessary. This is the approach used in the VC-API work, for example. The data model spec generally just says what can be there, it doesn't tell you how to process it.

**Comment by TallTed** [comment]
> I think we should have the data model spec avoid business rules / particular processing decisions as much as possible.

This.

I also note that the current VCDM spec says that `credentialSchema` "_can_ be included by an [issuer](https://www.w3.org/TR/vc-data-model-2.0/#dfn-issuers) in the [verifiable credentials](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verifiable-credential) that it issues". This optionality should be reflected in the definition that follows, i.e., —

_If present_, the value of the _optional_ `credentialSchema` [property](https://www.w3.org/TR/vc-data-model-2.0/#dfn-property) MUST be one or more data schemas that provide [verifiers](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verifier) with enough information to determine if the provided data conforms to the provided schema.

All things considered, it would probably also be better to change that MUST to a SHOULD.

**Comment by decentralgabe** [comment]
Thanks @TallTed and @dlongley I agree with your reasoning. I'll attempt another PR to address this with more neutral language.

**Comment by OR13** [comment]
Please add an example using multiple schemas.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-07-12-vcwg#section5-4) on 2023-07-12

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.4. Verification of multiple credential schemas (issue vc-data-model#950)

_See github issue [vc-data-model#950](https://github.com/w3c/vc-data-model/issues/950)._




**Brent Zundel:** multiple schemas.  

**Orie Steele:** I implemented support for this recently, essentially the recommendation that I have is that we treat this property like all the other properties... object or array of object w/ array and type. I already have a working implementation that supports multiple schemas, would object if that is made illegal before CR.  

**Gabe Cohen:** I think we are agreed, you can have multiple, and the processing rules are determined by each schema type.  

**Manu Sporny:** +1 to both, the type property is what tells you what to do.  

**Brent Zundel:** seems its before CR.  

**Ivan Herman:** its normative so it must indeed be before CR.  

</details>
