### ISSUE TITLE
Should `validFrom` and `validUntil` change to ISO8601 or Unix Time Stamp, or remain XML Date Time Strings?

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-model#962]
```
new Date().toISOString()
// '2022-10-26T20:10:59.098Z'
```

Is this legal?

### Option A - ISO8601

```json
"validFrom": "2020-10-26T20:10:59.098Z",
"validUntil": "2025-10-26T20:10:59.098Z"
```

### Option B - W3C / XML Date Time

```json
"validFrom": "2020-10-26T20:10:59",
"validUntil": "2025-10-26T20:10:59"
```

### Option C - Unix Time Stamp

```json
"validFrom": 1666815247,
"validUntil": 1666815247
```

Related:

- https://github.com/digitalbazaar/vc-js/blob/main/lib/index.js#L262
- https://github.com/digitalbazaar/jsonld-signatures/blob/main/lib/util.js#L23

**Comment by BenjaminMoe** [comment]
My vote goes towards **Option A** (`YYYY-MM-DDTHH:mm:ss.SSSZ`). When working with credentials it makes it much easier to work with being able call `new Date().toISOString()`, instead of having to write extra steps to account for the lack of milliseconds on XML Date Time. 

Fix: For **Option B**, the [current examples from the vc-data-model](https://www.w3.org/TR/vc-data-model/#example-a-simple-example-of-a-verifiable-credential) are shown as `2010-01-01T19:23:24Z`. (Stops at the second with a 'Z' on the end). Spec links: https://www.w3.org/TR/xmlschema11-2/#dateTime

**Comment by nissimsan** [comment]
The `Z` of option A implies that timezone offsets are allowed, meaning that for example `"validFrom": "2020-10-26T20:10:59-01:00"` would also be possible. My vote goes towards **Option A** on that argument.

**Comment by BenjaminMoe** [comment]
Also note that for **Option C**, i've done this a few times where I've used a unix timestamp in databases to track time. It's really easy for engineers, but it destroys human readability. And it creates a ton of issues where you have to constantly change the `int` back to a readable string for product or anyone else to read.

**Comment by TallTed** [comment]
Please change the title of this issue from a nonsensical statement to the question —
```Should `validFrom` and `validUntil` change to ISO8601 or Unix Time Stamp, or remain XML Date Time Strings?```

**Comment by dlongley** [comment]
I worry, from the comments, that it's not clear that the differences between the options are easily understood. I know that I don't know all the differences either, but it's clear that at least some people are looking at the examples and inferring differences that might not be reflective of what's actually in the specs, which aren't linked in the OP.

For example, I think the first example (listed under Option A: ISO8601) is also a valid XML DateTime (Option B).

My understanding of the specs is that XML DateTime is a [more restricted subset of ISO8601](https://docstore.mik.ua/orelly/xml/schema/ch04_05.htm) (and the [XML DateTime spec](https://www.w3.org/TR/xmlschema11-2) mentions throughout that it is consistent with ISO8601). It does allow for millisecond precision and considers values generated by JavaScript `Date`'s `toISOString()` method to be valid.

The lexical form for [XML DateTime](https://www.w3.org/TR/xmlschema11-2/#dateTime) is:

> dateTimeLexicalRep ::= [yearFrag](https://www.w3.org/TR/xmlschema11-2/#nt-yrFrag) '-' [monthFrag](https://www.w3.org/TR/xmlschema11-2/#nt-moFrag) '-' [dayFrag](https://www.w3.org/TR/xmlschema11-2/#nt-daFrag) 'T' (([hourFrag](https://www.w3.org/TR/xmlschema11-2/#nt-hrFrag) ':' [minuteFrag](https://www.w3.org/TR/xmlschema11-2/#nt-miFrag) ':' [secondFrag](https://www.w3.org/TR/xmlschema11-2/#nt-seFrag)) | [endOfDayFrag](https://www.w3.org/TR/xmlschema11-2/#nt-eodFrag)) [timezoneFrag](https://www.w3.org/TR/xmlschema11-2/#nt-tzFrag)?   Constraint:  Day-of-month Representations

So it seems, to me, the difference between Option A and Option B is that Option B is just a more constrained (less optionality) version of Option A. If people are just going to look at the examples, we might need many more examples of what would be considered valid in the ISO8601 option and then a subset of those in the XML DateTime option ... or perhaps we could have a few that are valid in both and then show a couple that are valid in ISO8601 but not in XML DateTime.

W3C has an internationalization "checklist" for spec writers with a date time section here: https://www.w3.org/TR/international-specs/#locale

Since ISO 8601 is an ISO standard, searching for its spec isn't as easy as searching for a W3C spec (the latter is more or less immediately found). Here's the wikipedia article for ISO 8601: https://en.wikipedia.org/wiki/ISO_8601

**Comment by msporny** [comment]
@OR13 wrote:
> Is this legal?

Yes, it is. :)

Remember that we started off with RFC3339, considered ISO8601, and went with XML Schema 1.1 because it was a reasonable subset of ISO8601 and was the newest, openly available spec we could choose from:

https://github.com/w3c/vc-data-model/issues/782#issuecomment-916601353

-1 for Unix time... it doesn't support subsecond precision (unless we use one of the newer, non-standard definitions).

-1 for ISO8601 because the standard is not easily accessible to implementers and it has some weird stuff in there like week `2020-W06-5` and day offsets `2020-039` that I expect most developers won't implement/support. We'd have to subset it with something reasonable that would probably end up looking like XML Schema 1.1's datetime values.

+1 for keeping it as-is, unless we can find a more compelling reason to change.

**Comment by OR13** [comment]
Since this is legal, I am proposing to close this issue;

```
new Date().toISOString()
// '2022-10-26T20:10:59.098Z'
```

We probably want to update the example in the next version to use better date strings...

```
  "issuanceDate": "2010-01-01T19:23:24Z",
```

**Comment by TallTed** [comment]
> We probably want to update the example in the next version to use better date strings...

@OR13 -- That needs an open issue (could reopen this one) and/or a PR so it happens, rather than just a note in a now-closed issue.
