### ISSUE TITLE
Verifier Role Confusion

### ISSUE THREAD

**Issue by mwherman2000** [w3c/vc-data-model#984]
I have a clarifying question about the VC 3-role model ...a perhaps naïve question about the Verifier role...

Is the Verifier role 
(a) a "service" that can be asked to verify the authenticity of a VC for someone? ...or... 
(b) is the Verifier the someone who is seeking to have the authenticity of a VC verified?  
...they're quite different.

...do you have link that explains your choice (e.g. into the VC spec)?

A Bank is used in many Verifier examples (not sure if its used in the VC spec itself) ...this choice doesn't provide any clarity because a Bank can be both an (a) and a (b).

This definition from the VC spec isn't adequate...

> A role an [entity](https://www.w3.org/TR/vc-data-model/#dfn-entities) performs by receiving one or more [verifiable credentials](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-credentials), optionally inside a [verifiable presentation](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-presentations) for processing.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-04-04-vcwg-special#section1-2) on 2023-04-04

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.2. Verifier Role Confusion (issue vc-data-model#984)

_See github issue [vc-data-model#984](https://github.com/w3c/vc-data-model/issues/984)._




**Kristina Yasuda:** By Michael Herman. No comments on this issue. Anyone willing to sign up for it?.  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-04-12-vcwg#section4-9) on 2023-04-12

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.9. Verifier Role Confusion (issue vc-data-model#984)

_See github issue [vc-data-model#984](https://github.com/w3c/vc-data-model/issues/984)._




**Brent Zundel:** issue #984 no one has commented on it. No one has asked to be assigned to it.  

> *Charles Lehner:* i think the (b) there may have been what was called "the relying party".

**Brent Zundel:** what should we do?  
… not for the day - looking like no action will be taken for #984.  

**Oliver Terbu:** wishes to be assigned to #984.  

**Brent Zundel:** will be bothering for those not marked close. We're done. IIW next week!  

---


</details>

**Comment by awoie** [comment]
> I have a clarifying question about the VC 3-role model ...a perhaps naïve question about the Verifier role...
> 
> Is the Verifier role (a) a "service" that can be asked to verify the authenticity of a VC for someone? ...or... (b) is the Verifier the someone who is seeking to have the authenticity of a VC verified? ...they're quite different.
> 
> ...do you have link that explains your choice (e.g. into the VC spec)?
> 
> A Bank is used in many Verifier examples (not sure if its used in the VC spec itself) ...this choice doesn't provide any clarity because a Bank can be both an (a) and a (b).
> 
> This definition from the VC spec isn't adequate...
> 
> > A role an [entity](https://www.w3.org/TR/vc-data-model/#dfn-entities) performs by receiving one or more [verifiable credentials](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-credentials), optionally inside a [verifiable presentation](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-presentations) for processing.

I'd say that both models a) and b) can apply. At least I observed both cases in the field.

Do you think that any of the sections in the VCDM that involves the verifier role would be affected by this ambiguity? Do you have a list of paragraphs that would be specifically affected by this? If we cannot point to specific paragraphs that would need to change, I'd suggest closing this issue.

**Comment by Sakurann** [comment]
question has been answered. no actions right away

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-06-21-vcwg#section2-3) on 2023-06-21

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.3. Verifier Role Confusion (issue vc-data-model#984)

_See github issue [vc-data-model#984](https://github.com/w3c/vc-data-model/issues/984)._




**Kristina Yasuda:** Ok I think this is pending close.  
… Any objections?  

> *Manu Sporny:* +1 to pending close.

</details>
