### ISSUE TITLE
Clarify credentialStatus

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#991]
There is some confusion about the semantics of the credentialStatus field, whether it refers to the status of the credential or the verifiable credential. The current text says it is a property of the VC and not the embedded credential. If this is so, it should be removed from the data model as it is not a property of the credential, or of the credential metadata. It is a property of the proof (either JWT or LD-proof) and should be defined along with the proof description.

However, both the underlying credential (e.g. degree certificate) and the digitally signed VC can have their own separate statuses. A person's degree can be revoked years after it has been issued, whilst a VC could be revoked if the issuer's private key is compromised. Therefore the proof specification should describe how the VC's proof can be revoked, whilst the VCDM should specify how the credential can be revoked.  The following table shows the effects of combining these two revocation schemes.

```
Credential Status            Revoked Credential.          Not Revoked Credential
Revoked VC.                        unknown                         unknown
Not Revoked VC.             Credential Revoked                  Credential OK
```
If the VC has been revoked (e.g. because the issuer's private key was hacked) then we cannot tell what the status of the credential is, because the VC cannot be verified. In fact we cannot verify any of the credential's properties in this case.
Only if the VC has not been revoked, can we tell the status of the embedded credential. Thus it is logical that the credentialStatus field should apply to the credential and not to the verifiable credential as the current text states.
A PR is needed to change the definition of credentialStatus

**Comment by TallTed** [comment]
I do not think I understand your table. Is it meant to be a matrix? What are the periods (e.g., `VC.`, `Credential.`) doing?

**Comment by David-Chadwick** [comment]
yes its a matrix indicating the status of the credential should either, neither or both of the credential or verifiable credential be revoked. You can ignore the periods.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-04-05-vcwg#section3-7) on 2023-04-05

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.7. Clarify credentialStatus (issue vc-data-model#991)

_See github issue [vc-data-model#991](https://github.com/w3c/vc-data-model/issues/991)._




**Brent Zundel:** Clarify credentialStatus.  
… Not sure if this has been resolved because of our adoption of the StatusList work item.  

**David Chadwick:** I think it's a valid comment. If you take the case of a degree certificate, revoke could happen if the private key is compromised or a student cheated. Need to differentiate between them.  
… There was a problem with the CredentialStatusList. Did raise an issue.  
… It would be nice if anyone involved in CredentialStatusList could say so.  

**Brent Zundel:** Assigned davidc.  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-06-07-vcwg#section2-8) on 2023-06-07

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.8. Clarify credentialStatus (issue vc-data-model#991)

_See github issue [vc-data-model#991](https://github.com/w3c/vc-data-model/issues/991)._




**Brent Zundel:** next issue 991, to discuss label. raised by and assigned to DavidC.  

**Orie Steele:** We have a separate work item for credential status. This issue seems overtaken by events with open PRs. Close this PR and go over to that work item.  

> *Orie Steele:* I suggest closing this issue.

**Brent Zundel:** suggestion is to move this item to status list repo.  

> *Orie Steele:* and instead reviewing the open PRs on that work item.

> *Orie Steele:* (you don't).

**Joe Andrieu:** that is not correct. Does seem to be about a specific status mechanism.  

> *Orie Steele:* there are not 2 objects, we spent over month on this.

> *Dave Longley:* +1 just one object.

**David Chadwick:** There are 2 objects, credential and verifiable credential and now talking about the status is "mixed up" as well.  
… one could be valid while the other is invalid and vice versa.  

> *Brent Zundel:* +1 just one object.

> *Joe Andrieu:* +1 just one object, but this is the layering problem.

> *Orie Steele:* It seems http range 14 is yet again, disrupting our ability to communicate.

**Dave Longley:** key revocation at the crypto layer is different than at the credential layer.  
… key revocation and credential revocation are different things.  

**Joe Andrieu:** We don't have separate items in our work. We have just one digital thing.  

> *Orie Steele:* joe is correct, and the digital thing, may or may not have any integrity protection.

**David Chadwick:** Driver's license is my credential (and I've been driving for a long time).  

**Joe Andrieu:** There are three layers here. Different between having driven, the physical license and a digital thing.  
… we don't have good language differentiating these three things.  

**David Chadwick:** Yes it is difficult to talk about.  

**Dave Longley:** there can a validity period on a proof (expressed via internal / external proof securing mechanism), a validity period on the VC, and a validity period expressed in a claim about a license that someone possesses ... all different things.  
all works with 1 VC object.

---

</details>

**Comment by David-Chadwick** [comment]
Here is some proposed text for inclusion in the VCDM section 4.9 Status

Note. This property says nothing about the status of the underlying certificate/ticket/qualification/licence (collectively called certificate from hereon) from which the verifiableCredential was created. If the verifiableCredential has been revoked, then the certificate may or may not still be valid. It is out of scope of this specification how the status of the underlying certificate is determined

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-06-28-vcwg#section2-12) on 2023-06-28

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.12. Clarify credentialStatus (issue vc-data-model#991)

_See github issue [vc-data-model#991](https://github.com/w3c/vc-data-model/issues/991)._




**Brent Zundel:** #991.  
… how do we triage this one?  

**David Chadwick:** depends is how much left in the core DM. Wants to change the terminology to "certificate verifiable credential". Certificate can be revoked or the VC can be revoked and status list should be able to distinguish between the two.  

> *Orie Steele:* It is relevant to the previous issue, and competitive positioning vs mDoc.

**Brent Zundel:** sounds like it's VC Status List work item.  

**David Chadwick:** this is generic, not depending on the revocation status per se.  

**Joe Andrieu:** issue is related to the core. Appreciates certificate suggestion. Status should just be about the VC. If about cert, should use ghe claim status of the cert.  

**David Chadwick:** If we work remotely, then we have only VCs, Certs are only relevant f2f. Therefore if in the remote situation you only have the VC but the underlying cert can't be verified.  

**Brent Zundel:** Proposes this issue be before CR and allow it to continue within the issue.  

**Joe Andrieu:** fine with proposal - Re: David's ideas. Cert status? Either a mechanism to check it is there or not. If it exists you can put it in the claim.  

**Brent Zundel:** encourages conversation to continue in the issue.  
… to DavidC's question proposed text should be put in the issue.  

</details>

**Comment by OR13** [comment]
This issue does not make sense to me.

**Comment by David-Chadwick** [comment]
@OR13 This is because it was written from the perspective of the credential and the verifiableCredential being different data objects, the credential being derived from the underlying certificate e.g. university degree, from which it was created, and then it being signed to create a VC. Now that it has been determined that credential and verifiableCredential are different terms for the same data object, nevertheless the original certificate from which the VC was created may or may not have been revoked, and may or may not have been the reason for the issuing of the revocation list. However, the status field says nothing about this. Hence the reason for adding the clarifying note.

**Comment by Sakurann** [comment]
PR #1211 somewhat addresses this.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-08-02-vcwg#section2-3) on 2023-08-02

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.3. Clarify credentialStatus (issue vc-data-model#991)

_See github issue [vc-data-model#991](https://github.com/w3c/vc-data-model/issues/991)._




**Brent Zundel:** if we want for ready for PR, ask assigned person what their timeline could be -- that might be valuable question to ask.  

**Kristina Yasuda:** for clarify credentialStatus --- DavidC go ahead.  

> *Dmitri Zagidulin:* does that object /need/ a name?

**David Chadwick:** This is partly tied into the difference between credential and verifiable credential... manu tried to clarify that text... the definition of verifiable credential is that it's secured... what is the object called that is unsecured? That hasn't been answered satisfactorily... the text for this one, underlying object or credential could be revoked, vc could be revoked.... we haven't fully nailed down what we call the unsecured verifiable credential.  
… I don't believe it can be called credential... VC and C seemed to be same object before.  

**Orie Steele:** I agree with some of what David Chadwick said, we're still struggling Credential vs. VC language -- manu has PR w/ language speaking to it... the way I'm making sense of this is specification registers two media types, subtypes of JSON, and they might be secured or they might not be and up to verifier to check... media types are hints, not assurance that something has security.  

> *Michael Prorock:* +1 orie.

**Orie Steele:** vc+ld+json is JSON media type of something that might not be secured... just be careful about how interpret this.  

**Sebastian Crane:** Three different scenarios, VC (valid in terms of structure and secure in it has a cryptographic proof), but receiver has not yet done either verification of structure nor have they done cryptography to ensure signature is correct. That is a "pending VC".  
… Another is that you have a VC that was once valid, but has been revoked, and one could call that "revoked VC".  
… Final scenario is where everything is fine, "verified VC" -- if we can find a new name for that, confusion might remain.  

> *Orie Steele:* `proof` is optional... so that seems to conflict with the RDF type definition.

> *David Chadwick:* +1 to manu that a VC is always secured.

**Manu Sporny:** There is a PR out to fix the issue. It says that a Verifiable Credential credential is secured. PR means that it has to be secured for you to call it a VC. That does not preclude it from having errors.  

> *Orie Steele:* its a mistake to use english language that contradicts the RDF data model.

> *Kristina Yasuda:* to reconcile with orie's interpretation of vc+ld+json, vcdm does not say where to use that media type so it can be cty in vc-jose-cose, so should be no conflict..?

**Manu Sporny:** One school of thought is that it doesn't matter, another school of thought is that invalid or erroneous data can not be called a Verifiable Credential.  

> *David Chadwick:* +1 to manu that vc and c are not the same thing.

**Manu Sporny:** The current PR tries to say that it conforms to our document, and it is secure. A 'credential document' is the term for things that aren't secure or aren't conforment.  

_See github pull request [vc-data-model#1211](https://github.com/w3c/vc-data-model/pull/1211)._




**Joe Andrieu:** I preferred the other language, felt like there were two dimensions, other dimensionality -- difference between VC and credential in real world... having a bachelors degree, have that whether or not I have a VC... but that's not what this is about.  
… When we sign a credential, not sure how to coherently describe position, will try again later.  

**Kristina Yasuda:** PR1211 might address this, anything else that needs to be done.  

**David Chadwick:** Yes, this is good, glad you changed position manu, that aligns w/ what I was concerned w/ all along... you and I agree now.  
… The PR that we are discussing now, what is underlying document/credential/certificate -- we start w/ paper document, that is turned into some JSON (credential), which is then turned into (verifiable credential) w/ proof on it.  
… This PR was talking about first and 3rd object... how do we signal that... agreeing that we are not going to say anything about underlying paper document.  
… That is what this PR was about... your degree is removed, but VC is still around saying you had a degree. That's what we're trying to address in terms of revocation.  

**Kristina Yasuda:** can you add language to clarify this, Manu?  

**Manu Sporny:** I will try my best.  

**Sebastian Crane:** Respoding to DavidC -- if there is consensus one way or another, we should have resolution that we are are/not addressing first layer in VCs.  
… Looking for input on that.  

> *Michael Prorock:* no.

**Sebastian Crane:** before something becomes JSON -- paper credential -- are we talking about that? if physical degree is revoked, is VC-native way that addresses that situation?  

**David Chadwick:** Yes, that's what this issue was about.  

**Sebastian Crane:** Yes, would like to see resolution.  

**Joe Andrieu:** With a slight refactoring, we already do that -- we don't have mechanism to separate revocation of real world paper credential from digital version... we do have a mechanism to state that VC is revoked.  

> *Brent Zundel:* The revocation check of the real world credential sounds entirely out of scope for our group.

**Joe Andrieu:** You said "Credential Object", made sense to me DavidC, JSON that's not signed yet.  

> *Kristina Yasuda:* there are two things: validity of the signature and validity of the data about the subject. we have status list for the latter and individual mechanism per securing mechanism.

> *Kristina Yasuda:* I am pretty confused what we need beyond that.

**Sebastian Crane:** For status list, which allows revocation for VC... difference between that and real world credential... if you revoke VC, because you gave no reason for that, cryptography for revoking, don't know if that credential was ever valid... maintaining list of changes, knowledge graph, can you say "I once believed that the person had a degree" -- important aspect.  

> *Joe Andrieu:* status list isn't for cryptographic revocation.

**Manu Sporny:** I really like David Chadwick's model of three parts. I see that Orie's concern that the language and the RDF definitions don't match, for which I have some PRs to resolve the difference.  
… The thing we care most about in this specification is the third and final part, which has to be secured.  
… We can add a new RDF term to align with this new three-part model.  

**Kristina Yasuda:** I think manu has enough data to update the PR.  

**Orie Steele:** We did start w/ abstract credential class -- that VC inherited from -- all of this happened before, it'll all happen again.  

**Kristina Yasuda:** ETA for hashes PR, manu?  

**Manu Sporny:** Within two weeks.  

</details>

**Comment by brentzundel** [comment]
PR #1211 was raised to address this issue and has been merged. This issue will be closed in 7 days if there are no objections.
